### ISSUE TITLE
Spack env: unreachable config

### ISSUE THREAD

**Issue by sknigh** [spack/spack#10031]
Spack environment configs become unreachable with 'spack config edit' if the last edit creates an invalid YAML file. In my case, I commended out all of the specs in my environment, which left a dangling 'spec' key. I was able to write and quit the file without any linting; but when I tried to repoen it, I got an error and a trace.

```
# spack config edit
Traceback (most recent call last):
  File "spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "spack/lib/spack/spack/main.py", line 605, in main
    env = ev.find_environment(args)
  File "spack/lib/spack/spack/environment.py", line 182, in find_environment
    return Environment(env)
  File "spack/lib/spack/spack/environment.py", line 365, in __init__
    self._read_manifest(f)
  File "spack/lib/spack/spack/environment.py", line 377, in _read_manifest
    self.yaml = _read_yaml(f)
  File "spack/lib/spack/spack/environment.py", line 318, in _read_yaml
    validate(data, filename)
  File "spack/lib/spack/spack/environment.py", line 311, in validate
    e, data, filename, e.instance.lc.line + 1)
AttributeError: 'NoneType' object has no attribute 'lc'
```

Linting the config immediately after closing is a better idea in my opinion. Validating before opening prevents users from correcting mistakes.

**Comment by citibeth** [comment]
Can you just edit this directly with Emacs/vi?  Why are we adding code and complexity to Spack to replicate what text editors already do?

**Comment by alalazo** [comment]
Still an issue with an active environment.

**Comment by becker33** [comment]
This was fixed in Spack 1.1.0
