### ISSUE TITLE
mirror create fails

### ISSUE THREAD

**Issue by IanLee1521** [spack/spack#10139]
After merging in https://github.com/spack/spack/pull/8993 `spack mirror create ...` seems to fail on (at least) mirroring `python@3.6`.

```bash
% ./bin/spack -d mirror create -D python@3.6
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/modules.yaml
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/linux/modules.yaml
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/config.yaml
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/repos.yaml
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/packages.yaml
==> READ LOCK: /home/lee1001/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /home/lee1001/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /home/lee1001/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> Reading config file /home/lee1001/.spack/linux/compilers.yaml
Traceback (most recent call last):
  File "./bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/cmd/mirror.py", line 220, in mirror
    action[args.mirror_command](args)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/cmd/mirror.py", line 207, in mirror_create
    colify(s.cformat("$_$@") for s in error)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/concretize.py", line 56, in disable_compiler_existence_check
    yield
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/cmd/mirror.py", line 195, in mirror_create
    directory, specs, num_versions=args.versions_per_spec)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/mirror.py", line 179, in create
    specs, num_versions=kwargs.get('num_versions', 1))
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/mirror.py", line 109, in get_matching_versions
    version_order.remove(spec.version)
ValueError: list.remove(x): x not in list
```

This is something in the concretization of the packages (I think).

I added a `print(spec)` line right before https://github.com/spack/spack/blob/f8c650b9c41421e1eda79caeedcdd68dcfb77171/lib/spack/spack/mirror.py#L107 and see what more it might give me, and it produced: 

```bash
% ./bin/spack -d mirror create -D -d /transfer/lee1001/spack-mirror python@3.6
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/modules.yaml
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/linux/modules.yaml
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/config.yaml
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/repos.yaml
==> Reading config file /home/lee1001/projs/llnl/spack/etc/spack/defaults/packages.yaml
==> READ LOCK: /home/lee1001/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /home/lee1001/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /home/lee1001/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> Reading config file /home/lee1001/.spack/linux/compilers.yaml
bzip2@1.0.6%gcc@4.4.7+shared arch=linux-rhel6-x86_64  ^diffutils@3.6%gcc@4.4.7 arch=linux-rhel6-x86_64
pkgconf@1.5.4%gcc@4.4.7 arch=linux-rhel6-x86_64
perl@5.26.2%gcc@4.4.7+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-rhel6-x86_64  ^gdbm@1.18.1%gcc@4.4.7 arch=linux-rhel6-x86_64  ^ncurses@6.1%gcc@4.4.7~symlinks~termlib arch=linux-rhel6-x86_64  ^pkgconf@1.5.4%gcc@4.4.7 arch=linux-rhel6-x86_64  ^readline@7.0%gcc@4.4.7 arch=linux-rhel6-x86_64
gdbm@1.18.1%gcc@4.4.7 arch=linux-rhel6-x86_64  ^ncurses@6.1%gcc@4.4.7~symlinks~termlib arch=linux-rhel6-x86_64  ^pkgconf@1.5.4%gcc@4.4.7 arch=linux-rhel6-x86_64  ^readline@7.0%gcc@4.4.7 arch=linux-rhel6-x86_64
python@3.6%gcc@4.4.7+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+pythoncmd+shared~tk~ucs4 arch=linux-rhel6-x86_64  ^bzip2@1.0.6%gcc@4.4.7+shared arch=linux-rhel6-x86_64  ^diffutils@3.6%gcc@4.4.7 arch=linux-rhel6-x86_64  ^gdbm@1.18.1%gcc@4.4.7 arch=linux-rhel6-x86_64  ^ncurses@6.1%gcc@4.4.7~symlinks~termlib arch=linux-rhel6-x86_64  ^openssl@1.1.1%gcc@4.4.7+systemcerts arch=linux-rhel6-x86_64  ^perl@5.26.2%gcc@4.4.7+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-rhel6-x86_64  ^pkgconf@1.5.4%gcc@4.4.7 arch=linux-rhel6-x86_64  ^readline@7.0%gcc@4.4.7 arch=linux-rhel6-x86_64  ^sqlite@3.25.3%gcc@4.4.7~functions arch=linux-rhel6-x86_64  ^zlib@1.2.11%gcc@4.4.7+optimize+pic+shared arch=linux-rhel6-x86_64
Traceback (most recent call last):
  File "./bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/cmd/mirror.py", line 220, in mirror
    action[args.mirror_command](args)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/cmd/mirror.py", line 207, in mirror_create
    colify(s.cformat("$_$@") for s in error)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/concretize.py", line 56, in disable_compiler_existence_check
    yield
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/cmd/mirror.py", line 195, in mirror_create
    directory, specs, num_versions=args.versions_per_spec)
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/mirror.py", line 178, in create
    specs, num_versions=kwargs.get('num_versions', 1))
  File "/home/lee1001/projs/llnl/spack/lib/spack/spack/mirror.py", line 108, in get_matching_versions
    version_order.remove(spec.version)
ValueError: list.remove(x): x not in list
```

In case that helps.

cc/ @tgamblin who I was discussing this with.

**Comment by IanLee1521** [comment]
Maybe something in https://github.com/spack/spack/pull/8993/files#diff-f47960f7abb204c009469e281a99d55d

**Comment by scheibelp** [comment]
You can avoid the immediate error by specifying a complete version:

`./bin/spack -d mirror create -D python@3.6.5`

When I tried this out though, it also ran into a different issue, which I have addressed with #10171.

**Comment by IanLee1521** [comment]
@scheibelp -- that worked for me, though note (not sure if related) when I did the above mirror create for `python@3.6.5`, I got the following error for `bzip2@1.0.6`:

```
...
==> Adding package bzip2@1.0.6 to mirror
==> Fetching https://fossies.org/linux/misc/bzip2-1.0.6.tar.gz
######################################################################## 100.0%
==> Staging archive: /Users/lee1001/projs/llnl/spack/var/spack/stage/bzip2-1.0.6-vfmdedxrupkurelhiarhiuiccvkluoks/bzip2-1.0.6.tar.gz
==> Created stage in /Users/lee1001/projs/llnl/spack/var/spack/stage/bzip2-1.0.6-vfmdedxrupkurelhiarhiuiccvkluoks
==> Warning: Error while fetching bzip2@1.0.6
  global name 'spack_cc' is not defined
...
```

**Comment by scheibelp** [comment]
https://github.com/spack/spack/issues/10139#issuecomment-450946194 should now be fixed by https://github.com/spack/spack/pull/10150. Feel free to reopen if the problem persists.

**Comment by IanLee1521** [comment]
@scheibelp  -- Confirmed that PR fixed the `bzip2` issue, but not the original issue (also, did #10171 get closed without being merged?)

```
> ./bin/spack mirror create -D -d mirror python@3.6
==> Error: list.remove(x): x not in list
```

**Comment by scheibelp** [comment]
> Confirmed that PR fixed the bzip2 issue, but not the original issue

That's true: https://github.com/spack/spack/issues/10139#issuecomment-449208016 is one approach to addressing the issue originally reported here. Even so, minimally there should be a more-informative error message when the user doesn't specify an exact version.

> did #10171 get closed without being merged?

Yes: it did not resolve the issue as reported in this PR but rather the follow up issue that you mentioned in https://github.com/spack/spack/issues/10139#issuecomment-450946194. That issue was resolved by another PR so I closed #10171
