### ISSUE TITLE
Specifying package version in packages.yaml throws datetime.date schema error

### ISSUE THREAD

**Issue by DarylGrunau** [spack/spack#10283]
I am attempting to restrict versions of a given package, r3d, in my `packages.yaml` file, and in doing so, Spack is throwing the following error:

```console
$ spack spec r3d
Input spec
--------------------------------
r3d

Concretized
--------------------------------
==> Error: <unknown file>: datetime.date(2018, 12, 19) is not valid under any of the given schemas
```

The issue appears to be entirely related to the "date" format of the actual package version, "2018-12-19" during concretization.  Replacing dashes with dots or no characters at all permits proper operation.  Success is also seen if I remove the version stanza entirely from the `packages.yaml` file.

### Steps to reproduce the issue

Edit your packages.yaml file and insert the following stanza:

```console
  r3d:
    version: [2018-12-19]
```
and then issue this command:
```console
$ spack spec r3d
```

### Error Message

The full debug error message follows:

```console
$ spack --debug spec r3d
==> Reading config file /usr/projects/packages/user_contrib/spack/etc/spack/defaults/modules.yaml
==> Reading config file /usr/projects/packages/user_contrib/spack/etc/spack/defaults/linux/modules.yaml
==> Reading config file /usr/projects/packages/user_contrib/spack/etc/spack/modules.yaml
==> Reading config file /usr/projects/packages/user_contrib/spack/etc/spack/defaults/config.yaml
Input spec
--------------------------------
r3d

Concretized
--------------------------------
==> Reading config file /usr/projects/packages/user_contrib/spack/etc/spack/defaults/repos.yaml
==> Reading config file /usr/projects/packages/user_contrib/spack/etc/spack/repos.yaml
==> Reading config file /usr/projects/packages/user_contrib/spack/etc/spack/defaults/packages.yaml
==> Reading config file /usr/projects/packages/user_contrib/spack/etc/spack/linux/packages.yaml
==> Error: <unknown file>: datetime.date(2018, 12, 19) is not valid under any of the given schemas
Traceback (most recent call last):
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/cmd/spec.py", line 72, in spec
    spec.concretize()
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/spec.py", line 1901, in concretize
    self._expand_virtual_packages(),
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/spec.py", line 1809, in _expand_virtual_packages
    candidates = concretizer.choose_virtual_or_external(spec)
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/concretize.py", line 115, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/concretize.py", line 89, in _valid_virtuals_and_externals
    if is_spec_buildable(cspec):
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/package_prefs.py", line 230, in is_spec_buildable
    allpkgs = get_packages_config()
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/package_prefs.py", line 30, in get_packages_config
    config = spack.config.get('packages')
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/config.py", line 666, in get
    return config.get(path, default, scope)
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/config.py", line 519, in get
    value = self.get_config(section, scope=scope)
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/config.py", line 484, in get_config
    data = scope.get_section(section)
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/config.py", line 179, in get_section
    data   = _read_config_file(path, schema)
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/config.py", line 734, in _read_config_file
    _validate(data, schema)
  File "/usr/projects/packages/user_contrib/spack/lib/spack/spack/config.py", line 712, in _validate
    raise ConfigFormatError(e, data)
spack.config.ConfigFormatError: <unknown file>: datetime.date(2018, 12, 19) is not valid under any of the given schemas
```

### Information on your system

My platform is a VirtualBox image running Centos 7,  Intel `x86_64` architecture and GCC as compiler.  I am using a customized `packages.yaml` file as described above.

-----

**Comment by adamjstewart** [comment]
What happens if you add quotes around the version number? Many things like compiler specifications require quotes to be valid YAML constructs.

**Comment by DarylGrunau** [comment]
Success using quotes - closing!  Sorry about the false alarm.

**Comment by DarylGrunau** [comment]
Perhaps this nuance should be reflected in the documentation.  Poking through many examples show no quotes around anything within a list context ...
