### ISSUE TITLE
py-pytest: Pytest not working (missing dependency to py-pathlib2)

### ISSUE THREAD

**Issue by dorier** [spack/spack#10352]
### Steps to reproduce the issue

```console
$ spack install py-pytest 
```
I'm working with python@2.7.15. The installation works fine. However when I load the package
```console
$ spack load -r py-pytest`
```
and then try to run it:
```console
$ pytest
```
I get the following error:
```
Traceback (most recent call last):
  File "/home/mdorier/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/py-pytest-3.7.2-itwcak47miqyoztbrmakbs7cyllz47jz/bin/pytest", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/mdorier/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/py-setuptools-40.4.3-kjb5igu5c36zx55ci5jjfcajynzqn2nw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/home/mdorier/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/py-setuptools-40.4.3-kjb5igu5c36zx55ci5jjfcajynzqn2nw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/home/mdorier/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/py-setuptools-40.4.3-kjb5igu5c36zx55ci5jjfcajynzqn2nw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/mdorier/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/py-setuptools-40.4.3-kjb5igu5c36zx55ci5jjfcajynzqn2nw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/home/mdorier/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/py-setuptools-40.4.3-kjb5igu5c36zx55ci5jjfcajynzqn2nw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/mdorier/spack/opt/spack/linux-debian9-x86_64/gcc-6.3.0/py-setuptools-40.4.3-kjb5igu5c36zx55ci5jjfcajynzqn2nw/lib/python2.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pathlib2>=2.2.0' distribution was not found and is required by pytest
```
It seems that there is a missing dependency to `py-pathlib2`. When I look in the py-pytest package I see the following:

```python
depends_on('py-pathlib2@2.2.0:', when='^python@:3.5', type=('build', 'run'))
```
which should mean that for versions of Python up to 3.5, py-pathlib2 should be installed. Yet, it isn't installed. I had to install it and load it manually.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to open a new issue if the problem persists.
