### ISSUE TITLE
Feature: buildcache relocation with different layout and compiler location

### ISSUE THREAD

**Issue by gartung** [spack/spack#10522]
I had an idea during my commute on how to relocate buildcaches to a directory layout that is different than the current layout. I depends on being able to reconstructing the rpath from the spec stored with the buildcache. If this is possible, then the buildcache could be created with binaries that have the rpaths removed. Upon installation the reconstructed rpath would be added to the binaries. 

@tgamblin  do you think reconstructing the rpaths is possible?

**Comment by gartung** [comment]
Also the compiler specific rpaths could be removed and added since compilers with the same name and version are supposed to be identical.

**Comment by gartung** [comment]
maybe this method 

spack.build_environment.get_rpaths(pkg)

**Comment by gartung** [comment]
Damn I see that spack.build_environment.get_rpaths(pkg) is only usable during package install.

**Comment by gartung** [comment]
Although this might work if prefix/.spack directory is created first

spack.build_environment.get_rpaths(spec.package)

**Comment by gartung** [comment]
Picked up this trick from Chris Green for getting the build environment of a package before installing.
****

**Comment by gartung** [comment]
I also want to remove the any compiler rpath added and reconstruct them based on just the compiler name and version.

**Comment by gartung** [comment]
I was trying to create a buildcache for gcc that was linked against system zlib with this entry in packages.yaml

  zlib:
    paths:
      zlib@1.2.7+optimize+pic+shared arch=linux-rhel7-x86_64: /usr

The spec.yaml refers to zlib@1.2.7 but the current zlib package has removed that version. I thought I could be clever and use .spack/repos/builtin to get the old zlib package. However I see that the zlib package.py was not saved in .spack/repos/builtin.
 @tgamblin would it be possible to save all package.py files used in generating spec.yaml. It might also be good to save the packages.yaml and config.yaml that were used in generating spec.yaml in the .spack directory. This might allow better regeneration of the old hash.

**Comment by gartung** [comment]
@tgamblin It looks as though the version was never specified in the zlib package. The version 1.2.7 was added by @chissg so that it would match the actual version installed by rpm. Now when I try to create a buildcache for gcc built against this external zlib I get a weird error that may be a side effect of merging in pr #9199 into my pr #10287


==> Warning: Missing a source id for zlib@1.2.7
==> Error: 'MultiValuedVariant' object has no attribute '_patches_in_order_of_appearance'

**Comment by gartung** [comment]
```
==> [2019-02-27-20:44:36.739291] Warning: Missing a source id for zlib@1.2.7
Traceback (most recent call last):
  File "/build/work/spack-tools/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/build/work/spack-tools/spack/lib/spack/spack/main.py", line 675, in main
    return _invoke_command(command, parser, args, unknown)
  File "/build/work/spack-tools/spack/lib/spack/spack/main.py", line 446, in _invoke_command
    return_val = command(parser, args)
  File "/build/work/spack-tools/spack/lib/spack/spack/cmd/buildcache.py", line 556, in buildcache
    args.func(args)
  File "/build/work/spack-tools/spack/lib/spack/spack/cmd/buildcache.py", line 338, in createtarball
    not args.no_rebuild_index)
  File "/build/work/spack-tools/spack/lib/spack/spack/binary_distribution.py", line 384, in build_tarball
    spec_dict['full_hash'] = spec.full_hash()
  File "/build/work/spack-tools/spack/lib/spack/spack/spec.py", line 1306, in full_hash
    package_hash = self.package.content_hash()
  File "/build/work/spack-tools/spack/lib/spack/spack/package.py", line 1092, in content_hash
    for p in self.spec.patches)
  File "/build/work/spack-tools/spack/lib/spack/llnl/util/lang.py", line 183, in __call__
    self.cache[args] = self.func(*args)
  File "/build/work/spack-tools/spack/lib/spack/spack/spec.py", line 2690, in patches
    for sha256 in self.variants['patches']._patches_in_order_of_appearance:
AttributeError: 'MultiValuedVariant' object has no attribute '_patches_in_order_of_appearance'
```

**Comment by gartung** [comment]
@tgamblin I have implemented this for the FNAL spack dev testing. This includes some extra things I had to backport.
https://github.com/FNALssi/spack/compare/MVP1a...gartung:MVP1a-branch

**Comment by gartung** [comment]
https://github.com/spack/spack/pull/13747 
implement this feature

**Comment by gartung** [comment]
Implemented some of this in
https://github.com/FNALssi/spack/pull/27
Because the directory layout was changed between tag MVP1 and MVP1a and I got the error about the directory layout when using buildcaches built with the MVP1 tag
