### ISSUE TITLE
Package png not found

### ISSUE THREAD

**Issue by floli** [spack/spack#10544]
Hello,

on a fresh checkout, trying to install py-numpy with python 3.7 gives a weird error message. `spack install py-numpy` without python 3 works.

### Steps to reproduce the issue

```console
% git clone https://github.com/spack/spack.git
Cloning into 'spack'...
[...]
% . spack/share/spack/setup-env.sh            
% spack install py-numpy ^python3.7.0
==> Error: Package png not found.
```

### Error Message

If Spack reported an error, provide the error message. If it did not report an error
but the output appears incorrect, provide the incorrect output. If there was no error
message and no output but the result is incorrect, describe how it does not match
what you expect. To provide more information you might re-run the commands with 
the additional -sd flags:
```console
% spack -sd install py-numpy ^python3.7.0
==> Error: unrecognized arguments: -sd
% spack install -sd py-numpy ^python3.7.0
==> Error: unrecognized arguments: -sd
```
that activate the full debug output. 

### Information on your system
* Ubuntu 16.04
* no additional configuration, fresh checkout of spack

**Comment by scheibelp** [comment]
Can you retry the command with just `-d`? Like `spack -d install py-numpy...`

**Comment by scheibelp** [comment]
I checked into it and `-s` has been replaced with `--stacktrace`, so you can add both options like `spack -d --stacktrace install py-numpy...`

I'll update the issue template to reflect that change - sorry about the confusion!

**Comment by alalazo** [comment]
Can't reproduce. As there's a typo that is reported systematically above, I wonder if that's not the error:
```console
$ spack install py-numpy ^python3.7.0
```
should read:
```console
$ spack install py-numpy ^python@3.7.0
```
with the `@` character to denote the version.

**Comment by floli** [comment]
Ok, it seems that the problem is related to my shell and how it expands `^`. Changed to bash, but:
```
% spack -d --stacktrace install py-numpy ^python3.7.0
lib/spack/spack/config.py:681 ==> Reading config file /home/lindnefn/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:681 ==> Reading config file /home/lindnefn/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:681 ==> Reading config file /home/lindnefn/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:681 ==> Reading config file /home/lindnefn/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:681 ==> Reading config file /home/lindnefn/spack/etc/spack/defaults/packages.yaml
lib/spack/llnl/util/lock.py:334 ==> READ LOCK: /home/lindnefn/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> READ LOCK: /home/lindnefn/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> READ LOCK: /home/lindnefn/.spack/cache/tags/.builtin-index.json.lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> READ LOCK: /home/lindnefn/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> READ LOCK: /home/lindnefn/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> READ LOCK: /home/lindnefn/.spack/cache/patches/.builtin-index.json.lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> READ LOCK: /home/lindnefn/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> READ LOCK: /home/lindnefn/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> READ LOCK: /home/lindnefn/.spack/cache/providers/.builtin-index.json.lock[0:0] [Released]
lib/spack/spack/config.py:681 ==> Reading config file /home/lindnefn/.spack/linux/compilers.yaml
lib/spack/spack/error.py:55 ==> Error: py-numpy does not depend on 0
Traceback (most recent call last):
  File "/home/lindnefn/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/lindnefn/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/home/lindnefn/spack/lib/spack/spack/cmd/install.py", line 259, in install
    args.package, concretize=True, tests=tests)
  File "/home/lindnefn/spack/lib/spack/spack/cmd/__init__.py", line 143, in parse_specs
    raise SpackError(msg)
spack.error.SpackError: py-numpy does not depend on 0
```

same I get for zsh using `% spack -d --stacktrace install py-numpy "^python3.7.0"`

**Comment by floli** [comment]
Ah, sorry, about the forgotten `@`, with that and proper escaping for my shell it works (well, actually, there is a timeout error fetching `http://distfiles.dereferenced.org/pkgconf/pkgconf-1.5.4.tar.xz`, but I assume that's transient).

Thanks all for your help, sorry about the fuzz.
