### ISSUE TITLE
CDash reporter fails when installing pkgs with `-f <spec.yaml>`

### ISSUE THREAD

**Issue by scottwittenburg** [spack/spack#10564]
When calling `spack install ...` with arguments which cause CDash reporting, passing specs to install on the command line works fine, while passing `-f <spec.yaml` causes the CDash reporter to raise an exception.

### Steps to reproduce the issue

Given a spec.yaml file like this one:

```console
$ cat /tmp/pkgconf.yaml 
spec:
- pkgconf:
    version: 1.4.2
    arch:
      platform: darwin
      platform_os: highsierra
      target: x86_64
    compiler:
      name: clang
      version: 9.1.0-apple
    namespace: builtin
    parameters:
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    hash: 564r23i4wovhvwngsweex2smvsrfug3e
```

Attempt to install it using the CDash reporting arguments, as follows:

```console
$ spack -d install \
    --cdash-upload-url 'https://cdash.spack.io/submit.php?project=Spack' \
    --cdash-build 'pkgconf@1.4.2%clang@9.1.0-apple arch=highsierra-x86_64' \
    --cdash-site 'Spack AWS Gitlab Instance' \
    --cdash-track Experimental \
    -f /tmp/pkgconf.yaml
```

### Error Message

I cut out most of the debug output until the exception message:

```console
...
Traceback (most recent call last):
  File "/Users/scott/projects/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/Users/scott/projects/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/scott/projects/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/Users/scott/projects/spack/lib/spack/spack/cmd/install.py", line 325, in install
    install_spec(args, kwargs, abstract, concrete)
  File "/Users/scott/projects/spack/lib/spack/spack/report.py", line 265, in __exit__
    self.report_writer.build_report(self.filename, report_data)
  File "/Users/scott/projects/spack/lib/spack/spack/reporters/cdash.py", line 185, in build_report
    self.upload(phase_report)
  File "/Users/scott/projects/spack/lib/spack/spack/reporters/cdash.py", line 239, in upload
    response = opener.open(request)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

While it seems the package was installed (because `spack` finds it after the exception message is printed) the reporting fails.

```console
$ spack find
==> 1 installed package
-- darwin-highsierra-x86_64 / clang@9.1.0-apple -----------------
pkgconf@1.4.2
```

### Information on your system

It's probably clear from information included above this is on OSX (highsierra), using the system clang compiler.  But I have also encountered this issue on Ubuntu and Centos.

**Comment by alalazo** [comment]
@scottwittenburg Is this still an issue?

**Comment by scottwittenburg** [comment]
That approach to install isn't used in CI anymore, so I don't know.  But if it's still a problem, it probably deserves a new issue with relevant stack trace and other details.
