### ISSUE TITLE
Installation issue: mvapich2

### ISSUE THREAD

**Issue by jumpydiaz** [spack/spack#10674]
I'm attempting to install mvapich2 using gcc6.4 and another instance with gcc@8.2, with all of it's dependents being compiled with gcc4.8.5. I keep getting a 'cross compiling' error.
---

### Steps to reproduce the issue

```console
called from script
spack install mvapich2@2.3%gcc@6.4.0~alloca ch3_rank_bits=32 +cuda~debug fabrics=psm file_systems=auto process_managers=auto +regcache threads=multiple arch=linux-centos7-x86_64 \
    ^bison@3.0.5%gcc@4.8.5 arch=linux-centos7-x86_64 \
        ^diffutils@3.7%gcc@4.8.5 arch=linux-centos7-x86_64 \
        ^help2man@1.47.4%gcc@4.8.5 arch=linux-centos7-x86_64 \
            ^gettext@0.19.8.1%gcc@4.8.5+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-centos7-x86_64 \
                ^bzip2@1.0.6%gcc@4.8.5+shared arch=linux-centos7-x86_64 \
                ^libxml2@2.9.8%gcc@4.8.5~python arch=linux-centos7-x86_64 \
                    ^libiconv@1.15%gcc@4.8.5 arch=linux-centos7-x86_64 \
                    ^pkgconf@0.27.1%gcc@4.8.5 arch=linux-centos7-x86_64 \
                    ^xz@5.2.4%gcc@4.8.5 arch=linux-centos7-x86_64 \
                    ^zlib@1.2.7%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64 \
                ^ncurses@6.1%gcc@4.8.5~symlinks~termlib arch=linux-centos7-x86_64 \
                ^tar@1.26%gcc@4.8.5 patches=08921fcbd732050c74ddf1de7d8ad95ffdbc09f8b4342456fa2f6a0dd02a957c,5c314db58d005043bf407abaf25eb9823b9032a22fd12a0b142d4bf548130fa4,d428578be7fb99b831eb61e53b8d88a859afe08b479a21238180899707d79ce4 arch=linux-centos7-x86_64 \
            ^perl@5.16.3%gcc@4.8.5+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-centos7-x86_64 \
        ^m4@1.4.16%gcc@4.8.5 patches=c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e +sigsegv arch=linux-centos7-x86_64 \
    ^cuda@10.0.130%gcc@4.8.5 arch=linux-centos7-x86_64 \
    ^findutils@4.6.0%gcc@4.8.5 patches=84b916c0bf8c51b7e7b28417692f0ad3e7030d1f3c248ba77c42ede5c1c5d11e,bd9e4e5cc280f9753ae14956c4e4aa17fe7a210f55dd6c84aa60b12d106d47a2 arch=linux-centos7-x86_64 \
        ^autoconf@2.69%gcc@4.8.5 arch=linux-centos7-x86_64 \
        ^automake@1.13.4%gcc@4.8.5 arch=linux-centos7-x86_64 \
        ^libtool@2.4.2%gcc@4.8.5 arch=linux-centos7-x86_64 \
        ^texinfo@6.5%gcc@4.8.5 arch=linux-centos7-x86_64 \
    ^libpciaccess@0.13.5%gcc@4.8.5 arch=linux-centos7-x86_64 \
        ^util-macros@1.19.1%gcc@4.8.5 arch=linux-centos7-x86_64 \
    ^psm@3.3%gcc@4.8.5 arch=linux-centos7-x86_64 \
        ^libuuid@1.0.3%gcc@4.8.5 arch=linux-centos7-x86_64 # Fill in the exact spec you are using
```
... # and the relevant part of the error message

3 errors found in build log:
     935    checking whether make supports nested variables... yes
     936    checking whether to enable maintainer-specific portions of Makefiles... yes
     937    checking for style of include used by make... GNU
     938    checking whether the C compiler works... yes
     939    checking for C compiler default output file name... a.out
     940    checking for suffix of executables...
  * 941    checking whether we are cross compiling... configure: error: in `/tmp/root/spack-stage/spack-stage-3WAodj/mvapich2-2.3/src/mpi/romio':
  * 942    configure: error: cannot run C compiled programs.
     943    If you meant to cross compile, use `--host'.
     944    See `config.log' for more details
  * 945    configure: error: src/mpi/romio configure failed

### Platform and user environment

```commandline
$ uname -a 
Linux omitted 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.6.1810 (Core) 
``` 

- `packages.yaml`
- `compilers.yaml`
````
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/gcc
      cxx: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/g++
      f77: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/gfortran
      fc: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/gfortran
    spec: gcc@6.4.0
    target: x86_64`
````

to the issue

### Additional information

```console
$ spack spec --install-status [above]
```
```
Concretized
--------------------------------
 -   mvapich2@2.3%gcc@6.4.0~alloca ch3_rank_bits=32 +cuda~debug fabrics=psm file_systems=auto process_managers=auto +regcache threads=multiple arch=linux-centos7-x86_64 
[+]      ^bison@3.0.5%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]          ^diffutils@3.7%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]          ^help2man@1.47.4%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]              ^gettext@0.19.8.1%gcc@4.8.5+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-centos7-x86_64 
[+]                  ^bzip2@1.0.6%gcc@4.8.5+shared arch=linux-centos7-x86_64 
[+]                  ^libxml2@2.9.8%gcc@4.8.5~python arch=linux-centos7-x86_64 
[+]                      ^libiconv@1.15%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]                      ^pkgconf@0.27.1%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]                      ^xz@5.2.4%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]                      ^zlib@1.2.7%gcc@4.8.5+optimize+pic+shared arch=linux-centos7-x86_64 
[+]                  ^ncurses@6.1%gcc@4.8.5~symlinks~termlib arch=linux-centos7-x86_64 
[+]                  ^tar@1.26%gcc@4.8.5 patches=08921fcbd732050c74ddf1de7d8ad95ffdbc09f8b4342456fa2f6a0dd02a957c,5c314db58d005043bf407abaf25eb9823b9032a22fd12a0b142d4bf548130fa4,d428578be7fb99b831eb61e53b8d88a859afe08b479a21238180899707d79ce4 arch=linux-centos7-x86_64 
[+]              ^perl@5.16.3%gcc@4.8.5+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-centos7-x86_64 
[+]          ^m4@1.4.16%gcc@4.8.5 patches=c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e +sigsegv arch=linux-centos7-x86_64 
[+]      ^cuda@10.0.130%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]      ^findutils@4.6.0%gcc@4.8.5 patches=84b916c0bf8c51b7e7b28417692f0ad3e7030d1f3c248ba77c42ede5c1c5d11e,bd9e4e5cc280f9753ae14956c4e4aa17fe7a210f55dd6c84aa60b12d106d47a2 arch=linux-centos7-x86_64 
[+]          ^autoconf@2.69%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]          ^automake@1.13.4%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]          ^libtool@2.4.2%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]          ^texinfo@6.5%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]      ^libpciaccess@0.13.5%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]          ^util-macros@1.19.1%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]      ^psm@3.3%gcc@4.8.5 arch=linux-centos7-x86_64 
[+]          ^libuuid@1.0.3%gcc@4.8.5 arch=linux-centos7-x86_64 
...

```
to show people whether Spack installed a faulty software or if it was not able to
build it at all. 

If your build didn't make it past the configure stage, Spack as also commands to parse 
logs and report error and warning messages:
```console
$ spack log-parse --show=errors,warnings buildlog
```
```
spack log-parse --show=errors,warnings /apps/spack/var/spack/stage/mvapich2-2.3-kkhcg5c3tm2honmvg3kd7cp6i6hlixtt/mvapich2-2.3/spack-build.out
3 errors
1 warnings
     630    checking for max C struct floating point alignment... sixteen
     631    checking for max C struct alignment of structs with doubles... eight
     632    checking for max C struct floating point alignment with long doubles... sixteen
  >> 633    configure: WARNING: Structures containing long doubles may be aligned differently from structures with floats or longs.  MVAPICH2 does not handle this case automatically and you should avoid assumed extents for structures containing float types.
     634    checking if alignment of structs with doubles is based on position... no
     635    checking if alignment of structs with long long ints is based on position... no
     636    checking if double alignment breaks rules, find actual alignment... no

     ...

     938    checking whether the C compiler works... yes
     939    checking for C compiler default output file name... a.out
     940    checking for suffix of executables...
  >> 941    checking whether we are cross compiling... configure: error: in `/tmp/root/spack-stage/spack-stage-NdXpGg/mvapich2-2.3/src/mpi/romio':
  >> 942    configure: error: cannot run C compiled programs.
     943    If you meant to cross compile, use `--host'.
     944    See `config.log' for more details
  >> 945    configure: error: src/mpi/romio configure failed
```

Rebuilding the package with the following options:
```console
$ spack -d install -j 1 <above spec>
...
```
```
==> [2019-02-21-20:00:41.074013] Installing mvapich2
==> [2019-02-21-20:00:41.074131] Searching for binary cache of mvapich2
==> [2019-02-21-20:00:41.074427] Reading config file /apps/spack/etc/spack/mirrors.yaml
==> [2019-02-21-20:00:41.076184] Finding buildcaches in /apps/spack-mirror/build_cache
==> [2019-02-21-20:00:41.079571] No binary for mvapich2 found: installing from source
==> [2019-02-21-20:00:41.221030] No libraries found for psm
==> [2019-02-21-20:00:41.656132] Warning: A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> [2019-02-21-20:00:41.737930] Using cached archive: /apps/spack/var/spack/cache/mvapich2/mvapich2-2.3.tar.gz
==> [2019-02-21-20:00:41.800909] Staging archive: /apps/spack/var/spack/stage/mvapich2-2.3-kkhcg5c3tm2honmvg3kd7cp6i6hlixtt/mvapich2-2.3.tar.gz
==> [2019-02-21-20:00:41.802290] '/bin/tar' '-xf' '/apps/spack/var/spack/stage/mvapich2-2.3-kkhcg5c3tm2honmvg3kd7cp6i6hlixtt/mvapich2-2.3.tar.gz'
==> [2019-02-21-20:00:43.405720] Created stage in /apps/spack/var/spack/stage/mvapich2-2.3-kkhcg5c3tm2honmvg3kd7cp6i6hlixtt
==> [2019-02-21-20:00:43.406692] No patches needed for mvapich2
==> [2019-02-21-20:00:43.406824] Building mvapich2 [AutotoolsPackage]
==> [2019-02-21-20:00:43.407118] WRITE LOCK: /apps/spack/var/spack/stage/.lock[6847860753799464130:1] [Acquiring]
==> [2019-02-21-20:00:43.407521] WRITE LOCK: /apps/spack/var/spack/stage/.lock[6847860753799464130:1] [Acquired]
==> [2019-02-21-20:00:43.408205] WRITE LOCK: /apps/spack/opt/spack/.spack-db/prefix_lock[2974365570231540283:1] [Acquiring]
==> [2019-02-21-20:00:43.408428] WRITE LOCK: /apps/spack/opt/spack/.spack-db/prefix_lock[2974365570231540283:1] [Acquired]
==> [2019-02-21-20:00:43.413118] Executing phase: 'autoreconf'
==> [2019-02-21-20:00:43.419966] Executing phase: 'configure'
==> [2019-02-21-20:02:01.617879] WRITE LOCK: /apps/spack/opt/spack/.spack-db/prefix_lock[2974365570231540283:1] [Released]
==> [2019-02-21-20:02:01.619183] WRITE LOCK: /apps/spack/var/spack/stage/.lock[6847860753799464130:1] [Released]
==> [2019-02-21-20:02:01.630982] Error: ProcessError: Command exited with status 1:
    '/apps/spack/var/spack/stage/mvapich2-2.3-kkhcg5c3tm2honmvg3kd7cp6i6hlixtt/mvapich2-2.3/configure' '--prefix=/apps/spack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/mvapich2-2.3-kkhcg5c3tm2honmvg3kd7cp6i6hlixtt' '--enable-shared' '--enable-romio' '--disable-silent-rules' '--disable-new-dtags' '--enable-fortran=all' '--enable-threads=multiple' '--with-ch3-rank-bits=32' '--disable-alloca' '--enable-fast=all' '--enable-cuda' '--with-cuda=/apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-10.0.130-kqvlz4iqfrzow5vznahf4cted6fpxm3w' '--enable-registration-cache' '--with-device=ch3:psm' '--with-psm=/apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/psm-3.3-3n4557pruwwynqxsqexewb6qw6bsgex3'

3 errors found in build log:
     935    checking whether make supports nested variables... yes
     936    checking whether to enable maintainer-specific portions of Makefiles... yes
     937    checking for style of include used by make... GNU
     938    checking whether the C compiler works... yes
     939    checking for C compiler default output file name... a.out
     940    checking for suffix of executables...
  >> 941    checking whether we are cross compiling... configure: error: in `/tmp/root/spack-stage/spack-stage-d6z5R6/mvapich2-2.3/src/mpi/romio':
  >> 942    configure: error: cannot run C compiled programs.
     943    If you meant to cross compile, use `--host'.
     944    See `config.log' for more details
  >> 945    configure: error: src/mpi/romio configure failed

See build log for details:
  /apps/spack/var/spack/stage/mvapich2-2.3-kkhcg5c3tm2honmvg3kd7cp6i6hlixtt/mvapich2-2.3/spack-build.out
Traceback (most recent call last):
  File "/apps/spack/lib/spack/spack/build_environment.py", line 761, in child_process
    return_value = function()
  File "/apps/spack/lib/spack/spack/package.py", line 1497, in build_process
    phase(self.spec, self.prefix)
  File "/apps/spack/lib/spack/spack/package.py", line 101, in phase_wrapper
    phase(spec, prefix)
  File "/apps/spack/lib/spack/spack/build_systems/autotools.py", line 256, in configure
    inspect.getmodule(self).configure(*options)
  File "/apps/spack/lib/spack/spack/util/executable.py", line 188, in __call__
    proc.returncode, long_msg)
ProcessError: Command exited with status 1:
    '/apps/spack/var/spack/stage/mvapich2-2.3-kkhcg5c3tm2honmvg3kd7cp6i6hlixtt/mvapich2-2.3/configure' '--prefix=/apps/spack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/mvapich2-2.3-kkhcg5c3tm2honmvg3kd7cp6i6hlixtt' '--enable-shared' '--enable-romio' '--disable-silent-rules' '--disable-new-dtags' '--enable-fortran=all' '--enable-threads=multiple' '--with-ch3-rank-bits=32' '--disable-alloca' '--enable-fast=all' '--enable-cuda' '--with-cuda=/apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-10.0.130-kqvlz4iqfrzow5vznahf4cted6fpxm3w' '--enable-registration-cache' '--with-device=ch3:psm' '--with-psm=/apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/psm-3.3-3n4557pruwwynqxsqexewb6qw6bsgex3'
```

**Comment by jumpydiaz** [comment]
edited to clean up formatting for readability

**Comment by mwkrentel** [comment]
@jumpydiaz Could you try the following experiment for me?

I'm semi-suspicious of the empty modules: field for this compiler
entry.

```
 compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/gcc
      cxx: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/g++
      f77: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/gfortran
      fc: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/gfortran
    spec: gcc@6.4.0
    target: x86_64
```

You built gcc-6.4.0 from spack (right?), so spack will create a module
file for it.  Try adding the module name to the modules: field.  This
will be something like `gcc-6.4.0-gcc-4.8.5-3zna454`.

Also, run `module use` or otherwise set MODULEPATH and check that
`module avail` shows the `gcc-6.4.0` module.  The default spack
modules directory is `$spack/share/spack/modules` or else whatever you
set in `config.yaml`.

Then, retry spack install for mvapich2 %gcc@6.4.0.

I want to test the theory that spack needs to load gcc-6.4.0 as a
module in order to have all of the paths set correctly.

**Comment by jumpydiaz** [comment]
updated compilers.yaml:
```compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.8.5
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: [gcc-6.4.0-gcc-4.8.5-3zna454]
    operating_system: centos7
    paths:
      cc: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/gcc
      cxx: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/g++
      f77: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/gfortran
      fc: /apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-6.4.0-3zna454grl6qrwxti6q4hsvfxedwllcl/bin/gfortran
    spec: gcc@6.4.0
    target: x86_64
```

output of module avail:
```# module avail
------------------------------ /apps/spack/share/spack/modules/linux-centos7-x86_64 -------------------------------
autoconf-2.69-gcc-4.8.5-3vtyesw     help2man-1.47.4-gcc-4.8.5-lwmh6gh      mvapich2-2.3-gcc-8.2.0-cftehcs        
automake-1.13.4-gcc-4.8.5-wccqfbw   help2man-1.47.4-gcc-6.4.0-jde5qz5      ncurses-6.1-gcc-4.8.5-rqw3cmc         
bison-3.0.5-gcc-4.8.5-oov4wpb       hwloc-1.11.11-gcc-6.4.0-jvab5sb        ncurses-6.1-gcc-6.4.0-ree7wyp         
bison-3.0.5-gcc-6.4.0-o7vodvc       hwloc-1.11.11-gcc-8.2.0-bdggyi3        perl-5.16.3-gcc-4.8.5-zy3chf6         
bzip2-1.0.6-gcc-4.8.5-fxe4hfn       isl-0.18-gcc-4.8.5-l4somr6             pgi-18.10-gcc-4.8.5-oypleqy           
cuda-10.0.130-gcc-4.8.5-kqvlz4i     kokkos-2.7.00-gcc-6.4.0-inzkhxu        pgi-18.10-gcc-8.2.0-55466pi           
diffutils-3.7-gcc-4.8.5-ko7qdei     kokkos-2.7.00-gcc-8.2.0-dze5wbt        pkgconf-0.27.1-gcc-4.8.5-zu5gihn      
diffutils-3.7-gcc-6.4.0-wepilbw     libiconv-1.15-gcc-4.8.5-bli6oh4        psm-3.3-gcc-4.8.5-3n4557p             
findutils-4.6.0-gcc-4.8.5-3ckpsot   libpciaccess-0.13.5-gcc-4.8.5-5chyfxo  tar-1.26-gcc-4.8.5-hao53jb            
findutils-4.6.0-gcc-6.4.0-dbc6ptu   libtool-2.4.2-gcc-4.8.5-yw23lwr        texinfo-6.5-gcc-4.8.5-da23koh         
findutils-4.6.0-gcc-8.2.0-fleuvyd   libuuid-1.0.3-gcc-4.8.5-wthjh67        texinfo-6.5-gcc-6.4.0-xfjyw4f         
gcc-6.4.0-gcc-4.8.5-3zna454         libxml2-2.9.8-gcc-4.8.5-apf7vhw        texinfo-6.5-gcc-8.2.0-gugaof2         
gettext-0.19.8.1-gcc-4.8.5-zspdixt  m4-1.4.16-gcc-4.8.5-jy7hoa7            util-macros-1.19.1-gcc-4.8.5-p66qdrt  
gettext-0.19.8.1-gcc-6.4.0-23jd335  mpc-1.1.0-gcc-4.8.5-v5rqsbk            xz-5.2.4-gcc-4.8.5-agv5zlv            
gmp-6.1.2-gcc-4.8.5-6bsovvk         mpfr-3.1.6-gcc-4.8.5-kflyoj7           zlib-1.2.7-gcc-4.8.5-kqvjt5p          

-------------------------------------------- /apps/modules/modulefiles --------------------------------------------
dot  module-git  module-info  modules  null  use.own  

------------------------------------------- /apps/packages/modulefiles --------------------------------------------
cuda/10.0.130                                  netcdf/4.6.1/parallel/openmpi/3.1.2/pgi/18.10  pgi/18.10  
hdf5/1.10.3/parallel/openmpi/3.1.2/pgi/18.10   netcdf/4.6.1/serial/gcc/6.4.0                  
hdf5/1.10.3/serial/pgi/18.10                   netcdf/4.6.1/serial/gcc/8.2.0                  
netcdf/4.6.1/parallel/openmpi/3.1.2/gcc/6.4.0  netcdf/4.6.1/serial/pgi/18.10                  
netcdf/4.6.1/parallel/openmpi/3.1.2/gcc/8.2.0  openmpi/3.1.2/pgi/18.10        
```
reran the same complete spec as originally listed above, this time with a clean slate, it built everything fine up until mvapich2, this is the output:
```==> Installing mvapich2
==> Searching for binary cache of mvapich2
==> Finding buildcaches in /apps/spack-mirror/build_cache
==> No binary for mvapich2 found: installing from source
==> Warning: A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
==> Warning: Could not detect module function from bash. Trying to detect modulecmd from `which`
==> Using cached archive: /apps/spack/var/spack/cache/mvapich2/mvapich2-2.3.tar.gz
==> Staging archive: /apps/spack/var/spack/stage/mvapich2-2.3-6rtcptvvwee5eontraexe2mqpefq27ir/mvapich2-2.3.tar.gz
==> Created stage in /apps/spack/var/spack/stage/mvapich2-2.3-6rtcptvvwee5eontraexe2mqpefq27ir
==> No patches needed for mvapich2
==> Building mvapich2 [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/apps/spack/var/spack/stage/mvapich2-2.3-6rtcptvvwee5eontraexe2mqpefq27ir/mvapich2-2.3/configure' '--prefix=/apps/spack/opt/spack/linux-centos7-x86_64/gcc-6.4.0/mvapich2-2.3-6rtcptvvwee5eontraexe2mqpefq27ir' '--enable-shared' '--enable-romio' '--disable-silent-rules' '--disable-new-dtags' '--enable-fortran=all' '--enable-threads=multiple' '--with-ch3-rank-bits=32' '--disable-alloca' '--enable-fast=all' '--enable-cuda' '--with-cuda=/apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-10.0.130-kqvlz4iqfrzow5vznahf4cted6fpxm3w' '--enable-registration-cache' '--with-device=ch3:psm' '--with-psm=/apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/psm-3.3-3n4557pruwwynqxsqexewb6qw6bsgex3' '--with-file-system=nfs'

3 errors found in build log:
     935    checking whether make supports nested variables... yes
     936    checking whether to enable maintainer-specific portions of Makefiles... yes
     937    checking for style of include used by make... GNU
     938    checking whether the C compiler works... yes
     939    checking for C compiler default output file name... a.out
     940    checking for suffix of executables...
  >> 941    checking whether we are cross compiling... configure: error: in `/tmp/root/spack-stage/spack-stage-pLl
            fxO/mvapich2-2.3/src/mpi/romio':
  >> 942    configure: error: cannot run C compiled programs.
     943    If you meant to cross compile, use `--host'.
     944    See `config.log' for more details
  >> 945    configure: error: src/mpi/romio configure failed

See build log for details:
  /apps/spack/var/spack/stage/mvapich2-2.3-6rtcptvvwee5eontraexe2mqpefq27ir/mvapich2-2.3/spack-build.out
```
```
# which modulecmd
/apps/modules/bin/modulecmd
```

**Comment by mwkrentel** [comment]
So, it fails with the same error message.  That's too bad.

I still think it's correct to specify the module as you have done.
(That is, it's incorrect without it.)  But clearly it's failing for a
different reason.

In that case, I think I'm out of ideas.  Sorry.  You could try the
spack slack channel.  This is mentioned in the spack readthedocs
somewhere.

**Comment by jrood-nrel** [comment]
Can you show the `config.log` that shows why the test C program is failing when it tries to run it?
