### ISSUE TITLE
Module command not found

### ISSUE THREAD

**Issue by floli** [spack/spack#10768]
Hello,

spack doesn't seem to like my module system which I need to load for the compiler:

```
spack.util.module_cmd.ModuleError: get_module_cmd cannot determine the module command from bash
spack.util.module_cmd.ModuleError: `which` did not find any modulecmd executable
spack.util.module_cmd.ModuleError: Spack requires modulecmd or a defined module function. Make sure modulecmd is in your path or the function "module" is defined in your bash environment.
```
see below for full output.

```
> . ~/work/software/spack/share/spack/setup-env.sh 

> cat .spack/linux/compilers.yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles11
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: null
      fc: null
    spec: gcc@4.3
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: [gcc/7]
    operating_system: sles11
    paths:
      cc: /lrz/mnt/sys.x86_64/compilers/gcc/7.3.0/bin/gcc
      cxx: /lrz/mnt/sys.x86_64/compilers/gcc/7.3.0/bin/g++
      f77: /lrz/mnt/sys.x86_64/compilers/gcc/7.3.0/bin/gfortran
      fc: /lrz/mnt/sys.x86_64/compilers/gcc/7.3.0/bin/gfortran
    spec: gcc@7.3.0
    target: x86_64
[...]
```
I have modified the `compilers.yaml` by adding the `modules` entry for gcc 7.3.0, which I use to load the compiler on the SuperMUC HPC system.

Because outgoing internet connection is not allowed, I have created a mirror and added it.

Now, trying to install something gives me:

```
> spack -d --stacktrace install cmake
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/config.py:681 ==> [2019-03-01-10:46:16.879782] Reading config file /gpfs/work/xxx/yyy/software/spack/etc/spack/defaults/modules.yaml
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/config.py:681 ==> [2019-03-01-10:46:16.919323] Reading config file /gpfs/work/xxx/yyy/software/spack/etc/spack/defaults/linux/modules.yaml
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/config.py:681 ==> [2019-03-01-10:46:16.940892] Reading config file /gpfs/work/xxx/yyy/software/spack/etc/spack/defaults/config.yaml
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/config.py:681 ==> [2019-03-01-10:46:17.258166] Reading config file /gpfs/work/xxx/yyy/software/spack/etc/spack/defaults/repos.yaml
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/config.py:681 ==> [2019-03-01-10:46:20.397862] Reading config file /gpfs/work/xxx/yyy/software/spack/etc/spack/defaults/packages.yaml
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:20.484523] READ LOCK: /home/hpc/xxx/yyy/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquiring]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:20.502559] READ LOCK: /home/hpc/xxx/yyy/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquired]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:20.538830] READ LOCK: /home/hpc/xxx/yyy/.spack/cache/providers/.builtin-index.json.lock[0:0] [Released]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:20.545962] READ LOCK: /home/hpc/xxx/yyy/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquiring]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:20.547808] READ LOCK: /home/hpc/xxx/yyy/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquired]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:20.565254] READ LOCK: /home/hpc/xxx/yyy/.spack/cache/patches/.builtin-index.json.lock[0:0] [Released]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:20.571960] READ LOCK: /home/hpc/xxx/yyy/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquiring]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:20.573883] READ LOCK: /home/hpc/xxx/yyy/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquired]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:20.575242] READ LOCK: /home/hpc/xxx/yyy/.spack/cache/tags/.builtin-index.json.lock[0:0] [Released]
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/config.py:681 ==> [2019-03-01-10:46:20.597968] Reading config file /home/hpc/xxx/yyy/.spack/linux/compilers.yaml
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/database.py:192 ==> [2019-03-01-10:46:22.772694] DATABASE LOCK TIMEOUT: 120s
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/database.py:196 ==> [2019-03-01-10:46:22.773328] PACKAGE LOCK TIMEOUT: No timeout
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.783844] WRITE LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[1886061678766783786:1] [Acquiring]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.786239] WRITE LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[1886061678766783786:1] [Acquired]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.786963] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.788973] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.790899] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/lock[0:0] [Released]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.809330] WRITE LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[1886061678766783786:1] [Released]
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/stage.py:477 ==> [2019-03-01-10:46:22.864680] link /gpfs/work/xxx/yyy/software/spack/var/spack/stage/cmake-3.13.4-grmumnkgxx5fklmtb6qc45525mh5puxi -> /tmp/yyy/spack-stage/spack-stage-moejk3k1
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.865707] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[1886061678766783786:1] [Acquiring]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.866714] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[1886061678766783786:1] [Acquired]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.868062] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[1886061678766783786:1] [Released]
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/package.py:1397 ==> [2019-03-01-10:46:22.868691] Installing cmake dependencies
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.871987] WRITE LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[8101021379126344853:1] [Acquiring]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.872580] WRITE LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[8101021379126344853:1] [Acquired]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.872941] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.873533] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.874111] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/lock[0:0] [Released]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.874876] WRITE LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[8101021379126344853:1] [Released]
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/stage.py:477 ==> [2019-03-01-10:46:22.879323] link /gpfs/work/xxx/yyy/software/spack/var/spack/stage/diffutils-3.7-4dmtqc7jk54svfpk6rzpdj5rhuymk45r -> /tmp/yyy/spack-stage/spack-stage-kzxi67cf
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.879978] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[8101021379126344853:1] [Acquiring]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.880560] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[8101021379126344853:1] [Acquired]
gpfs/work/xxx/yyy/software/spack/lib/spack/llnl/util/lock.py:334 ==> [2019-03-01-10:46:22.881286] READ LOCK: /gpfs/work/xxx/yyy/software/spack/opt/spack/.spack-db/prefix_lock[8101021379126344853:1] [Released]
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/package.py:1413 ==> [2019-03-01-10:46:22.881700] Installing diffutils
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/package.py:1308 ==> [2019-03-01-10:46:22.881951] Searching for binary cache of diffutils
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/config.py:681 ==> [2019-03-01-10:46:22.884961] Reading config file /home/hpc/xxx/yyy/.spack/linux/mirrors.yaml
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/binary_distribution.py:606 ==> [2019-03-01-10:46:22.888282] Finding buildcaches in /home/hpc/xxx/yyy/work/spack-mirror-2019-02-27//build_cache
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/package.py:1424 ==> [2019-03-01-10:46:22.941617] No binary for diffutils found: installing from source
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/build_environment.py:694 ==> [2019-03-01-10:46:23.090952] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py:120 ==> [2019-03-01-10:46:23.107854] Loading module: gcc/7
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py:22 ==> [2019-03-01-10:46:23.130498] Warning: Could not detect module function from bash. Trying to detect modulecmd from `which`
gpfs/work/xxx/yyy/software/spack/lib/spack/spack/error.py:55 ==> [2019-03-01-10:46:23.162787] Error: ModuleError: Spack requires modulecmd or a defined module function. Make sure modulecmd is in your path or the function "module" is defined in your bash environment.

/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/build_environment.py:787, in child_process:
        784            tb_string = traceback.format_exc()
        785
        786            # build up some context from the offending package so we can
  >>    787            # show that, too.
        788            package_context = get_package_context(tb)
        789
        790            build_log = None


Traceback (most recent call last):
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py", line 64, in get_module_cmd_from_bash
    find_exec = re.search(r'.*`(.*(:? bash | sh ).*)`.*', module_func)
  File "/lrz/sys/tools/python/intelpython35_u4/intelpython3/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py", line 70, in get_module_cmd_from_bash
    module_func)
  File "/lrz/sys/tools/python/intelpython35_u4/intelpython3/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py", line 19, in get_module_cmd
    return get_module_cmd_from_bash(bashopts)
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py", line 73, in get_module_cmd_from_bash
    raise ModuleError('get_module_cmd cannot '
spack.util.module_cmd.ModuleError: get_module_cmd cannot determine the module command from bash

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py", line 25, in get_module_cmd
    return get_module_cmd_from_which()
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py", line 36, in get_module_cmd_from_which
    raise ModuleError('`which` did not find any modulecmd executable')
spack.util.module_cmd.ModuleError: `which` did not find any modulecmd executable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/build_environment.py", line 769, in child_process
    setup_package(pkg, dirty=dirty)
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/build_environment.py", line 717, in setup_package
    load_module(mod)
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py", line 123, in load_module
    modulecmd = get_module_cmd()
  File "/gpfs/work/xxx/yyy/software/spack/lib/spack/spack/util/module_cmd.py", line 27, in get_module_cmd
    raise ModuleError('Spack requires modulecmd or a defined module'
spack.util.module_cmd.ModuleError: Spack requires modulecmd or a defined module function. Make sure modulecmd is in your path or the function "module" is defined in your bash environment.
```
```
> uname -a
Linux login22 3.0.101-108.77-default #1 SMP Mon Oct 1 13:13:39 UTC 2018 (4733e02) x86_64 x86_64 x86_64 GNU/Linux
```
The `module` command works out of the box in my bash environment, `set` shows me, it is defined as a bash function:
```
module () 
{ 
    moduleraw $* 2>&1
}
moduleraw () 
{ 
    eval `/usr/bin/tclsh $MODULE_BIN/modulecmd.tcl bash $*`
}
```

This is a follow up from https://github.com/spack/spack/issues/10574, which has went away from it's original question.

Thanks!

**Comment by alalazo** [comment]
Is this a duplicate of #8193, which would be solved by #8570 or something different?

**Comment by floli** [comment]
I think #8570 fixes it. This particular error went away, but know spack doesn't recognize the mirror I have created, likely because the package versions have changed.

Unfortunately, the `use-module-interface` brach doesn't work on the system I use to create the mirror (`RecursionError: maximum recursion depth exceeded in comparison`), so I can't test it further.

**Comment by alalazo** [comment]
Duplicate of #8193
