### ISSUE TITLE
Spack attempts to execute error messages generated when manipulating module system

### ISSUE THREAD

**Issue by frankwillmore** [spack/spack#11035]
Attempting to get a spec for hdf5 on a compute node on cray XC-40 system (theta).

It appears spack makes calls to the module system to manipulate the environment, but when the module system generates warning messages, it doesn't recognize them as such and attempts to execute the error messages as if they were valid python. 

### Steps to reproduce the issue

```console
$ spack -d spec hdf5 arch=cray-cnl6-mic_knl
```

### Error Message

```console
Traceback (most recent call last):
  File "/soft/spack/spack-dev/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/main.py", line 675, in main
    return _invoke_command(command, parser, args, unknown)
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/main.py", line 446, in _invoke_command
    return_val = command(parser, args)
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/cmd/spec.py", line 76, in spec
    spec.concretize()
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/spec.py", line 1977, in concretize
    load_module(mod)
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/util/module_cmd.py", line 134, in load_module
    unload_module(text[i + 1])
  File "/lus/theta-fs0/software/spack/spack-dev/lib/spack/spack/util/module_cmd.py", line 108, in unload_module
    exec(compile(unload_output, '<string>', 'exec'))
  File "<string>", line 534
    craype-mic-knl requires cce/8.4 or later, intel/14.0 or later, or gcc/5.1 or later
                          ^
SyntaxError: invalid syntax
```

### Information on your system
Cray XC-40 (theta)

**Comment by wscullin** [comment]
@FrankD412 Which release / pull of Spack are you working against. This should be solved. Please see #3153 and then #10597

**Comment by frankwillmore** [comment]
I pulled the latest commit:

commit a6511fbafcf16dd60d424e9d31b667339857628a
Author: Peter Scheibel <scheibel1@llnl.gov>
Date:   Thu Mar 28 11:25:44 2019 -0700

and I still see this issue.

**Comment by wscullin** [comment]
So, the message comes out of Cray's craype-mic-knl module. Can you share the output of:

`module list`

and 

`spack arch`

and

`echo ${CRAY_CPU_TARGET}`

as mentioned, in #3153, there was logic added that should load cce, bypassing bad logic in the craype-mic-knl module. It's checking in the environment for "CRAY_CPU_TARGET" to be "mic-knl", if it's not for some reason, then the cce load won't take place. I'm trying to figure out why that test is failing in your environment.

**Comment by frankwillmore** [comment]
After reading the related posts, I was able to manipulate the module system by hand, and get the spec to render. 

My point is, spack is executing arbitrary code generated by the module system without verifying whether it is valid python and is generating an unchecked fatal error. 

Might pylint or pyflakes be appropriate?

**Comment by alalazo** [comment]
Closing since `platfrom=cray` has been removed from Spack, and theta has been retired.
