### ISSUE TITLE
When reading an older install database,  a system package defined in  packages.yaml triggers an error because prefix is defined as None 

### ISSUE THREAD

**Issue by gartung** [spack/spack#11033]
```

==> [2019-03-28-09:45:40.882685] Error: RuntimeError: Unable to locate perl command in None/bin

/scratch/gartung/work/spack/var/spack/repos/builtin/packages/perl/package.py:194, in setup_dependent_package:
        191        """
        192
        193        # perl extension builds can have a global perl executable function
  >>    194        module.perl = self.spec['perl'].command
        195
        196        # Add variables for library directory
        197        module.perl_lib_dir = dependent_spec.prefix.lib.perl5


Traceback (most recent call last):
  File "/scratch/gartung/work/spack/lib/spack/spack/build_environment.py", line 766, in child_process
    setup_package(pkg, dirty=dirty)
  File "/scratch/gartung/work/spack/lib/spack/spack/build_environment.py", line 687, in setup_package
    dpkg.setup_dependent_package(pkg.module, spec)
  File "/scratch/gartung/work/spack/var/spack/repos/builtin/packages/perl/package.py", line 195, in setup_dependent_package
  File "/scratch/gartung/work/spack/lib/spack/spack/spec.py", line 810, in __get__
    value = f()
  File "/scratch/gartung/work/spack/lib/spack/spack/spec.py", line 802, in <lambda>
    callbacks_chain.append(lambda: self.default(self, instance, cls))
  File "/scratch/gartung/work/spack/lib/spack/spack/spec.py", line 654, in _command_default_handler
    raise RuntimeError(msg.format(spec.name, spec.prefix.bin))
RuntimeError: Unable to locate perl command in None/bin
```

**Comment by gartung** [comment]
This may be an artifact of using an existing spack install where system perl was added to the database in the old format. Reindexing seems to have fixed this.

**Comment by gartung** [comment]
@scheibelp

**Comment by gartung** [comment]
I ran into a similar problem with ftgl and mesa-glu as a provider for glu, a dependency in the ROOT package.
