### ISSUE TITLE
'spack location' command fails

### ISSUE THREAD

**Issue by scottwittenburg** [spack/spack#11105]
After installing a package (in this case, `diffutils`, but also tried with other packages), asking spack for the location of that packages results in an error.  I tested all the arguments to `spack location`, and it seems it's the `--build-dir` one that causes the problem.

### Steps to reproduce the issue

Checking what packages I have so far, it's pretty clean.

```console
$ spack find
==> 0 installed packages
```

Now install a basic package.

```
$ spack install diffutils
==> Installing diffutils
==> Searching for binary cache of diffutils
==> Finding buildcaches on https://mirror.spack.io
==> No binary for diffutils found: installing from source
==> Using cached archive: /data/scott/projects/spack/var/spack/cache/diffutils/diffutils-3.7.tar.xz
==> Staging archive: /data/scott/projects/spack/var/spack/stage/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il/diffutils-3.7.tar.xz
==> Created stage in /data/scott/projects/spack/var/spack/stage/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il
==> No patches needed for diffutils
==> Building diffutils [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed diffutils
  Fetch: 0.01s.  Build: 33.05s.  Total: 33.06s.
[+] /data/scott/projects/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il
```

Now run the `spack location` command on that spec.

```
$ spack location diffutils
==> Error: [Errno 2] No such file or directory: '/data/scott/projects/spack/var/spack/stage/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il'
```

Try the other arguments to see if any of them work.

```
$ spack location --module-dir diffutils
/data/scott/projects/spack/lib/spack/spack
$ spack location --spack-root
/data/scott/projects/spack
$ spack location --install-dir diffutils
/data/scott/projects/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il
$ spack location --package-dir diffutils
/data/scott/projects/spack/var/spack/repos/builtin/packages/diffutils
$ spack location --packages
/data/scott/projects/spack/var/spack/repos/builtin
$ spack location --stage-dir diffutils
/data/scott/projects/spack/var/spack/stage/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il
$ spack location --stages
/data/scott/projects/spack/var/spack/stage
$ spack location --build-dir diffutils
==> Error: [Errno 2] No such file or directory: '/data/scott/projects/spack/var/spack/stage/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il'
```

### Error Message

Run that last command again to get the stack trace.

```
$ spack -d location --build-dir diffutils
==> [2019-04-03-12:10:23.291452] Imported location from built-in commands
==> [2019-04-03-12:10:23.293459] Imported location from built-in commands
==> [2019-04-03-12:10:23.344303] Reading config file /data/scott/projects/spack/etc/spack/defaults/modules.yaml
==> [2019-04-03-12:10:23.355828] Reading config file /data/scott/projects/spack/etc/spack/defaults/linux/modules.yaml
==> [2019-04-03-12:10:23.359239] Reading config file /data/scott/projects/spack/etc/spack/defaults/config.yaml
==> [2019-04-03-12:10:23.372371] Reading config file /home/scott/.spack/config.yaml
==> [2019-04-03-12:10:23.390068] Reading config file /data/scott/projects/spack/etc/spack/defaults/repos.yaml
==> [2019-04-03-12:10:23.439136] Reading config file /data/scott/projects/spack/etc/spack/defaults/packages.yaml
==> [2019-04-03-12:10:23.461014] Reading config file /home/scott/.spack/packages.yaml
==> [2019-04-03-12:10:23.469425] READ LOCK: /home/scott/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquiring]
==> [2019-04-03-12:10:23.469652] READ LOCK: /home/scott/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquired]
==> [2019-04-03-12:10:23.470192] READ LOCK: /home/scott/.spack/cache/tags/.builtin-index.json.lock[0:0] [Released]
==> [2019-04-03-12:10:23.473840] READ LOCK: /home/scott/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquiring]
==> [2019-04-03-12:10:23.474031] READ LOCK: /home/scott/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquired]
==> [2019-04-03-12:10:23.488062] READ LOCK: /home/scott/.spack/cache/patches/.builtin-index.json.lock[0:0] [Released]
==> [2019-04-03-12:10:23.491552] READ LOCK: /home/scott/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquiring]
==> [2019-04-03-12:10:23.491732] READ LOCK: /home/scott/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquired]
==> [2019-04-03-12:10:23.523688] READ LOCK: /home/scott/.spack/cache/providers/.builtin-index.json.lock[0:0] [Released]
==> [2019-04-03-12:10:23.531009] Reading config file /home/scott/.spack/linux/compilers.yaml
Traceback (most recent call last):
  File "/data/scott/projects/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/data/scott/projects/spack/lib/spack/spack/main.py", line 695, in main
    return _invoke_command(command, parser, args, unknown)
  File "/data/scott/projects/spack/lib/spack/spack/main.py", line 446, in _invoke_command
    return_val = command(parser, args)
  File "/data/scott/projects/spack/lib/spack/spack/cmd/location.py", line 110, in location
    if not pkg.stage.source_path:
  File "/data/scott/projects/spack/lib/spack/spack/stage.py", line 582, in source_path
    return self[0].source_path
  File "/data/scott/projects/spack/lib/spack/spack/stage.py", line 341, in source_path
    for p in [os.path.join(self.path, f) for f in os.listdir(self.path)]:
OSError: [Errno 2] No such file or directory: '/data/scott/projects/spack/var/spack/stage/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il'
```

Based on that information, I tried doing the install again, this time with `--keep-stage`, and after that, I no longer saw the error.

```
$ spack uninstall --all
==> The following packages will be uninstalled:

    -- linux-ubuntu16.04-x86_64 / gcc@5.5.0 -------------------------
    ds255jv diffutils@3.7%gcc
==> Do you want to proceed? [y/N] y
==> Successfully uninstalled diffutils@3.7%gcc@5.5.0 arch=linux-ubuntu16.04-x86_64 /ds255jv
$ spack find
==> 0 installed packages
$ spack install --keep-stage diffutils
==> Installing diffutils
==> Searching for binary cache of diffutils
==> Finding buildcaches on https://mirror.spack.io
==> No binary for diffutils found: installing from source
==> Using cached archive: /data/scott/projects/spack/var/spack/cache/diffutils/diffutils-3.7.tar.xz
==> Staging archive: /data/scott/projects/spack/var/spack/stage/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il/diffutils-3.7.tar.xz
==> Created stage in /data/scott/projects/spack/var/spack/stage/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il
==> No patches needed for diffutils
==> Building diffutils [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed diffutils
  Fetch: 0.01s.  Build: 34.18s.  Total: 34.19s.
[+] /data/scott/projects/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.5.0/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il
$ spack location diffutils
/data/scott/projects/spack/var/spack/stage/diffutils-3.7-ds255jvufrjssbbpyjkg5wuweiodk7il/diffutils-3.7
```

### Information on your system

Platform: Linux Ubuntu 16.04 (x86_64)

Custom packages.yaml:

```
$ cat ~/.spack/packages.yaml 
packages:
  opengl:
    paths:
      opengl@4.5.0: /opt/opengl
    buildable: False
```

Compilers:

```
$ spack compilers
==> Available compilers
-- gcc ubuntu16.04-x86_64 ---------------------------------------
gcc@5.5.0  gcc@5.4.0  gcc@4.9.3  gcc@4.8
```

**Comment by s-sajid-ali** [comment]
I think the [issue](https://github.com/spack/spack/issues/11086) I'm seeing is related since I get a similar error for `spack location ...`

**Comment by tgamblin** [comment]
By default, `spack location` gives you the location of the build directory, under `/var/spack/stage`.  So, this is expected behavior, as the build directory is removed after installation.

The main reason for this default, at least originally is so that `spack cd` takes you to the build directory by default (`spack cd` uses `spack location`).  If you have a build error you can do this:

```bash
$ spack stage <spec>
$ spack cd <spec>
$ spack env <spec> bash
$ <run build commands in the build area to debug>
```

I have thought for a while that a more sensible default for `spack location` would be to find the installation directory (so basically change the default from `-b` to `-i`), but the worry is that this would break peoples' existing scripts.  The above workflow would need to change to use `spack cd -b`, and existing usage of `spack location` with no arguments would also need to add `-b`.

I have a feeling `spack location -i` is much more commonly used, and this wouldn't change its behavior.

Do people have opinions about this?  Is this something we should change?

**Comment by sethrj** [comment]
I'm definitely in favor of `spack location` and `spack cd` defaulting to `-i`. Maybe have a short deprecation period where the default is `build` but it prints a warning if you don't use `-b`? Maybe a configure option?

**Comment by alalazo** [comment]
@tgamblin +1 to have `-i` as default for `spack location`.

**Comment by alalazo** [comment]
Ok, I marked this `not-a-bug` because of https://github.com/spack/spack/issues/11105#issuecomment-480333781 but I would say that `spack location` still has issues (besides the specific one reported here):
```console
$ spack location --help
usage: spack location [-h] [-m | -r | -i | -p | -P | -s | -S | --source-dir | -b | -e [name]] ...

print out locations of packages and spack directories

positional arguments:
  spec                  package spec

optional arguments:
  --source-dir          source directory for a spec (requires it to be staged first)
  -P, --packages        top-level packages directory for Spack
  -S, --stages          top level stage directory
  -b, --build-dir       build directory for a spec (requires it to be staged first)
  -e [name], --env [name]
                        location of the named or current environment
  -h, --help            show this help message and exit
  -i, --install-dir     install prefix for spec (spec need not be installed) <---
  -m, --module-dir      spack python module directory
  -p, --package-dir     directory enclosing a spec's package.py file
  -r, --spack-root      spack installation root
  -s, --stage-dir       stage directory for a spec

$ spack location -i hdf5
==> Error: Spec 'hdf5' matches no installed packages.
```
