### ISSUE TITLE
cannot source share/setup-env.csh on LANL trinitite

### ISSUE THREAD

**Issue by jhnlvsq** [spack/spack#11506]
tt-fey1 spack_5-15/spack> source share/spack/setup-env.csh
Traceback (most recent call last):
  File "/lustre/ttscratch1/levesque/spack_5-15/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/lustre/ttscratch1/levesque/spack_5-15/spack/lib/spack/spack/main.py", line 640, in main
    print_setup_info(*args.print_shell_vars.split(','))
  File "/lustre/ttscratch1/levesque/spack_5-15/spack/lib/spack/spack/main.py", line 576, in print_setup_info
    shell_set('_sp_sys_type', spack.architecture.sys_type())
  File "/lustre/ttscratch1/levesque/spack_5-15/spack/lib/spack/llnl/util/lang.py", line 184, in _memoized_function
    func.cache[args] = func(*args)
  File "/lustre/ttscratch1/levesque/spack_5-15/spack/lib/spack/spack/architecture.py", line 494, in sys_type
    arch = Arch(platform(), 'default_os', 'default_target')
  File "/lustre/ttscratch1/levesque/spack_5-15/spack/lib/spack/llnl/util/lang.py", line 184, in _memoized_function
    func.cache[args] = func(*args)
  File "/lustre/ttscratch1/levesque/spack_5-15/spack/lib/spack/spack/architecture.py", line 478, in platform
    return platform_cls()
  File "/lustre/ttscratch1/levesque/spack_5-15/spack/lib/spack/spack/platforms/cray.py", line 67, in __init__
    self.add_target(name, self.targets[safe_name])
KeyError: u'haswell'
_sp_tcl_roots: Undefined variable.
_sp_dotkit_roots: Undefined variable.

**Comment by hainest** [comment]
@jhnlvsq I have found on Cori at NERSC that you must have the `craype-haswell` module loaded for Spack to find the haswell architecture information.

**Comment by plamborn** [comment]
I previously was successful using spack on Trinitite, but now I get this same error.  The error is the same with our without the craype-haswell module loaded.

**Comment by alalazo** [comment]
I'm going through old issues. Is this still a problem?

**Comment by jhnlvsq** [comment]
no

From: Massimiliano Culpo ***@***.***>
Date: Tuesday, June 6, 2023 at 1:18 PM
To: spack/spack ***@***.***>
Cc: ***@***.*** ***@***.***>, Mention ***@***.***>
Subject: Re: [spack/spack] cannot source share/setup-env.csh on LANL trinitite (#11506)

I'm going through old issues. Is this still a problem?
