### ISSUE TITLE
Issue setting up Spack on Stampede2

### ISSUE THREAD

**Issue by qobilidop** [spack/spack#11522]
I'm trying to set up Spack on Stampede2, with system Intel compiler and MPI, but couldn't make it work. I have asked for help [on the mailing list](https://groups.google.com/d/msg/spack/VSZqELYczok/09O4TV13AgAJ), but didn't get it resolved there. Probably email is not as effective a media as GitHub issue tracker for this kind of discussion. So I decided to report it here.

### Steps to reproduce the issue

```console
$ spack install mpi
==> intel-mpi@2018.2.199 : has external module in impi/18.0.2
==> intel-mpi@2018.2.199 : is actually installed in /opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64
==> intel-mpi@2018.2.199 : generating module file
('debug', '() {  if [ -z "${LMOD_SH_DBG_ON+x}" ]; then\n case "$-" in \n *v*x*)\n __lmod_sh_dbg=\'vx\'\n ;;\n *v*)\n __lmod_sh_dbg=\'v\'\n ;;\n *x*)\n __lmod_sh_dbg=\'x\'\n ;;\n esac;\n fi;\n if [ -n "${__lmod_sh_dbg')
==> Error: Error: unterminated ${ in format:'() {  if [ -z "${LMOD_SH_DBG_ON+x}" ]; then
 case "$-" in 
 *v*x*)
 __lmod_sh_dbg='vx'
 ;;
 *v*)
 __lmod_sh_dbg='v'
 ;;
 *x*)
 __lmod_sh_dbg='x'
 ;;
 esac;
 fi;
 if [ -n "${__lmod_sh_dbg'
```

### Error Message

```console
$ spack -d --stacktrace install mpi
lib/spack/spack/config.py:683 ==> [2019-05-21-00:04:23.068180] Reading config file /home1/03560/tg828592/opt/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:683 ==> [2019-05-21-00:04:23.075014] Reading config file /home1/03560/tg828592/opt/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:683 ==> [2019-05-21-00:04:23.077788] Reading config file /home1/03560/tg828592/opt/spack/etc/spack/defaults/config.yaml
lib/spack/spack/cmd/__init__.py:98 ==> [2019-05-21-00:04:23.092772] Imported install from built-in commands
lib/spack/spack/cmd/__init__.py:98 ==> [2019-05-21-00:04:23.093802] Imported install from built-in commands
lib/spack/spack/config.py:683 ==> [2019-05-21-00:04:23.102649] Reading config file /home1/03560/tg828592/opt/spack/etc/spack/defaults/repos.yaml
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.175080] READ LOCK: /home1/03560/tg828592/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.175764] READ LOCK: /home1/03560/tg828592/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.176624] READ LOCK: /home1/03560/tg828592/.spack/cache/tags/.builtin-index.json.lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.178966] READ LOCK: /home1/03560/tg828592/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.179620] READ LOCK: /home1/03560/tg828592/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.187958] READ LOCK: /home1/03560/tg828592/.spack/cache/patches/.builtin-index.json.lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.190317] READ LOCK: /home1/03560/tg828592/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.190948] READ LOCK: /home1/03560/tg828592/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.207350] READ LOCK: /home1/03560/tg828592/.spack/cache/providers/.builtin-index.json.lock[0:0] [Released]
lib/spack/spack/config.py:683 ==> [2019-05-21-00:04:23.215037] Reading config file /home1/03560/tg828592/opt/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:683 ==> [2019-05-21-00:04:23.225054] Reading config file /home1/03560/tg828592/.spack/packages.yaml
lib/spack/spack/config.py:683 ==> [2019-05-21-00:04:23.256745] Reading config file /home1/03560/tg828592/.spack/compilers.yaml
lib/spack/spack/util/module_cmd.py:112 ==> [2019-05-21-00:04:23.429715] Module name: impi/18.0.2
lib/spack/spack/util/module_cmd.py:119 ==> [2019-05-21-00:04:23.430045] Package directory variable prefix: IMPI
lib/spack/spack/package.py:1280 ==> [2019-05-21-00:04:23.433942] intel-mpi@2018.2.199 : has external module in impi/18.0.2
lib/spack/spack/package.py:1282 ==> [2019-05-21-00:04:23.434177] intel-mpi@2018.2.199 : is actually installed in /opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64
lib/spack/spack/database.py:214 ==> [2019-05-21-00:04:23.436924] DATABASE LOCK TIMEOUT: 120s
lib/spack/spack/database.py:218 ==> [2019-05-21-00:04:23.437221] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.437929] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.438622] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.440015] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.440560] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.441202] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.442337] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/spack/package.py:1300 ==> [2019-05-21-00:04:23.443226] intel-mpi@2018.2.199 : generating module file
lib/spack/spack/hooks/sbang.py:102 ==> [2019-05-21-00:04:23.443938] SKIP: shebang filtering [external package]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.444753] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.445396] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.446628] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.447245] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.447963] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.449151] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/spack/modules/common.py:709 ==> [2019-05-21-00:04:23.450514]  WRITE: intel-mpi@2018.2.199%intel@18.0.2 arch=linux-centos7-x86_64/gzav7jv [/home1/03560/tg828592/opt/spack/share/spack/modules/linux-centos7-x86_64/intel-mpi-2018.2.199-intel-18.0.2-gzav7jv]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.466402] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.467111] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-05-21-00:04:23.468208] READ LOCK: /home1/03560/tg828592/opt/spack/opt/spack/.spack-db/lock[0:0] [Released]
lib/spack/spack/build_systems/intel.py:41 ==> [2019-05-21-00:04:23.501325] normalize_path.normalize_suite_dir:  /opt/intel/compilers_and_libraries_2018.2.199
lib/spack/spack/build_systems/intel.py:41 ==> [2019-05-21-00:04:23.502480] file_to_source.normalize_path:       /opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpivars.sh
lib/spack/spack/build_systems/intel.py:1002 ==> [2019-05-21-00:04:23.502765] sourcing /opt/intel/compilers_and_libraries_2018.2.199/linux/mpi/intel64/bin/mpivars.sh
('debug', '() {  if [ -z "${LMOD_SH_DBG_ON+x}" ]; then\n case "$-" in \n *v*x*)\n __lmod_sh_dbg=\'vx\'\n ;;\n *v*)\n __lmod_sh_dbg=\'v\'\n ;;\n *x*)\n __lmod_sh_dbg=\'x\'\n ;;\n esac;\n fi;\n if [ -n "${__lmod_sh_dbg')
Traceback (most recent call last):
  File "/home1/03560/tg828592/opt/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/main.py", line 695, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/main.py", line 446, in _invoke_command
    return_val = command(parser, args)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/cmd/install.py", line 334, in install
    install_spec(args, kwargs, abstract, concrete)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/cmd/install.py", line 206, in install_spec
    install(spec, kwargs)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/cmd/install.py", line 195, in install
    spec.package.do_install(**kwargs)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/package.py", line 1406, in do_install
    return self._process_external_package(explicit)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/package.py", line 1301, in _process_external_package
    spack.hooks.post_install(self.spec)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/hooks/__init__.py", line 54, in __call__
    hook(*args, **kwargs)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/hooks/module_file_generation.py", line 29, in <lambda>
    post_install = lambda spec: _for_each_enabled(spec, 'write')
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/hooks/module_file_generation.py", line 22, in _for_each_enabled
    getattr(generator, method_name)()
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/modules/common.py", line 735, in write
    context = self.context.to_dict()
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/tengine.py", line 67, in to_dict
    d = [(name, getattr(self, name)) for name in self.context_properties]
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/modules/common.py", line 615, in environment_modifications
    x.value = self.spec.format(x.value)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/spec.py", line 3107, in format
    return self.old_format(format_string, **kwargs)
  File "/home1/03560/tg828592/opt/spack/lib/spack/spack/spec.py", line 3419, in old_format
    "'%s'" % format_string)
ValueError: Error: unterminated ${ in format:'() {  if [ -z "${LMOD_SH_DBG_ON+x}" ]; then
 case "$-" in 
 *v*x*)
 __lmod_sh_dbg='vx'
 ;;
 *v*)
 __lmod_sh_dbg='v'
 ;;
 *x*)
 __lmod_sh_dbg='x'
 ;;
 esac;
 fi;
 if [ -n "${__lmod_sh_dbg'
```

### Information on your system

platform: [Stampede2](https://www.tacc.utexas.edu/systems/stampede2)

```console
$ module list

Currently Loaded Modules:
  1) git/2.9.0       3) cmake/3.10.2   5) TACC           7) libfabric/1.7.0   9) python2/2.7.15
  2) autotools/1.1   4) xalt/2.6.5     6) intel/18.0.2   8) impi/18.0.2
```

`compilers.yaml`:
```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos7
    paths:
      cc: /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/icc
      cxx: /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/icpc
      f77: /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/ifort
      fc: /opt/intel/compilers_and_libraries_2018.2.199/linux/bin/intel64/ifort
    spec: intel@18.0.2
    target: x86_64
```

`packages.yaml`:
```yaml
packages:
  all:
    compiler: [intel]
    providers:
      mpi: [intel-mpi]
  intel-mpi:
    buildable: False
    modules:
      intel-mpi@2018.2.199: impi/18.0.2
```

**Comment by qobilidop** [comment]
One piece of additional information I could provide is that the string in the error message comes from

```console
BASH_FUNC_module()=() {  if [ -z "${LMOD_SH_DBG_ON+x}" ]; then
 case "$-" in 
 *v*x*)
 __lmod_sh_dbg='vx'
 ;;
 *v*)
 __lmod_sh_dbg='v'
 ;;
 *x*)
 __lmod_sh_dbg='x'
 ;;
 esac;
 fi;
 if [ -n "${__lmod_sh_dbg:-}" ]; then
 set +$__lmod_sh_dbg;
 echo "Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for Lmod's output";
 fi;
 eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh);
 local _lmod_my_status=$?;
 if [ -n "${__lmod_sh_dbg:-}" ]; then
 echo "Shell debugging restarted";
 set -$__lmod_sh_dbg;
 unset __lmod_sh_dbg;
 fi;
 return $_lmod_my_status
}
```

which I believe is set by Spack during `. "$SPACK_ROOT"/share/spack/setup-env.sh`. Somehow mysteriously it gets into the spec string causing the error.

**Comment by qobilidop** [comment]
Good news! I tried using the system mvapich2 module for MPI instead, and it works. So the issue could be very specific to the system impi module.

The mvapich2 package is configured in `packages.yaml` like the following:
```yaml
  mvapich2:
    buildable: False
    modules:
      mvapich2@2.3.1: mvapich2/2.3.1
```
And `spack install mvapich2` works.

**Comment by qobilidop** [comment]
As a side note, I have successfully configured intel compiler + intel mpi on Bridges. The differences between Stampede2 and Bridges I noticed are:

1. Stampede2 is using lmod while Bridges is using environment-modules.
2. There is a separate impi module on Stampede2, while on Bridges intel-mpi is part of the intel module.

Probably these point to where the issue is?

**Comment by qobilidop** [comment]
I have tracked the issue to [this part of code](https://github.com/spack/spack/blob/b13665d06554ab6ef734cb276abc63ba4fe99ce2/lib/spack/spack/modules/common.py#L607). Usually the `x.name` here would be the environment variables modified by module like `PATH`, `CPATH` and the like. But somehow `BASH_FUNC_module()` gets in there.

**Comment by qobilidop** [comment]
Another finding, `BASH_FUNC_module()` in the error message is in a truncated form (stopping at `if [ -n "${__lmod_sh_dbg'`). Does this click with anyone?

**Comment by qobilidop** [comment]
I think I've found the source of the issue. Here's a minimal example to reproduce:

```python
from spack.util.environment import EnvironmentModifications

env = EnvironmentModifications.from_sourcing_file('empty.sh')
for x in env:
    print(x, x.name)
```

On Stampede2, even with an empty file `empty.sh`, the output would be:
```console
(<spack.util.environment.UnsetEnv object at 0x2b77dca85250>, 'PS1')
(<spack.util.environment.RemovePath object at 0x2b77dca85310>, 'BASH_FUNC_module()')
(<spack.util.environment.RemovePath object at 0x2b77dca85390>, 'BASH_FUNC_module()')
(<spack.util.environment.PrependPath object at 0x2b77dca85410>, 'BASH_FUNC_module()')
```

These would eventually be passed to the part of code linked above and cause the trouble. Now I need to figure out what is `EnvironmentModifications.from_sourcing_file` doing.

**Comment by qobilidop** [comment]
I'm very close to solving this issue. Let me summarize what happened first:

- In the step of generating module file, at some point, we are in [`environment_modifications()`](https://github.com/spack/spack/blob/edca0cde1c5e85bb0523fbac824858e434ca67da/lib/spack/spack/modules/common.py#L565).
- There [`self.spec.package.setup_environment(_, env)`](https://github.com/spack/spack/blob/edca0cde1c5e85bb0523fbac824858e434ca67da/lib/spack/spack/modules/common.py#L590) gets called, which in this case is actually [`IntelPackage.setup_environment()`](https://github.com/spack/spack/blob/9d34326992fd467476380474d3101bc26eec16ed/lib/spack/spack/build_systems/intel.py#L984).
- There [`EnvironmentModifications.from_sourcing_file(f, *args)`](https://github.com/spack/spack/blob/9d34326992fd467476380474d3101bc26eec16ed/lib/spack/spack/build_systems/intel.py#L1023) gets called, which as demonstrated above, erroneously includes `'BASH_FUNC_module()'`.

The last hard bit to figure out is why `EnvironmentModifications.from_sourcing_file` behaves this way on Stampede2. As a workaround, I could pass a blacklist to it when it's called
```python
EnvironmentModifications.from_sourcing_file(f, *args, blacklist=['BASH_FUNC_module()'])
```
I could live with this hack for now, but I feel there are still real issues to be solved in that function.

**Comment by qobilidop** [comment]
Just found out that #10753 would solve this issue too! What a journey!

**Comment by becker33** [comment]
Assigning this to @alalazo since his PR #10753 will resolve the issue.

@qobilidop The reason it's specific to Stampede among the machines you work on is the version of TCL modules in use. It looks like new EnvironmentModules v4 does something special with BASH_FUNC_module() and some other variables.
