### ISSUE TITLE
Flags do not propagate correctly [Clang8+Polly]

### ISSUE THREAD

**Issue by termi-official** [spack/spack#11655]
I tried to setup some optimized builds with spack by using LLVM's polyhedral optimizer (polly). Specific optimizations are enabled by passing command line flags (e.g. -O3 -mllvm -polly -mllvm -polly-vectorizer=stripmine) to the toolchain. As a side note, I use LLVM8.0.0 from the spack repository for reproducibility. I tried to pass these flags down via cflags (and cxxflags) and ran into two problems (the full compiler.yaml can be found below):

1. The second "-mllvm" just disappears at some point, leaving "-mllvm -polly -polly-vectorizer=stripmine". This basically results in the build breaking instantaneously. I "resolved" this by removing the second pair of arguments, i.e. "-mllvm -polly-vectorizer=stripmine".
2. Now this hotfix allowed me to build some packages, but I got stuck at building cmake. Thebuild of this dependency failed due to a strange warning, which I could not reproduce when compiling the corresponding files manually via command line.
```console
clang-8: warning: argument unused during compilation: '-mllvm -polly' [-Wunused-command-line-argument]
```

### Steps to reproduce the issue

```console
$ spack install llvm@8.0.0
$ spack module load llvm@8.0.0
$ spack compiler find
```

At this point I manually adjusted the compiler.yaml (see below).

For 1.
```console
$ spack install petsc@3.11.1 %clang@8.0.0 cflags="-O3 -mllvm -polly -mllvm -polly-vectorizer=stripmine -mtune=native -march=native" cxxflags="-O3 -mllvm -polly -mllvm -polly-vectorizer=stripmine -mtune=native -march=native" +fftw +mumps 
```
This one fails immediately.
Note: "-mtune=native -march=native" should be optional. 

For 2.
```console
$ spack install petsc@3.11.1 %clang@8.0.0 cflags="-O3 -mllvm -polly -mtune=native -march=native" cxxflags="-O3 -mllvm -polly -mtune=native -march=native" +fftw +mumps 
```
It also looks like this one is already reproducible simply by building cmake directly, i.e.
```console
$ spack install cmake %clang@8.0.0 cflags="-O3 -mllvm -polly -mtune=native -march=native" cxxflags="-O3 -mllvm -polly -mtune=native -march=native"
``` 

Note: Building petsc withouth cflags and cxxflags as above works fine with
```console
spack install petsc@3.11.1 %clang@8.0.0
```
although I had to patch vtk, tcl, metis and parmetis according to previously reported suggestions issues. These patches seem to not have any effect on the hereby reported issue.

### Error Message

```console
$ spack -d --stacktrace install cmake %clang@8.0.0 cflags="-O3 -mllvm -polly -mtune=native -march=native" cxxflags="-O3 -mllvm -polly -mtune=native -march=native"
```
with the following output
```console
lib/spack/spack/package.py:1449 ==> [2019-06-07-11:09:23.983996] Installing cmake
lib/spack/spack/package.py:1313 ==> [2019-06-07-11:09:23.984114] Searching for binary cache of cmake
lib/spack/spack/binary_distribution.py:598 ==> [2019-06-07-11:09:23.984523] Warning: No Spack mirrors are currently configured
lib/spack/spack/package.py:1460 ==> [2019-06-07-11:09:23.990612] No binary for cmake found: installing from source
lib/spack/spack/build_environment.py:285 ==> [2019-06-07-11:09:24.106631] No libraries found for tar
lib/spack/spack/build_environment.py:299 ==> [2019-06-07-11:09:24.106998] No headers found for tar
lib/spack/spack/build_environment.py:285 ==> [2019-06-07-11:09:24.183962] No libraries found for gettext
lib/spack/spack/build_environment.py:689 ==> [2019-06-07-11:09:24.358744] A dependency has updated CPATH, this may lead pkg-config to assume that the package is part of the system includes and omit it when invoked with '--cflags'.
lib/spack/spack/fetch_strategy.py:442 ==> [2019-06-07-11:09:24.378504] Using cached archive: /home/termi/Repos/spack/var/spack/cache/cmake/cmake-3.14.4.tar.gz
lib/spack/spack/fetch_strategy.py:319 ==> [2019-06-07-11:09:24.387141] Staging archive: /home/termi/Repos/spack/var/spack/stage/cmake-3.14.4-vs2fjyf2i2u2czdzwbzhjb4jzlkd7zbq/cmake-3.14.4.tar.gz
lib/spack/spack/util/executable.py:159 ==> [2019-06-07-11:09:24.388106] '/usr/bin/tar' '-xf' '/home/termi/Repos/spack/var/spack/stage/cmake-3.14.4-vs2fjyf2i2u2czdzwbzhjb4jzlkd7zbq/cmake-3.14.4.tar.gz'
lib/spack/spack/stage.py:447 ==> [2019-06-07-11:09:24.762819] Created stage in /home/termi/Repos/spack/var/spack/stage/cmake-3.14.4-vs2fjyf2i2u2czdzwbzhjb4jzlkd7zbq
lib/spack/spack/package.py:1001 ==> [2019-06-07-11:09:24.763456] No patches needed for cmake
lib/spack/spack/package.py:1484 ==> [2019-06-07-11:09:24.763628] Building cmake [Package]
lib/spack/llnl/util/lock.py:334 ==> [2019-06-07-11:09:24.763961] WRITE LOCK: /home/termi/Repos/spack/var/spack/stage/.lock[8970318281414705665:1] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-06-07-11:09:24.764312] WRITE LOCK: /home/termi/Repos/spack/var/spack/stage/.lock[8970318281414705665:1] [Acquired]
lib/spack/llnl/util/lock.py:334 ==> [2019-06-07-11:09:24.764825] WRITE LOCK: /home/termi/Repos/spack/opt/spack/.spack-db/prefix_lock[6222332497253061840:1] [Acquiring]
lib/spack/llnl/util/lock.py:334 ==> [2019-06-07-11:09:24.765097] WRITE LOCK: /home/termi/Repos/spack/opt/spack/.spack-db/prefix_lock[6222332497253061840:1] [Acquired]
lib/spack/spack/package.py:1525 ==> [2019-06-07-11:09:24.770445] Executing phase: 'bootstrap'
lib/spack/llnl/util/lock.py:334 ==> [2019-06-07-11:09:54.787307] WRITE LOCK: /home/termi/Repos/spack/opt/spack/.spack-db/prefix_lock[6222332497253061840:1] [Released]
lib/spack/llnl/util/lock.py:334 ==> [2019-06-07-11:09:54.788130] WRITE LOCK: /home/termi/Repos/spack/var/spack/stage/.lock[8970318281414705665:1] [Released]
lib/spack/spack/error.py:55 ==> [2019-06-07-11:09:54.794473] Error: ProcessError: Command exited with status 11:
    './bootstrap' '--prefix=/home/termi/Repos/spack/opt/spack/linux-opensuse_leap15-x86_64/clang-8.0.0/cmake-3.14.4-vs2fjyf2i2u2czdzwbzhjb4jzlkd7zbq' '--parallel=32' '--no-system-libs' '--no-qt-gui' '--' '-DCMAKE_USE_OPENSSL=ON'

2 errors found in build log:
     242    -- Checking if compiler supports needed C++17 constructs
     243    -- Checking if compiler supports needed C++17 constructs - yes
     244    -- Checking if compiler supports C++ make_unique
     245    -- Checking if compiler supports C++ make_unique - no
     246    -- Checking if compiler supports C++ unique_ptr
     247    -- Checking if compiler supports C++ unique_ptr - no
  >> 248    CMake Error at CMakeLists.txt:92 (message):
     249      The C++ compiler does not support C++11 (e.g.  std::unique_ptr).
     250    
     251    
     252    -- Configuring incomplete, errors occurred!
     253    See also "/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeOutput.log".
     254    See also "/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeError.log".
     255    ---------------------------------------------
  >> 256    Error when bootstrapping CMake:
     257    Problem while running initial CMake
     258    ---------------------------------------------

See build log for details:
  /home/termi/Repos/spack/var/spack/stage/cmake-3.14.4-vs2fjyf2i2u2czdzwbzhjb4jzlkd7zbq/spack-build.out
Traceback (most recent call last):
  File "/home/termi/Repos/spack/lib/spack/spack/build_environment.py", line 765, in child_process
    return_value = function()
  File "/home/termi/Repos/spack/lib/spack/spack/package.py", line 1530, in build_process
    phase(self.spec, self.prefix)
  File "/home/termi/Repos/spack/lib/spack/spack/package.py", line 102, in phase_wrapper
    phase(spec, prefix)
  File "/home/termi/Repos/spack/var/spack/repos/builtin/packages/cmake/package.py", line 144, in bootstrap
  File "/home/termi/Repos/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
ProcessError: Command exited with status 11:
    './bootstrap' '--prefix=/home/termi/Repos/spack/opt/spack/linux-opensuse_leap15-x86_64/clang-8.0.0/cmake-3.14.4-vs2fjyf2i2u2czdzwbzhjb4jzlkd7zbq' '--parallel=32' '--no-system-libs' '--no-qt-gui' '--' '-DCMAKE_USE_OPENSSL=ON'
```

File content of /home/termi/Repos/spack/var/spack/stage/cmake-3.14.4-vs2fjyf2i2u2czdzwbzhjb4jzlkd7zbq/spack-build.out
```console
lib/spack/spack/package.py:1525 ==> [2019-06-07-11:09:24.770445] Executing phase: 'bootstrap'
lib/spack/spack/util/executable.py:159 ==> [2019-06-07-11:09:24.778282] './bootstrap' '--prefix=/home/termi/Repos/spack/opt/spack/linux-opensuse_leap15-x86_64/clang-8.0.0/cmake-3.14.4-vs2fjyf2i2u2czdzwbzhjb4jzlkd7zbq' '--parallel=32' '--no-system-libs' '--no-qt-gui' '--' '-DCMAKE_USE_OPENSSL=ON'
---------------------------------------------
CMake 3.14.4, Copyright 2000-2019 Kitware, Inc. and Contributors
C compiler on this system is: /home/termi/Repos/spack/lib/spack/env/clang/clang       
C++ compiler on this system is: /home/termi/Repos/spack/lib/spack/env/clang/clang++          
Makefile processor on this system is: gmake
/home/termi/Repos/spack/lib/spack/env/clang/clang++ has setenv
/home/termi/Repos/spack/lib/spack/env/clang/clang++ has unsetenv
/home/termi/Repos/spack/lib/spack/env/clang/clang++ does not have environ in stdlib.h
/home/termi/Repos/spack/lib/spack/env/clang/clang++ has stl wstring
/home/termi/Repos/spack/lib/spack/env/clang/clang++ does not have <ext/stdio_filebuf.h>
---------------------------------------------
/home/termi/Repos/spack/lib/spack/env/clang/clang++              -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Bootstrap.cmk   -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source   -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source/LexerParser   -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Utilities  -c /tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source/cmAddCustomCommandCommand.cxx -o cmAddCustomCommandCommand.o
/home/termi/Repos/spack/lib/spack/env/clang/clang++              -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Bootstrap.cmk   -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source   -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source/LexerParser   -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Utilities  -c /tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source/cmAddCustomTargetCommand.cxx -o cmAddCustomTargetCommand.o
...excluded some noise...
/home/termi/Repos/spack/lib/spack/env/clang/clang++               -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Bootstrap.cmk   -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source   -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source/LexerParser   -I/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Utilities  cmAddCustomCommandCommand.o cmAddCustomTargetCommand.o cmAddDefinitionsCommand.o cmAddDependenciesCommand.o cmAddExecutableCommand.o cmAddLibraryCommand.o cmAddSubDirectoryCommand.o cmAddTestCommand.o cmBreakCommand.o cmBuildCommand.o cmCMakeMinimumRequired.o cmCMakePolicyCommand.o cmCPackPropertiesGenerator.o cmCacheManager.o cmCommand.o cmCommandArgumentParserHelper.o cmCommandArgumentsHelper.o cmCommands.o cmCommonTargetGenerator.o cmComputeComponentGraph.o cmComputeLinkDepends.o cmComputeLinkInformation.o cmComputeTargetDepends.o cmConditionEvaluator.o cmConfigureFileCommand.o cmContinueCommand.o cmCoreTryCompile.o cmCreateTestSourceList.o cmCustomCommand.o cmCustomCommandGenerator.o cmDefinePropertyCommand.o cmDefinitions.o cmDepends.o cmDependsC.o cmDisallowedCommand.o cmDocumentationFormatter.o cmEnableLanguageCommand.o cmEnableTestingCommand.o cmExecProgramCommand.o cmExecuteProcessCommand.o cmExpandedCommandArgument.o cmExportBuildFileGenerator.o cmExportFileGenerator.o cmExportInstallFileGenerator.o cmExportSet.o cmExportSetMap.o cmExportTryCompileFileGenerator.o cmExprParserHelper.o cmExternalMakefileProjectGenerator.o cmFileCommand.o cmFileTimeComparison.o cmFindBase.o cmFindCommon.o cmFindFileCommand.o cmFindLibraryCommand.o cmFindPackageCommand.o cmFindPathCommand.o cmFindProgramCommand.o cmForEachCommand.o cmFunctionCommand.o cmFSPermissions.o cmGeneratedFileStream.o cmGeneratorExpression.o cmGeneratorExpressionContext.o cmGeneratorExpressionDAGChecker.o cmGeneratorExpressionEvaluationFile.o cmGeneratorExpressionEvaluator.o cmGeneratorExpressionLexer.o cmGeneratorExpressionNode.o cmGeneratorExpressionParser.o cmGeneratorTarget.o cmGetCMakePropertyCommand.o cmGetDirectoryPropertyCommand.o cmGetFilenameComponentCommand.o cmGetPropertyCommand.o cmGetSourceFilePropertyCommand.o cmGetTargetPropertyCommand.o cmGetTestPropertyCommand.o cmGlobalCommonGenerator.o cmGlobalGenerator.o cmGlobalUnixMakefileGenerator3.o cmGlobVerificationManager.o cmHexFileConverter.o cmIfCommand.o cmIncludeCommand.o cmIncludeGuardCommand.o cmIncludeDirectoryCommand.o cmIncludeRegularExpressionCommand.o cmInstallCommand.o cmInstallCommandArguments.o cmInstallDirectoryGenerator.o cmInstallExportGenerator.o cmInstallFilesCommand.o cmInstallFilesGenerator.o cmInstallGenerator.o cmInstallScriptGenerator.o cmInstallSubdirectoryGenerator.o cmInstallTargetGenerator.o cmInstallTargetsCommand.o cmInstalledFile.o cmLinkDirectoriesCommand.o cmLinkItem.o cmLinkLineComputer.o cmListCommand.o cmListFileCache.o cmLocalCommonGenerator.o cmLocalGenerator.o cmLocalUnixMakefileGenerator3.o cmMSVC60LinkLineComputer.o cmMacroCommand.o cmMakeDirectoryCommand.o cmMakefile.o cmMakefileExecutableTargetGenerator.o cmMakefileLibraryTargetGenerator.o cmMakefileTargetGenerator.o cmMakefileUtilityTargetGenerator.o cmMarkAsAdvancedCommand.o cmMathCommand.o cmMessageCommand.o cmMessenger.o cmNewLineStyle.o cmOSXBundleGenerator.o cmOptionCommand.o cmOrderDirectories.o cmOutputConverter.o cmParseArgumentsCommand.o cmPathLabel.o cmPolicies.o cmProcessOutput.o cmProjectCommand.o cmProperty.o cmPropertyDefinition.o cmPropertyDefinitionMap.o cmPropertyMap.o cmReturnCommand.o cmRulePlaceholderExpander.o cmScriptGenerator.o cmSearchPath.o cmSeparateArgumentsCommand.o cmSetCommand.o cmSetDirectoryPropertiesCommand.o cmSetPropertyCommand.o cmSetSourceFilesPropertiesCommand.o cmSetTargetPropertiesCommand.o cmSetTestsPropertiesCommand.o cmSiteNameCommand.o cmSourceFile.o cmSourceFileLocation.o cmState.o cmStateDirectory.o cmStateSnapshot.o cmStringReplaceHelper.o cmStringCommand.o cmSubdirCommand.o cmSystemTools.o cmTarget.o cmTargetCompileDefinitionsCommand.o cmTargetCompileFeaturesCommand.o cmTargetCompileOptionsCommand.o cmTargetIncludeDirectoriesCommand.o cmTargetLinkLibrariesCommand.o cmTargetPropCommandBase.o cmTargetPropertyComputer.o cmTargetSourcesCommand.o cmTest.o cmTestGenerator.o cmTimestamp.o cmTryCompileCommand.o cmTryRunCommand.o cmUnexpectedCommand.o cmUnsetCommand.o cmUVHandlePtr.o cmVersion.o cmWhileCommand.o cmWorkingDirectory.o cmake.o cmakemain.o cmcmd.o cm_string_view.o cmCommandArgumentLexer.o cmCommandArgumentParser.o cmExprLexer.o cmExprParser.o cmListFileLexer.o Directory.o EncodingCXX.o FStream.o Glob.o RegularExpression.o SystemTools.o EncodingC.o ProcessUNIX.o String.o System.o Terminal.o uv-src-strscpy.c.o uv-src-timer.c.o uv-src-uv-common.c.o uv-src-unix-cmake-bootstrap.c.o uv-src-unix-core.c.o uv-src-unix-fs.c.o uv-src-unix-loop.c.o uv-src-unix-loop-watcher.c.o uv-src-unix-no-fsevents.c.o uv-src-unix-pipe.c.o uv-src-unix-poll.c.o uv-src-unix-posix-hrtime.c.o uv-src-unix-posix-poll.c.o uv-src-unix-process.c.o uv-src-unix-signal.c.o uv-src-unix-stream.c.o  -ldl -lrt -o cmake
clang-8: warning: argument unused during compilation: '-mllvm -polly' [-Wunused-command-line-argument]
loading initial cache file /tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Bootstrap.cmk/InitialCacheFlags.cmake
-- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
-- Check for working C compiler: /home/termi/Repos/spack/lib/spack/env/clang/clang
-- Check for working C compiler: /home/termi/Repos/spack/lib/spack/env/clang/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/termi/Repos/spack/lib/spack/env/clang/clang++
-- Check for working CXX compiler: /home/termi/Repos/spack/lib/spack/env/clang/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking if compiler supports needed C++17 constructs
-- Checking if compiler supports needed C++17 constructs - yes
-- Checking if compiler supports C++ make_unique
-- Checking if compiler supports C++ make_unique - no
-- Checking if compiler supports C++ unique_ptr
-- Checking if compiler supports C++ unique_ptr - no
CMake Error at CMakeLists.txt:92 (message):
  The C++ compiler does not support C++11 (e.g.  std::unique_ptr).


-- Configuring incomplete, errors occurred!
See also "/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeOutput.log".
See also "/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeError.log".
---------------------------------------------
Error when bootstrapping CMake:
Problem while running initial CMake
---------------------------------------------
```

File content of /tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeError.log
```console
Determining if compiler supports C++ make_unique failed with the following output:
Change Dir: /tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_484f2/fast 
gmake -f CMakeFiles/cmTC_484f2.dir/build.make CMakeFiles/cmTC_484f2.dir/build
gmake[1]: Entering directory '/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_484f2.dir/cm_cxx_make_unique.cxx.o
/home/termi/Repos/spack/lib/spack/env/clang/clang++    -std=gnu++17 -o CMakeFiles/cmTC_484f2.dir/cm_cxx_make_unique.cxx.o -c /tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source/Checks/cm_cxx_make_unique.cxx
Linking CXX executable cmTC_484f2
/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Bootstrap.cmk/cmake -E cmake_link_script CMakeFiles/cmTC_484f2.dir/link.txt --verbose=1
/home/termi/Repos/spack/lib/spack/env/clang/clang++       CMakeFiles/cmTC_484f2.dir/cm_cxx_make_unique.cxx.o  -o cmTC_484f2 
clang-8: warning: argument unused during compilation: '-mllvm -polly' [-Wunused-command-line-argument]
gmake[1]: Leaving directory '/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeTmp'


Determining if compiler supports C++ unique_ptr failed with the following output:
Change Dir: /tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_9d046/fast 
gmake -f CMakeFiles/cmTC_9d046.dir/build.make CMakeFiles/cmTC_9d046.dir/build
gmake[1]: Entering directory '/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_9d046.dir/cm_cxx_unique_ptr.cxx.o
/home/termi/Repos/spack/lib/spack/env/clang/clang++    -std=gnu++17 -o CMakeFiles/cmTC_9d046.dir/cm_cxx_unique_ptr.cxx.o -c /tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Source/Checks/cm_cxx_unique_ptr.cxx
Linking CXX executable cmTC_9d046
/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/Bootstrap.cmk/cmake -E cmake_link_script CMakeFiles/cmTC_9d046.dir/link.txt --verbose=1
/home/termi/Repos/spack/lib/spack/env/clang/clang++       CMakeFiles/cmTC_9d046.dir/cm_cxx_unique_ptr.cxx.o  -o cmTC_9d046 
clang-8: warning: argument unused during compilation: '-mllvm -polly' [-Wunused-command-line-argument]
gmake[1]: Leaving directory '/tmp/termi/spack-stage/spack-stage-y1Wc_A/cmake-3.14.4/CMakeFiles/CMakeTmp'
```

### Information on your system

This includes:

 1. openSUSE Leap 15.1
 2. customized compiler.yaml to include gfortran and llvm's rpath
```yaml
compilers:
- compiler:
    environment: {}
    extra_rpaths: [/home/termi/Repos/spack/opt/spack/linux-opensuse_leap15-x86_64/gcc-8.2.1/llvm-8.0.0-43synebubx4ya37p7it63xmsmlfoqu6c/lib]
    modules: []
    operating_system: opensuse_leap15
    paths:
      cc: /home/termi/Repos/spack/opt/spack/linux-opensuse_leap15-x86_64/gcc-8.2.1/llvm-8.0.0-43synebubx4ya37p7it63xmsmlfoqu6c/bin/clang
      cxx: /home/termi/Repos/spack/opt/spack/linux-opensuse_leap15-x86_64/gcc-8.2.1/llvm-8.0.0-43synebubx4ya37p7it63xmsmlfoqu6c/bin/clang++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: clang@8.0.0
    target: x86_64
```

**Comment by termi-official** [comment]
A short update for the latter problem: To workaround the issue I appended "-Wno-unused-command-line-argument" to cflags and cxxflags.

**Comment by cdfh** [comment]
@termi-official Have you tried adding LLVM to your compiler's modules in `compilers.yaml`?

From memory, this fixed a similar problem I was experiencing in using libc++ with clang. This is my `compilers.yaml` file:

```
compilers:
- compiler:
    environment: {}
    extra_rpaths:
    - /spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/llvm-8.0.0-vcde4opt4xfhe5qcrktcagi6r7uhskgf/lib
    flags: {}
    modules:
    - llvm-8.0.0-gcc-5.4.0-vcde4op
    operating_system: ubuntu16.04
    paths:
      cc: /spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/llvm-8.0.0-vcde4opt4xfhe5qcrktcagi6r7uhskgf/bin/clang
      cxx: /spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/llvm-8.0.0-vcde4opt4xfhe5qcrktcagi6r7uhskgf/bin/clang++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: clang@8.0.0
    target: x86_64
```

You can find which module you need with:

`spack module tcl find llvm`
