### ISSUE TITLE
More than one spec in string

### ISSUE THREAD

**Issue by floli** [spack/spack#11689]
I have installed `vtk` to find out that it does not include the python3 libraries I needed. According to https://spack.readthedocs.io/en/latest/tutorial_configuration.html?highlight=variant#variant-preferences I try to modify the variants using `spack config --scope defaults edit packages`:
```
packages:
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag, fj]
    providers:
      [...]
      unwind: [libunwind]
    variants: [python3]
    permissions:
      read: world
      write: user
```
Also tried `variants: python3`, but both gives me:

```
% spack -d spec vtk^hdf5+hl+mpi              
==> [2019-06-13-13:17:58.237971] Reading config file /home/lindnefn/software/spack/etc/spack/defaults/modules.yaml
==> [2019-06-13-13:17:58.251196] Reading config file /home/lindnefn/software/spack/etc/spack/defaults/linux/modules.yaml
==> [2019-06-13-13:17:58.257256] Reading config file /home/lindnefn/software/spack/etc/spack/defaults/config.yaml
==> [2019-06-13-13:17:58.280716] Imported spec from built-in commands
==> [2019-06-13-13:17:58.281762] Imported spec from built-in commands
Input spec
--------------------------------
vtk
    ^hdf5+hl+mpi

Concretized
--------------------------------
==> [2019-06-13-13:17:58.314745] Reading config file /home/lindnefn/software/spack/etc/spack/defaults/repos.yaml
==> [2019-06-13-13:18:00.529243] Reading config file /home/lindnefn/software/spack/etc/spack/defaults/packages.yaml
==> [2019-06-13-13:18:00.554323] READ LOCK: /home/lindnefn/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquiring]
==> [2019-06-13-13:18:00.556654] READ LOCK: /home/lindnefn/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquired]
==> [2019-06-13-13:18:00.557722] READ LOCK: /home/lindnefn/.spack/cache/tags/.builtin-index.json.lock[0:0] [Released]
==> [2019-06-13-13:18:00.562944] READ LOCK: /home/lindnefn/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquiring]
==> [2019-06-13-13:18:00.565229] READ LOCK: /home/lindnefn/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquired]
==> [2019-06-13-13:18:00.581565] READ LOCK: /home/lindnefn/.spack/cache/patches/.builtin-index.json.lock[0:0] [Released]
==> [2019-06-13-13:18:00.586966] READ LOCK: /home/lindnefn/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquiring]
==> [2019-06-13-13:18:00.589533] READ LOCK: /home/lindnefn/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquired]
==> [2019-06-13-13:18:00.638742] READ LOCK: /home/lindnefn/.spack/cache/providers/.builtin-index.json.lock[0:0] [Released]
==> [2019-06-13-13:18:01.377768] Reading config file /home/lindnefn/.spack/linux/compilers.yaml
Traceback (most recent call last):
  File "/home/lindnefn/software/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/home/lindnefn/software/spack/lib/spack/spack/main.py", line 696, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/lindnefn/software/spack/lib/spack/spack/main.py", line 446, in _invoke_command
    return_val = command(parser, args)
  File "/home/lindnefn/software/spack/lib/spack/spack/cmd/spec.py", line 77, in spec
    spec.concretize()
  File "/home/lindnefn/software/spack/lib/spack/spack/spec.py", line 1925, in concretize
    self._concretize_helper())
  File "/home/lindnefn/software/spack/lib/spack/spack/spec.py", line 1752, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/lindnefn/software/spack/lib/spack/spack/spec.py", line 1769, in _concretize_helper
    concretizer.concretize_variants(self)))
  File "/home/lindnefn/software/spack/lib/spack/spack/concretize.py", line 269, in concretize_variants
    preferred_variants = PackagePrefs.preferred_variants(spec.name)
  File "/home/lindnefn/software/spack/lib/spack/spack/package_prefs.py", line 185, in preferred_variants
    spec = spack.spec.Spec("%s %s" % (pkg_name, variants))
  File "/home/lindnefn/software/spack/lib/spack/spack/spec.py", line 960, in __init__
    raise ValueError("More than one spec in string: " + spec_like)
ValueError: More than one spec in string: cmake python3
```

which gives no glues to me.

Thanks!

**Comment by floli** [comment]
Ok, by reading the source code I found out that I need to use `+python3`. Maybe it's worth writing that in the documentation?

But still, the package does not install any python3 libs. The spec gives me:

`vtk@8.1.2%gcc@8.1.0 build_type=RelWithDebInfo ~ffmpeg+mpi+opengl2~osmesa~python+python3~qt~xdmf arch=linux-ubuntu16.04-x86_64`

Is that correct for enabling python3 support?
