### ISSUE TITLE
spack install fails when modules loaded

### ISSUE THREAD

**Issue by tjfulle** [spack/spack#11803]
`spack install` fails with a cryptic message if compiler module is already loaded.

### Details
If a compiler defines a module, eg:

```console
$ cat <spack-user-prefix>/compilers.yaml
compilers:
- compiler:
    modules: [gcc/7.3.0]
    operating_system: rhel6
    paths:
      cc: <compiler-prefix>/bin/gcc
      cxx: <compiler-prefix>/bin/g++
      f77: <compiler-prefix>/bin/gfortran
      fc: <compiler-prefix>/bin/gfortran
    spec: gcc@7.3.0
```

and the module is loaded

```console
$ module ls
1) gcc/7.3.0
```

when I install a package using that compiler I get a cryptic error message:

```console
$ spack install some-package %gcc@7.3.0
...
==> No binary for <some-package> found: installing from source
==> Error: SyntaxError: invalid syntax (<string>, line 1)

<spack-root>/lib/spack/spack/build_environment.py:784, in child_process:
        781            tb_string = traceback.format_exc()
        782
        783            # build up some context from the offending package so we can
  >>    784            # show that, too.
        785            package_context = get_package_context(tb)
        786
        787            build_log = None
```

Hmm, that doesn't help much.  Installing with the debug flag helps make some sense of the error:

```console
$ spack -d install some-package %gcc@7.3.0
Warning: sems-gcc/7.3.0 is already loaded, use 'module reload' to reload


==> [2019-06-20-15:14:15.521261] Error: SyntaxError: invalid syntax (<string>, line 1)

<spack-root>/spack/lib/spack/spack/build_environment.py:784, in child_process:
        781            tb_string = traceback.format_exc()
        782
        783            # build up some context from the offending package so we can
  >>    784            # show that, too.
        785            package_context = get_package_context(tb)
        786
        787            build_log = None


Traceback (most recent call last):
  File "<spack-root>/lib/spack/spack/build_environment.py", line 766, in child_process
    setup_package(pkg, dirty=dirty)
  File "<spack-root>/lib/spack/spack/build_environment.py", line 714, in setup_package
    load_module(mod)
  File "<spack-root>k/lib/spack/spack/util/module_cmd.py", line 147, in load_module
    exec(compile(load, '<string>', 'exec'))
  File "<string>", line 1
    ==> Warning: sems-gcc/7.3.0 is already loaded, use 'module reload' to reload
     ^
SyntaxError: invalid syntax
```

Okay, so spack tries to load the module and the warning that the module is already loaded must be being `eval`d or `exec`d?  Perhaps spack can query if a module is loaded before trying to load, or unload it unconditionally and then load it?

If I get some time, I'll see if I can't gin up a solution.

**Comment by scheibelp** [comment]
> If I get some time, I'll see if I can't gin up a solution.

I will take you up on that gracious offer, so I have assigned this to you; if you find you don't have the time for this, could you add an update in the next few weeks? I agree it's a legitimate problem so it would be good to know whether someone is looking into it.

**Comment by tjfulle** [comment]
@scheibelp I'll take a look this week.  Off the top of my head, there seem to be a few relatively straightforward solutions:

- check if the module is loaded and if it is, do nothing
- check if the module is loaded and if it is, reload it, otherwise load it
- unconditionally unload the module before loading

option 1 above would incur the least number of potential side-effects related to module hierarchy (if the user is using Lmod)

Do you have a preference?  See other options?

**Comment by alalazo** [comment]
@tjfulle I'm spending some time looking through old issues. Has there been any progress to report on this one?

**Comment by tjfulle** [comment]
@alalazo, not that I am aware of.
