### ISSUE TITLE
Installation Issue: netcdf  "AttributeError: 'list' object has no attribute 'directories'"

### ISSUE THREAD

**Issue by songchaomail** [spack/spack#11858]
### Steps to reproduce the issue

```console
$ spack install netcdf
......
==> Installing netcdf
==> Searching for binary cache of netcdf
==> Warning: No Spack mirrors are currently configured
==> No binary for netcdf found: installing from source
==> Error: AttributeError: 'list' object has no attribute 'directories'
~/spack/lib/spack/spack/build_environment.py:782, in child_process:
        779            tb_string = traceback.format_exc()
        780
        781            # build up some context from the offending package so we can
  >>    782            # show that, too.
        783            package_context = get_package_context(tb)
        784
        785            build_log = None
```

### Platform and user environment

```commandline
$ uname -a 
Linux localhost.localdomain 2.6.32-754.15.3.el6.x86_64 #1 SMP Tue Jun 18 16:25:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	CentOS release 6.10 (Final)
``` 

- `compilers.yaml`
 compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: centos6
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.4.7
    target: x86_64

### Additional information
- If  the "depends_on('hdf5@1.8.9:+hl+mpi', when='+mpi')" line is commented out in netcdf's package.py file, the listing error disappears.
- Python version is 2.6.6.

**Comment by scheibelp** [comment]
Does `spack -d install...` give any additional context?

**Comment by songchaomail** [comment]
@scheibelp 
The following is Traceback after executing spack -d install netcdf.
Traceback (most recent call last):
  File "/home/songchao/spack/lib/spack/spack/build_environment.py", line 764, in child_process
    setup_package(pkg, dirty=dirty)
  File "/home/songchao/spack/lib/spack/spack/build_environment.py", line 673, in setup_package
    set_build_environment_variables(pkg, spack_env, dirty)
  File "/home/songchao/spack/lib/spack/spack/build_environment.py", line 283, in set_build_environment_variables
    dep_link_dirs.extend(query.libs.directories)
AttributeError: 'list' object has no attribute 'directories'

**Comment by scheibelp** [comment]
A couple more questions:

* What Spack commit are you on?
* Do you have any entries in `packages.yaml` (that you added yourself)?

**Comment by songchaomail** [comment]
- The Spack commit I'm using is: 30ce818fc44834d822887e812e34cbb02e5af2d0
$git show
commit 30ce818fc44834d822887e812e34cbb02e5af2d0
Author: Patrick Gartung <gartung@fnal.gov>
Date:   Mon Jun 24 21:09:24 2019 -0500
    Fix for #10063 : install from source if buildcache with different DAG exist (#11834)

- I didn't add packages.yaml file or entries in it.

**Comment by scheibelp** [comment]
I'm having trouble reproducing this on a newer CentOS (7) docker image. So I'll need more info:

Can you give the output of `spack spec -I netcdf`?

Can you try the following:

```
$ spack-python
> from spack.spec import Spec
> x = Spec('netcdf')
> x.concretize()
> x['hdf5'].libs.directories
```

**Comment by songchaomail** [comment]
**- $spack spec -I netcdf %gcc@4.4.7**

Input spec

 netcdf%gcc@4.4.7
Concretized

  netcdf@4.7.0%gcc@4.4.7\~dap\~hdf4 maxdims=1024 maxvars=8192 +mpi\~parallel-netcdf patches=10a1c3f7fa05e2c82457482e272bbe04d66d0047b237ad0a73e87d63d848b16c +pic+shared arch=linux-centos6-x86_64
[+]      ^autoconf@2.69%gcc@4.4.7 arch=linux-centos6-x86_64
[+]          ^m4@1.4.18%gcc@4.4.7 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-centos6-x86_64
[+]              ^libsigsegv@2.11%gcc@4.4.7 arch=linux-centos6-x86_64
[+]          ^perl@5.26.2%gcc@4.4.7+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-centos6-x86_64
[+]              ^gdbm@1.18.1%gcc@4.4.7 arch=linux-centos6-x86_64
[+]                  ^readline@7.0%gcc@4.4.7 arch=linux-centos6-x86_64
[+]                      ^ncurses@6.1%gcc@4.4.7\~symlinks\~termlib arch=linux-centos6-x86_64
[+]                          ^pkgconf@1.6.0%gcc@4.4.7 arch=linux-centos6-x86_64
[+]      ^automake@1.16.1%gcc@4.4.7 arch=linux-centos6-x86_64
[+]      ^hdf5@1.10.4%gcc@4.4.7\~cxx\~debug\~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-centos6-x86_64
[+]          ^openmpi@3.1.4%gcc@4.4.7\~cuda+cxx_exceptions fabrics=none \~java\~legacylaunchers\~memchecker\~pmi schedulers=none \~sqlite3\~thread_multiple+vt arch=linux-centos6-x86_64
[+]              ^hwloc@1.11.11%gcc@4.4.7\~cairo\~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos6-x86_64
[+]                  ^libpciaccess@0.13.5%gcc@4.4.7 arch=linux-centos6-x86_64
[+]                      ^libtool@2.4.6%gcc@4.4.7 arch=linux-centos6-x86_64
[+]                      ^util-macros@1.19.1%gcc@4.4.7 arch=linux-centos6-x86_64
[+]                  ^libxml2@2.9.9%gcc@4.4.7~python arch=linux-centos6-x86_64
[+]                      ^libiconv@1.15%gcc@4.4.7 arch=linux-centos6-x86_64
[+]                      ^xz@5.2.4%gcc@4.4.7 arch=linux-centos6-x86_64
[+]                      ^zlib@1.2.11%gcc@4.4.7+optimize+pic+shared arch=linux-centos6-x86_64
[+]                  ^numactl@2.0.12%gcc@4.4.7 arch=linux-centos6-x86_64

**- $ spack python**
Spack version 0.12.1
Python 2.6.6, Linux x86_64
\> from spack.spec import Spec
\> x = Spec('netcdf')
\> x.concretize()
\> x['hdf5'].libs.directories
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'list' object has no attribute 'directories'

**Comment by songchaomail** [comment]
I found that x['hdf5'].libs command returned null, even though  hdf5 was installed seperately.

**Comment by scheibelp** [comment]
> I found that x['hdf5'].libs command returned null, even though hdf5 was installed seperately.

To be clear: when you say it was installed separately, do you mean that it was installed by Spack with a separate command, or that it was installed without Spack? Based on https://github.com/spack/spack/issues/11858#issuecomment-508309413 it appears that there is a version installed by Spack (but I'm interested if you want to use a version that was not installed by Spack).

Also according to https://github.com/spack/spack/issues/11858#issuecomment-508309413, it doesn't look like `x['hdf5'].libs` is null (or `None`), although it's not the expected type. Were you running different commands in https://github.com/spack/spack/issues/11858#issuecomment-508309413 and https://github.com/spack/spack/issues/11858#issuecomment-508649899?

Can you also print the output of the following:

```
$ spack-python
> from spack.spec import Spec
> from llnl.util.filesystem import find_libraries
> x = Spec('netcdf')
> x.concretize()
> x['hdf5'].prefix
> find_libraries(['libhdf5_hl', 'libhdf5'], x['hdf5'].prefix, shared=True, recursive=True)
```

**Comment by songchaomail** [comment]
- "hdf5 was installed seperately" means I've installed hdf5 with Spack: spack install hdf5
- I run different command in https://github.com/spack/spack/issues/11858#issuecomment-508309413 and https://github.com/spack/spack/issues/11858#issuecomment-508649899. In https://github.com/spack/spack/issues/11858#issuecomment-508649899, I run the following:
$spack-python
Spack version 0.12.1
Python 2.6.6, Linux x86_64
\> from spack.spec import Spec
\> x = Spec('hdf5')
\> x.concretize()
\> x['hdf5'].libs
[]

- $ spack-python
Spack version 0.12.1
Python 2.6.6, Linux x86_64
\> from spack.spec import Spec
\> from llnl.util.filesystem import find_libraries
\> x = Spec('netcdf')
\> x.concretize()
\> x['hdf5'].prefix
'/home/songchao/spack/opt/spack/linux-centos6-x86_64/gcc-4.9.3/hdf5-1.10.4-chi747qhc5awatgmret66wtppwmznone'
\> find_libraries(['libhdf5_hl', 'libhdf5'], x['hdf5'].prefix, shared=True, recursive=True)
LibraryList([])

**Comment by scheibelp** [comment]
Can you `ls` the `lib` directory of the `hdf5` installation and add the results here?

**Comment by songchaomail** [comment]
ls: cannot access /home/songchao/spack/opt/spack/linux-centos6-x86_64/gcc-4.9.3/hdf5-1.10.4-chi747qhc5awatgmret66wtppwmznone: No such file or directory

ls: cannot access /home/songchao/spack/opt/spack/linux-centos6-x86_64/gcc-4.9.3/hdf5-1.10.4-chi747qhc5awatgmret66wtppwmznone/lib: No such file or directory

**Comment by coneheadusa** [comment]
Similar problem.  ==> Error: AttributeError: 'list' object has no attribute 'directories'
Here is the error trace and the results of the spack-python commands.

git status
HEAD detached at v0.14.2

spack install netcdf-c
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/libsigsegv-2.12-5tcftzfms4dwmgnd5rsizk4chgdvffvl
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/pkgconf-1.6.3-lukqxyhmlepbm6qb5jxsh5l7qct2zkhe
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/util-macros-1.19.1-ep2nrtjyhrql7gtd4bl7dtklbob6jjlf
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/libiconv-1.16-jqgtklw7hjmkz57cuiwb77jflh5udoyv
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/xz-5.2.4-iobwchfafsghgmcymiffeqs62m2tbd6s
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/zlib-1.2.11-gcrfowf2m3tywl4fh333mer3w2q6ytha
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/m4-1.4.18-zdkakokbcavymibgrcbuepqlrebfnvki
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/ncurses-6.1-wvb3o772j5qqhit24ixbmgpoacbvzfow
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/libxml2-2.9.9-xn3x7tddtauechnyeobnytst2j5j7itp
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/libtool-2.4.6-vaww7z5mpsogkzpsmfkmlfyltznvlkvs
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/readline-8.0-mpvwqmqurgl5c5pe4zhtedvbrelcvu4l
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/libpciaccess-0.13.5-ezehfay2nlsc3fbqqohwsu44kfnhw23b
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/gdbm-1.18.1-tfxuc73krs6plzc57krhrjj6wshq267y
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/perl-5.30.1-okwlcclbmmopozk6rjlzjedbkmejlme6
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/autoconf-2.69-wtulr7putk4sbmb4ojsf7chmfwu7veox
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/automake-1.16.1-v7xlqse3zdrhncuijfdxradczecwzsdu
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/numactl-2.0.12-2fobyho7hiu7k54ylbwzb37ksmttua3v
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hwloc-1.11.11-rcu2uxbtolosixmztfuyg3pmaqvuhzpp
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/openmpi-3.1.5-26oaaspxkc4lukzzkcbfx5w73hgd2ifm
[+] /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6
==> 80943: Installing netcdf-c
==> Finding buildcaches in /mirror/build_cache
==> Fetching file:///mirror/build_cache/linux-ubuntu18.04-haswell-gcc-7.4.0-netcdf-c-4.7.3-hg7pv354zgjgdll5zzctemeu6ofexif4.spec.yaml
curl: (37) Couldn't open file /mirror/build_cache/linux-ubuntu18.04-haswell-gcc-7.4.0-netcdf-c-4.7.3-hg7pv354zgjgdll5zzctemeu6ofexif4.spec.yaml
==> Failed to fetch file from URL: file:///mirror/build_cache/linux-ubuntu18.04-haswell-gcc-7.4.0-netcdf-c-4.7.3-hg7pv354zgjgdll5zzctemeu6ofexif4.spec.yaml
    Curl failed with error 37
==> Fetching from file:///mirror/build_cache/linux-ubuntu18.04-haswell-gcc-7.4.0-netcdf-c-4.7.3-hg7pv354zgjgdll5zzctemeu6ofexif4.spec.yaml failed.
==> Error: AttributeError: 'list' object has no attribute 'directories'

/home/spack/spack/lib/spack/spack/build_environment.py:818, in child_process:
        815            tb_string = traceback.format_exc()
        816
        817            # build up some context from the offending package so we can
  >>    818            # show that, too.
        819            package_context = get_package_context(tb)
        820
        821            build_log = None

==> Error: Failed to install netcdf-c due to ChildError: AttributeError: 'list' object has no attribute 'directories'
/home/spack/spack/lib/spack/spack/build_environment.py:818, in child_process:
        815            tb_string = traceback.format_exc()
        816
        817            # build up some context from the offending package so we can
  >>    818            # show that, too.
        819            package_context = get_package_context(tb)
        820
        821            build_log = None`

spack-python
Spack version 0.14.2
Python 3.6.9, Linux x86_64
>>> from spack.spec import Spec
>>> from llnl.util.filesystem import find_libraries
>>> x = Spec('netcdf-c')
>>> x.concretize()
>>>  x['hdf5'].prefix
>>> x['hdf5'].prefix
'/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6'
>>> find_libraries(['libhdf5_hl', 'libhdf5'], x['hdf5'].prefix, shared=True, recursive=True)
LibraryList(['/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5_hl.so', '/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5.so'])

s /home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/*
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5.a
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5.la
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5.settings
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5.so
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5.so.103
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5.so.103.0.0
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5_hl.a
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5_hl.la
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5_hl.so
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5_hl.so.100
/home/spack/spack/opt/spack/linux-ubuntu18.04-haswell/gcc-7.4.0/hdf5-1.10.4-swz6r2hzdm5yv4gmx2kbaqlvia4xo4x6/lib/libhdf5_hl.so.100.1.1
