### ISSUE TITLE
`spack uninstall` can't install packages that no longer exist

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#11870]
This is a regression of #3476, which was fixed in #3915.  It looks like #8772 broke it.

cc @olesenm.

### Steps to reproduce the issue

```console
$ spack install xz
$ cd var/spack/repos/builtin/packages && mv xz xzo && sed -i~ 's/Xz/Xzo/' xzo/package.py
$ spack -d uninstall -yf xz
```

### Error Message

```console
==> [2019-06-27-10:56:48.219992] Error: Package xz not found.
Traceback (most recent call last):
  File "/Users/gamblin2/src/spack/lib/spack/spack/main.py", line 696, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/gamblin2/src/spack/lib/spack/spack/main.py", line 446, in _invoke_command
    return_val = command(parser, args)
  File "/Users/gamblin2/src/spack/lib/spack/spack/cmd/uninstall.py", line 336, in uninstall
    args, spack.cmd.parse_specs(args.packages) if args.packages else [any])
  File "/Users/gamblin2/src/spack/lib/spack/spack/cmd/uninstall.py", line 326, in uninstall_specs
    do_uninstall(env, uninstall_list, args.force)
  File "/Users/gamblin2/src/spack/lib/spack/spack/cmd/uninstall.py", line 210, in do_uninstall
    spack.package.Package.uninstall_by_spec(item, force=True)
  File "/Users/gamblin2/src/spack/lib/spack/spack/package.py", line 1998, in uninstall_by_spec
    spack.store.layout.remove_install_directory(spec)
  File "/Users/gamblin2/src/spack/lib/spack/spack/directory_layout.py", line 94, in remove_install_directory
    path = self.path_for_spec(spec)
  File "/Users/gamblin2/src/spack/lib/spack/spack/directory_layout.py", line 81, in path_for_spec
    if self.check_upstream and spec.package.installed_upstream:
  File "/Users/gamblin2/src/spack/lib/spack/spack/spec.py", line 1098, in package
    self._package = spack.repo.get(self)
  File "/Users/gamblin2/src/spack/lib/spack/spack/repo.py", line 1199, in get
    return path.get(spec)
  File "/Users/gamblin2/src/spack/lib/spack/spack/repo.py", line 93, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/Users/gamblin2/src/spack/lib/spack/spack/repo.py", line 651, in get
    return self.repo_for_pkg(spec).get(spec)
  File "/Users/gamblin2/src/spack/lib/spack/spack/repo.py", line 93, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/Users/gamblin2/src/spack/lib/spack/spack/repo.py", line 883, in get
    raise UnknownPackageError(spec.name)
spack.repo.UnknownPackageError: Package xz not found.
```

`uninstall_by_spec` in package.py is a static method specifically because it shouldn’t require a `Package` to exist in order to uninstall a spec with a particular name.  Clearly I didn't add a good enough regression test for this.

It looks like the `spec.package` reference in `remove_install_directory()` breaks the no-existing-package requirement.  So we need a fix for that, and a good regression test.  Regression testing this may be somewhat tricky.

**Comment by adamjstewart** [comment]
@scheibelp maybe you can take a look at #3690 while you're at it. They may be related.
