### ISSUE TITLE
Installation issue: font-util (after PR #11785)

### ISSUE THREAD

**Issue by obreitwi** [spack/spack#12026]
When trying to install `font-util`, we get the following issue:

```console
==> Building font-util [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Error: TypeError: 'NoneType' object is not callable

spack/var/spack/repos/builtin/packages/font-util/package.py:105, in font_install:
        102                autoreconf(*autoconf_args)
        103                configure = Executable("./configure")
        104                configure('--prefix={0}'.format(self.prefix))
  >>    105                make('install')
```
The relevant changes seem to have been introduced in PR #11785.

---

### Steps to reproduce the issue

```console
$ spack -d install font-util
...

==> [2019-07-15-16:36:30.035005] Error: TypeError: 'NoneType' object is not callable

spack/var/spack/repos/builtin/packages/font-util/package.py:105, in font_install:
        102                autoreconf(*autoconf_args)
        103                configure = Executable("./configure")
        104                configure('--prefix={0}'.format(self.prefix))
  >>    105                make('install')

See build log for details:
  spack/var/spack/stage/font-util-1.3.1-q5hczcgqfekayqefsobccst4owvx6jz6/spack-build-out.txt

Traceback (most recent call last):
  File "spack/lib/spack/spack/build_environment.py", line 765, in child_process
    return_value = function()
  File "spack/lib/spack/spack/package.py", line 1628, in build_process
    phase(self.spec, self.prefix)
  File "spack/lib/spack/spack/package.py", line 110, in phase_wrapper
    callback(instance)
  File "spack/var/spack/repos/builtin/packages/font-util/package.py", line 103, in font_install
    configure = Executable("./configure")
TypeError: 'NoneType' object is not callable
==> [2019-07-15-16:36:30.035695] READ LOCK: spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-07-15-16:36:30.036259] READ LOCK: spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-07-15-16:36:30.042096] READ LOCK: spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-07-15-16:36:30.049128] ChildError: TypeError: 'NoneType' object is not callable
spack/var/spack/repos/builtin/packages/font-util/package.py:105, in font_install:
        102                autoreconf(*autoconf_args)
        103                configure = Executable("./configure")
        104                configure('--prefix={0}'.format(self.prefix))
  >>    105                make('install')
```

### Platform and user environment

```commandline
$ uname -a 
Linux HOSTNAME 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64 GNU/Linux
``` 
### Additional information

```console
$ spack spec --install-status font-util
 -   font-util@1.3.1%gcc@8.2.0 fonts=encodings,font-adobe-100dpi,font-adobe-75dpi,font-adobe-utopia-100dpi,font-adobe-utopia-75dpi,font-adobe-utopia-type1,font-alias,font-arabic-misc,font-bh-100dpi,font-bh-75dpi,font-bh-lucidatypewriter-100dpi,font-bh-lucidatypewriter-75dpi,font-bh-ttf,font-bh-type1,font-bitstream-100dpi,font-bitstream-75dpi,font-bitstream-speedo,font-bitstream-type1,font-cronyx-cyrillic,font-cursor-misc,font-daewoo-misc,font-dec-misc,font-ibm-type1,font-isas-misc,font-jis-misc,font-micro-misc,font-misc-cyrillic,font-misc-ethiopic,font-misc-meltho,font-misc-misc,font-mutt-misc,font-schumacher-misc,font-screen-cyrillic,font-sun-misc,font-winitzki-cyrillic,font-xfree86-type1 arch=linux-debian9-x86_64
[+]      ^bdftopcf@1.0.5%gcc@8.2.0 arch=linux-debian9-x86_64
[+]          ^fontsproto@2.1.3%gcc@8.2.0 arch=linux-debian9-x86_64
[+]              ^pkgconf@1.6.1%gcc@8.2.0 arch=linux-debian9-x86_64
[+]              ^util-macros@1.19.1%gcc@8.2.0 arch=linux-debian9-x86_64
[+]          ^libxfont@1.5.2%gcc@8.2.0 arch=linux-debian9-x86_64
[+]              ^freetype@2.9.1%gcc@8.2.0 patches=08466355e8649235ff01f13b3e56bbd551c7cfb2ca97903cc11575c163ea32a3 arch=linux-debian9-x86_64
[+]                  ^bzip2@1.0.8%gcc@8.2.0+shared arch=linux-debian9-x86_64
[+]                      ^diffutils@3.7%gcc@8.2.0 arch=linux-debian9-x86_64
[+]                  ^libpng@1.6.34%gcc@8.2.0 arch=linux-debian9-x86_64
[+]                      ^zlib@1.2.11%gcc@8.2.0+optimize+pic+shared arch=linux-debian9-x86_64
[+]              ^libfontenc@1.1.3%gcc@8.2.0 arch=linux-debian9-x86_64
[+]                  ^xproto@7.0.31%gcc@8.2.0 arch=linux-debian9-x86_64
[+]              ^xtrans@1.3.5%gcc@8.2.0 arch=linux-debian9-x86_64
[+]      ^mkfontdir@1.0.7%gcc@8.2.0 arch=linux-debian9-x86_64
[+]          ^mkfontscale@1.1.2%gcc@8.2.0 arch=linux-debian9-x86_64
```

**Comment by ajw1980** [comment]
I saw this as well. It is a missing dependency in font-util/package.py. It needs at least this I think:
```
    depends_on('autoconf', type='build')
    depends_on('automake', type='build')
```

**Comment by obreitwi** [comment]
> I saw this as well. It is a missing dependency in font-util/package.py. It needs at least this I think:
> 
> ```
>     depends_on('autoconf', type='build')
>     depends_on('automake', type='build')
> ```

Thank you for the hint! The `build`-dependency is not enough, though: We need a `run` dependency so that the executables are still available after the install step. The full workaround is:

```console
$ git apply <<EOF
diff --git a/var/spack/repos/builtin/packages/font-util/package.py b/var/spack/repos/builtin/packages/font-util/package.py
index ec56b0789..632f18753 100644
--- a/var/spack/repos/builtin/packages/font-util/package.py
+++ b/var/spack/repos/builtin/packages/font-util/package.py
@@ -20,6 +20,9 @@ class FontUtil(AutotoolsPackage):
     depends_on('mkfontscale', type='build')
     depends_on('mkfontdir', type='build')
 
+    depends_on('automake', type=('build', 'run'))
+    depends_on('autoconf', type=('build', 'run'))
+
     font_baseurl = 'https://www.x.org/archive/individual/font/'
     fonts = []
     # name, version, md5
EOF
```

**Comment by ajw1980** [comment]
It built correctly for me with just the build dependency. I don't know why autoconf would need to be a runtime dependency for this.

**Comment by obreitwi** [comment]
> It built correctly for me with just the build dependency. I don't know why autoconf would need to be a runtime dependency for this.

Ok, very weird: After uninstalling `font-util` and removing the `run` dependency, re-installing did succeed for me as well (although for some reason it did not the first time around).

However, I'm pretty sure the issue should be taking care of by the `AutotoolsPackage`-base, should it not?

**Comment by wspear** [comment]
In addition to addressing this particular bug, is there any way spack can produce more meaningful error output for similar issues? I was trying to formulate a report of this issue myself and found that it built on one platform but not another (in retrospect it is clear that one had the missing dependencies installed outside of spack). With only a python-level error to go on I wasn't sure how to present it in a reproducible way.

**Comment by scheibelp** [comment]
I'll add a PR based on @ajw1980's suggestion

@obreitwi 

> However, I'm pretty sure the issue should be taking care of by the AutotoolsPackage-base, should it not?

It does not: even if a package is an `AutotoolsPackage`, it was found that not such packages require these dependencies, so `AutotoolsPackage` does not include them by default.

@wspear 

> With only a python-level error to go on I wasn't sure how to present it in a reproducible way.

If you run the install with `-d` like `spack -d install ...` it should report the error message. Failing that, the error message should be in the build log (which is placed in the staging directory in the case of a failed install).

**Comment by obreitwi** [comment]
Thank you!
