### ISSUE TITLE
CMake: Could NOT find MPI (missing: MPI_C_FOUND C)

### ISSUE THREAD

**Issue by junghans** [spack/spack#12120]
I was trying to build the `legion` spackage, but `MPI` could not be found.

### Steps to reproduce the issue

```console
$  spack install legion
```

### Error Message

```console
-- Could NOT find MPI_C (missing: MPI_C_WORKS)
CMake Error at /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND C)
Call Stack (most recent call first):
  /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/share/cmake-3.15/Modules/FindMPI.cmake:1687 (find_package_handle_standard_args)
  cmake/FindGASNet.cmake:160 (find_package)
  cmake/FindGASNet.cmake:262 (_GASNet_create_component_target)
  CMakeLists.txt:218 (find_package)


-- Configuring incomplete, errors occurred!
```

### Information on your system

I test this on multiple plattform and with multiple openmpi versions.

If I dig into the the `CMakeError.log`, I see:
```
Building C object CMakeFiles/cmTC_6d446.dir/test_mpi.c.o
/home/junghans/spack/lib/spack/env/gcc/gcc  -isystem /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/include  -fexceptions -pthread -o CMakeFiles/cmTC_6d446.dir/test_mpi.c.o   -c /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/share/cmake-3.15/Modules/FindMPI/test_mpi.c
Linking C executable cmTC_6d446
/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/cmake-3.15.0-ywkxfyybtze5ubp47jx4pm26hu7icbae/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6d446.dir/link.txt --verbose=1
/home/junghans/spack/lib/spack/env/gcc/gcc      -rdynamic CMakeFiles/cmTC_6d446.dir/test_mpi.c.o  -o cmTC_6d446 -Wl,-rpath,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib -Wl,-rpath -Wl,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/hwloc-1.11.11-k6j3l64m7lqc7ftuimrmn4pymwpacno2/lib -Wl,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib -L/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/hwloc-1.11.11-k6j3l64m7lqc7ftuimrmn4pymwpacno2/lib -pthread /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib/libmpi.so
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib: file not recognized: Is a directory
```
So there is this `/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib` argument in the link line.

if you ran:
```console
$ /home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/bin/mpicc --showme
/usr/bin/gcc -I/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/include -fexceptions -pthread -L/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/hwloc-1.11.11-k6j3l64m7lqc7ftuimrmn4pymwpacno2/lib -Wl,-rpath -Wl,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/hwloc-1.11.11-k6j3l64m7lqc7ftuimrmn4pymwpacno2/lib -Wl,-rpath -Wl,/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib -L/home/junghans/spack/opt/spack/linux-gentoo2-x86_64/gcc-8.3.0/openmpi-3.1.4-6acrjmf2z73obkgvund42tbimv7j5lwc/lib -lmpi
```
it seems the wrapper inject this directory somehow.

**Comment by hightower8083** [comment]
i had this also -- it helped to replace cmake-3.15 with some <3.15

**Comment by junghans** [comment]
@hightower8083 thanks, that works!

**Comment by junghans** [comment]
@bradking, I hope you are aware of that issue in cmake-3.15.

**Comment by tldahlgren** [comment]
Thanks for this information.  I have also been having this problem trying to build ``xsdk`` with cmake 3.15.

**Comment by hightower8083** [comment]
it seems to concern specifically `openmpi` -- in my cases `3.15` done fine with `mpich`

**Comment by mathstuf** [comment]
I tracked down the regression to this MR: https://gitlab.kitware.com/cmake/cmake/merge_requests/3449

**Comment by mathstuf** [comment]
The error causes `-Wl,-rpath -Wl,/path1 -Wl,-rpath -Wl,/path2` to be deduplicated now that CMake sees the individual arguments down to `-Wl,-rpath -Wl,/path1 -Wl,/path2` which is invalid. This is probably why it shows up sometimes, but not always.

**Comment by bradking** [comment]
Recorded in [CMake Issue 19516](https://gitlab.kitware.com/cmake/cmake/issues/19516).

**Comment by robertmaynard** [comment]
The MR that fixes this issue in CMake is now open ( https://gitlab.kitware.com/cmake/cmake/merge_requests/3605 ).

I recommend this approach over the one in #12129 , as it keeps the fixes necessary for CUDA projects which use MPI and CUDA Separable Compilation.

**Comment by robertmaynard** [comment]
The above MR is part of CMake 3.15.1 which was released today.

**Comment by alexbprofit** [comment]
```
  Building wheel for lyncs-mpi (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'E:\Download\python\refactoring\Scripts\python.exe' 'E:\Download\python\refactorin
g\lib\site-packages\pip-21.0.1-py3.8.egg\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Us
ers\Alex_PC\AppData\Local\Temp\tmph3d75mhb'
       cwd: C:\Users\Alex_PC\AppData\Local\Temp\pip-install-r98__9l0\lyncs-mpi_caba08b056b84ae
290de94c43ddf2067
  Complete output (75 lines):
  Warning: 'keywords' should be a list, got type 'set'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\abc.py -> build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\cartesian.py -> build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\cart_array.py -> build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\client.py -> build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\comm.py -> build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\config.py -> build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\distributed.py -> build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\lib.py -> build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\testing.py -> build\lib.win-amd64-3.8\lyncs_mpi
  copying lyncs_mpi\__init__.py -> build\lib.win-amd64-3.8\lyncs_mpi
  running build_ext
  CMake Error at C:/Users/Alex_PC/AppData/Local/Temp/pip-build-env-5qgeq482/overlay/Lib/site-p
ackages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
    Could NOT find MPI (missing: MPI_C_FOUND)

        Reason given by package: MPI component 'CXX' was requested, but language CXX is not en
abled.  MPI component 'Fortran' was requested, but language Fortran is not enabled.

  Call Stack (most recent call first):
    C:/Users/Alex_PC/AppData/Local/Temp/pip-build-env-5qgeq482/overlay/Lib/site-packages/cmake
/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE
)
    C:/Users/Alex_PC/AppData/Local/Temp/pip-build-env-5qgeq482/overlay/Lib/site-packages/cmake
/data/share/cmake-3.18/Modules/FindMPI.cmake:1721 (find_package_handle_standard_args)
    CMakeLists.txt:5 (find_package)


  Traceback (most recent call last):
    File "E:\Download\python\refactoring\lib\site-packages\pip-21.0.1-py3.8.egg\pip\_vendor\pe
p517\_in_process.py", line 280, in <module>
      main()
    File "E:\Download\python\refactoring\lib\site-packages\pip-21.0.1-py3.8.egg\pip\_vendor\pe
p517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "E:\Download\python\refactoring\lib\site-packages\pip-21.0.1-py3.8.egg\pip\_vendor\pe
p517\_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\Alex_PC\AppData\Local\Temp\pip-build-env-5qgeq482\overlay\Lib\site-packages
\setuptools\build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\Alex_PC\AppData\Local\Temp\pip-build-env-5qgeq482\overlay\Lib\site-packages
\setuptools\build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\Alex_PC\AppData\Local\Temp\pip-build-env-5qgeq482\overlay\Lib\site-packages
\setuptools\build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 17, in <module>
      setup(
    File "C:\Users\Alex_PC\AppData\Local\Temp\pip-build-env-5qgeq482\overlay\Lib\site-packages
\lyncs_setuptools\setuptools.py", line 111, in setup
      return _SETUP(**complete_kwargs(*args, **kwargs))
    File "C:\Users\Alex_PC\AppData\Local\Temp\pip-build-env-5qgeq482\overlay\Lib\site-packages
\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line
 148, in setup
      dist.run_commands()
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line
 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line
 985, in run_command
      cmd_obj.run()
    File "C:\Users\Alex_PC\AppData\Local\Temp\pip-build-env-5qgeq482\overlay\Lib\site-packages
\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line
313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line
 985, in run_command
      cmd_obj.run()
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\distutils\command\build.
py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line
313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line
 985, in run_command
      cmd_obj.run()
    File "C:\Users\Alex_PC\AppData\Local\Temp\pip-build-env-5qgeq482\overlay\Lib\site-packages
\lyncs_setuptools\cmake.py", line 45, in run
      self.build_extension(ext)
    File "C:\Users\Alex_PC\AppData\Local\Temp\pip-build-env-5qgeq482\overlay\Lib\site-packages
\lyncs_setuptools\cmake.py", line 80, in build_extension
      out = subprocess.check_output(
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 411
, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "C:\Users\Alex_PC\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512
, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Alex_PC\\AppData\\Local\\Temp\
\pip-install-r98__9l0\\lyncs-mpi_caba08b056b84ae290de94c43ddf2067', '-DEXTERNAL_INSTALL_LOCATI
ON=C:\\Users\\Alex_PC\\AppData\\Local\\Temp\\pip-install-r98__9l0\\lyncs-mpi_caba08b056b84ae29
0de94c43ddf2067\\build\\lib.win-amd64-3.8\\lyncs_mpi', '-DCMAKE_BUILD_TYPE=Release']' returned
 non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for lyncs-mpi
  ERROR: Could not build wheels for lyncs-mpi which use PEP 517 and cannot be installed directly```
cmake 3.18.4
pip 21.0.1
python 3.8.2
This problem not fixed(

**Comment by Nazehs** [comment]
Getting a similar error too

CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for module 'mpi-c'
--   No package 'mpi-c' found
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_WORKS) 
-- Checking for module 'mpi-cxx'
--   No package 'mpi-cxx' found
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_WORKS) 
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.22/Modules/FindMPI.cmake:1830 (find_package_handle_standard_args)
  CMakeLists.txt:17 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/Users/nazehabel/auryn/build/release/CMakeFiles/CMakeOutput.log".
See also "/Users/nazehabel/auryn/build/release/CMakeFiles/CMakeError.log".
nazehabel@cexxys-MacBook-Pro release %

**Comment by szl-opensees** [comment]
i meet the same problem at cmake 2.5

**Comment by Hemrajbhattarai** [comment]
@Nazehs 
were you able to find the solution to the problem you mentioned above?
My problem is very similar to yours.
