### ISSUE TITLE
Spack broken on Blue Waters

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#12187]
On the current develop, no Spack command works on Blue Waters.

### Steps to reproduce the issue

Any Spack command:
```console
$ spack help
```

### Error Message

```
Traceback (most recent call last):
  File "/u/sciteam/stewart1/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/main.py", line 704, in main
    if spack.config.get('config:debug'):
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/config.py", line 627, in get
    return config.get(path, default, scope)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/lang.py", line 558, in __getattr__
    return getattr(self.instance, name)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/lang.py", line 554, in instance
    self._instance = self.factory()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/config.py", line 609, in _config
    _add_platform_scope(cfg, ConfigScope, name, path)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/config.py", line 562, in _add_platform_scope
    platform = spack.architecture.platform().name
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/lang.py", line 184, in _memoized_function
    func.cache[args] = func(*args)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/architecture.py", line 388, in platform
    return platform_cls()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/platforms/cray.py", line 76, in __init__
    back_distro = Cnl()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/operating_systems/cnl.py", line 57, in __init__
    version = self._detect_crayos_version()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/operating_systems/cnl.py", line 66, in _detect_crayos_version
    release_attrs = read_cle_release_file()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/operating_systems/cnl.py", line 37, in read_cle_release_file
    with open(_cle_release_file) as release_file:
IOError: [Errno 2] No such file or directory: '/etc/opt/cray/release/cle-release'
```

### Information on your system

```console
$ cat /etc/*-release
Cluster Manager v6.1
slave
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64"
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
$ uname -a
Linux h2ologin2 3.0.101-0.47.106.59-default #1 SMP Wed Jan 23 09:00:24 UTC 2019 (624897e) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by adamjstewart** [comment]
It looks like the correct name of the file does not contain a dash:
```
$ cat /etc/opt/cray/release/clerelease
5.2.UP04
```

**Comment by adamjstewart** [comment]
@tgamblin This bug was introduced in #11906.

**Comment by chuckatkins** [comment]
FWIW, in CMake we use a set of heuristics to determine the CLE version:

1. `CRAYOS_VERSION` environment variable
2.  `XTOS_VERSION` environment variable
3.  `RELEASE=(.*)` in the `/etc/opt/cray/release/cle-release` file
4.  Direct contents of `/etc/opt/cray/release/clerelease`
