### ISSUE TITLE
How to handle Python certificates

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#12340]
### Issue

I'm trying to use a Spack-installed Python package (`py-earthengine-api`) but I found that Spack's Python package doesn't install any certificates:
```
Traceback (most recent call last):
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/http/client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
```

### Solution

Is there a way we can get Spack's `python` package to automatically install certificates so that `ssl` actually works? I once had to do something similar for the `mercurial` package, where I added `py-certifi` as a dependency and manually configured `hgrc` to point to the certificate installation directory. Maybe we could add `py-certifi` as a resource to the `python` package?

### Workarounds

Currently, you can do `spack install py-certifi` to solve this problem. The issue with this workaround is that Python packages that require the `ssl` library never explicitly state a dependency on `certifi`. It is just expected to be part of the Python installation.

**Comment by adamjstewart** [comment]
Hmm, I may have overreacted. I didn't want to build Python with an obsolete `openssl` so I used a module on the system. Unfortunately, this module is woefully out-of-date. I tried getting the Blue Waters admins to update it but they refused. Let me try rebuilding Python with Spack's openssl package.

**Comment by adamjstewart** [comment]
Yep, installing my own `openssl` and linking Python to that solved the issue!
