### ISSUE TITLE
installation issue: Bazel doesn't build beyond 0.17.2

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#12398]
I am currently trying to build latest tensorflow 1.x version for which  Bazel v0.24.1 is needed.  As shown below, Bazel won't build beyond 1.17.2

I tried commenting out a few patches that might be irrelavent for newer versions: fix_env_handling-0.17.2.patch, link.patch, and unix_cc_configure-0.17.2.patch but then I am getting different build errors. 

### Steps to reproduce the issue

```console
==> Installing bazel
==> Searching for binary cache of bazel
==> Warning: No Spack mirrors are currently configured
==> No binary for bazel found: installing from source
==> Warning: There is no checksum on file to fetch bazel@0.18.1 safely.
==>   Fetch anyway? [y/N] y
==> Fetching with no checksum.
  Add a checksum or use --no-checksum to skip this check.
==> Fetching https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel-0.18.1-dist.zip
######################################################################## 100.0%
==> Staging archive: /disk/software/lib/hpcpm/spack/var/spack/stage/bazel-0.18.1-bti25k6egb4fehuhaqb4cba5equsmi5e/bazel-0.18.1-dist.zip
==> Created stage in /disk/software/lib/hpcpm/spack/var/spack/stage/bazel-0.18.1-bti25k6egb4fehuhaqb4cba5equsmi5e
==> Applied patch /disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/fix_env_handling-0.17.2.patch
1 out of 1 hunk FAILED -- saving rejects to file src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkAction.java.rej
==> Patch /disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/link.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/link.patch' '-d' '.'

```

### Platform and user environment

Please report your OS here:
```commandline
Linux ws-067 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
 Description:	CentOS Linux release 7.6.1810 (Core) 
``` 
gcc@9.1.0 (will also try compiling with 4.8 soon)

### Additional information

Rebuilding the package with the following options:
```console
$ spack -d install bazel@0.18.1
==> [2019-08-12-17:25:20.214705] Fetching https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel-0.18.1-dist.zip
==> [2019-08-12-17:25:20.229222] '/usr/bin/curl' '-C' '-' '-o' '/disk/software/lib/hpcpm/spack/var/spack/stage/bazel-0.18.1-bti25k6egb4fehuhaqb4cba5equsmi5e/bazel-0.18.1-dist.zip.part' '-f' '-D' '-' '-L' 'https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel-0.18.1-dist.zip' '-#'
######################################################################## 100.0%
==> [2019-08-12-17:25:25.737364] Staging archive: /disk/software/lib/hpcpm/spack/var/spack/stage/bazel-0.18.1-bti25k6egb4fehuhaqb4cba5equsmi5e/bazel-0.18.1-dist.zip
==> [2019-08-12-17:25:25.746666] '/usr/bin/unzip' '-q' '/disk/software/lib/hpcpm/spack/var/spack/stage/bazel-0.18.1-bti25k6egb4fehuhaqb4cba5equsmi5e/bazel-0.18.1-dist.zip'
==> [2019-08-12-17:25:27.244610] Created stage in /disk/software/lib/hpcpm/spack/var/spack/stage/bazel-0.18.1-bti25k6egb4fehuhaqb4cba5equsmi5e
==> [2019-08-12-17:25:27.246456] '/usr/bin/patch' '-s' '-p' '1' '-i' '/disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/fix_env_handling-0.17.2.patch' '-d' '.'
==> [2019-08-12-17:25:27.252151] Applied patch /disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/fix_env_handling-0.17.2.patch
==> [2019-08-12-17:25:27.253205] '/usr/bin/patch' '-s' '-p' '1' '-i' '/disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/link.patch' '-d' '.'
1 out of 1 hunk FAILED -- saving rejects to file src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkAction.java.rej
==> [2019-08-12-17:25:27.257628] ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/link.patch' '-d' '.'
==> [2019-08-12-17:25:27.257816] Patch /disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/link.patch failed.
==> [2019-08-12-17:25:27.265272] Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/link.patch' '-d' '.'
Traceback (most recent call last):
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/build_environment.py", line 766, in child_process
    return_value = function()
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/package.py", line 1577, in build_process
    self.do_patch()
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/package.py", line 1119, in do_patch
    patch.apply(self.stage)
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/patch.py", line 88, in apply
    apply_patch(stage, self.path, self.level, self.working_dir)
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/patch.py", line 40, in apply_patch
    '-d', working_dir)
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/link.patch' '-d' '.'
==> [2019-08-12-17:25:27.265925] READ LOCK: /disk/software/lib/hpcpm/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-08-12-17:25:27.267076] READ LOCK: /disk/software/lib/hpcpm/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-08-12-17:25:27.315370] READ LOCK: /disk/software/lib/hpcpm/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-08-12-17:25:27.321321] ChildError: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/link.patch' '-d' '.'Traceback (most recent call last):
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/build_environment.py", line 766, in child_process
    return_value = function()
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/package.py", line 1577, in build_process
    self.do_patch()
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/package.py", line 1119, in do_patch
    patch.apply(self.stage)
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/patch.py", line 88, in apply
    apply_patch(stage, self.path, self.level, self.working_dir)
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/patch.py", line 40, in apply_patch
    '-d', working_dir)
  File "/disk/software/lib/hpcpm/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/disk/software/lib/hpcpm/spack/var/spack/repos/builtin/packages/bazel/link.patch' '-d' '.'
```

**Comment by jcftang** [comment]
I suspect your system of patch may have issues on lustre or other networked filesystems where it fails to patch 'read only' files, try adding a depends_on("patch") in the bazel build and see if that helps?

**Comment by Sinan81** [comment]
Just tried it, I am still getting the same error. Thanks for the suggestion though.

**Comment by Sinan81** [comment]
On a Vagrant Centos7 box tested that TF v0.18.1 builds once link.patch is commented out (gcc@4.8.5)

**Comment by Sinan81** [comment]
v0.19.2 fails
```
2 errors found in build log:
[1,401 / 1,447] @bazel_tools//third_party/zlib:zlib; 0s local
[1,402 / 1,448] @bazel_tools//src/main/cpp/util:filesystem; 0s lo
             cal
[1,404 / 1,450] @bazel_tools//src/main/cpp/util:logging; 0s local
[1,405 / 1,450] [-----] @bazel_tools//third_party/ijar:zipper
[1,410 / 1,451] //src/main/protobuf:deps_proto; 0s worker
[1,412 / 1,451] .../build/buildjar/javac/plugins:dependency; 0s w
             orker
  >> 1629    ERROR: /tmp/spack-stage/vagrant/bazel-0.19.2-pv2xxissoloq7nquygv7o
             or3eydsuyye/spack-src/src/java_tools/buildjar/java/com/google/devt
             ools/build/buildjar/javac/plugins/BUILD:15:1: Building src/java_to
             ols/buildjar/java/com/google/devtools/build/buildjar/javac/plugins
             /libdependency.jar (3 source files) and running annotation process
             ors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1):
              java failed: error executing command
     1630      (cd /tmp/bazel_8JkJd8zd/out/execroot/io_bazel && \
     1631      exec env - \
     1632        LC_CTYPE=en_US.UTF-8 \
     1633      external/embedded_jdk/bin/java -Xmx512m -XX:+TieredCompilation '
             -XX:TieredStopAtLevel=1' -jar bazel-out/host/bin/src/java_tools/bu
             ildjar/java/com/google/devtools/build/buildjar/bootstrap_VanillaJa
             vaBuilder_deploy.jar @bazel-out/k8-opt/bin/src/java_tools/buildjar
             /java/com/google/devtools/build/buildjar/javac/plugins/libdependen
             cy.jar-0.params)
     1634    [1,412 / 1,451] .../build/buildjar/javac/plugins:dependency; 0s wo
             rker
/google/devtools/build/buildjar/javac/plugins/dependency/StrictJa
             vaDepsPlugin.java:180: error: incompatible types: int cannot be co
             nverted to com.sun.tools.javac.code.Lint.LintCategory
     1636    note: Some messages have been simplified; recompile with -Xdiags:v
             erbose to get full output
     1637    [1,412 / 1,451] .../build/buildjar/javac/plugins:dependency; 0s wo
Target //src:bazel_nojdk failed to build
     1639    [1,413 / 1,451] no action
INFO: Elapsed time: 680.746s, Critical Path: 88.50s, Remote (0.00
             % of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
     1641    [1,413 / 1,451] no action

See build log for details:
```

**Comment by Sinan81** [comment]
I just realized that it helps to use openjdk@1.8 as opposed to the latest.

**Comment by Sinan81** [comment]
This developer applies a jdk patch for v0.25.1 https://github.com/vbatts/copr-build-bazel/tree/01a8b80dec0c04b458e4d674e1bc3f024306cfda

**Comment by Sinan81** [comment]
for v0.24.1: in the following link jdk 11 is used for the build and a jdk patch  is applied 

https://github.com/vbatts/copr-build-bazel/tree/01a8b80dec0c04b458e4d674e1bc3f024306cfda

**Comment by Sinan81** [comment]
Easybuild uses jdk8 to compile v0.25: https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/b/Bazel/Bazel-0.25.2-GCCcore-8.2.0.eb

**Comment by aweits** [comment]
Sinan,
  The issue here is with the linker and environment patches. They need to be updated to pass these environment variables:

+    SPACK_TARGET_ARGS
+    SPACK_DTAGS_TO_ADD
+    SPACK_DTAGS_TO_STRIP
+    SPACK_LINKER_ARG

also, there seems to be an issue with the code that deals with the dependent module make_jobs, which I've hacked around using hasattr().

I'll work towards submitting an actual fix, but hopefully this gets you unstuck.

**Comment by Sinan81** [comment]
@aweits Thanks for the suggestions. It would be great if Bazel v0.24.1 can be built so that we can build latest Tensorflow version with it. I should also mention that now it is possible to build Bazel v0.19.x with the following PR: #13112
