### ISSUE TITLE
Installation issue: cutadapt

### ISSUE THREAD

**Issue by omsai** [spack/spack#12419]
1. The issue exists both with the git stable master 0.12.1 branch as well as the develop branch.
2. Yes, in both cases I confirmed the `package.py` file has the line `depends_on('py-setuptools', type=('build', 'run'))` as described in #11279

### Steps to reproduce the issue

```python-traceback
$ spack install py-cutadapt
...
$ spack load py-cutadapt
$ cutadapt
Traceback (most recent call last):
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-cutadapt-1.13-jwalyjs6mh4tpqdpw27twheq3dzoneoj/bin/cutadapt", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
pan14001@corelab2:~$ spack load -r py-cutadapt
pan14001@corelab2:~$ cutadapt
Traceback (most recent call last):
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-cutadapt-1.13-jwalyjs6mh4tpqdpw27twheq3dzoneoj/bin/cutadapt", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.4.0/py-setuptools-41.0.1-6ll4vdwgfhpd5l7fhvu7wsct2mxvi5tz/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'bz2file' distribution was not found and is required by xopen
pan14001@corelab2:~$
```

### Platform and user environment

Please report your OS here:

```console
$ uname -a 
Linux corelab2 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    Ubuntu 18.04.3 LTS
``` 
and, if relevant, post or attach `packages.yaml` to the issue

```yaml
packages:
  all:
    permissions:
      write: group
      group: users
  r:
    paths:
      r@3.6.1: /usr/bin
    buildable: false
```

### Additional information

```console
$ spack spec --install-status py-cutadapt
Input spec
--------------------------------
 -   py-cutadapt

Concretized
--------------------------------
[+]  py-cutadapt@1.13%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]      ^py-setuptools@41.0.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]          ^python@2.7.16%gcc@7.4.0+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-ubuntu18.04-x86_64
[+]              ^bzip2@1.0.8%gcc@7.4.0+shared arch=linux-ubuntu18.04-x86_64
[+]                  ^diffutils@3.7%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]              ^expat@2.2.5%gcc@7.4.0+libbsd arch=linux-ubuntu18.04-x86_64
[+]                  ^libbsd@0.9.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]              ^gdbm@1.18.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]                  ^readline@7.0%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]                      ^ncurses@6.1%gcc@7.4.0~symlinks~termlib arch=linux-ubuntu18.04-x86_64
[+]                          ^pkgconf@1.6.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]              ^gettext@0.19.8.1%gcc@7.4.0+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-ubuntu18.04-x86_64
[+]                  ^libxml2@2.9.9%gcc@7.4.0~python arch=linux-ubuntu18.04-x86_64
[+]                      ^libiconv@1.15%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]                      ^xz@5.2.4%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]                      ^zlib@1.2.11%gcc@7.4.0+optimize+pic+shared arch=linux-ubuntu18.04-x86_64
[+]                  ^tar@1.31%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]              ^libffi@3.2.1%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
[+]              ^openssl@1.1.1c%gcc@7.4.0+systemcerts arch=linux-ubuntu18.04-x86_64
[+]                  ^perl@5.26.2%gcc@7.4.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-ubuntu18.04-x86_64
[+]              ^sqlite@3.28.0%gcc@7.4.0+fts~functions arch=linux-ubuntu18.04-x86_64
[+]      ^py-xopen@0.5.0%gcc@7.4.0 arch=linux-ubuntu18.04-x86_64
```

**Comment by omsai** [comment]
Issue persists using latest upstream version available on `pip`:

```console
$ spack install py-cutadapt@2.4 ^python@3:
```

**Comment by omsai** [comment]
This issue was PEBKAC.  I had run into an issue with a duplicate of bzip2 in my local namespace to solve the type of problem described in this [mailing list post](https://groups.google.com/g/spack/c/yeceTzEdq5w/m/c71I97KGCwAJ).  No problem installing `py-cutadapt@2.10` now.

```console
$ spack spec -I py-cutadapt
Input spec
--------------------------------
 -   py-cutadapt

Concretized
--------------------------------
 -   py-cutadapt@2.10%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
 -       ^py-dnaio@0.4.2%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]          ^py-pip@21.3.1%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]              ^python@3.9.12%gcc@7.5.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu18.04-ivybridge
[+]                  ^bzip2@1.0.8%gcc@7.5.0~debug~pic+shared arch=linux-ubuntu18.04-ivybridge
[+]                  ^expat@2.4.8%gcc@7.5.0+libbsd arch=linux-ubuntu18.04-ivybridge
[+]                      ^libbsd@0.11.5%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]                          ^libmd@1.0.4%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]                  ^gdbm@1.19%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]                      ^readline@8.1%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]                          ^ncurses@6.2%gcc@7.5.0~symlinks+termlib abi=none arch=linux-ubuntu18.04-ivybridge
[+]                  ^gettext@0.21%gcc@7.5.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu18.04-ivybridge
[+]                      ^libiconv@1.16%gcc@7.5.0 libs=shared,static arch=linux-ubuntu18.04-ivybridge
[+]                      ^libxml2@2.9.12%gcc@7.5.0~python arch=linux-ubuntu18.04-ivybridge
[+]                          ^xz@5.2.5%gcc@7.5.0~pic libs=shared,static arch=linux-ubuntu18.04-ivybridge
[+]                          ^zlib@1.2.12%gcc@7.5.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu18.04-ivybridge
[+]                      ^tar@1.34%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]                  ^libffi@3.4.2%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]                  ^openssl@1.1.1n%gcc@7.5.0~docs~shared certs=system arch=linux-ubuntu18.04-ivybridge
[+]                  ^sqlite@3.37.2%gcc@7.5.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-ubuntu18.04-ivybridge
[+]                  ^util-linux-uuid@2.37.4%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]          ^py-setuptools@59.4.0%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
 -           ^py-setuptools-scm@7.0.5%gcc@7.5.0+toml arch=linux-ubuntu18.04-ivybridge
 -               ^py-packaging@21.3%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
 -                   ^py-pyparsing@3.0.9%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
 -                       ^py-flit-core@3.7.1%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
[+]                          ^py-wheel@0.37.0%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
 -               ^py-tomli@2.0.1%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
 -               ^py-typing-extensions@4.3.0%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
 -           ^py-xopen@0.8.4%gcc@7.5.0 arch=linux-ubuntu18.04-ivybridge
$ spack install py-cutadapt && spack load py-cutadapt && cutadapt --help
...
cutadapt version 2.10

Copyright (C) 2010-2020 Marcel Martin <marcel.martin@scilifelab.se>

cutadapt removes adapter sequences from high-throughput sequencing reads.

Usage:
    cutadapt -a ADAPTER [options] [-o output.fastq] input.fastq
...
$ spack debug report
* **Spack:** 0.19.0.dev0 (164d5fc7a40e09b26a50a0bb358519643cf98d32)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-ivybridge
* **Concretizer:** clingo
```
