### ISSUE TITLE
.DS_Store issues with environments

### ISSUE THREAD

**Issue by adrienbernede** [spack/spack#12510]
I have some troubles using environments on MacOS as soon as .DS_Store exists. I know the problem was already reported, but is supposed to have been solved.

### Steps to reproduce the issue
I have a simple reproducer for the issue I am running into : 
 - On MacOs.
 - Clone Spack.
 - Use finder and "go to folder" to navigate the `spack/var/spack/repos/builtin/packages`, and try clicking some directory until a `.DS_Store` file is created.

Then the two following didn’t worked for me:
 - Try to concertize even the simpler external environment.
 - Create a new environment, activate it, and try to add a spec.

Both leads to:
```
==> Error: [Errno 20] Not a directory:
'/Users/bernede1/Tests/spack/var/spack/repos/builtin/packages/.DS_Store/package.py'
```

Spack is up-to-date and history contains the Christmas merge of #10198.

### Error Message
```
> spack -d --stacktrace add gcc
lib/spack/spack/cmd/__init__.py:98 ==> [2019-08-21-11:26:08.487537] Imported add from built-in commands
lib/spack/spack/cmd/__init__.py:98 ==> [2019-08-21-11:26:08.488309] Imported add from built-in commands
lib/spack/spack/config.py:684 ==> [2019-08-21-11:26:08.522024] Reading config file /Users/username/Tests/spack/et    c/spack/defaults/modules.yaml
lib/spack/spack/config.py:684 ==> [2019-08-21-11:26:08.528377] Reading config file /Users/username/Tests/spack/et    c/spack/defaults/darwin/modules.yaml
lib/spack/spack/config.py:684 ==> [2019-08-21-11:26:08.530475] Reading config file /Users/username/Tests/spack/va    r/spack/environments/toto/spack.yaml
lib/spack/spack/config.py:684 ==> [2019-08-21-11:26:08.533611] Reading config file /Users/username/Tests/spack/et    c/spack/defaults/config.yaml
lib/spack/spack/config.py:684 ==> [2019-08-21-11:26:08.552602] Reading config file /Users/username/Tests/spack/et    c/spack/defaults/repos.yaml
Traceback (most recent call last):
  File "/Users/username/Tests/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/Users/username/Tests/spack/lib/spack/spack/main.py", line 697, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/username/Tests/spack/lib/spack/spack/main.py", line 447, in _invoke_command
    return_val = command(parser, args)
  File "/Users/username/Tests/spack/lib/spack/spack/cmd/add.py", line 31, in add
    if not env.add(spec, args.list_name):
  File "/Users/username/Tests/spack/lib/spack/spack/environment.py", line 772, in add
    elif not spack.repo.path.exists(spec.name):
  File "/Users/username/Tests/spack/lib/spack/spack/repo.py", line 678, in exists
    return any(repo.exists(pkg_name) for repo in self.repos)
  File "/Users/username/Tests/spack/lib/spack/spack/repo.py", line 678, in <genexpr>
    return any(repo.exists(pkg_name) for repo in self.repos)
  File "/Users/username/Tests/spack/lib/spack/spack/repo.py", line 1030, in exists
    return pkg_name in self._pkg_checker
  File "/Users/username/Tests/spack/lib/spack/spack/repo.py", line 1003, in _pkg_checker
    self._fast_package_checker = FastPackageChecker(self.packages_path)
  File "/Users/username/Tests/spack/lib/spack/spack/repo.py", line 132, in __init__
    self._paths_cache[packages_path] = self._create_new_cache()
  File "/Users/username/Tests/spack/lib/spack/spack/repo.py", line 175, in _create_new_cache
    raise e
OSError: [Errno 20] Not a directory: '/Users/username/Tests/spack/var/spack/repos/builtin/packages/.DS_Store/package.py'
```

### Information on your system
MacOs, Apple laptop.

**Comment by alalazo** [comment]
Related to #5610
