### ISSUE TITLE
Warning: specifying a "dotkit" module root has no effect

### ISSUE THREAD

**Issue by mathsen** [spack/spack#13045]
Today I pulled the newest commits from the spack dev branch (since I was affected by [this](https://github.com/spack/spack/pull/12962) bug and now executing setup-env.sh leads to this error:

```
$ $SPACK_ROOT/share/spack/setup-env.sh 

==> Warning: specifying a "dotkit" module root has no effect [support for dotkit module files has been dropped]
Traceback (most recent call last):
  File "/apps/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/apps/spack/lib/spack/spack/main.py", line 651, in main
    print_setup_info(*args.print_shell_vars.split(','))
  File "/apps/spack/lib/spack/spack/main.py", line 598, in print_setup_info
    module_to_roots[name].append(path)
KeyError: 'dotkit'

```
The warning is also shown when running just "spack list", here is the (relevant) output with the "-d --stacktrace" option:

```
$ spack -d --stacktrace list

lib/spack/spack/config.py:684 ==> [2019-10-04-08:09:48.160306] Reading config file /apps/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:684 ==> [2019-10-04-08:09:48.169278] Reading config file /apps/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/config.py:684 ==> [2019-10-04-08:09:48.172336] Reading config file /home/anselmam/.spack/modules.yaml
lib/spack/spack/config.py:684 ==> [2019-10-04-08:09:48.177407] Reading config file /apps/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:684 ==> [2019-10-04-08:09:48.191328] Reading config file /home/anselmam/.spack/config.yaml
lib/spack/spack/schema/__init__.py:93 ==> [2019-10-04-08:09:48.204053] Warning: specifying a "dotkit" module root has no effect [support for dotkit module files has been dropped]
lib/spack/spack/cmd/__init__.py:101 ==> [2019-10-04-08:09:48.206996] Imported list from built-in commands
lib/spack/spack/cmd/__init__.py:101 ==> [2019-10-04-08:09:48.207759] Imported list from built-in commands
lib/spack/spack/config.py:684 ==> [2019-10-04-08:09:48.218166] Reading config file /apps/spack/etc/spack/defaults/repos.yaml
```

Afterwards spack does not change my $MODULEPATH, so the modules created by spack are not available with "module av", if I don't adjust my $MODULEPATH manually.

### Information on your system
 1. Arch linux
 2. lmod for loading module files

**Comment by alalazo** [comment]
Can you please run:
```console
spack config blame config
```
and post the output? I think I missed to update a place in `main.py` when writing #11986 and that you have a custom `dotkit` path specified in `config.yaml`.

**Comment by mathsen** [comment]
Here we go:
```

$ spack config blame config
==> Warning: specifying a "dotkit" module root has no effect [support for dotkit module files has been dropped]
---                                            config:
_builtin                                         debug: False
~/.spack/config.yaml:66             verify_ssl: True
~/.spack/config.yaml:77             checksum: True
~/.spack/config.yaml:82             dirty: False
_builtin                                         build_jobs: 16
~/.spack/config.yaml:49             build_stage:
~/.spack/config.yaml:51             - $spack/var/spack/stage
/apps/spack/etc/spack/defaults/config.yaml:63    - $tempdir/$user/spack-stage
/apps/spack/etc/spack/defaults/config.yaml:64    - ~/.spack/stage
~/.spack/config.yaml:19             install_tree: $spack/opt/spack
~/.spack/config.yaml:23             template_dirs:
~/.spack/config.yaml:24             - $spack/share/spack/templates
~/.spack/config.yaml:28             install_path_scheme: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}
~/.spack/config.yaml:32             module_roots:
~/.spack/config.yaml:33               tcl: $spack/share/spack/modules
~/.spack/config.yaml:34               lmod: $spack/share/spack/lmod
~/.spack/config.yaml:35               dotkit: $spack/share/spack/dotkit
~/.spack/config.yaml:56             source_cache: $spack/var/spack/cache
~/.spack/config.yaml:61             misc_cache: ~/.spack/cache
~/.spack/config.yaml:72             install_missing_compilers: False
~/.spack/config.yaml:90             build_language: C
~/.spack/config.yaml:99             locks: True
~/.spack/config.yaml:109            ccache: False
~/.spack/config.yaml:116            db_lock_timeout: 120
~/.spack/config.yaml:124            package_lock_timeout: !!null 'None'
```
Hope that helps :)

**Comment by alalazo** [comment]
@mathsen Working on a more permanent fix right now. As a quicker workaround you can delete:
```console
~/.spack/config.yaml:35               dotkit: $spack/share/spack/dotkit
```

**Comment by mathsen** [comment]
@alalazo That was really fast! Thanks for the (very) quick help!

**Comment by mathsen** [comment]
@alalazo With your fix I now get:

```
$ $SPACK_ROOT/share/spack/setup-env.sh

==> Warning: specifying a "dotkit" module root has no effect [support for dotkit module files has been dropped]
```

Nothing more - so I guess it works :) The warning comes from the fact, that I just copied the default config from the spack root directory to my home folder and adjusted the things I needed... I removed the "dotkit" line as you advised (and which seems to be new default now).

Unfortunately I'm still not able to see the spack module files without manipulating my $MODULEPATH manually... but I think that's another problem...

**Comment by alalazo** [comment]
> Unfortunately I'm still not able to see the spack module files without manipulating my $MODULEPATH manually... but I think that's another problem...

I am not able to reproduce your issue with MODULEPATH. Can you please open a new bug report if you find a reliable reproducer?

**Comment by mathsen** [comment]
alalazo: Ignore my comment, now everything works as expected... I just had to comment in the line where setup-env.sh is being sourced in my .profile file...
Thanks again for your fast help fixing this bug!
