### ISSUE TITLE
Spack trying to create module for external package when it has been told not to

### ISSUE THREAD

**Issue by bartlettroscoe** [spack/spack#13516]
CC: @fryeguy52 

Tag: snl-atdm-issue

Using the updated 0.13.0 version of spack, using the files:

<details>
<summary><b>spack.yaml</b></summary>

```
# Spack env file to build a compiler using Spack
#
# NOTE: Spack will not only read this file but will also write to it so make
# sure you create a copy before spack uses it!
#
spack:
  # Packages to build (ordered mostly by dependencies)
  specs: [
    gcc@7.2.0 ,
    ]
  modules:
    tcl:
      hash_length: 0
      naming_scheme: spack-${PACKAGE}/${VERSION}
      whitelist:
        - gcc
      blacklist:
        - '%'
      all:
        conflict:
          - '{name}'
        filter:
          environment_blacklist: [CPATH, LIBRARY_PATH]
        environment:
          set:
            ${PACKAGE}_ROOT: ${PREFIX}
      verbose: false
  packages:
    all:
      compiler: []
  include:
    - packages_tools_for_compiler_build.yaml
    - common_options.yaml
    - preinstalled_packages.yaml
```

</details>

<details>
<summary><b>common_options.yaml</b></summary>

```
mirrors:
  local_filesystem: file:///ascldap/users/rabartl/Spack.base4/atdm-spack/atdm-spack-tarball-mirror
config:
  misc_cache: .spack/cache
```

</details>

<details>
<summary><b>preinstalled_packages.yaml</b></summary>

```
packages:
  perl:
    buildable: False
    paths:
      perl@5.10.1 %gcc arch=linux-rhel6-x86_64: /usr
      perl@5.10.1 %gcc arch=linux-rhel6-core2: /usr
  autoconf:
    buildable: False
    paths:
      autoconf@2.63 %gcc arch=linux-rhel6-x86_64: /usr 
      autoconf@2.63 %gcc arch=linux-rhel6-core2: /usr 
  automake:
    buildable: False
    paths:
      automake@1.11.1 %gcc arch=linux-rhel6-x86_64: /usr
      automake@1.11.1 %gcc arch=linux-rhel6-core2: /usr
  m4:
    buildable: False
    paths:
      m4@1.4.13 %gcc arch=linux-rhel6-x86_64: /usr
      m4@1.4.13 %gcc arch=linux-rhel6-core2: /usr
  libtool:
    buildable: False
    paths:
      libtool@2.2.6b %gcc arch=linux-rhel6-x86_64: /usr
      libtool@2.2.6b %gcc arch=linux-rhel6-core2: /usr
  tar:
    buildable: False
    paths:
      tar@1.23 %gcc arch=linux-rhel6-x86_64: /
      tar@1.23 %gcc arch=linux-rhel6-core2: /
  diffutils:
    buildable: False
    paths:
      diffutils@2.8.1 %gcc arch=linux-rhel6-x86_64: /usr
      diffutils@2.8.1 %gcc arch=linux-rhel6-core2: /usr
```

</details>

<details>
<summary><b>atdm-spack/spack/etc/spack/modules.yaml</b></summary>

```
# This file is needed to stop spack from trying to generate dotkit modules for
# external packages

modules:
  enable::
    - tcl
```

</details>

running:

```
$./atdm-spack/spack/bin/spack install
```

produces:

```
==> Concretized gcc@7.2.0
 -   zzfkclh  gcc@7.2.0%gcc@4.4.7~binutils languages=c,c++,fortran ~nvptx patches=51aebe82afc9a0433ca3503a36592edf5ca769b1433986919cfb9ae2ddf3e343 ~piclibs~strip arch=linux-rhel6-core2
 -   pbouq4g      ^gmp@6.1.2%gcc@4.4.7 arch=linux-rhel6-core2
 -   egzrwwp          ^autoconf@2.63%gcc@4.4.7 arch=linux-rhel6-core2
 -   j3qtjf4          ^automake@1.11.1%gcc@4.4.7 arch=linux-rhel6-core2
 -   2uogxqf          ^libtool@2.2.6b%gcc@4.4.7 arch=linux-rhel6-core2
 -   2m4zmsg          ^m4@1.4.13%gcc@4.4.7+sigsegv arch=linux-rhel6-core2
 -   nizawm4      ^isl@0.18%gcc@4.4.7 arch=linux-rhel6-core2
 -   ddtcqci      ^libiconv@1.16%gcc@4.4.7 arch=linux-rhel6-core2
 -   giua3so      ^mpc@1.1.0%gcc@4.4.7 arch=linux-rhel6-core2
 -   laq5nlz          ^mpfr@3.1.6%gcc@4.4.7 patches=66a5d58364113a21405fc53f4a48f4e8 arch=linux-rhel6-core2
 -   6phegih      ^zlib@1.2.11%gcc@4.4.7+optimize+pic+shared arch=linux-rhel6-core2

==> Updating view at /home/rabartl/Spack.base4/.spack-env/view
==> Installing environment /home/rabartl/Spack.base4
==> autoconf@2.63 : externally installed in /usr
==> autoconf@2.63 : generating module file
==> Error: Unexpected end of input
```

The detailed output from:

```
$ ./atdm-spack/spack/bin/spack -d install --verbose
```

is given in:

<details>

<summary><b>Detailed install debug output</b></summary>

```
==> [2019-10-30-18:03:13.374007] Reading config file /home/rabartl/Spack.base4/atdm-spack/spack/etc/spack/defaults/modules.yaml
==> [2019-10-30-18:03:13.382169] Reading config file /home/rabartl/Spack.base4/atdm-spack/spack/etc/spack/defaults/linux/modules.yaml
==> [2019-10-30-18:03:13.384991] Reading config file /home/rabartl/Spack.base4/atdm-spack/spack/etc/spack/modules.yaml
==> [2019-10-30-18:03:13.386331] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.386915] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.387344] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.388334] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.389182] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.389991] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.390570] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.392415] Imported install from built-in commands
==> [2019-10-30-18:03:13.393237] Imported install from built-in commands
==> [2019-10-30-18:03:13.393939] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.394527] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.395183] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.395751] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.396494] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.437327] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.437453] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.437637] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.437719] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.437822] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.437992] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.438252] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.438358] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.438529] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.438602] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.438702] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.438874] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.445279] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.445400] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.445581] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.445662] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.445766] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.445938] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.446190] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.446302] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.446474] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.446542] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.446642] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.446814] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.452996] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.453117] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.453309] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.453390] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.453493] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.453662] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.453914] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.454017] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.454187] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.454260] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.454360] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.454531] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.458184] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.458309] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.458488] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.458571] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.458674] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.458841] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.459091] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.459199] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.459372] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.459439] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.459538] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.459708] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.469406] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.469532] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.469714] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.469794] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.469897] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.470065] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.470322] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.470426] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.470595] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.470663] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.470762] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.470930] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.478420] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.478541] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.478721] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.478803] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.478905] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.479074] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.479333] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.479439] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.479609] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.479676] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.479776] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.479944] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.483919] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.484038] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.484222] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.484304] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.484406] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.484572] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.484824] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.484926] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.485095] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.485166] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.485277] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.485446] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.486373] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.486479] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.486653] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.486738] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.486839] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.487004] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.487080] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.487179] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.487350] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.488077] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.488319] WRITE LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/prefix_lock[7432435367349373429:1] [Acquiring]
==> [2019-10-30-18:03:13.488437] WRITE LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/prefix_lock[7432435367349373429:1] [Acquired]
==> [2019-10-30-18:03:13.488500] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.488596] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.488768] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.488836] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.488936] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.489108] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.494997] WRITE LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/prefix_lock[7432435367349373429:1] [Released]
==> [2019-10-30-18:03:13.496312] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.497804] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.498074] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/prefix_lock[7432435367349373429:1] [Acquiring]
==> [2019-10-30-18:03:13.498191] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/prefix_lock[7432435367349373429:1] [Acquired]
==> [2019-10-30-18:03:13.498264] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.498359] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.498545] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.498796] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/prefix_lock[7432435367349373429:1] [Released]
==> [2019-10-30-18:03:13.498860] Installing gcc dependencies
==> [2019-10-30-18:03:13.499302] Reading config file /home/rabartl/Spack.base4/packages_tools_for_compiler_build.yaml
==> [2019-10-30-18:03:13.501024] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.501137] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.501327] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.501398] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-10-30-18:03:13.501500] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-10-30-18:03:13.501673] READ LOCK: /home/rabartl/Spack.base4/atdm-spack/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-10-30-18:03:13.502424] SKIP: shebang filtering [external package]
==> [2019-10-30-18:03:13.506373] SpecParseError: Unexpected end of input
==> [2019-10-30-18:03:13.506433] Error: Unexpected end of input
==> [2019-10-30-18:03:13.486161] Updating view at /home/rabartl/Spack.base4/.spack-env/view
==> [2019-10-30-18:03:13.486258] Installing environment /home/rabartl/Spack.base4
==> [2019-10-30-18:03:13.500953] autoconf@2.63 : externally installed in /usr
==> [2019-10-30-18:03:13.502374] autoconf@2.63 : generating module file
Traceback (most recent call last):
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/main.py", line 715, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/main.py", line 457, in _invoke_command
    return_val = command(parser, args)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/cmd/install.py", line 234, in install
    env.install_all(args)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/environment.py", line 1132, in install_all
    self._install(spec, **kwargs)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/environment.py", line 975, in _install
    spec.package.do_install(**install_args)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/package.py", line 1620, in do_install
    dep.package.do_install(**dep_kwargs)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/package.py", line 1580, in do_install
    return self._process_external_package(explicit)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/package.py", line 1463, in _process_external_package
    spack.hooks.post_install(self.spec)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/hooks/__init__.py", line 60, in __call__
    hook(*args, **kwargs)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/hooks/module_file_generation.py", line 29, in <lambda>
    post_install = lambda spec: _for_each_enabled(spec, 'write')
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/hooks/module_file_generation.py", line 22, in _for_each_enabled
    getattr(generator, method_name)()
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/modules/common.py", line 749, in write
    if self.conf.blacklisted:
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/modules/common.py", line 440, in blacklisted
    blacklist_matches = [x for x in blrules if spec.satisfies(x)]
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/spec.py", line 2823, in satisfies
    other = self._autospec(other)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/spec.py", line 2808, in _autospec
    return Spec(spec_like)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/spec.py", line 1018, in __init__
    spec_list = SpecParser(self).parse(spec_like)
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/parse.py", line 152, in parse
    return self.do_parse()
  File "/home/rabartl/Spack.base4/atdm-spack/spack/lib/spack/spack/spec.py", line 4058, in do_parse
    raise SpecParseError(e)
spack.spec.SpecParseError: Unexpected end of input
```

</details>

**Comment by bartlettroscoe** [comment]
Why is spack trying to build modules for these external packages when it is specifically told not to in the `spack.yaml` file which has:

```
  modules:
    tcl:
      hash_length: 0
      naming_scheme: spack-${PACKAGE}/${VERSION}
      whitelist:
        - gcc
      blacklist:
        - '%'
      all:
        conflict:
          - '{name}'
        filter:
          environment_blacklist: [CPATH, LIBRARY_PATH]
        environment:
          set:
            ${PACKAGE}_ROOT: ${PREFIX}
      verbose: false
```

I think we saw something like this before which is why our script installs the file `atdm-spack/spack/etc/spack/modules.yaml` which is:

```
# This file is needed to stop spack from trying to generate dotkit modules for
# external packages

modules:
  enable::
    - tcl
```

We can't get around problems like #13507 if we can't get spack to point to external packages on the system.

**Comment by alalazo** [comment]
Hi @bartlettroscoe from what I can see you have a syntax error in your file:
```yaml
modules:
    tcl:
      hash_length: 0
      naming_scheme: spack-${PACKAGE}/${VERSION}
      whitelist:
        - gcc
      blacklist:
        - '%' # <-- Error: Unexpected end of input
      all:
        conflict:
          - '{name}'
        filter:
          environment_blacklist: [CPATH, LIBRARY_PATH]
        environment:
          set:
            ${PACKAGE}_ROOT: ${PREFIX}
      verbose: false
```
 if there was not a typo copying the YAML file, I am surprised module files got generated at all. Can you please double check the `blacklist` entry above and comment here?

**Comment by bartlettroscoe** [comment]
@alalazo, thanks for the catch.  Looks like this was a defect in our script used to generate that file.  Looks like I sense fixed it as it now shows:

```
# Spack env file to build a compiler using Spack
#
# NOTE: Spack will not only read this file but will also write to it so make
# sure you create a copy before spack uses it!
#
spack:
  # Packages to build (ordered mostly by dependencies)
  specs: [
    gcc@7.2.0 arch=linux-rhel6-x86_64,
    ]
  modules:
    tcl:
      hash_length: 0
      naming_scheme: spack-${PACKAGE}/${VERSION}
      whitelist:
        - gcc
      blacklist:
        - '%gcc@4.4.7'
      all:
        conflict:
          - '{name}'
        filter:
          environment_blacklist: [CPATH, LIBRARY_PATH]
        environment:
          set:
            ${PACKAGE}_ROOT: ${PREFIX}
      verbose: false
  packages:
    all:
      compiler: [gcc@4.4.7]
  include:
    - packages_tools_for_compiler_build.yaml
    - common_options.yaml
    - preinstalled_packages.yaml
```

I will give this a try again and see what happens.

**Comment by alalazo** [comment]
@bartlettroscoe Any news on the state of this issue?
