### ISSUE TITLE
Unable to concretize environment if python isn't installed yet

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#13529]
Spack Environments crashes when you try to concretize/update an environment that contains Python, but Python hasn't been installed yet.

### Steps to reproduce the issue

```console
$ cd foo  # directory containing spack.yaml
$ spack install
```

### Error Message

```console
==> Updating view at /mnt/a/u/sciteam/stewart1/crop_classification/.spack-env/view
Traceback (most recent call last):
  File "/u/sciteam/stewart1/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/main.py", line 653, in main
    ev.activate(env, args.use_env_repo)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/environment.py", line 163, in activate
    cmds += env.add_default_view_to_shell(shell)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/environment.py", line 1074, in add_default_view_to_shell
    spec, self.default_view))
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/environment.py", line 1055, in environment_modifications_for_spec
    spec, context='run'
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/build_environment.py", line 759, in modifications_from_dependencies
    dpkg.setup_dependent_package(pkg.module, spec)
  File "/mnt/a/u/sciteam/stewart1/spack/var/spack/repos/builtin/packages/python/package.py", line 729, in setup_dependent_package
    module.setup_py = Executable(
  File "/mnt/a/u/sciteam/stewart1/spack/var/spack/repos/builtin/packages/python/package.py", line 526, in command

RuntimeError: Unable to locate python command in /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-interlagos/gcc-5.3.0/python-3.7.4-6qsrqzoxsh2tvcsoyfec5gdfibgtlsiq/bin
```
The problem is that Python is not yet installed, so the installation directory does not exist, and `spec['python'].command` crashes.

### Information on your system

Cray CNL5, GCC 5.3.0

`spack.yaml`:
```yaml
spack:
  specs:
  - gdal+python
  - python@3.7:+sqlite3
  - py-flake8
  - py-matplotlib
  - py-numpy
  - py-pandas
  - 'py-pytest@3.9:'
  - py-scikit-learn
  - 'py-scipy@0.14:'
  - 'py-tables@3.0.0:'
  - 'py-torch@0.4:'
  - py-torchvision
  concretization: together
```
@becker33 I believe this is related to #13249. Spack is trying to run `setup_run_environment` even for packages that are not yet installed, causing this crash.

**Comment by adamjstewart** [comment]
The following diff seems to fix the problem for me, although it might break other things I don't realize:
```diff
diff --git a/lib/spack/spack/environment.py b/lib/spack/spack/environment.py
index b6b181481..e2ee756a4 100644
--- a/lib/spack/spack/environment.py
+++ b/lib/spack/spack/environment.py
@@ -1069,7 +1069,7 @@ class Environment(object):
             return env_mod.shell_modifications(shell)
 
         for _, spec in self.concretized_specs():
-            if spec in self.default_view:
+            if spec in self.default_view and spec.package.installed:
                 env_mod.extend(self.environment_modifications_for_spec(
                     spec, self.default_view))
 
@@ -1087,7 +1087,7 @@ class Environment(object):
             return env_mod.shell_modifications(shell)
 
         for _, spec in self.concretized_specs():
-            if spec in self.default_view:
+            if spec in self.default_view and spec.package.installed:
                 env_mod.extend(
                     self.environment_modifications_for_spec(
                         spec, self.default_view).reversed())
```
Let me know if you want me to push a PR. I prob won't have time to add unit tests though.

**Comment by healther** [comment]
That would have fixed the problem for me, for the record, installing the `python` from outside the environment fixes the problem
