### ISSUE TITLE
Error when creating mirror in already existing mirror location

### ISSUE THREAD

**Issue by white238** [spack/spack#13722]
I ran spack twice in a row to create a mirror in the same location.  I expected it to update the mirror location with new packages.  It errored.

### Steps to reproduce the issue

```console
$ spack/bin/spack mirror create -d /usr/WS2/white238/serac/mirror --dependencies serac_devtools
$ spack/bin/spack mirror create -d /usr/WS2/white238/serac/mirror --dependencies serac_devtools
```

### Error Message

==> Adding package serac_devtools@fakeversion to mirror
==> Error: 'FileExistsError' object has no attribute 'message'

Running with -d got two stack traces in a single spack run:

Traceback (most recent call last):
  File "/usr/WS2/white238/serac/repo/uberenv_libs/spack/lib/spack/spack/mirror.py", line 506, in add_single_spec
    pkg_stage.cache_mirror(mirror_stats)
  File "/usr/WS2/white238/serac/repo/uberenv_libs/spack/lib/spack/spack/util/pattern.py", line 68, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/usr/WS2/white238/serac/repo/uberenv_libs/spack/lib/spack/spack/stage.py", line 508, in cache_mirror
    self.mirror_paths.cosmetic_path)
  File "/usr/WS2/white238/serac/repo/uberenv_libs/spack/lib/spack/spack/caches.py", line 72, in store
    os.symlink(relative_dst, cosmetic_path)
FileExistsError: [Errno 17] File exists: 'serac_devtools-fakeversion.tar.gz' -> '/usr/WS2/white238/serac/mirror/serac_devtools/serac_devtools-fakeversion.tar.gz'

==> [2019-11-13-11:04:55.099182] Successfully updated mirror in file:///usr/WS2/white238/serac/mirror
  Archive stats:
    50   already present
    0    added
    1    failed to fetch.
==> [2019-11-13-11:04:55.099393] Error: Failed downloads:
serac_devtools@fakeversion
Traceback (most recent call last):
  File "/usr/WS2/white238/serac/repo/uberenv_libs/spack/lib/spack/spack/main.py", line 715, in main
    return _invoke_command(command, parser, args, unknown)
  File "/usr/WS2/white238/serac/repo/uberenv_libs/spack/lib/spack/spack/main.py", line 457, in _invoke_command
    return_val = command(parser, args)
  File "/usr/WS2/white238/serac/repo/uberenv_libs/spack/lib/spack/spack/cmd/mirror.py", line 338, in mirror
    action[args.mirror_command](args)
  File "/usr/WS2/white238/serac/repo/uberenv_libs/spack/lib/spack/spack/cmd/mirror.py", line 324, in mirror_create
    sys.exit(1)
SystemExit: 1

### Information on your system

This includes:

 1. llnl, toss3, rzgenie
 2. Custom package.py:

from spack import *

class SeracDevtools(BundlePackage):
    """This is a set of tools necessary for the developers of Serac"""

    version('fakeversion')

    depends_on('astyle')
    depends_on('cmake')
    depends_on('cppcheck')
    depends_on('doxygen')
    depends_on('python')
    depends_on('py-sphinx')

**Comment by scheibelp** [comment]
For starters the mirror logic shouldn't be attempting to fetch `BundlePackage`s. Is there by chance a `url` attribute in your `SeracDevtools` package?

Either way I'll need to fix the error reporting.

**Comment by white238** [comment]
The copy and pasted (though weirdly formatted) SeracDevTools is all that is in that file.  There is no url attribute.

**Comment by scheibelp** [comment]
https://github.com/spack/spack/pull/13789 (which is now part of develop) will address the issue where this error terminates the whole process of mirroring.

However, I can replicate the issue where Spack attempts to download a version of `serac-devtools` (in the current develop branch this means that an error message is printed but Spack continues to download the dependency packages).
