### ISSUE TITLE
cannot proceed uninstalling specs with remaining dependents

### ISSUE THREAD

**Issue by ifelsefi** [spack/spack#13842]
Just pulled the latest from `develop` and now I cannot remove packages anymore which have dependents.

```
    -- linux-centos7-cascadelake / gcc@9.2.0 ------------------------
    5aalmfg m4@1.4.18%gcc  patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv
==> Do you want to proceed? [y/N] y
==> Error: unexpected error [cannot proceed uninstalling specs with remaining dependents m4]
```

**Comment by alalazo** [comment]
A few questions:

1. Are you working within an environment?
2. Can you show the output of `spack dependents -i /5aalmfg`?

**Comment by ifelsefi** [comment]
No environment.

Maybe this is related.  Trying to now add `hmmer` with previously installed OpenMPI.  But I get anon spec error.

```
[root@phobos centos7]# spack spec hmmer ^/xofc6eg %gcc@9.2.0 target=$(spack arch -t)
Input spec
--------------------------------
hmmer
    ^openmpi@4.0.2%gcc@9.2.0~cuda+cxx_exceptions fabrics=verbs ~java+legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-centos7-cascadelake
        ^hwloc@1.11.11%gcc@9.2.0~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos7-cascadelake
            ^libpciaccess@0.13.5%gcc@9.2.0 arch=linux-centos7-cascadelake
            ^libxml2@2.9.9%gcc@9.2.0~python arch=linux-centos7-cascadelake
                ^libiconv@1.16%gcc@9.2.0 arch=linux-centos7-cascadelake
                ^xz@5.2.4%gcc@9.2.0 arch=linux-centos7-cascadelake
                ^zlib@1.2.11%gcc@9.2.0+optimize+pic+shared arch=linux-centos7-cascadelake
            ^numactl@2.0.12%gcc@9.2.0 arch=linux-centos7-cascadelake

Concretized
--------------------------------
hmmer@3.3%gcc@9.2.0~gsl+mpi arch=linux-centos7-cascadelake
    ^openmpi@4.0.2%gcc@9.2.0~cuda+cxx_exceptions fabrics=verbs ~java+legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-centos7-cascadelake
        ^hwloc@1.11.11%gcc@9.2.0~cairo~cuda~gl+libxml2~nvml+pci+shared arch=linux-centos7-cascadelake
            ^libpciaccess@0.13.5%gcc@9.2.0 arch=linux-centos7-cascadelake
            ^libxml2@2.9.9%gcc@9.2.0~python arch=linux-centos7-cascadelake
                ^libiconv@1.16%gcc@9.2.0 arch=linux-centos7-cascadelake
                ^xz@5.2.4%gcc@9.2.0 arch=linux-centos7-cascadelake
                ^zlib@1.2.11%gcc@9.2.0+optimize+pic+shared arch=linux-centos7-cascadelake
            ^numactl@2.0.12%gcc@9.2.0 arch=linux-centos7-cascadelake

Input spec
--------------------------------
%gcc@9.2.0 arch=linux-None-cascadelake

Concretized
--------------------------------
==> Error: Attempting to concretize anonymous spec
```
Odd that we see `arch=linux-None-cascadelake`

**Comment by alalazo** [comment]
For the anonymous spec see https://github.com/spack/spack/issues/13834#issuecomment-557421679

**Comment by ifelsefi** [comment]
I forget that compiler is know thanks @alalazo!

Let me see if I can reproduce this uninstall issue.  I manually removed the previous specs and problem's gone for now.

**Comment by ifelsefi** [comment]
Ok issue present again

Trying to get `hmmer` going with previously-added MPI:

```
[root@phobos centos7]# spack install hmmer ^/xofc6eg
==> libpciaccess is already installed in /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/libpciaccess-0.13.5-da4vwv3dsaldnmi246howsekahwgleon
==> libiconv is already installed in /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/libiconv-1.16-vfegwsn4i6jlfbqmwp7neqhvuge7xpuj
==> xz is already installed in /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/xz-5.2.4-5ifshq5gh72jv4kpohem2jeit634dnof
==> zlib is already installed in /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/zlib-1.2.11-ndmeluphsrq2cxkfdmxg4wma6w4hknqs
==> libxml2 is already installed in /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/libxml2-2.9.9-cpatapvhr3dc7hvriujjioozufsccg2a
==> Installing numactl
==> Searching for binary cache of numactl
==> Warning: No Spack mirrors are currently configured
==> No binary for numactl found: installing from source
==> Fetching https://github.com/numactl/numactl/archive/v2.0.12.tar.gz
######################################################################## 100.0%
==> Staging archive: /tmp/root/spack-stage/spack-stage-numactl-2.0.12-bi25exb6tecgklh3pkw26iiy5rknljwy/v2.0.12.tar.gz
==> Created stage in /tmp/root/spack-stage/spack-stage-numactl-2.0.12-bi25exb6tecgklh3pkw26iiy5rknljwy
==> No patches needed for numactl
==> Building numactl [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Error: RuntimeError: Cannot generate configure: missing dependencies ['m4', 'autoconf', 'automake', 'libtool']

/pbtech_mounts/software/spack/centos7/lib/spack/spack/build_systems/autotools.py:210, in autoreconf:
        207        autotools = ['m4', 'autoconf', 'automake', 'libtool']
        208        missing = [x for x in autotools if x not in spec]
        209        if missing:
  >>    210            msg = 'Cannot generate configure: missing dependencies {0}'
        211            raise RuntimeError(msg.format(missing))
        212        tty.msg('Configure script not found: trying to generate it')
        213        tty.warn('*********************************************************')

```

As you can see we are missing some dependencies that Spack did not add.  Though they are in fact present:

```
[root@phobos centos7]# spack find m4 arch=cascadelake
==> 1 installed package
-- linux-centos7-cascadelake / gcc@9.2.0 ------------------------
m4@1.4.18
[root@phobos centos7]# spack find autoconf arch=cascadelake
==> 1 installed package
-- linux-centos7-cascadelake / gcc@9.2.0 ------------------------
autoconf@2.69
[root@phobos centos7]# spack find automake arch=cascadelake
==> 1 installed package
-- linux-centos7-cascadelake / gcc@9.2.0 ------------------------
automake@1.16.1
[root@phobos centos7]# spack find libtool arch=cascadelake
==> 1 installed package
-- linux-centos7-cascadelake / gcc@9.2.0 ------------------------
libtool@2.4.6
```

If I try to remove `libiconv`, which was recently installed as a dependency for `hmmer`, I get the uninstall issue:


```
[root@phobos centos7]# spack uninstall /vfegwsn4i6jlfbqmwp7neqhvuge7xpuj
==> The following packages will be uninstalled:

    -- linux-centos7-cascadelake / gcc@9.2.0 ------------------------
    vfegwsn libiconv@1.16%gcc 
==> Do you want to proceed? [y/N] y
==> Error: unexpected error [cannot proceed uninstalling specs with remaining dependents libiconv]
```

Seems an issue with dependents:

```

[root@phobos centos7]# spack dependents -i /vfegwsn
==> Dependents of libiconv@1.16%gcc@9.2.0/vfegwsn
-- linux-centos7-cascadelake / gcc@9.2.0 ------------------------
cpatapv libxml2@2.9.9
```

**Comment by ifelsefi** [comment]
Another

Some recent things added to this target:

```
[root@phobos centos7]# ls -ltr /pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-cascadelake/gcc-9.2.0/ | tail
drwxr-sr-x  6 root root   55 Nov 20 11:46 bcftools-1.9-yeiyyofpsivquifdzcrcrvnn2jbpuipy
drwxr-sr-x  4 root root   29 Nov 20 11:50 bedops-2.4.35-7yrtwholtbmbxsee72dlqmzjmmbhp3i5
drwxr-sr-x  7 root root   65 Nov 20 11:52 gsl-2.5-e5qmuo45fr3cuu2amdvqxnac2xy2v3un
drwxr-sr-x  6 root root   53 Nov 20 11:54 openblas-0.3.7-o5rocg26djbcjmaekw2yuu3tg6syc6ys
drwxr-sr-x  5 root root   39 Nov 20 11:57 py-numpy-1.17.4-2ltpmxierjkhbwlvfwjsggvqlgv7cfwm
drwxr-sr-x  5 root root   39 Nov 20 11:59 py-macs2-2.2.4-q46qssuqgss42t2kwxk5cg3tplesiwee
drwxr-sr-x  7 root root   65 Nov 22 11:30 libiconv-1.16-vfegwsn4i6jlfbqmwp7neqhvuge7xpuj
drwxr-sr-x  7 root root   65 Nov 22 11:30 xz-5.2.4-5ifshq5gh72jv4kpohem2jeit634dnof
drwxr-sr-x  6 root root   55 Nov 22 11:30 zlib-1.2.11-ndmeluphsrq2cxkfdmxg4wma6w4hknqs
drwxr-sr-x  7 root root   65 Nov 22 11:30 libxml2-2.9.9-cpatapvhr3dc7hvriujjioozufsccg2a
```

One more try:

```
[root@phobos centos7]# spack -d uninstall /5ifshq5gh72jv4kpohem2jeit634dnof
==> [2019-11-22-11:56:51.763146] Reading config file /pbtech_mounts/software/spack/centos7/etc/spack/defaults/modules.yaml
==> [2019-11-22-11:56:51.770418] Reading config file /pbtech_mounts/software/spack/centos7/etc/spack/defaults/linux/modules.yaml
==> [2019-11-22-11:56:51.773363] Reading config file /pbtech_mounts/software/spack/centos7/etc/spack/defaults/config.yaml
==> [2019-11-22-11:56:51.786869] Imported uninstall from built-in commands
==> [2019-11-22-11:56:51.787243] Imported uninstall from built-in commands
==> [2019-11-22-11:56:51.811006] DATABASE LOCK TIMEOUT: 120s
==> [2019-11-22-11:56:51.811056] PACKAGE LOCK TIMEOUT: No timeout
==> [2019-11-22-11:56:51.811269] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-11-22-11:56:51.811899] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-11-22-11:56:51.922187] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-11-22-11:56:51.922751] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-11-22-11:56:51.923198] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-11-22-11:56:52.025387] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-11-22-11:56:52.025966] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-11-22-11:56:52.026513] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-11-22-11:56:52.169298] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-11-22-11:56:52.227510] The following packages will be uninstalled:

    -- linux-centos7-cascadelake / gcc@9.2.0 ------------------------
    5ifshq5 xz@5.2.4%gcc 
==> [2019-11-22-11:56:52.228126] Do you want to proceed? [y/N] y
==> [2019-11-22-11:56:53.743255] Reading config file /pbtech_mounts/software/spack/centos7/etc/spack/defaults/repos.yaml
==> [2019-11-22-11:56:53.789795] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-11-22-11:56:53.790315] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-11-22-11:56:53.905394] READ LOCK: /pbtech_mounts/software/spack/centos7/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-11-22-11:56:53.905905] SpackError: unexpected error [cannot proceed uninstalling specs with remaining dependents xz]
==> [2019-11-22-11:56:53.905947] Error: unexpected error [cannot proceed uninstalling specs with remaining dependents xz]
Traceback (most recent call last):
  File "/pbtech_mounts/software/spack/centos7/lib/spack/spack/main.py", line 715, in main
    return _invoke_command(command, parser, args, unknown)
  File "/pbtech_mounts/software/spack/centos7/lib/spack/spack/main.py", line 457, in _invoke_command
    return_val = command(parser, args)
  File "/pbtech_mounts/software/spack/centos7/lib/spack/spack/cmd/uninstall.py", line 348, in uninstall
    uninstall_specs(args, specs)
  File "/pbtech_mounts/software/spack/centos7/lib/spack/spack/cmd/uninstall.py", line 338, in uninstall_specs
    do_uninstall(env, uninstall_list, args.force)
  File "/pbtech_mounts/software/spack/centos7/lib/spack/spack/cmd/uninstall.py", line 232, in do_uninstall
    raise spack.error.SpackError(msg)
```

**Comment by ifelsefi** [comment]
Hmm

```
[root@phobos centos7]# spack verify -a
==> In package ncurses/ct7dhsj
/pbtech_mounts/software/spack/centos7/opt/spack/linux-centos7-broadwell/gcc-9.2.0/ncurses-6.1-ct7dhsjx4szui27fgyiismkausozw5o5 verification failed with error(s):
    manifest missing
```

**Comment by ifelsefi** [comment]
OK I did `spack uninstall -a arch=cascadelake` and now this problem no longer present after pulling the code that detects cascadelake architecture properly.  Before I was doing `module use` to get that target working.  Perhaps that had a negative impact.
