### ISSUE TITLE
spack find options in environment context

### ISSUE THREAD

**Issue by adrienbernede** [spack/spack#13971]
Some `spack find` options does not work in environment context (didn’t test all options). 

### Steps to reproduce the issue

```console
$ spack install <spec>
$ spack env create test   
$ spack add <spec>
$ spack find -p <spec>
$ spack find -L <spec>
```

### Error Message

spack -d find -p
```console
==> [2019-12-03-16:08:54.354183] Reading config file /Spack/etc/spack/defaults/modules.yaml
==> [2019-12-03-16:08:54.364138] Reading config file /Spack/etc/spack/defaults/darwin/modules.yaml
==> [2019-12-03-16:08:54.369209] Imported find from built-in commands
==> [2019-12-03-16:08:54.369877] Imported find from built-in commands
==> [2019-12-03-16:08:54.379773] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-12-03-16:08:54.380109] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-12-03-16:08:54.384563] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-12-03-16:08:54.385031] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-12-03-16:08:54.385281] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-12-03-16:08:54.389610] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-12-03-16:08:54.389791] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-12-03-16:08:54.390017] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-12-03-16:08:54.394221] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-12-03-16:08:54.394654] In environment test
==> [2019-12-03-16:08:54.394711] Root specs
==> [2019-12-03-16:08:54.395055] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-12-03-16:08:54.395437] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-12-03-16:08:54.399598] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-12-03-16:08:54.399690] SpecError: Spec is not concrete: zlib
==> [2019-12-03-16:08:54.406229] Error: Spec is not concrete: zlib
Traceback (most recent call last):
  File "/Spack/lib/spack/spack/main.py", line 715, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Spack/lib/spack/spack/main.py", line 457, in _invoke_command
    return_val = command(parser, args)
  File "/Spack/lib/spack/spack/cmd/find.py", line 222, in find
    display_env(env, args, decorator)
  File "/Spack/lib/spack/spack/cmd/find.py", line 178, in display_env
    variants=True
  File "/Spack/lib/spack/spack/cmd/__init__.py", line 390, in display_specs
    format_list(specs)
  File "/Spack/lib/spack/spack/cmd/__init__.py", line 384, in format_list
    print(path_fmt % (string, spec.prefix))
  File "/Spack/lib/spack/spack/spec.py", line 1343, in prefix
    raise SpecError("Spec is not concrete: " + str(self))
spack.error.SpecError: Spec is not concrete: zlib
```

spack -d find -L
```console
==> [2019-12-03-16:04:50.207995] Reading config file /Spack/etc/spack/defaults/modules.yaml
==> [2019-12-03-16:04:50.217298] Reading config file /Spack/etc/spack/defaults/darwin/modules.yaml
==> [2019-12-03-16:04:50.223074] Imported find from built-in commands
==> [2019-12-03-16:04:50.223804] Imported find from built-in commands
==> [2019-12-03-16:04:50.239337] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-12-03-16:04:50.239735] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-12-03-16:04:50.244797] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-12-03-16:04:50.245360] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-12-03-16:04:50.245689] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-12-03-16:04:50.250478] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-12-03-16:04:50.250725] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2019-12-03-16:04:50.251017] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2019-12-03-16:04:50.255718] READ LOCK: /Spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2019-12-03-16:04:50.256644] In environment test
==> [2019-12-03-16:04:50.256802] Root specs
Traceback (most recent call last):
  File "/Spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/Spack/lib/spack/spack/main.py", line 715, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Spack/lib/spack/spack/main.py", line 457, in _invoke_command
    return_val = command(parser, args)
  File "/Spack/lib/spack/spack/cmd/find.py", line 222, in find
    display_env(env, args, decorator)
  File "/Spack/lib/spack/spack/cmd/find.py", line 178, in display_env
    variants=True
  File "//Spack/lib/spack/spack/cmd/__init__.py", line 390, in display_specs
    format_list(specs)
  File "/Spack/lib/spack/spack/cmd/__init__.py", line 360, in format_list
    formatted.append((fmt(spec), spec))
  File "/Spack/lib/spack/spack/cmd/__init__.py", line 350, in fmt
    string += gray_hash(s, hlen) + ' '
  File "/Spack/lib/spack/spack/cmd/__init__.py", line 215, in gray_hash
    h = spec.dag_hash(length) if spec.concrete else '-' * length
TypeError: can't multiply sequence by non-int of type 'NoneType'
```

### Information on your system

This includes:

Latest develop, on MacOs and Linux cluster

-----

Thank

**Comment by nazavode** [comment]
Looks like this is related to #9875

**Comment by adrienbernede** [comment]
@nazavode you are right!
I looked for an existing issue with "spack" "find" and "environment" keywords.
However the search engine defaults to "most recent" sorting, and I couldn’t find the "relevance" sorting. Any suggestion?

**Comment by adrienbernede** [comment]
sort:relevance seems to work, but is not in the list.

**Comment by nazavode** [comment]
> However the search engine defaults to "most recent" sorting, and I couldn’t find the "relevance" sorting. Any suggestion?

Agree that it doesn't work smoothly at all, I gave up trying to make sense out of the issue *auto* search engine results... :cry:
