### ISSUE TITLE
Installation issue: py-llvmlite

### ISSUE THREAD

**Issue by iarspider** [spack/spack#14107]
### Steps to reproduce the issue

```console
$ spack spec py-llvmlite@0.29.0 ^python@2.7.16

Input spec
--------------------------------
py-llvmlite@0.29.0
    ^python@2.7.16

Concretized
--------------------------------
py-llvmlite@0.29.0%gcc@8.3.0 arch=linux-centos7-skylake
    ^binutils@2.30.0%gcc@8.3.0~gold~headers~libiberty+nls~plugins arch=linux-centos7-skylake
    ^llvm@8.0.0%gcc@8.3.0~all_targets build_type=Release +clang+compiler-rt~flang~gold+internal_unwind+libcxx+link_dylib~lld~lldb~omp_tsan patches=3fa900e31763cc7ff604430b86faa4eb650048c1796ebd39db2dcf84f6168a8b +polly~python~shared_libs arch=linux-centos7-skylake
        ^cmake@3.8.1%gcc@8.3.0~doc+ncurses+openssl+ownlibs patches=dd3a40d4d92f6b2158b87d6fb354c277947c776424aa03f6dc8096cf3135f5d0 ~qt arch=linux-centos7-skylake
        ^perl-data-dumper@2.173%gcc@8.3.0 arch=linux-centos7-skylake
            ^perl@5.16.3%gcc@8.3.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-centos7-skylake
        ^python@2.7.16%gcc@8.3.0+bz2+ctypes+dbm+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-centos7-skylake
            ^bzip2@1.0.6%gcc@8.3.0+shared arch=linux-centos7-skylake
            ^expat@2.2.9%gcc@8.3.0~libbsd arch=linux-centos7-skylake
            ^gdbm@1.10%gcc@8.3.0 arch=linux-centos7-skylake
            ^gettext@0.20.1%gcc@8.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-skylake
                ^libxml2@2.9.9%gcc@8.3.0~python arch=linux-centos7-skylake
                    ^libiconv@2.17%gcc@8.3.0 arch=linux-centos7-skylake
                    ^pkgconf@0.27.1%gcc@8.3.0 arch=linux-centos7-skylake
                    ^xz@5.2.2%gcc@8.3.0 arch=linux-centos7-skylake
                    ^zlib@1.2.11%gcc@8.3.0+optimize+pic+shared arch=linux-centos7-skylake
                ^ncurses@5.9%gcc@8.3.0 patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=linux-centos7-skylake
                ^tar@1.26%gcc@8.3.0 patches=08921fcbd732050c74ddf1de7d8ad95ffdbc09f8b4342456fa2f6a0dd02a957c,5c314db58d005043bf407abaf25eb9823b9032a22fd12a0b142d4bf548130fa4,d428578be7fb99b831eb61e53b8d88a859afe08b479a21238180899707d79ce4 arch=linux-centos7-skylake
            ^libffi@3.2.1%gcc@8.3.0 arch=linux-centos7-skylake
            ^openssl@1.0.2k%gcc@8.3.0+systemcerts arch=linux-centos7-skylake
            ^readline@8.0%gcc@8.3.0 arch=linux-centos7-skylake
            ^sqlite@3.30.1%gcc@8.3.0+column_metadata+fts~functions~rtree arch=linux-centos7-skylake
    ^py-enum34@1.1.6%gcc@8.3.0 arch=linux-centos7-skylake
        ^py-setuptools@41.4.0%gcc@8.3.0 arch=linux-centos7-skylake

$ spack install py-llvmlite@0.29.0 ^python@2.7.16
==> Error: ProcessError: Command exited with status 1:
    '/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/python-2.7.16-thcifv7hiw2y5pgh5isqo4oodmunmvak/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'

4 errors found in build log:
     5     running build_ext
     6     /mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/python-2.7.16-thcifv7hiw2y5pgh5isqo4oodmunmvak/bin/python2.7 /tmp/sftnight/spack-stage/spack-stage-py-llvmlite-0.29.0-cv4wumr6cezzghl2ckyi6ihvde7qra4v/spack-src/ffi/build.py
     7     LLVM version... # static-libstdc++ avoids runtime dependencies on a
     8     # particular libstdc++ version.
     9     /mnt/build/jenkins/spack/lib/spack/env/gcc/g++  -shared -I/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/llvm-8.0.0-xspwikircwrdgcfijzftcigniyjerfam/include -std=c++11 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -g -flto assembly.cpp b
           itcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp object_file.cpp -o libllvmlite.so  -L/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/llvm-8.0.0-xspwikircwrdgcfijzftcigniyjerfam/lib -flto -Wl,--ex
           clude-libs=ALL -lLLVM-8
     10    /cvmfs/sft.cern.ch/lcg/contrib/binutils/2.30/x86_64-centos7/bin/ld: /tmp/cc2iUoiT.ltrans0.ltrans.o: relocation R_X86_64_32 against symbol `_ZTVN4llvm11raw_ostreamE@@LLVM_8' can not be used when making a shared object; recompile with -fPIC
  >> 11    /cvmfs/sft.cern.ch/lcg/contrib/binutils/2.30/x86_64-centos7/bin/ld: final link failed: Nonrepresentable section on output
  >> 12    collect2: error: ld returned 1 exit status
  >> 13    make: *** [libllvmlite.so] Error 1
     14    8.0.0
     15
     16    SVML not detected
     17    Traceback (most recent call last):
     18      File "/tmp/sftnight/spack-stage/spack-stage-py-llvmlite-0.29.0-cv4wumr6cezzghl2ckyi6ihvde7qra4v/spack-src/ffi/build.py", line 168, in <module>
     19        main()

     ...

     21        main_posix('linux', '.so')
     22      File "/tmp/sftnight/spack-stage/spack-stage-py-llvmlite-0.29.0-cv4wumr6cezzghl2ckyi6ihvde7qra4v/spack-src/ffi/build.py", line 150, in main_posix
     23        subprocess.check_call(['make', '-f', makefile])
     24      File "/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/python-2.7.16-thcifv7hiw2y5pgh5isqo4oodmunmvak/lib/python2.7/subprocess.py", line 190, in check_call
     25        raise CalledProcessError(retcode, cmd)
     26    subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2
  >> 27    error: command '/mnt/build/jenkins/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/python-2.7.16-thcifv7hiw2y5pgh5isqo4oodmunmvak/bin/python2.7' failed with exit status 1
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux 453207a49b28 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:    CentOS Linux release 7.7.1908 (Core) 
``` 

`compilers.yaml` and `packages.yaml`: https://gist.github.com/iarspider/7a9a7685e9c93fb214b608bb85bf9f19

**Comment by iarspider** [comment]
Additional log files:

[spack-build-out.txt](https://github.com/spack/spack/files/3949722/spack-build-out.txt)
[spack-cc-py-llvmlite-cv4wumr.in.log](https://github.com/spack/spack/files/3949723/spack-cc-py-llvmlite-cv4wumr.in.log)
[spack-cc-py-llvmlite-cv4wumr.out.log](https://github.com/spack/spack/files/3949724/spack-cc-py-llvmlite-cv4wumr.out.log)

**Comment by s-sajid-ali** [comment]
Could you try adding the patches described in https://github.com/spack/spack/pull/8123#issuecomment-556319317 ? The PR adds support for only one patch but now that `spack arch` can recognize cpu's, it should be possible to pull in all the patches.

**Comment by adamjstewart** [comment]
@iarspider can you see if this issue still exists on develop?

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to open a new issue if the problem persists.
