### ISSUE TITLE
Recursion depth throws exception instead of Spack Error

### ISSUE THREAD

**Issue by nicholas-sly** [spack/spack#14586]
*Explain, in a clear and concise way, the command you ran and the result you were trying to achieve.
Example: "When concretizing a spec that with a matrix that results in `numactl ^numactl`, the error is thrown as a python exception instead of a Spack error, and is difficult to debug because of that."*

### Steps to reproduce the issue

```console
$ cat spack.yaml
spack:
  definitions:
  - numactl:
    - '^numactl@1.0.0.system'
  - packages:
    - numactl
  - builds:
    - matrix:
      - [$packages]
      - [$numactl]
  specs:
  - $builds
  view: false
  packages:
    numactl:
      paths:
        numactl@1.0.0.system%pgi: /lib64
      version: [ 2.0.12 ]
      target: []
      compiler: []
      buildable: true
      modules: {}
      providers: {}
$ spack -d concretize -f
Traceback (most recent call last):
  File "/usr/projects/hpctest/sly/git/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/main.py", line 715, in main
    return _invoke_command(command, parser, args, unknown)
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/main.py", line 457, in _invoke_command
    return_val = command(parser, args)
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/cmd/concretize.py", line 21, in concretize
    concretized_specs = env.concretize(force=args.force)
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/environment.py", line 906, in concretize
    return self._concretize_separately()
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/environment.py", line 974, in _concretize_separately
    concrete = _concretize_from_constraints(uspec_constraints)
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/environment.py", line 1526, in _concretize_from_constraints
    return s.concretized()
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/spec.py", line 2297, in concretized
    clone.concretize()
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/spec.py", line 2150, in concretize
    self._expand_virtual_packages(concretizer),
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/spec.py", line 2057, in _expand_virtual_packages
    candidates = concretizer.choose_virtual_or_external(spec)
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/concretize.py", line 126, in choose_virtual_or_external
    abi_exemplar = find_spec(spec, lambda x: x.compiler)
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/concretize.py", line 605, in find_spec
    for relative in spec.root.traverse(deptypes=all):
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/spec.py", line 1152, in root
    return next(iter(self._dependents.values())).parent.root
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/spec.py", line 1152, in root
    return next(iter(self._dependents.values())).parent.root
  File "/yellow/usr/projects/hpctest/sly/git/spack/lib/spack/spack/spec.py", line 1152, in root
    return next(iter(self._dependents.values())).parent.root
  [Previous line repeated 489 more times]
  File "/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python3.6/_collections_abc.py", line 682, in values
    return ValuesView(self)
RecursionError: maximum recursion depth exceeded
```

### Information on your system

This includes:

 1. which platform you are using
 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)

 1. TOSS system (RHEL7) at LANL.
 2. Only other configuration that should matter for reproducing is a compiler.  In this case, I'm using a gcc@7.4.0 that is loaded by a module.

-----

We encourage you to try, as much as possible, to reduce your problem to the minimal example that still reproduces the issue. That would help us a lot in fixing it quickly and effectively!

If you want to ask a question about the tool (how to use it, what it can currently do, etc.), try the `#general` channel on our Slack first. We have a welcoming community and chances are you'll get your reply faster and without opening an issue.

Other than that, thanks for taking the time to contribute to Spack!

**Comment by alalazo** [comment]
Don't know if we should handle that with a better error message, but the `spack.yaml` seems wrong to me:
```yaml
spack:
  definitions:
  - numactl:
    - '^numactl@1.0.0.system'
  - packages:
    - numactl
  - builds:
    - matrix:
      - [$packages]
      - [$numactl]
  specs:
  - $builds
```
If I'm not reading this incorrectly you're asking Spack to build `numactl ^numactl@1.0.0.system` which is probably what causes the recursion.

**Comment by becker33** [comment]
@alalazo yes that's what causes the recursion, I believe the issue is we should catch that and report a reasonable Spack error instead of a python recursion error
