### ISSUE TITLE
intel-mkl in environment: not linking mklvars.sh

### ISSUE THREAD

**Issue by flxmr** [spack/spack#14697]
Hello, I've now started to use spack environments for my stuff. So I set up a spack.yaml with everything I need, using intel-mkl for numerics.
With `spack install` MKL compiled fine, and QuantumEspresso installed fine as well, but somehow the environment broke, trying to load it, just yields the simple error (after `spack env activate`):
```
==> Error: Trying to source non-existing file: <spack_dir>/var/spack/environments/dft_intel-20-01/.spack-env/view/compilers_and_libraries/linux/mkl/bin/mklvars.sh
```
As I had ran `spack install` with the environment active, running any command (e.g. `spack find`) within the environment yields a full trace:
```
Traceback (most recent call last):                                                                                                           
  File "<spack-dir>/bin/spack", line 64, in <module>                                                                   
    sys.exit(spack.main.main())                                                                                                              
  File "<spack-dir>/lib/spack/spack/main.py", line 663, in main                                              
    ev.activate(env, args.use_env_repo)                                                                                                      
  File "<spack-dir>/lib/spack/spack/environment.py", line 163, in activate                                   
    cmds += env.add_default_view_to_shell(shell)                                                                                             
  File "<spack-dir>/lib/spack/spack/environment.py", line 1107, in add_default_view_to_shell                 
    spec, self.default_view))                                                                                                                
  File "<spack-dir>/lib/spack/spack/user_environment.py", line 89, in environment_modifications_for_spec     
    spec.package.setup_run_environment(env)                                                                                                  
  File "<spack-dir>/lib/spack/spack/build_systems/intel.py", line 1018, in setup_run_environment             
    env.extend(EnvironmentModifications.from_sourcing_file(f, *args))                                                                        
  File "<spack-dir>/lib/spack/spack/util/environment.py", line 587, in from_sourcing_file                    
    raise RuntimeError(msg)                                                                                                                  
RuntimeError: Trying to source non-existing file: <spack-dir>/var/spack/environments/dft_intel-20-01/.spack-env/view/compilers_and_libraries/linux/mkl/bin/mklvars.sh                                                                                     
```
I just linked the compilers_and_libraries-folder. That works. So I guess it's just some change in the environment-handling in the intel-package.

**Comment by flxmr** [comment]
I think I can close this, this just appears, when spack somehow stalls (because the compiler get's killed or the read fails or whatever)
