### ISSUE TITLE
Stack trace when calling full_hash() method (at least on py-pillow pkg)

### ISSUE THREAD

**Issue by scottwittenburg** [spack/spack#14735]
I haven't seen this with other packages, so I'm not sure what's special about `py-pillow`, but I'm reproducing this easily with the following:

```
$ spack python
Spack version 0.13.3
Python 3.6.9, Linux x86_64
>>> from spack.spec import Spec
>>> s = Spec('py-pillow')
>>> s.concretize()
>>> s.full_hash()
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/data/scott/projects/spack/lib/spack/spack/spec.py", line 1424, in full_hash
    return self._cached_hash(ht.full_hash, length)
  File "/data/scott/projects/spack/lib/spack/spack/spec.py", line 1391, in _cached_hash
    hash_string = self._spec_hash(hash)
  File "/data/scott/projects/spack/lib/spack/spack/spec.py", line 1365, in _spec_hash
    self.to_node_dict(hash=hash), default_flow_style=True)
  File "/data/scott/projects/spack/lib/spack/spack/spec.py", line 1521, in to_node_dict
    d['package_hash'] = self.package.content_hash()
  File "/data/scott/projects/spack/lib/spack/spack/package.py", line 1281, in content_hash
    hash_content.append(package_hash(self.spec, content))
  File "/data/scott/projects/spack/lib/spack/spack/util/package_hash.py", line 118, in package_hash
    content = package_content(spec)
  File "/data/scott/projects/spack/lib/spack/spack/util/package_hash.py", line 113, in package_content
    return ast.dump(package_ast(spec))
  File "/data/scott/projects/spack/lib/spack/spack/util/package_hash.py", line 132, in package_ast
    RemoveDirectives(spec).visit(root)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/data/scott/projects/spack/lib/spack/spack/util/package_hash.py", line 56, in visit_ClassDef
    c for c in node.body
  File "/data/scott/projects/spack/lib/spack/spack/util/package_hash.py", line 57, in <listcomp>
    if (not self.is_directive(c) and not self.is_spack_attr(c))]
  File "/data/scott/projects/spack/lib/spack/spack/util/package_hash.py", line 46, in is_directive
    node.value.func.id in spack.directives.__all__)
AttributeError: 'Call' object has no attribute 'id'
```

Here's some system information:

```console
$ uname -a
Linux beast 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

**Comment by scottwittenburg** [comment]
@eugeneswalker This just broke a pipeline for me, have you ever seen it?  I'm not sure if it just affects a subset of packages (including `py-pillow`) or what.  I haven't dug into it yet to see what could be going on, or if I can patch it.

**Comment by eugeneswalker** [comment]
@scottwittenburg I haven't seen this before, but I am seeing it now.

**Comment by scheibelp** [comment]
This appears to be from recent edits like https://github.com/spack/spack/pull/14385 (from last month) that add lines like:

```
run_after('install')(PythonPackage.sanity_check_prefix)
```

The AST traversal logic I wrote to compute the full hash trips over those statements. I'll have to update it to make it more robust. I'll aim to do that by 2/7

**Comment by adamjstewart** [comment]
For the record, I refactored most of those lines from the py-pillow package in a follow-up commit. I think the sanity check prefix is the only one that remains.

**Comment by scheibelp** [comment]
I've started on the fix at https://github.com/spack/spack/pull/14763. I've verified that it resolves this issue but haven't yet added a test for it.
