### ISSUE TITLE
Failure to `install` in environments with external intel

### ISSUE THREAD

**Issue by sethrj** [spack/spack#14797]
Including an external intel compiler as part of a Spack environment prevents installation of that environment. I think it's because external codes don't get linked into a Spack view.

### Steps to reproduce the issue

With environment file `test.yaml`:
```yaml
spack:
  specs:
    - intel@18.0.2
  view: true
```

```console
$ spack env create test ./test.yaml
==> Updating view at /projects/spack/var/spack/environments/test/.spack-env/view
==> Created environment 'test' in /projects/spack/var/spack/environments/test
$ spack env activate test
$ spack concretize
==> Concretized intel@18.0.2
[+]  i4xujzv  intel@18.0.2%gcc@8.3.0 auto_dispatch=none +rpath arch=linux-rhel6-x86_64
==> Updating view at /projects/spack/var/spack/environments/test/.spack-env/view
==> Warning: [/projects/spack/var/spack/environments/test/.spack-env/view] Skipping external package: intel@18.0.2%gcc@8.3.0 auto_dispatch=none +rpath arch=linux-rhel6-x86_64/i4xujzv
```

Then try installing:

### Error Message

```console
$ spack install
Traceback (most recent call last):
  File "/projects/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/projects/spack/lib/spack/spack/main.py", line 693, in main
    ev.activate(env, args.use_env_repo)
  File "/projects/spack/lib/spack/spack/environment.py", line 163, in activate
    cmds += env.add_default_view_to_shell(shell)
  File "/projects/spack/lib/spack/spack/environment.py", line 1107, in add_default_view_to_shell
    spec, self.default_view))
  File "/projects/spack/lib/spack/spack/user_environment.py", line 89, in environment_modifications_for_spec
    spec.package.setup_run_environment(env)
  File "/projects/spack/lib/spack/spack/build_systems/intel.py", line 1018, in setup_run_environment
    env.extend(EnvironmentModifications.from_sourcing_file(f, *args))
  File "/projects/spack/lib/spack/spack/util/environment.py", line 587, in from_sourcing_file
    raise RuntimeError(msg)
RuntimeError: Trying to source non-existing file: /projects/spack/var/spack/environments/test/.spack-env/view/compilers_and_libraries/linux/bin/compilervars.sh
```

### Information on your system

relevant section  of `etc/spack/packages.yaml`:
```yaml
packages:
  intel:
    paths:
      intel@18.0.2: /opt/intel-2018
    buildable: False
```

**Comment by scheibelp** [comment]
Apologies for taking so long to look at this. I'll be checking into it more tomorrow

I'm having trouble reproducing this on my Mac, the output I get is:

```
spack install
==> Installing environment test1
==> intel@18.0.2 : externally installed in /opt/intel-2018
==> intel@18.0.2 : generating module file
==> Warning: cannot perform the requested write operation on module files [Trying to source non-existing file: /opt/intel-2018/compilers_and_libraries/mac/bin/compilervars.sh]
==> intel@18.0.2 : registering into DB
```

Do you see any messages like that before your error message?

**Comment by sethrj** [comment]
Thanks for checking this out! It's been a while since I looked at this too. It looks like with the latest version of spack, the error happens on `spack env deactivate` and on subsequent `spack env activate`:
```console
$ spack install
==> Installing environment test
==> intel@18.0.2 : externally installed in /opt/intel-2018
==> intel@18.0.2 : generating module file
==> Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      source /opt/intel-2018/compilers_and_libraries_2018.2.199/linux/bin/compilervars.sh intel64 &> /dev/null && python3 -c "import os, json; print(json.dumps(dict(os.environ)))"
  Quotes aren't needed because spack doesn't use a shell.
  Consider removing them
==> intel@18.0.2 : registering into DB
==> Updating view at /tmp/tmp.vFtlhck78w/var/spack/environments/test/.spack-env/view
==> Warning: [/tmp/tmp.vFtlhck78w/var/spack/environments/test/.spack-env/view] Skipping external package: intel@18.0.2%gcc@4.4.7 auto_dispatch=none +rpath arch=linux-rhel6-x86_64/zcwv7dl
$ spack env deactivate
Traceback (most recent call last):
  File "/tmp/tmp.vFtlhck78w/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/main.py", line 704, in main
    ev.activate(env, args.use_env_repo)
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/environment.py", line 163, in activate
    cmds += env.add_default_view_to_shell(shell)
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/environment.py", line 1107, in add_default_view_to_shell
    spec, self.default_view))
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/user_environment.py", line 89, in environment_modifications_for_spec
    spec.package.setup_run_environment(env)
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/build_systems/intel.py", line 1018, in setup_run_environment
    env.extend(EnvironmentModifications.from_sourcing_file(f, *args))
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/util/environment.py", line 587, in from_sourcing_file
    raise RuntimeError(msg)
RuntimeError: Trying to source non-existing file: /tmp/tmp.vFtlhck78w/var/spack/environments/test/.spack-env/view/compilers_and_libraries/linux/bin/compilervars.sh
```

I'm reliably reproducing this with:
```sh
#!/bin/sh -e
function echo_and_run { echo "$@"; "$@" ; }
export SPACK_ROOT=/tmp/tmp.vFtlhck78w
cd $SPACK_ROOT
echo_and_run git clean -fxd >/dev/null
echo_and_run cp ~/test-etc-spack/{compilers,packages}.yaml etc/spack/
echo_and_run source ${SPACK_ROOT}/share/spack/setup-env.sh
echo_and_run spack env create test ~/test.yaml
echo_and_run spack env activate test
echo_and_run spack concretize
echo_and_run spack install
echo_and_run spack env deactivate
echo_and_run spack env activate test
echo "Done!"
```

**Comment by scheibelp** [comment]
Just to check - what Spack version are you using? I have followed your script closely on latest develop (`spack --version` reports `0.14.0-211-b8064df49`) and still cannot reproduce it.

Could you provide the output of running the following script with `spack-python` after activating the environment:

```
import spack.environment as env
e = env.get_env({}, 'shell')
user_to_concrete = dict(e.concretized_specs())
print(user_to_concrete.values()[0].prefix)
print(user_to_concrete.values()[0].package.file_to_source)
```

**Comment by sethrj** [comment]
Before installing the environment:
```console
$ spack --version
0.14.0-166-46f56c72f
```

After running `spack install`, I can no longer run spack at all while in the environment:
```
$ spack-python
Traceback (most recent call last):
  File "/tmp/tmp.vFtlhck78w/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/main.py", line 704, in main
    ev.activate(env, args.use_env_repo)
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/environment.py", line 163, in activate
    cmds += env.add_default_view_to_shell(shell)
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/environment.py", line 1107, in add_default_view_to_shell
    spec, self.default_view))
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/user_environment.py", line 89, in environment_modifications_for_spec
    spec.package.setup_run_environment(env)
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/build_systems/intel.py", line 1018, in setup_run_environment
    env.extend(EnvironmentModifications.from_sourcing_file(f, *args))
  File "/tmp/tmp.vFtlhck78w/lib/spack/spack/util/environment.py", line 587, in from_sourcing_file
    raise RuntimeError(msg)
RuntimeError: Trying to source non-existing file: /tmp/tmp.vFtlhck78w/var/spack/environments/test/.spack-env/view/compilers_and_libraries/linux/bin/compilervars.sh
```

I can, however, run `spack-python` *before* I Install. I had to adjust your script for python 3 (`values()` returns a view):
```
>>> print(next(iter(user_to_concrete.values())).prefix)
/opt/intel-2018
>>> print(next(iter(user_to_concrete.values())).package.file_to_source)
/opt/intel-2018/compilers_and_libraries_2018.2.199/linux/bin/compilervars.sh
```

**Comment by scheibelp** [comment]
I think I see the issue: https://github.com/spack/spack/pull/15475 (WIP) may address this
