### ISSUE TITLE
Installation issue: cp2k with intel 2018.5 compiler

### ISSUE THREAD

**Issue by samcom12** [spack/spack#15033]
Installation issue: cp2k with Intel 2018.5 compiler.

---
### Steps to reproduce the issue

```console
$ spack install cp2k  %intel@18.0.5  blas=mkl +cuda+cuda_blas+cuda_fft+elpa+mpi+openmp+pexsi+plumed ^intel-mpi 

No patches needed for cp2k
==> Building cp2k [MakefilePackage]
==> Executing phase: 'edit'
==> Error: KeyError: 'none'

/home/samir/spack/var/spack/repos/builtin/packages/cp2k/package.py:392, in edit:
        389                    '37': 'K80',
        390                    '60': 'P100',
        391                    '70': 'V100',
  >>    392                }[cuda_arch]
        393
        394                if (cuda_arch == '35'
        395                        and self.spec.satisfies('+cuda_arch_35_k20x')):

See build log for details:
  /tmp/samir/spack-stage/spack-stage-cp2k-6.1-xpeoh7ztmfohfdylqzursgf2el2tc2fp/spack-build-out.txt


### Platform and user environment
```commandline
$ uname -a 
Linux login04 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- `compilers.yaml`
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment:
      unset: []
    extra_rpaths: []
    flags: {}
    spec: gcc@4.8.5
- compiler:
    paths:
      cc: /home/apps/gcc-5.5.0/bin/gcc
      cxx: /home/apps/gcc-5.5.0/bin/g++
      f77: /home/apps/gcc-5.5.0/bin/gfortran
      fc: /home/apps/gcc-5.5.0/bin/gfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@5.5.0
- compiler:
    paths:
      cc: /opt/ohpc/pub/apps/intel/2018_2/compilers_and_libraries_2018.5.274/linux/bin/intel64/icc
      cxx: /opt/ohpc/pub/apps/intel/2018_2/compilers_and_libraries_2018.5.274/linux/bin/intel64/icpc
      f77: /opt/ohpc/pub/apps/intel/2018_2/compilers_and_libraries_2018.5.274/linux/bin/intel64/ifort
      fc: /opt/ohpc/pub/apps/intel/2018_2/compilers_and_libraries_2018.5.274/linux/bin/intel64/ifort
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@18.0.5
- compiler:
    paths:
      cc: /opt/ohpc/pub/apps/intel/2016/compilers_and_libraries_2016.4.258/linux/bin/intel64/icc
      cxx: /opt/ohpc/pub/apps/intel/2016/compilers_and_libraries_2016.4.258/linux/bin/intel64/icpc
      f77: /opt/ohpc/pub/apps/intel/2016/compilers_and_libraries_2016.4.258/linux/bin/intel64/ifort
      fc: /opt/ohpc/pub/apps/intel/2016/compilers_and_libraries_2016.4.258/linux/bin/intel64/ifort
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@16.0.4
- compiler:
    paths:
      cc: /opt/ohpc/pub/apps/intel/2019/compilers_and_libraries_2019.5.281/linux/bin/intel64/icc
      cxx: /opt/ohpc/pub/apps/intel/2019/compilers_and_libraries_2019.5.281/linux/bin/intel64/icpc
      f77: /opt/ohpc/pub/apps/intel/2019/compilers_and_libraries_2019.5.281/linux/bin/intel64/ifort
      fc: /opt/ohpc/pub/apps/intel/2019/compilers_and_libraries_2019.5.281/linux/bin/intel64/ifort
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: intel@19.0.5.281
- compiler:
    paths:
      cc: /opt/ohpc/pub/compiler/gcc/8.3.0/bin/gcc
      cxx: /opt/ohpc/pub/compiler/gcc/8.3.0/bin/g++
      f77: /opt/ohpc/pub/compiler/gcc/8.3.0/bin/gfortran
      fc: /opt/ohpc/pub/compiler/gcc/8.3.0/bin/gfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@8.3.0
~

### Additional information
```console
$  spack spec --install-status cp2k  %intel@18.0.5  blas=mkl +cuda+cuda_blas+cuda_fft+elpa+mpi+openmp+pexsi+plumed ^intel-mpi

Input spec
--------------------------------
 -   cp2k%intel@18.0.5 blas=mkl +cuda+cuda_blas+cuda_fft+elpa+mpi+openmp+pexsi+plumed
 -       ^intel-mpi

Concretized
--------------------------------
 -   cp2k@6.1%intel@18.0.5 blas=mkl +cuda cuda_arch=none ~cuda_arch_35_k20x+cuda_blas+cuda_fft+elpa+libxc lmax=5 +mpi                                                                                                                                                            +openmp+pexsi+plumed~sirius smm=libxsmm arch=linux-centos7-skylake_avx512
[+]      ^cuda@10.2.89%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]          ^libxml2@2.9.9%intel@18.0.5~python arch=linux-centos7-skylake_avx512
[+]              ^libiconv@1.16%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]              ^pkgconf@1.6.3%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]              ^xz@5.2.4%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]              ^zlib@1.2.11%intel@18.0.5+optimize+pic+shared arch=linux-centos7-skylake_avx512
[+]      ^elpa@2017.11.001%intel@18.0.5+openmp+optflags arch=linux-centos7-skylake_avx512
[+]          ^intel-mkl@2020.0.166%intel@18.0.5~ilp64+shared threads=openmp arch=linux-centos7-skylake_avx512
[+]              ^cpio@2.13%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]          ^intel-mpi@2019.6.166%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]      ^fftw@3.3.8%intel@18.0.5+mpi+openmp~pfft_patches precision=double,float arch=linux-centos7-skylake_avx512
[+]      ^libint@1.1.6%intel@18.0.5~fortran tune=none arch=linux-centos7-skylake_avx512
[+]          ^autoconf@2.69%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]              ^m4@1.4.18%intel@18.0.5 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9                                                                                                                                                            b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-centos7-skylake_avx512
[+]                  ^libsigsegv@2.12%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]              ^perl@5.30.1%intel@18.0.5+cpanm+shared+threads arch=linux-centos7-skylake_avx512
[+]                  ^gdbm@1.18.1%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]                      ^readline@8.0%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]                          ^ncurses@6.1%intel@18.0.5~symlinks~termlib arch=linux-centos7-skylake_avx512
[+]          ^automake@1.16.1%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]          ^libtool@2.4.6%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]      ^libxc@4.3.2%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]      ^libxsmm@1.14%intel@18.0.5~debug~generator~header-only~shared arch=linux-centos7-skylake_avx512
[+]      ^pexsi@0.10.2%intel@18.0.5+fortran arch=linux-centos7-skylake_avx512
[+]          ^parmetis@4.0.3%intel@18.0.5 build_type=RelWithDebInfo ~gdb patches=4f892531eb0a807eb1b82e683a416d3e3515                                                                                                                                                            4a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59c                                                                                                                                                            ca6e1209df4ef3b033bc4ee3cf50f369bce972a9d +shared arch=linux-centos7-skylake_avx512
[+]              ^cmake@3.16.2%intel@18.0.5~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-skylake_avx512
[+]                  ^openssl@1.1.1d%intel@18.0.5+systemcerts arch=linux-centos7-skylake_avx512
[+]              ^metis@5.1.0%intel@18.0.5 build_type=Release ~gdb~int64 patches=4991da938c1d3a1d3dea78e49bbebecba002                                                                                                                                                            73f98df2a656e38b83d55b281da1 ~real64+shared arch=linux-centos7-skylake_avx512
[+]          ^superlu-dist@5.3.0%intel@18.0.5 build_type=RelWithDebInfo ~int64~openmp+shared arch=linux-centos7-skyla                                                                                                                                                            ke_avx512
[+]      ^plumed@2.5.3%intel@18.0.5+gsl+mpi optional_modules=all +shared arch=linux-centos7-skylake_avx512
[+]          ^gsl@2.5%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]      ^python@3.7.6%intel@18.0.5+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readlin                                                                                                                                                            e+shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=linux-centos7-skylake_avx512
[+]          ^bzip2@1.0.8%intel@18.0.5+shared arch=linux-centos7-skylake_avx512
[+]              ^diffutils@3.7%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]          ^expat@2.2.9%intel@18.0.5+libbsd arch=linux-centos7-skylake_avx512
[+]              ^libbsd@0.10.0%intel@18.0.5 patches=71b49f52a01420ab632f23373135853a2565f88725fb77e625a7fbf7ea812eef                                                                                                                                                             arch=linux-centos7-skylake_avx512
[+]          ^gettext@0.20.1%intel@18.0.5+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-skylake_avx                                                                                                                                                            512
[+]              ^tar@1.32%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]          ^libffi@3.2.1%intel@18.0.5 arch=linux-centos7-skylake_avx512
[+]          ^sqlite@3.30.1%intel@18.0.5~column_metadata+fts~functions~rtree arch=linux-centos7-skylake_avx512
...
```

**Comment by samcom12** [comment]
Output of -
$spack -d  install -j 1 cp2k  %intel@18.0.5  blas=mkl +cuda+cuda_blas+cuda_fft+elpa+mpi+openmp+pexsi+plumed ^intel-mpi

==> [2020-02-18-11:40:35.738182] WRITE LOCK: /tmp/samir/spack-stage/.lock[4027222519714943872:1] [Released]
==> [2020-02-18-11:40:35.746170] Error: KeyError: 'none'

/home/samir/spack/var/spack/repos/builtin/packages/cp2k/package.py:392, in edit:
        389                    '37': 'K80',
        390                    '60': 'P100',
        391                    '70': 'V100',
  >>    392                }[cuda_arch]
        393
        394                if (cuda_arch == '35'
        395                        and self.spec.satisfies('+cuda_arch_35_k20x')):

See build log for details:
  /tmp/samir/spack-stage/spack-stage-cp2k-6.1-xpeoh7ztmfohfdylqzursgf2el2tc2fp/spack-build-out.txt

Traceback (most recent call last):
  File "/home/samir/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/home/samir/spack/lib/spack/spack/package.py", line 1751, in build_process
    phase(self.spec, self.prefix)
  File "/home/samir/spack/lib/spack/spack/package.py", line 111, in phase_wrapper
    phase(spec, prefix)
  File "/home/samir/spack/var/spack/repos/builtin/packages/cp2k/package.py", line 393, in edit
KeyError: 'none'
==> [2020-02-18-11:40:35.748225] READ LOCK: /home/samir/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2020-02-18-11:40:35.749690] READ LOCK: /home/samir/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2020-02-18-11:40:35.810230] READ LOCK: /home/samir/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2020-02-18-11:40:35.871471] ChildError: KeyError: 'none'
/home/samir/spack/var/spack/repos/builtin/packages/cp2k/package.py:392, in edit:
        389                    '37': 'K80',
        390                    '60': 'P100',
        391                    '70': 'V100',
  >>    392                }[cuda_arch]
        393
        394                if (cuda_arch == '35'
        395                        and self.spec.satisfies('+cuda_arch_35_k20x')):

See build log for details:
  /tmp/samir/spack-stage/spack-stage-cp2k-6.1-xpeoh7ztmfohfdylqzursgf2el2tc2fp/spack-build-out.txt
Traceback (most recent call last):
  File "/home/samir/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/home/samir/spack/lib/spack/spack/package.py", line 1751, in build_process
    phase(self.spec, self.prefix)
  File "/home/samir/spack/lib/spack/spack/package.py", line 111, in phase_wrapper
    phase(spec, prefix)
  File "/home/samir/spack/var/spack/repos/builtin/packages/cp2k/package.py", line 393, in edit
KeyError: 'none'

**Comment by adamjstewart** [comment]
You need to determine your `cuda_arch` and set it (either on the command-line or in `packages.yaml`). See https://developer.nvidia.com/cuda-gpus and the CudaPackage base class (`spack edit -b cuda`)
