### ISSUE TITLE
Installation issue: py-torchvision

### ISSUE THREAD

**Issue by jychoi-hpc** [spack/spack#15139]
I am trying to install py-torchvision with spack but getting the following error:
```
Error: 'Call' object has no attribute 'id'
```

### Steps to reproduce the issue

```console
$ spack install -v py-torchvision
Error: 'Call' object has no attribute 'id'
```

### Error Message

Here is a full debug output:
```console
$ spack -d install --stacktrace -v py-torchvision
Traceback (most recent call last):
  File "/home/jyc/sw/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/home/jyc/sw/spack/lib/spack/spack/main.py", line 763, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/jyc/sw/spack/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "/home/jyc/sw/spack/lib/spack/spack/cmd/install.py", line 382, in install
    install_spec(args, kwargs, abstract, concrete)
  File "/home/jyc/sw/spack/lib/spack/spack/cmd/install.py", line 239, in install_spec
    spec.package.do_install(**kwargs)
  File "/home/jyc/sw/spack/lib/spack/spack/package.py", line 1439, in do_install
    builder.install(**kwargs)
  File "/home/jyc/sw/spack/lib/spack/spack/installer.py", line 1304, in install
    self._init_queue(install_deps, install_package)
  File "/home/jyc/sw/spack/lib/spack/spack/installer.py", line 910, in _init_queue
    spack.store.db.clear_failure(dep, force=False)
  File "/home/jyc/sw/spack/lib/spack/spack/database.py", line 409, in clear_failure
    if self.prefix_failure_marked(spec):
  File "/home/jyc/sw/spack/lib/spack/spack/database.py", line 492, in prefix_failure_marked
    return os.path.exists(self._failed_spec_path(spec))
  File "/home/jyc/sw/spack/lib/spack/spack/database.py", line 379, in _failed_spec_path
    '{0}-{1}'.format(spec.name, spec.full_hash()))
  File "/home/jyc/sw/spack/lib/spack/spack/spec.py", line 1424, in full_hash
    return self._cached_hash(ht.full_hash, length)
  File "/home/jyc/sw/spack/lib/spack/spack/spec.py", line 1391, in _cached_hash
    hash_string = self._spec_hash(hash)
  File "/home/jyc/sw/spack/lib/spack/spack/spec.py", line 1365, in _spec_hash
    self.to_node_dict(hash=hash), default_flow_style=True)
  File "/home/jyc/sw/spack/lib/spack/spack/spec.py", line 1521, in to_node_dict
    d['package_hash'] = self.package.content_hash()
  File "/home/jyc/sw/spack/lib/spack/spack/package.py", line 1283, in content_hash
    hash_content.append(package_hash(self.spec, content))
  File "/home/jyc/sw/spack/lib/spack/spack/util/package_hash.py", line 118, in package_hash
    content = package_content(spec)
  File "/home/jyc/sw/spack/lib/spack/spack/util/package_hash.py", line 113, in package_content
    return ast.dump(package_ast(spec))
  File "/home/jyc/sw/spack/lib/spack/spack/util/package_hash.py", line 132, in package_ast
    RemoveDirectives(spec).visit(root)
  File "/home/jyc/sw/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/python-3.7.6-hws7snhhwes5qq5iqmhot3jv7wvwm4li/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/jyc/sw/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/python-3.7.6-hws7snhhwes5qq5iqmhot3jv7wvwm4li/lib/python3.7/ast.py", line 326, in generic_visit
    value = self.visit(value)
  File "/home/jyc/sw/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/python-3.7.6-hws7snhhwes5qq5iqmhot3jv7wvwm4li/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/jyc/sw/spack/lib/spack/spack/util/package_hash.py", line 56, in visit_ClassDef
    c for c in node.body
  File "/home/jyc/sw/spack/lib/spack/spack/util/package_hash.py", line 57, in <listcomp>
    if (not self.is_directive(c) and not self.is_spack_attr(c))]
  File "/home/jyc/sw/spack/lib/spack/spack/util/package_hash.py", line 46, in is_directive
    node.value.func.id in spack.directives.__all__)
AttributeError: 'Call' object has no attribute 'id'
```

### Information on your system

I am using on a Power 9 machine with Red Hat
```console
$ uname -a
Linux raptor11 4.14.0-115.8.1.el7a.ppc64le #1 SMP Thu May 9 14:45:13 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
```

**Comment by scheibelp** [comment]
This may have just been resolved by https://github.com/spack/spack/pull/14763 (merged 1 hour ago): could you retry with the latest develop?

**Comment by jychoi-hpc** [comment]
It works perfectly!! Thank you for the quick help.
