### ISSUE TITLE
Concretization Issue due to new fftw variants

### ISSUE THREAD

**Issue by marvinbernhardt** [spack/spack#15194]
I run spac spec to concretize votca-csg. When I try to use an existing gromacs package, it fails due to the fftw package. I have some old fftw packages so this is almost certainly related to https://github.com/spack/spack/pull/12889.

### Steps to reproduce the issue

have some old gromacs and old fftw and then execute
```console
$ spack  spec -I votca-csg ^/qmpnnzb
==> [2020-02-25-01:21:23.418631] Reading config file /shared/spack/etc/spack/defaults/modules.yaml
==> [2020-02-25-01:21:23.435872] Reading config file /shared/spack/etc/spack/defaults/linux/modules.yaml
==> [2020-02-25-01:21:23.441325] Reading config file /shared/spack/etc/spack/defaults/config.yaml
==> [2020-02-25-01:21:23.472134] Reading config file /shared/spack/etc/spack/config.yaml
==> [2020-02-25-01:21:23.476842] Imported spec from built-in commands
==> [2020-02-25-01:21:23.477859] Imported spec from built-in commands
==> [2020-02-25-01:21:23.497424] DATABASE LOCK TIMEOUT: 120s
==> [2020-02-25-01:21:23.497515] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-02-25-01:21:23.498248] READ LOCK: /shared/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2020-02-25-01:21:23.498532] READ LOCK: /shared/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> [2020-02-25-01:21:23.585342] READ LOCK: /shared/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> [2020-02-25-01:21:23.586214] READ LOCK: /shared/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2020-02-25-01:21:23.586456] READ LOCK: /shared/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
Input spec
--------------------------------
==> [2020-02-25-01:21:23.673003] Reading config file /shared/spack/etc/spack/defaults/repos.yaml
 -   votca-csg
 -       ^gromacs@2019.5%gcc@8.2.0 build_type=RelWithDebInfo ~cuda~double~mpi~plumed+rdtscp+shared simd=SSE2 arch=linux-fedora29-x86_64
 -           ^fftw@3.3.8%gcc@8.2.0+double+float~fma+long_double+mpi~openmp~pfft_patches~quad simd=avx,avx2,sse2 arch=linux-fedora29-x86_64
 -               ^openmpi@2.1.1%gcc@8.2.0~cuda+cxx_exceptions fabrics=auto ~java~legacylaunchers~memchecker~pmi schedulers=auto ~sqlite3~thread_multiple+vt arch=linux-fedora29-x86_64

Concretized
--------------------------------
==> [2020-02-25-01:21:23.884246] READ LOCK: /shared/spack/opt/spack/.spack-db/lock[0:0] [Released]
Traceback (most recent call last):
  File "/shared/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/shared/spack/lib/spack/spack/main.py", line 715, in main
    return _invoke_command(command, parser, args, unknown)
  File "/shared/spack/lib/spack/spack/main.py", line 457, in _invoke_command
    return_val = command(parser, args)
  File "/shared/spack/lib/spack/spack/cmd/spec.py", line 101, in spec
    spec.concretize()
  File "/shared/spack/lib/spack/spack/spec.py", line 2149, in concretize
    user_spec_deps=user_spec_deps),
  File "/shared/spack/lib/spack/spack/spec.py", line 2626, in normalize
    visited, all_spec_deps, provider_index, tests)
  File "/shared/spack/lib/spack/spack/spec.py", line 2565, in _normalize_helper
    dep, visited, spec_deps, provider_index, tests)
  File "/shared/spack/lib/spack/spack/spec.py", line 2524, in _merge_dependency
    visited, spec_deps, provider_index, tests)
  File "/shared/spack/lib/spack/spack/spec.py", line 2565, in _normalize_helper
    dep, visited, spec_deps, provider_index, tests)
  File "/shared/spack/lib/spack/spack/spec.py", line 2524, in _merge_dependency
    visited, spec_deps, provider_index, tests)
  File "/shared/spack/lib/spack/spack/spec.py", line 2553, in _normalize_helper
    dep = self._evaluate_dependency_conditions(dep_name)
  File "/shared/spack/lib/spack/spack/spec.py", line 2372, in _evaluate_dependency_conditions
    substitute_abstract_variants(self)
  File "/shared/spack/lib/spack/spack/variant.py", line 603, in substitute_abstract_variants
    pkg_variant = spec.package_class.variants[name]
KeyError: 'double'
```
I used pdb and found out the KeyError in the last mentioned line is related to the fftw spec not containing the double variant.

```console
$ spack find -lvd /qmpnnzb
==> 1 installed package
-- linux-fedora29-x86_64 / gcc@8.2.0 ----------------------------
qmpnnzb gromacs@2019.5 build_type=RelWithDebInfo ~cuda~double~mpi~plumed+rdtscp+shared simd=SSE2
gkxnhig     fftw@3.3.8+double+float~fma+long_double+mpi~openmp~pfft_patches~quad simd=avx,avx2,sse2
7evvvkr         openmpi@2.1.1~cuda+cxx_exceptions fabrics=auto ~java~legacylaunchers~memchecker~pmi schedulers=auto ~sqlite3~thread_multiple+vt

$ spack find -lv fftw
==> 3 installed packages
-- linux-fedora29-x86_64 / gcc@8.2.0 ----------------------------
mu7tk3e fftw@3.3.8+double+float~fma+long_double~mpi+openmp~pfft_patches~quad simd=avx,avx2,sse2  e4wa6u5 fftw@3.3.8~mpi~openmp~pfft_patches precision=double,float
gkxnhig fftw@3.3.8+double+float~fma+long_double+mpi~openmp~pfft_patches~quad simd=avx,avx2,sse2
```

### Information on your system

I'm on master branch commit f9658e8958d58223e1ac0d2c872c20b235d5593d
Fedora release 29

Is there some way i can resolve this or is this a bug?

**Comment by scheibelp** [comment]
One possibility is that you can use a repo with the older versions of the `fftw`/`gromacs` packages (see: https://spack.readthedocs.io/en/latest/repositories.html#spack-repo-create). If you are trying to use the new `votca-csg` and that needs the newer `fftw`/`gromacs` definitions then that would not work. If you don't need the new `votca-csg` package definition then you can add the old one to the alternative repository along with `fftw`/`gromacs`.

Do you know what Spack commit your `fftw` spec is from?

**Comment by marvinbernhardt** [comment]
My fftw spec is roughly from 39725e07841f03da2a3f1a16a5f678ec224833f7 (develop branch around one year ago).

**Comment by marvinbernhardt** [comment]
Ok, so the way for me to go was reinstalling fftw. I somehow thought that it would maybe be possible to convert the old fftw to the new package definition, but I guess this way everything is much easier.
I don't close this issue yet, since you might want to improve the Error message? If not, you can close it.

**Comment by marvinbernhardt** [comment]
This is old and I can't reproduce it i think.
