### ISSUE TITLE
slate build broken w py3

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#15216]
Package `slate` is not building on Ubuntu 18.04, x86_64 using spack/develop . The problem can be reproduced using docker image `spack/ubuntu-bionic` (just make sure to pull up to the head of spack/develop)

`$> spack install slate`

```
....
cd testsweeper && make lib
 make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-slate-develop-dlkhugeigi7xluf2kmh545nibyx4abo4/spack-src/testsweeper'
 GNUmakefile:22: make.inc: No such file or directory
 python configure.py
 --------------------------------------------------------------------------------
                               Welcome to testsweeper.
 By default, configure will automatically choose the first valid value it finds
 for each option. You can set it to interactive to find all possible values and
 give you a choice:
     make config interactive=1
 If you have multiple compilers, we suggest specifying your desired compiler by
 setting CXX, as the automated search may prefer a different compiler.
 --------------------------------------------------------------------------------
 opening log file config/log.txt
 C++ compiler
 Trying $CXX = mpicxx
 mpicxx                                                                   no 
 none found
 A fatal error occurred. 
 testsweeper could not be configured.
...
==> [2020-02-25-20:06:57.863529] Error: ProcessError: Command exited with status 2:
     'make' '-j8' 'mpi=1' 'mkl=1' 'cuda=1' 'openmp=1' 'CXX=mpicxx'
 2 errors found in build log:
      217    Trying $CXX = mpicxx
      218    mpicxx                                                             
                   no
      219    none found
      220    A fatal error occurred.
      221    testsweeper could not be configured.
      222    GNUmakefile:27: recipe for target 'make.inc' failed
   >> 223    make[1]: *** [make.inc] Error 1
      224    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-slate
             -develop-dlkhugeigi7xluf2kmh545nibyx4abo4/spack-src/testsweeper'
      225    GNUmakefile:542: recipe for target 'testsweeper/libtestsweeper.so' 
             failed
   >> 226    make: *** [testsweeper/libtestsweeper.so] Error 2
      227    make: *** Waiting for unfinished jobs....
 See build log for details:
   /tmp/root/spack-stage/spack-stage-slate-develop-dlkhugeigi7xluf2kmh545nibyx4abo4/spack-build-out.txt
 Traceback (most recent call last):
   File "/builds/uo/e4s-new/spack/lib/spack/spack/build_environment.py", line 801, in child_process
     return_value = function()
   File "/builds/uo/e4s-new/spack/lib/spack/spack/package.py", line 1751, in build_process
     phase(self.spec, self.prefix)
   File "/builds/uo/e4s-new/spack/lib/spack/spack/package.py", line 111, in phase_wrapper
     phase(spec, prefix)
   File "/builds/uo/e4s-new/spack/var/spack/repos/builtin/packages/slate/package.py", line 49, in install
     install_tree('lib', prefix.lib)
   File "/builds/uo/e4s-new/spack/lib/spack/spack/build_environment.py", line 131, in __call__
     return super(MakeExecutable, self).__call__(*args, **kwargs)
   File "/builds/uo/e4s-new/spack/lib/spack/spack/util/executable.py", line 189, in __call__
     proc.returncode, long_msg)
 spack.util.executable.ProcessError: Command exited with status 2:
     'make' '-j8' 'mpi=1' 'mkl=1' 'cuda=1' 'openmp=1' 'CXX=mpicxx'
 ==> [2020-02-25-20:06:57.926349] READ LOCK: /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Acquiring]
 ==> [2020-02-25-20:06:57.926552] READ LOCK: /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Acquired]
 ==> [2020-02-25-20:06:57.936238] READ LOCK: /super/absurdly/ridiculously/obnoxiously/long/path/for/relocation/.spack-db/lock[0:0] [Released]
 ==> [2020-02-25-20:06:57.956142] ChildError: ProcessError: Command exited with status 2:
     'make' '-j8' 'mpi=1' 'mkl=1' 'cuda=1' 'openmp=1' 'CXX=mpicxx'
 2 errors found in build log:
      217    Trying $CXX = mpicxx
      218    mpicxx                                                             
                   no
      219    none found
      220    A fatal error occurred.
      221    testsweeper could not be configured.
      222    GNUmakefile:27: recipe for target 'make.inc' failed
   >> 223    make[1]: *** [make.inc] Error 1
      224    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-slate
             -develop-dlkhugeigi7xluf2kmh545nibyx4abo4/spack-src/testsweeper'
      225    GNUmakefile:542: recipe for target 'testsweeper/libtestsweeper.so' 
             failed
   >> 226    make: *** [testsweeper/libtestsweeper.so] Error 2
      227    make: *** Waiting for unfinished jobs....
 See build log for details:
   /tmp/root/spack-stage/spack-stage-slate-develop-dlkhugeigi7xluf2kmh545nibyx4abo4/spack-build-out.txt
 Traceback (most recent call last):
   File "/builds/uo/e4s-new/spack/lib/spack/spack/build_environment.py", line 801, in child_process
     return_value = function()
   File "/builds/uo/e4s-new/spack/lib/spack/spack/package.py", line 1751, in build_process
     phase(self.spec, self.prefix)
   File "/builds/uo/e4s-new/spack/lib/spack/spack/package.py", line 111, in phase_wrapper
     phase(spec, prefix)
   File "/builds/uo/e4s-new/spack/var/spack/repos/builtin/packages/slate/package.py", line 49, in install
     install_tree('lib', prefix.lib)
   File "/builds/uo/e4s-new/spack/lib/spack/spack/build_environment.py", line 131, in __call__
     return super(MakeExecutable, self).__call__(*args, **kwargs)
   File "/builds/uo/e4s-new/spack/lib/spack/spack/util/executable.py", line 189, in __call__
     proc.returncode, long_msg)
 spack.util.executable.ProcessError: Command exited with status 2:
     'make' '-j8' 'mpi=1' 'mkl=1' 'cuda=1' 'openmp=1' 'CXX=mpicxx'
```

@adamjstewart @G-Ragghianti

**Comment by eugeneswalker** [comment]
I think the Python configure script during the `slate` build process (by `testsweeper`) is to blame. With Python 3 there are a few spots where the config module uses bytes-like objects instead of strings or vice-versa. 

**testsweeper/config/config.py**
```
line 339 before: log.write( stdout )
line 339 after: log.write( str(stdout) )
...

line 341 before: log.write( stderr )
line 341 after: log.write( str(stderr) )
...

line 500 before: out = '(' + out.strip() + ')'
line 500 after: out = '(' + str(out.strip()) + ')'
...

line 521 before: if (flag in err):
line 521 after: if (flag in str(err)):
...
```

Build completes just fine with these changes.

**Comment by eugeneswalker** [comment]
This has been resolved https://github.com/spack/spack/pull/15454#issuecomment-598505629
