### ISSUE TITLE
Installation issue: quantum-espresso does not find fftw3.f

### ISSUE THREAD

**Issue by marvinbernhardt** [spack/spack#15232]
Installation of quantum-espresso fails, because it can't find fftw3.f.
The issue is kind of known from the mailing list, and it seems like it is more a problem of quantum espresso than of spack.
https://lists.quantum-espresso.org/pipermail/users/2017-September/039159.html
However, it might still be possible to fix this problem in the package.py i hope, but I don't know how to do it.

### Steps to reproduce the issue

```console
$ spack install quantum-espresso~mpi~scalapack target=x86_64 ^/e4wa6u5^/z35g5nd
[+] /shared/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.0/fftw-3.3.8-e4wa6u53rh6nm2wjaqfz6yuxra232xi7
[+] /shared/spack/opt/spack/linux-fedora29-core2/gcc-8.2.0/openblas-0.3.8-z35g5ndezfyipbxfeydqhmb4nz2nlc75
==> 9345: Installing quantum-espresso
==> Using cached archive: /shared/spack/var/spack/cache/_source-cache/archive/25/258b2a8a6280e86dad779e5c56356d8b35dc96d12ff33dabeee914bc03d6d602.tar.gz
==> Using cached archive: /shared/spack/var/spack/cache/_source-cache/archive/b1/b1aa3179ee1c069964fb9c21f3b832aebeae54947ce8d3cc1a74e7b154c3c10f
==> Staging archive: /shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/q-e-qe-6.5.tar.gz
==> Created stage in /shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io
==> Applied patch https://gitlab.com/QEF/q-e/commit/5fb1195b0844e1052b7601f18ab5c700f9cbe648.diff
==> 9345: quantum-espresso: Building quantum-espresso [Package]
==> 9345: quantum-espresso: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' 'all'

2 errors found in build log:
     1318    /shared/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.0/gcc-8.2.0-ynlewml22i4peay3x4aytn3savkp3atw/bin/gfortran -O3 -g -x f95-cpp-input -D__FFTW3   -I/shared/spack/va
             r/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src//include -I/shared/spack/var/spack/stage/mbernhardt/spack-stage-q
             uantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src//FoX/finclude -I/shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5
             ljogy2tsqxvqr7bm3io/spack-src//S3DE/iotk/include/  -c fft_scalar.FFTW.f90
     1319    /shared/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.0/gcc-8.2.0-ynlewml22i4peay3x4aytn3savkp3atw/bin/gfortran -O3 -g -x f95-cpp-input -D__FFTW3   -I/shared/spack/va
             r/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src//include -I/shared/spack/var/spack/stage/mbernhardt/spack-stage-q
             uantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src//FoX/finclude -I/shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5
             ljogy2tsqxvqr7bm3io/spack-src//S3DE/iotk/include/  -c fft_scalar.FFTW3.f90
     1320    fft_scalar.FFTW3.f90:37:2:
     1321    
     1322     #endif
     1323      1~~~~
  >> 1324    Fatal Error: fftw3.f: No such file or directory
     1325    compilation terminated.
  >> 1326    make[1]: *** [../make.inc:16: fft_scalar.FFTW3.o] Error 1
     1327    make[1]: Leaving directory '/shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src/FFTXlib'
     1328    make: *** [Makefile:207: libfft] Error 1

See build log for details:
  /shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-build-out.txt

==> Error: Failed to install quantum-espresso due to ChildError: ProcessError: Command exited with status 2:
    'make' 'all'
2 errors found in build log:
     1318    /shared/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.0/gcc-8.2.0-ynlewml22i4peay3x4aytn3savkp3atw/bin/gfortran -O3 -g -x f95-cpp-input -D__FFTW3   -I/shared/spack/va
             r/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src//include -I/shared/spack/var/spack/stage/mbernhardt/spack-stage-q
             uantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src//FoX/finclude -I/shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5
             ljogy2tsqxvqr7bm3io/spack-src//S3DE/iotk/include/  -c fft_scalar.FFTW.f90
     1319    /shared/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.0/gcc-8.2.0-ynlewml22i4peay3x4aytn3savkp3atw/bin/gfortran -O3 -g -x f95-cpp-input -D__FFTW3   -I/shared/spack/va
             r/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src//include -I/shared/spack/var/spack/stage/mbernhardt/spack-stage-q
             uantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src//FoX/finclude -I/shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5
             ljogy2tsqxvqr7bm3io/spack-src//S3DE/iotk/include/  -c fft_scalar.FFTW3.f90
     1320    fft_scalar.FFTW3.f90:37:2:
     1321    
     1322     #endif
     1323      1~~~~
  >> 1324    Fatal Error: fftw3.f: No such file or directory
     1325    compilation terminated.
  >> 1326    make[1]: *** [../make.inc:16: fft_scalar.FFTW3.o] Error 1
     1327    make[1]: Leaving directory '/shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-src/FFTXlib'
     1328    make: *** [Makefile:207: libfft] Error 1

See build log for details:
  /shared/spack/var/spack/stage/mbernhardt/spack-stage-quantum-espresso-6.5-3yxmuagwxd2o5ljogy2tsqxvqr7bm3io/spack-build-out.txt
Traceback (most recent call last):
  File "/shared/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/shared/spack/lib/spack/spack/installer.py", line 1034, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/shared/spack/lib/spack/spack/package.py", line 105, in phase_wrapper
    phase(spec, prefix)
  File "/shared/spack/var/spack/repos/builtin/packages/quantum-espresso/package.py", line 275, in install
  File "/shared/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/shared/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' 'all'

```

### Platform and user environment

```commandline
$ uname -a
Linux biby33 4.18.18-300.fc29.x86_64 #1 SMP Mon Nov 12 03:12:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/fedora-release 
Fedora release 29 (Twenty Nine)
```

### Additional information
excerpt from spack-build-out.txt
```
--------------------------------------------------------------------
ESPRESSO can take advantage of several optimized numerical libraries
(essl, fftw, mkl...).  This configure script attempts to find them,
but may fail if they have been installed in non-standard locations.
If a required library is not found, the local copy will be compiled.

The following libraries have been found:
  BLAS_LIBS=-L/shared/spack/opt/spack/linux-fedora29-core2/gcc-8.2.0/openblas-0.3.8-z35g5ndezfyipbxfeydqhmb4nz2nlc75/lib -lopenblas
  LAPACK_LIBS= -L/shared/spack/opt/spack/linux-fedora29-core2/gcc-8.2.0/openblas-0.3.8-z35g5ndezfyipbxfeydqhmb4nz2nlc75/lib -lopenblas
  FFT_LIBS= -L/shared/spack/opt/spack/linux-fedora29-x86_64/gcc-8.2.0/fftw-3.3.8-e4wa6u53rh6nm2wjaqfz6yuxra232xi7/lib -lfftw3
  
  

Please check if this is what you expect.

If any libraries are missing, you may specify a list of directories
to search and retry, as follows:
  ./configure LIBDIRS="list of directories, separated by spaces"

Configured for compilation of serial executables.

For more info, read the ESPRESSO User's Guide (Doc/users-guide.tex).
--------------------------------------------------------------------
``` 
So it finds FFTW but does not include the header files I guess.

**Comment by adamjstewart** [comment]
@naromero77

**Comment by naromero77** [comment]
Will take a look, but not until next week -- at a workshop this week.

**Comment by naromero77** [comment]
Can you also send me the output of:
`spack spec quantum-espresso~mpi~scalapack target=x86_64`

**Comment by marvinbernhardt** [comment]
Sure! 
```commandline
$ spack spec quantum-espresso~mpi~scalapack target=x86_64
Input spec
--------------------------------
quantum-espresso~mpi~scalapack arch=linux-None-x86_64

Concretized
--------------------------------
quantum-espresso@6.5%gcc@8.2.0~elpa~epw hdf5=none ~mpi~openmp+patch patches=b1aa3179ee1c069964fb9c21f3b832aebeae54947ce8d3cc1a74e7b154c3c10f ~scalapack arch=linux-fedora29-x86_64
    ^fftw@3.3.8%gcc@8.2.0+mpi~openmp~pfft_patches precision=double,float arch=linux-fedora29-x86_64
        ^openmpi@2.1.1%gcc@8.2.0~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-fedora29-x86_64
    ^openblas@0.3.8%gcc@8.2.0~consistentFPCSR~ilp64+pic+shared threads=none arch=linux-fedora29-x86_64

```
And, in case it's relevant, with the dependencies I try to install with:
```commandline
$ spack spec quantum-espresso~mpi~scalapack target=x86_64 ^/e4wa6u5^/z35g5nd
Input spec
--------------------------------
quantum-espresso~mpi~scalapack arch=linux-None-x86_64
    ^fftw@3.3.8%gcc@8.2.0~mpi~openmp~pfft_patches precision=double,float arch=linux-fedora29-x86_64
    ^openblas@0.3.8%gcc@8.2.0~consistentFPCSR~ilp64+pic+shared threads=openmp arch=linux-fedora29-core2

Concretized
--------------------------------
quantum-espresso@6.5%gcc@8.2.0~elpa~epw hdf5=none ~mpi~openmp+patch patches=b1aa3179ee1c069964fb9c21f3b832aebeae54947ce8d3cc1a74e7b154c3c10f ~scalapack arch=linux-fedora29-x86_64
    ^fftw@3.3.8%gcc@8.2.0~mpi~openmp~pfft_patches precision=double,float arch=linux-fedora29-x86_64
    ^openblas@0.3.8%gcc@8.2.0~consistentFPCSR~ilp64+pic+shared threads=openmp arch=linux-fedora29-core2
```

**Comment by tz-rrze** [comment]
it seems to be an one-line upstream problem with the configure/automake ...; they do not append include paths to the Fortran flags and not use the calculated c/cpp for Fortran.

@marvinbernhardt: as quick&dirty workaround try to add the line
`options.append('FFLAGS=-O3 -g -I{0}'.format(fftw_prefix.include))`
after the existing `FFTW_INCLUDE=` line in _var/spack/repos/builtin/packages/quantum-espresso/package.py_. It's ugly as it hardcodes the optimization flags which normally are auto-determined by configure - but CPATH/FPATH are not respected.

An other alternativ would be to use Intel MKL instead of FFTW3&OpenBLAS. MKL should no longer  require a license in most cases and is available through SPACK for installation. However that would require PR #15242 being applied (or you have to delete the only line with `BLAS_LIBS=` from _var/spack/repos/builtin/packages/quantum-espresso/package.py_ for MKL being detected correctly.

**Comment by marvinbernhardt** [comment]
q&d workaround works, I can install it. Since this is an upstream issue I will close.

**Comment by tz-rrze** [comment]
Upstream accepted enhanced autoconf/configure rules to better detect FFTW3 in the next release

https://gitlab.com/QEF/q-e/-/commit/1dae68a46dbc3345ff6a6e2fa3ee88f31aa2056c
https://gitlab.com/QEF/q-e/-/merge_requests/807
