### ISSUE TITLE
Broken py-setuptools on MacOS %gcc

### ISSUE THREAD

**Issue by scemama** [spack/spack#15265]
On MacOS, unable to install py-setuptools ^python@2.7:2.8

### Spack version

```console
$ spack --version
0.14.0-64-8ee7ee610
```

### Steps to reproduce the issue

Environment setup:

```console
$ git clone https://github.com/spack/spack.git
$ git checkout develop
$ source share/spack/setup-env.sh 
$ spack install gcc
$ spack load gcc
$ spack compiler find
$ spack install python@2.7:2.8
$ spack load python@2.7:2.8
$ which python
/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/bin/python
$ spack spec python
Input spec
--------------------------------
python

Concretized
--------------------------------
python@3.7.6%gcc@9.2.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations patches=210df3f28cde02a8135b58cc4168e70ab91dbf9097359d05938f1e2843875e57 +pic+pyexpat+pythoncmd+readline~shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=darwin-catalina-skylake
    ^bzip2@1.0.8%gcc@9.2.0+shared arch=darwin-catalina-skylake
        ^diffutils@3.7%gcc@9.2.0 arch=darwin-catalina-skylake
            ^libiconv@1.16%gcc@9.2.0 arch=darwin-catalina-skylake
    ^expat@2.2.9%gcc@9.2.0~libbsd arch=darwin-catalina-skylake
    ^gdbm@1.18.1%gcc@9.2.0 arch=darwin-catalina-skylake
        ^readline@8.0%gcc@9.2.0 arch=darwin-catalina-skylake
            ^ncurses@6.1%gcc@9.2.0~symlinks+termlib arch=darwin-catalina-skylake
                ^pkgconf@1.6.3%gcc@9.2.0 arch=darwin-catalina-skylake
    ^gettext@0.20.1%gcc@9.2.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-catalina-skylake
        ^libxml2@2.9.9%gcc@9.2.0~python arch=darwin-catalina-skylake
            ^xz@5.2.4%gcc@9.2.0 arch=darwin-catalina-skylake
            ^zlib@1.2.11%gcc@9.2.0+optimize+pic+shared arch=darwin-catalina-skylake
        ^tar@1.32%gcc@9.2.0 arch=darwin-catalina-skylake
    ^libffi@3.2.1%gcc@9.2.0 arch=darwin-catalina-skylake
    ^openssl@1.1.1d%gcc@9.2.0+systemcerts arch=darwin-catalina-skylake
        ^perl@5.30.1%gcc@9.2.0+cpanm+shared+threads arch=darwin-catalina-skylake
    ^sqlite@3.30.1%gcc@9.2.0~column_metadata+fts~functions~rtree arch=darwin-catalina-skylake

```

Command leading to the error:

```console
$ spack install py-setuptools python@2.7:2.8
```

### Error Message
```
==> 77749: Installing py-setuptools
==> Using cached archive: /Users/loos/Work/spack_test/spack/var/spack/cache/_source-cache/archive/7e/7eae782ccf36b790c21bde7d86a4f303a441cd77036b25c559a602cf5186ce4d.zip
==> Staging archive: /var/folders/0f/8kntpjz543q83m2zw8n7662r0000gn/T/loos/spack-stage/spack-stage-py-setuptools-41.4.0-ymphjj3lmodqp7kffhlpxn32yg76neti/setuptools-41.4.0.zip
==> Created stage in /var/folders/0f/8kntpjz543q83m2zw8n7662r0000gn/T/loos/spack-stage/spack-stage-py-setuptools-41.4.0-ymphjj3lmodqp7kffhlpxn32yg76neti
==> No patches needed for py-setuptools
==> 77749: py-setuptools: Building py-setuptools [PythonPackage]
==> 77749: py-setuptools: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    '/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'
See build log for details:
  /var/folders/0f/8kntpjz543q83m2zw8n7662r0000gn/T/loos/spack-stage/spack-stage-py-setuptools-41.4.0-ymphjj3lmodqp7kffhlpxn32yg76neti/spack-build-out.txt

==> Error: Failed to install py-setuptools due to ChildError: ProcessError: Command exited with status 1:
    '/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'See build log for details:
  /var/folders/0f/8kntpjz543q83m2zw8n7662r0000gn/T/loos/spack-stage/spack-stage-py-setuptools-41.4.0-ymphjj3lmodqp7kffhlpxn32yg76neti/spack-build-out.txt
Traceback (most recent call last):
  File "/Users/loos/Work/spack_test/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/Users/loos/Work/spack_test/spack/lib/spack/spack/installer.py", line 1050, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/Users/loos/Work/spack_test/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/Users/loos/Work/spack_test/spack/lib/spack/spack/build_systems/python.py", line 153, in build
    self.setup_py('build', *args)
  File "/Users/loos/Work/spack_test/spack/lib/spack/spack/build_systems/python.py", line 121, in setup_py
    self.python('-s', setup, '--no-user-cfg', *args, **kwargs)
  File "/Users/loos/Work/spack_test/spack/lib/spack/spack/build_systems/python.py", line 115, in python
    inspect.getmodule(self).python(*args, **kwargs)
  File "/Users/loos/Work/spack_test/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 1:
    '/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'
```

Content of `  /var/folders/0f/8kntpjz543q83m2zw8n7662r0000gn/T/loos/spack-stage/spack-stage-py-setuptools-41.4.0-ymphjj3lmodqp7kffhlpxn32yg76neti/spack-build-out.txt` :
```
==> 77749: py-setuptools: Executing phase: 'build'
==> [2020-02-28-14:44:36.550151, 77764] '/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'build'
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import setuptools
  File "/private/var/folders/0f/8kntpjz543q83m2zw8n7662r0000gn/T/loos/spack-stage/spack-stage-py-setuptools-41.4.0-ymphjj3lmodqp7kffhlpxn32yg76neti/spack-src/setuptools/__init__.py", line 18, in <module>
    import setuptools.version
  File "/private/var/folders/0f/8kntpjz543q83m2zw8n7662r0000gn/T/loos/spack-stage/spack-stage-py-setuptools-41.4.0-ymphjj3lmodqp7kffhlpxn32yg76neti/spack-src/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/private/var/folders/0f/8kntpjz543q83m2zw8n7662r0000gn/T/loos/spack-stage/spack-stage-py-setuptools-41.4.0-ymphjj3lmodqp7kffhlpxn32yg76neti/spack-src/pkg_resources/__init__.py", line 36, in <module>
    import email.parser
  File "/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/lib/python2.7/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser
  File "/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/lib/python2.7/email/feedparser.py", line 27, in <module>
    from email import message
  File "/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/lib/python2.7/email/message.py", line 16, in <module>
    import email.charset
  File "/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/lib/python2.7/email/charset.py", line 13, in <module>
    import email.base64mime
  File "/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/lib/python2.7/email/base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/lib/python2.7/email/utils.py", line 29, in <module>
    import urllib
  File "/Users/loos/Work/spack_test/spack/opt/spack/darwin-catalina-skylake/gcc-9.2.0/python-2.7.16-iqelz5ihrl5uoq7orks6ma5lmwqh5pqh/lib/python2.7/urllib.py", line 1440, in <module>
    from _scproxy import _get_proxy_settings, _get_proxies
ImportError: No module named _scproxy
```

This seems to be a known problem between Python installations and MacOS:
https://stackoverflow.com/questions/5647023/no-module-named-scproxy-on-osx

### Information on your system

```console
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76
$ uname -a
Darwin lcpqmc69.ups-tlse.fr 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
$ spack compiler list
==> Available compilers
-- clang catalina-x86_64 ----------------------------------------
clang@11.0.0-apple

-- gcc catalina-x86_64 ------------------------------------------
gcc@9.2.0  gcc@6.3.0
```

### General information

- [X ] I have run `spack --version` and reported the version of Spack
- [X ] I have searched the issues of this repo and believe this is not a duplicate
- [X ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
I've had very poor luck building _any_ package on macOS using GCC. I highly recommend using Clang + GFortran instead.

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to open a new issue if the problem persists.
