### ISSUE TITLE
Locale issues (from #15206)

### ISSUE THREAD

**Issue by iarspider** [spack/spack#15285]
As discussed in #15206, it seems that setting `LC_ALL` inside Spack build recpie doesn't seem to have any effect.

### Spack version
```console
$ spack --version
spack --version
0.14.0-90-c0032a3
```

### Steps to reproduce the issue

```console
$ LC_ALL=POSIX spack install icu4c
```

### Error Message

```console
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/tty/log.py:469 ==> [2020-03-02-11:51:30.302523, 23662] Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/tty/log.py", line 447, in _writer_daemon
    line = in_pipe.readline()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 88: ordinal not in range(128)
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:537 ==> [2020-03-02-11:51:30.319183, 23653] WRITE LOCK (spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna): /tmp/sftnight/spack-stage/.lock[4198365912513072791:1] [Releasing] 
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:477 ==> [2020-03-02-11:51:30.320020, 23653] WRITE LOCK (spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna): /tmp/sftnight/spack-stage/.lock[4198365912513072791:1] [Released at 11:51:30.319616] 
mnt/build/jenkins/vanilla_spack/lib/spack/spack/error.py:55 ==> [2020-03-02-11:51:30.344463, 23625] Error: ProcessError: Command exited with status -13:
    'make' '-j8'
See build log for details:
  /tmp/sftnight/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna/spack-build-out.txt

Traceback (most recent call last):
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/installer.py", line 1050, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_systems/autotools.py", line 284, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status -13:
    'make' '-j8'
mnt/build/jenkins/vanilla_spack/lib/spack/spack/installer.py:1451 ==> [2020-03-02-11:51:31.102516, 23625] Error: Failed to install icu4c due to ChildError: ProcessError: Command exited with status -13:
    'make' '-j8'See build log for details:
  /tmp/sftnight/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna/spack-build-out.txt
Traceback (most recent call last):
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/installer.py", line 1050, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_systems/autotools.py", line 284, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status -13:
    'make' '-j8'

mnt/build/jenkins/vanilla_spack/lib/spack/spack/installer.py:1255 ==> [2020-03-02-11:51:31.420344, 23625] Flagging icu4c as failed: ProcessError: Command exited with status -13:
    'make' '-j8'See build log for details:
  /tmp/sftnight/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna/spack-build-out.txt
Traceback (most recent call last):
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/installer.py", line 1050, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_systems/autotools.py", line 284, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status -13:
    'make' '-j8'

mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:537 ==> [2020-03-02-11:51:31.422526, 23625] WRITE LOCK (icu4c): /mnt/build/jenkins/vanilla_spack/opt/spack/.spack-db/prefix_failures[8626195556348426490:1] [Acquiring] 
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:178 ==> [2020-03-02-11:51:31.423091, 23625] write locking [8626195556348426490:1]: timeout None sec
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:477 ==> [2020-03-02-11:51:31.423510, 23625] WRITE LOCK (icu4c): /mnt/build/jenkins/vanilla_spack/opt/spack/.spack-db/prefix_failures[8626195556348426490:1] [Acquired at 11:51:31.423236] 
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:537 ==> [2020-03-02-11:51:31.423846, 23625] READ LOCK (database): /mnt/build/jenkins/vanilla_spack/opt/spack/.spack-db/lock[0:0] [Acquiring] 
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:178 ==> [2020-03-02-11:51:31.424190, 23625] read locking [0:0]: timeout 3 sec
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:477 ==> [2020-03-02-11:51:31.424472, 23625] READ LOCK (database): /mnt/build/jenkins/vanilla_spack/opt/spack/.spack-db/lock[0:0] [Acquired at 11:51:31.424273] 
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:537 ==> [2020-03-02-11:51:31.432353, 23625] READ LOCK (database): /mnt/build/jenkins/vanilla_spack/opt/spack/.spack-db/lock[0:0] [Releasing] 
mnt/build/jenkins/vanilla_spack/lib/spack/llnl/util/lock.py:477 ==> [2020-03-02-11:51:31.432677, 23625] READ LOCK (database): /mnt/build/jenkins/vanilla_spack/opt/spack/.spack-db/lock[0:0] [Released at 11:51:31.432444] 
mnt/build/jenkins/vanilla_spack/lib/spack/spack/main.py:766 ==> [2020-03-02-11:51:31.646415, 23625] ChildError: ProcessError: Command exited with status -13:
    'make' '-j8'See build log for details:
  /tmp/sftnight/spack-stage/spack-stage-icu4c-65.1-55wm4t2wm3y7ibzmdsn5jwhgqhplfxna/spack-build-out.txt
Traceback (most recent call last):
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/installer.py", line 1050, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_systems/autotools.py", line 284, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/mnt/build/jenkins/vanilla_spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status -13:
    'make' '-j8'
```

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

Pinging @alalazo as requested.

**Comment by michaelkuhn** [comment]
Does it make a difference if you set `build_language` to `C.UTF-8`?

**Comment by dev-zero** [comment]
Latest CP2K is also failing due to missing unicode support in the locale when building with a Python < 3.7 (later versions of Python have an implicit `open(..., encoding='utf-8')`).

@michaelkuhn this workaround works. Unfortunately `C.UTF-8` may not be available on older Centos/RHEL, where `en_US.UTF-8` should be used instead.

The easiest solution would probably be to change Spacks default to `C.UTF-8` nonetheless, have Spack check whether that is available and fallback to `C` if not, informing the user that some packages may break when building with a non-unicode locale.
