### ISSUE TITLE
Adding module entry in the compilers.yaml causes error

### ISSUE THREAD

**Issue by pramodk** [spack/spack#1534]
I added module entry as:

```
spack compiler info intel
intel@15.0.0:
    cc  = /gpfs/bbp.cscs.ch/apps/viz/intel/composer_xe_2015.0.090/bin/intel64/icc
    cxx = /gpfs/bbp.cscs.ch/apps/viz/intel/composer_xe_2015.0.090/bin/intel64/icpc
    f77 = /gpfs/bbp.cscs.ch/apps/viz/intel/composer_xe_2015.0.090/bin/intel64/ifort
    fc  = /gpfs/bbp.cscs.ch/apps/viz/intel/composer_xe_2015.0.090/bin/intel64/ifort
    modules  = ['intel/icomposer-2015.0.090']
    operating system  = redhat6
```

And when I try to install something:

```
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/bin/spack", line 184, in <module>
    main()
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/bin/spack", line 161, in main
    return_val = command(parser, args)
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/lib/spack/spack/cmd/install.py", line 92, in install
    explicit=True)
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/lib/spack/spack/package.py", line 1016, in do_install
    spack.build_environment.fork(self, build_process, dirty=dirty)
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/lib/spack/spack/build_environment.py", line 508, in fork
    setup_package(pkg, dirty=dirty)
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/lib/spack/spack/build_environment.py", line 445, in setup_package
    set_compiler_environment_variables(pkg, spack_env)
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/lib/spack/spack/build_environment.py", line 222, in set_compiler_environment_variables
    load_module(mod)
  File "/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/lugviz/softwares/sources/spack/lib/spack/spack/build_environment.py", line 137, in load_module
    exec(compile(load, '<string>', 'exec'))
  File "<string>", line 1
    Warning: The number of floating seats is limited. Do not use make -j as it checks out all the licences preventing other users from working
           ^
SyntaxError: invalid syntax
==> Error: Installation process had nonzero exit code : 256
```

Am I missing anything here? (that warning is coming from loading a module intel module).

**Comment by mamelara** [comment]
modules are more reserved for cray compilers since we are required to load the appropriate PrgEnv and compiler module name. For example mine looks like this:

```sh
- compiler:
    modules:
    - PrgEnv-intel
    - intel/16.0.3.210
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@16.0.3.210
```

On linux systems, spack determines the location of the compiler via $PATH. The [], is suppose to signify that the modules field is empty.

**Comment by alalazo** [comment]
Is this still an issue?

**Comment by alalazo** [comment]
@pramodk Closing this. Feel free to reopen if it is still an issue
