### ISSUE TITLE
Strange concretization behavior with --test=all

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#15377]
If I install a package with `--test=all`, I see some very strange concretization behavior. For example, `spack install --test=all py-attrs`, which might have a circular test dependency on itself, tries to build `py-attrs` before building `python`, and crashes due to a missing attribute that is normally defined by the `PythonPackage` base class. See below for full error message.

### Spack version

```console
$ spack --version
0.14.0-149-6412b9e71a
```

### Steps to reproduce the issue

```console
$ spack install --test=all py-attrs
```
Note that this error does not occur for `--test=root`. I'm not sure if this error exists for other packages or just packages with circular test dependencies.

### Error Message

```console
$ spack install --test=all py-attrs
==> Warning: clang@11.0.0-apple cannot build optimized binaries for "ivybridge". Using best target possible: "x86_64"
[+] /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/libiconv-1.16-gj3jnj46xug7rpjxwaepe6uwx35jdphz
[+] /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/expat-2.2.9-ctgvqggynhtr2zdidy2f64gk5vgt6jpg
[+] /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/pkgconf-1.6.3-t64p5ucui6qgo6tepzu44q3hrgpvabrx
[+] /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/xz-5.2.4-nahnpskrw2jjhtsviwietm4qcs5sa7oe
[+] /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/zlib-1.2.11-cvrek7vtvob6v2dfnvdowu2rkqtqtmmi
[+] /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.0-apple/libffi-3.2.1-2mukefjdfv5eb2oyrsawyoqdkh2zndsd
==> 2344: Installing py-attrs
==> Finding buildcaches in /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-2/test_ci_rebuild_basic0/working_dir/local_mirror/build_cache
==> Fetching file:///private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-2/test_ci_rebuild_basic0/working_dir/local_mirror/build_cache/darwin-catalina-x86_64-clang-11.0.0-apple-py-attrs-19.2.0-iozreocs7s2va7fnjekmid3f6ni6hymz.spec.yaml
curl: (37) Couldn't open file /private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-2/test_ci_rebuild_basic0/working_dir/local_mirror/build_cache/darwin-catalina-x86_64-clang-11.0.0-apple-py-attrs-19.2.0-iozreocs7s2va7fnjekmid3f6ni6hymz.spec
==> Failed to fetch file from URL: file:///private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-2/test_ci_rebuild_basic0/working_dir/local_mirror/build_cache/darwin-catalina-x86_64-clang-11.0.0-apple-py-attrs-19.2.0-iozreocs7s2va7fnjekmid3f6ni6hymz.spec.yaml
    Curl failed with error 37
==> Fetching from file:///private/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/pytest-of-Adam/pytest-2/test_ci_rebuild_basic0/working_dir/local_mirror/build_cache/darwin-catalina-x86_64-clang-11.0.0-apple-py-attrs-19.2.0-iozreocs7s2va7fnjekmid3f6ni6hymz.spec.yaml failed.
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check clang@11.0.0-apple for further details]
==> Using cached archive: /Users/Adam/spack/var/spack/cache/_source-cache/archive/f9/f913492e1663d3c36f502e5e9ba6cd13cf19d7fab50aa13239e420fef95e1396.tar.gz
==> Staging archive: /var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-attrs-19.2.0-iozreocs7s2va7fnjekmid3f6ni6hymz/attrs-19.2.0.tar.gz
==> Created stage in /var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-attrs-19.2.0-iozreocs7s2va7fnjekmid3f6ni6hymz
==> No patches needed for py-attrs
==> 2344: py-attrs: Building py-attrs [PythonPackage]
==> 2344: py-attrs: Executing phase: 'build'
==> Error: AttributeError: module 'spack.pkg.builtin.py-attrs' has no attribute 'python'

/Users/Adam/spack/lib/spack/spack/build_systems/python.py:114, in python:
  >>    114    def python(self, *args, **kwargs):
        115        inspect.getmodule(self).python(*args, **kwargs)

See build log for details:
  /var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-attrs-19.2.0-iozreocs7s2va7fnjekmid3f6ni6hymz/spack-build-out.txt

==> Error: Failed to install py-attrs due to ChildError: AttributeError: module 'spack.pkg.builtin.py-attrs' has no attribute 'python'
/Users/Adam/spack/lib/spack/spack/build_systems/python.py:114, in python:
  >>    114    def python(self, *args, **kwargs):
        115        inspect.getmodule(self).python(*args, **kwargs)

See build log for details:
  /var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-py-attrs-19.2.0-iozreocs7s2va7fnjekmid3f6ni6hymz/spack-build-out.txt
Traceback (most recent call last):
  File "/Users/Adam/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/Users/Adam/spack/lib/spack/spack/installer.py", line 1109, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/Users/Adam/spack/lib/spack/spack/build_systems/python.py", line 153, in build
    self.setup_py('build', *args)
  File "/Users/Adam/spack/lib/spack/spack/build_systems/python.py", line 121, in setup_py
    self.python('-s', setup, '--no-user-cfg', *args, **kwargs)
  File "/Users/Adam/spack/lib/spack/spack/build_systems/python.py", line 115, in python
    inspect.getmodule(self).python(*args, **kwargs)
AttributeError: module 'spack.pkg.builtin.py-attrs' has no attribute 'python'

==> Warning: Skipping build of py-hypothesis since py-attrs failed
==> Warning: Skipping build of py-pytest since py-attrs failed
```
As you can see, it builds some of the Python dependencies, but not Python itself. Because `python` is not a dependency of `py-attrs` (during testing), `self.python(...)` crashes.

### Information on your system

macOS 10.15.3
Python 3.7.6

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
P.S. @tgamblin we should add a flag to `spack spec` that allows you to get a spec including test deptypes.

**Comment by scheibelp** [comment]
There does appear to be a cyclic dependency:

```
$ spack-python
>>> from spack.spec import Spec
>>> x = Spec('py-attrs')
>>> x.concretize(tests=True)
>>> print x.tree()
py-attrs@19.2.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
    ^py-coverage@4.5.4%clang@9.0.0-apple arch=darwin-mojave-x86_64
        ^py-setuptools@41.4.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
            ^python@3.7.6%clang@9.0.0-apple+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations patches=210df3f28cde02a8135b58cc4168e70ab91dbf9097359d05938f1e2843875e57 +pic+pyexpat+pythoncmd+readline~shared+sqlite3+ssl~tix~tkinter~ucs4~uuid+zlib arch=darwin-mojave-x86_64
                ^bzip2@1.0.8%clang@9.0.0-apple+shared arch=darwin-mojave-x86_64
                    ^diffutils@3.7%clang@9.0.0-apple arch=darwin-mojave-x86_64
                        ^libiconv@1.16%clang@9.0.0-apple arch=darwin-mojave-x86_64
                ^expat@2.2.9%clang@9.0.0-apple~libbsd arch=darwin-mojave-x86_64
                ^gdbm@1.18.1%clang@9.0.0-apple arch=darwin-mojave-x86_64
                    ^readline@8.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
                        ^ncurses@6.1%clang@9.0.0-apple~symlinks~termlib arch=darwin-mojave-x86_64
                            ^pkgconf@1.6.3%clang@9.0.0-apple arch=darwin-mojave-x86_64
                ^gettext@0.20.1%clang@9.0.0-apple+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-mojave-x86_64
                    ^libxml2@2.9.9%clang@9.0.0-apple~python arch=darwin-mojave-x86_64
                        ^xz@5.2.4%clang@9.0.0-apple arch=darwin-mojave-x86_64
                        ^zlib@1.2.11%clang@9.0.0-apple+optimize+pic+shared arch=darwin-mojave-x86_64
                    ^tar@1.32%clang@9.0.0-apple arch=darwin-mojave-x86_64
                ^libffi@3.2.1%clang@9.0.0-apple arch=darwin-mojave-x86_64
                ^openssl@1.1.1d%clang@9.0.0-apple+systemcerts arch=darwin-mojave-x86_64
                    ^perl@5.30.1%clang@9.0.0-apple+cpanm+shared+threads arch=darwin-mojave-x86_64
                ^sqlite@3.30.1%clang@9.0.0-apple~column_metadata+fts~functions~rtree arch=darwin-mojave-x86_64
    ^py-hypothesis@4.41.2%clang@9.0.0-apple arch=darwin-mojave-x86_64
        ^py-attrs@19.2.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
    ^py-pympler@0.4.3%clang@9.0.0-apple arch=darwin-mojave-x86_64
    ^py-pytest@5.2.1%clang@9.0.0-apple arch=darwin-mojave-x86_64
        ^py-atomicwrites@1.3.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
        ^py-importlib-metadata@1.2.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
            ^py-packaging@19.2%clang@9.0.0-apple arch=darwin-mojave-x86_64
                ^py-pyparsing@2.4.2%clang@9.0.0-apple arch=darwin-mojave-x86_64
                ^py-six@1.12.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
            ^py-setuptools-scm@3.3.3%clang@9.0.0-apple arch=darwin-mojave-x86_64
            ^py-zipp@0.6.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
                ^py-more-itertools@7.2.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
        ^py-pluggy@0.13.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
        ^py-py@1.8.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
        ^py-wcwidth@0.1.7%clang@9.0.0-apple arch=darwin-mojave-x86_64
    ^py-zope-interface@4.5.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
        ^py-nose@1.3.7%clang@9.0.0-apple arch=darwin-mojave-x86_64
        ^py-zope-event@4.3.0%clang@9.0.0-apple arch=darwin-mojave-x86_64
```

Is the issue that:

* This cyclic dependency is required and Spack needs to accommodate that?
* This cyclic dependency is incorrect and Spack doesn't need to accommodate it but it should have reported it as an error

?

**Comment by adamjstewart** [comment]
@scheibelp I'm not sure. I imagine the current concretizer isn't smart enough to resolve the circular dependency, and that's fine. I'm hoping the new concretizer will be able to figure something out. Regardless, I think an error message reporting this circular dependency would be far better than whatever it is currently doing.

**Comment by scheibelp** [comment]
> I imagine the current concretizer isn't smart enough to resolve the circular dependency, and that's fine

I don't think our overall model addresses it either. While I can see how you could have:

`X--[t]-->Y--[r]-->X`

and install `X` but then wait to test it until `Y` is installed.

> Note that this error does not occur for `--test=root`

I'm glad that works although I can't claim that is on account of intent. Nevertheless I'll add a "workaround" tag for now since you discovered that.

@tgamblin this is a novel use case for dependency types and I'll add a tag for that too.
