### ISSUE TITLE
tau build fails on ppc64le

### ISSUE THREAD

**Issue by eugeneswalker** [spack/spack#15554]
I can't get `tau` to build on `ppc64le`. The compiler is `gcc@7.3.0` and I've tried on `CentOS 7`, `RHEL 7`, and `Ubuntu 18.04`. I'm using Spack @ develop (commit 958f26073efe340 from 18-March-2020).

```
$> spack install tau%gcc@7.3.0 target=ppc64le
...
==> Error: Failed to install tau due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j8' 'install'
14 errors found in build log:
     88     Installing utilities...
     89     ====================================================
     90      Copy /tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/tools/src/contrib/CubeReader.jar to /opt/spack/opt/sp
            ack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/ibm64linux/lib
     91     ====================================================
     92     ... done
     93     ***********************************************************************
  >> 94     grep: ./utils/FixMakefile.info: No such file or directory
  >> 95     grep: ./utils/FixMakefile.sed: No such file or directory
     96     NOTE: Saving configuration environment to /tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/.configure_env/67
            9200d18f3ed1b6889dc3743f981508
     97     NOTE: Enabled Profiling. Compiling with -DPROFILING_ON
     98     NOTE: Building POSIX I/O wrapper
     99     NOTE: GNU gfortran compiler specific options used
     100    NOTE: Using PAPI interface for Hardware Performance Counters ***
     101    NOTE: Using fixes for GNU 4.6+ compiler

     ...

     200    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/plugins'
     201    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/instrument'
     202    /bin/rm -f simple.o simple
     203    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/instrument'
     204    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/threads'
     205    Makefile:16: /tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthre
            ad-pdt: No such file or directory
  >> 206    make[1]: *** No rule to make target '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefil
            e.tau-papi-gnu-mpi-pthread-pdt'.  Stop.
     207    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/threads'
     208    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/cthreads'
     209    Makefile:16: /tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthre
            ad-pdt: No such file or directory
  >> 210    make[1]: *** No rule to make target '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefil
            e.tau-papi-gnu-mpi-pthread-pdt'.  Stop.
     211    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/cthreads'
     212    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/fortran'
     213    /bin/rm -f hello.o hello
     214    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/fortran'
     215    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/f90'
     216    /bin/rm -f cubes.o cubes
     217    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/f90'
     218    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/pi'
     219    Makefile:16: /tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthre
            ad-pdt: No such file or directory
  >> 220    make[1]: *** No rule to make target '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefil
            e.tau-papi-gnu-mpi-pthread-pdt'.  Stop.
     221    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/pi'
     222    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/NPB2.3'
     223    rm -f core
     224    rm -f *~ */core */*~ */*.o */npbparams.h */*.obj */*.exe
     225    rm -f MPI_dummy/test MPI_dummy/libmpi.a
     226    rm -f sys/setparams sys/makesuite sys/setparams.h
     227    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/NPB2.3'
     228    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/autoinstrument'
     229    Makefile:16: /tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthre
            ad-pdt: No such file or directory
  >> 230    make[1]: *** No rule to make target '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefil
            e.tau-papi-gnu-mpi-pthread-pdt'.  Stop.
     231    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/autoinstrument'
     232    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/reduce'
     233    Makefile:16: /tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthre
            ad-pdt: No such file or directory
  >> 234    make[1]: *** No rule to make target '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/ibm64linux/lib/Makefil
            e.tau-papi-gnu-mpi-pthread-pdt'.  Stop.
     235    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/examples/reduce'
     236    touch .clean
     237    Determining Configuration...
     238    System previously configured as a ibm64linux
     239    *********** RECURSIVELY MAKING SUBDIRECTORIES ***********
     240    *** COMPILING src/TraceInput DIRECTORY
     241    make[1]: Entering directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/src/TraceInput'
     242    g++ -m64 		   	  	    -I/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/include -I/opt/spack/o
            pt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/mpich-3.2.1-c3y5ohb72e6htbm3y7po6ymrcmxxatnp/include -O2 -g -Wl,-rpath,/opt/spack/opt/spack/linux-ub
            untu18.04-ppc64le/gcc-7.3.0/tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/tau
            -2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/lib64 -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/zlib-1.2.11-tdnmyepqgfsybqzc55zg
            ca3rvmp55epy/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/pdt-3.25.1-czegb3ismtstyml2wugkifojybw4cacs/lib -Wl,-rpath,/
            opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/otf2-2.2-puyvnijauo3dgbz7abnwmkx57o534yrx/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubunt
            u18.04-ppc64le/gcc-7.3.0/papi-5.7.0-l4d5fyx74jacdwz4ibimdsbckpw7i2qy/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/libd
            warf-20180129-zroyr5v2flabxnvow2ms5w7gtgydyzbv/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/libelf-0.8.13-jq5x36aspohj
            keofb2t7rfhbmd4bxe7c/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/binutils-2.33.1-ztxgm2hjuxq4pdosmxnh3t6k7h764nqc/lib
             -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/mpich-3.2.1-c3y5ohb72e6htbm3y7po6ymrcmxxatnp/lib -Wl,-rpath,/opt/spack/opt/s
            pack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/binutils-2.33.1-ztxgm2hjuxq4pdosmxnh3t6k7h764nqc/lib64 -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04
            -ppc64le/gcc-7.3.0/libunwind-1.3.1-t64vx2jrr4f4433yvrec6dn6w3rledu5/lib64 -I. -c TAU_tf.cpp
     243    g++ -m64 		   	  	    -I/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/include -I/opt/spack/o
            pt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/mpich-3.2.1-c3y5ohb72e6htbm3y7po6ymrcmxxatnp/include -O2 -g -Wl,-rpath,/opt/spack/opt/spack/linux-ub
            untu18.04-ppc64le/gcc-7.3.0/tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/tau
            -2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/lib64 -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/zlib-1.2.11-tdnmyepqgfsybqzc55zg
            ca3rvmp55epy/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/pdt-3.25.1-czegb3ismtstyml2wugkifojybw4cacs/lib -Wl,-rpath,/
            opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/otf2-2.2-puyvnijauo3dgbz7abnwmkx57o534yrx/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubunt
            u18.04-ppc64le/gcc-7.3.0/papi-5.7.0-l4d5fyx74jacdwz4ibimdsbckpw7i2qy/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/libd
            warf-20180129-zroyr5v2flabxnvow2ms5w7gtgydyzbv/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/libelf-0.8.13-jq5x36aspohj
            keofb2t7rfhbmd4bxe7c/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/binutils-2.33.1-ztxgm2hjuxq4pdosmxnh3t6k7h764nqc/lib
             -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/mpich-3.2.1-c3y5ohb72e6htbm3y7po6ymrcmxxatnp/lib -Wl,-rpath,/opt/spack/opt/s
            pack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/binutils-2.33.1-ztxgm2hjuxq4pdosmxnh3t6k7h764nqc/lib64 -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04
            -ppc64le/gcc-7.3.0/libunwind-1.3.1-t64vx2jrr4f4433yvrec6dn6w3rledu5/lib64 -I. -c TAU_Cwrapper.cpp
     244    g++ -m64 		   	  	    -I/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/include -I/opt/spack/o
            pt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/mpich-3.2.1-c3y5ohb72e6htbm3y7po6ymrcmxxatnp/include -O2 -g -Wl,-rpath,/opt/spack/opt/spack/linux-ub
            untu18.04-ppc64le/gcc-7.3.0/tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/tau
            -2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/lib64 -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/zlib-1.2.11-tdnmyepqgfsybqzc55zg
            ca3rvmp55epy/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/pdt-3.25.1-czegb3ismtstyml2wugkifojybw4cacs/lib -Wl,-rpath,/
            opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/otf2-2.2-puyvnijauo3dgbz7abnwmkx57o534yrx/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubunt
            u18.04-ppc64le/gcc-7.3.0/papi-5.7.0-l4d5fyx74jacdwz4ibimdsbckpw7i2qy/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/libd
            warf-20180129-zroyr5v2flabxnvow2ms5w7gtgydyzbv/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/libelf-0.8.13-jq5x36aspohj
            keofb2t7rfhbmd4bxe7c/lib -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/binutils-2.33.1-ztxgm2hjuxq4pdosmxnh3t6k7h764nqc/lib
             -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/mpich-3.2.1-c3y5ohb72e6htbm3y7po6ymrcmxxatnp/lib -Wl,-rpath,/opt/spack/opt/s
            pack/linux-ubuntu18.04-ppc64le/gcc-7.3.0/binutils-2.33.1-ztxgm2hjuxq4pdosmxnh3t6k7h764nqc/lib64 -Wl,-rpath,/opt/spack/opt/spack/linux-ubuntu18.04
            -ppc64le/gcc-7.3.0/libunwind-1.3.1-t64vx2jrr4f4433yvrec6dn6w3rledu5/lib64 -I. -c TAU_tf_writer.cpp
  >> 245    as: error while loading shared libraries: libopcodes-2.33.1.so: cannot open shared object file: No such file or directory
     246    Makefile:126: recipe for target 'TAU_Cwrapper.o' failed
  >> 247    make[1]: *** [TAU_Cwrapper.o] Error 1
     248    make[1]: *** Waiting for unfinished jobs....
  >> 249    as: error while loading shared libraries: libopcodes-2.33.1.so: cannot open shared object file: No such file or directory
     250    Makefile:123: recipe for target 'TAU_tf_writer.o' failed
  >> 251    make[1]: *** [TAU_tf_writer.o] Error 1
  >> 252    as: error while loading shared libraries: libopcodes-2.33.1.so: cannot open shared object file: No such file or directory
     253    Makefile:120: recipe for target 'TAU_tf.o' failed
  >> 254    make[1]: *** [TAU_tf.o] Error 1
     255    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-src/src/TraceInput'
     256    Makefile:180: recipe for target 'install' failed
  >> 257    make: *** [install] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-tau-2.29-ad3e57a5sfq4bxbwwir7wmyhks4k37u4/spack-build-out.txt
Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/opt/spack/lib/spack/spack/installer.py", line 1114, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/opt/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/opt/spack/var/spack/repos/builtin/packages/tau/package.py", line 274, in install
  File "/opt/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/opt/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j8' 'install'
```

Full build log:  [tau-ppc64le-log.txt](https://github.com/spack/spack/files/4351107/tau-ppc64le-log.txt)

@khuck @wspear

**Comment by mwkrentel** [comment]
@eugeneswalker If you look at the tau error log, I'm pretty sure the real
problem is that binutils failed.  All of the checks in tau say that
they can't find the binutils headers, logs, etc.

Why did binutils fail?  I don't know.  Maybe a transient fetch error,
maybe you're behind a proxy or something.  I build binutils with gcc
7.3.x and ppc64le all the time, so this config is supported.

Anyway, try `spack install -v binutils`, see if it tells you why
binutils failed.  Be sure to use the same spec that tau wants.

**Comment by eugeneswalker** [comment]
@mwkrentel Thank you! Yes, it was an error having to do with how rpaths were being handled when installing dependencies from a build cache. I am not having this problem since PR https://github.com/spack/spack/pull/15558.
