### ISSUE TITLE
KeyError: 'TERM' on Cray 

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#15620]
Since #15381 was merged, I'm seeing a KeyError when I try to submit build jobs on Cray.

### Spack version

```console
$ spack --version
0.14.1-323-4b771bc52
```

### Steps to reproduce the issue

I'm using the following PBS file on Blue Waters:
```bash
$ cat build-pytorch.pbs 
#!/usr/bin/env bash
#PBS -l nodes=1:ppn=32:xe
#PBS -l walltime=48:00:00
#PBS -q normal
#PBS -N pytorch-0.4.1
#PBS -A bbcj
#PBS -j oe
#PBS -M adamjs5@illinois.edu
#PBS -m abef

# Modules
# See https://github.com/numpy/numpy/issues/14233
module load binutils

# Environment
. ~/spack/share/spack/setup-env.sh

# Build PyTorch
aprun env spack --color=never install --test=root py-torch@0.4.1
```

### Error Message

The build fails with the following error:
```
Traceback (most recent call last):
  File "/u/sciteam/stewart1/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/main.py", line 770, in main
    if spack.config.get('config:debug'):
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/config.py", line 671, in get
    return config.get(path, default, scope)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/lang.py", line 552, in __getattr__
    return getattr(self.instance, name)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/lang.py", line 548, in instance
    self._instance = self.factory()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/config.py", line 653, in _config
    _add_platform_scope(cfg, ConfigScope, name, path)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/config.py", line 606, in _add_platform_scope
    platform = spack.architecture.platform().name
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/lang.py", line 178, in _memoized_function
    func.cache[args] = func(*args)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/architecture.py", line 516, in platform
    return platform_cls()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/platforms/cray.py", line 63, in __init__
    _target = self._default_target_from_env()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/platforms/cray.py", line 121, in _default_target_from_env
    env={'TERM': os.environ['TERM']},
  File "/usr/lib64/python2.6/UserDict.py", line 22, in __getitem__
    raise KeyError(key)
KeyError: 'TERM'
```
`TERM` is set when I am logged in to the login nodes, but not when I submit a job.

### Information on your system

Cray CNL5 Interlagos, Blue Waters

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

@becker33 @tgamblin

**Comment by adamjstewart** [comment]
If I revert the commit from #15381, I can run Spack properly, but now I see a new error:
```
==> 4686: Installing zlib
==> Using cached archive: /mnt/a/u/sciteam/stewart1/spack/var/spack/cache/zlib/zlib-1.2.11.tar.gz
==> Staging archive: /scratch/sciteam/stewart1/spack-stage-zlib-1.2.11-q2azpxyxsy5lnmmufuf3bdlzztetv766/zlib-1.2.11.tar.gz
==> Created stage in /scratch/sciteam/stewart1/spack-stage-zlib-1.2.11-q2azpxyxsy5lnmmufuf3bdlzztetv766
==> No patches needed for zlib
==> 4686: zlib: Building zlib [Package]
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/tty/log.py", line 494, in _writer_daemon
    if stdin in rlist and not _is_background_tty():
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/tty/log.py", line 50, in _is_background_tty
    return os.getpgrp() != os.tcgetpgrp(sys.stdout.fileno())
OSError: [Errno 25] Inappropriate ioctl for device
==> Error: IOError: [Errno 32] Broken pipe

/mnt/a/u/sciteam/stewart1/spack/var/spack/repos/builtin/packages/zlib/package.py:53, in install:
         50            config_args.append('--static')
         51        configure('--prefix={0}'.format(prefix), *config_args)
         52
  >>     53        make()
         54        if self.run_tests:
         55            make('check')
         56        make('install')

See build log for details:
  /scratch/sciteam/stewart1/spack-stage-zlib-1.2.11-q2azpxyxsy5lnmmufuf3bdlzztetv766/spack-build-out.txt

==> Error: Failed to install zlib due to ChildError: IOError: [Errno 32] Broken pipe
/mnt/a/u/sciteam/stewart1/spack/var/spack/repos/builtin/packages/zlib/package.py:53, in install:
         50            config_args.append('--static')
         51        configure('--prefix={0}'.format(prefix), *config_args)
         52
  >>     53        make()
         54        if self.run_tests:
         55            make('check')
         56        make('install')

See build log for details:
  /scratch/sciteam/stewart1/spack-stage-zlib-1.2.11-q2azpxyxsy5lnmmufuf3bdlzztetv766/spack-build-out.txt
Traceback (most recent call last):
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/installer.py", line 1114, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/filesystem.py", line 605, in working_dir
    yield
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/installer.py", line 1114, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/mnt/a/u/sciteam/stewart1/spack/var/spack/repos/builtin/packages/zlib/package.py", line 54, in install
    if self.run_tests:
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/spack/util/executable.py", line 159, in __call__
    tty.debug(cmd_line)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/tty/__init__.py", line 203, in debug
    info(message, *args, **kwargs)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/tty/__init__.py", line 181, in info
    ), stream=stream)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/tty/color.py", line 232, in cprint
    cwrite(string + "\n", stream, color)
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/tty/color.py", line 227, in cwrite
    stream.write(colorize(string, color=color))
  File "/mnt/a/u/sciteam/stewart1/spack/lib/spack/llnl/util/tty/log.py", line 139, in write
    self.stream.write(data)
IOError: [Errno 32] Broken pipe
```

**Comment by adamjstewart** [comment]
Note that neither of the above issues occur when I build on the login nodes instead of submitting a job.

**Comment by adamjstewart** [comment]
As suggested by @tgamblin, using `os.environ.get('TERM', '')` solves the first issue, but the second issue still remains.
