### ISSUE TITLE
Installation issue: llvm (master and 9.0.1)

### ISSUE THREAD

**Issue by mmrezaie** [spack/spack#15642]
### Spack version
0.14.1-328-a3e341385

### Steps to reproduce the issue
spack -v install llvm@master or llvm@9.0.1

### Platform and user environment
$ uname -a 
ubuntu 5.3.0-42-generic

$ lsb_release -d
Description:	Ubuntu 19.10

The build process finishes fine but when it wants to install it fails due permission failure when it wants to copy some files to my system's /usr/lib. Let me know if I have failed to provide more information.

2 errors found in build log:
     63822    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMTextAPI.a
     63823    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMDlltoolDriver.a
     63824    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMLibDriver.a
     63825    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMXRay.a
     63826    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMWindowsManifest.a
     63827    -- Installing: /usr/lib/ocaml/llvm/llvm.mli
  >> 63828    CMake Error at bindings/ocaml/llvm/cmake_install.cmake:49 (file):
     63829      file INSTALL cannot copy file
     63830      "/tmp/mrez/spack-stage/spack-stage-llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/spack-build/bindings/ocaml/llvm/llvm.mli"
  >> 63831      to "/usr/lib/ocaml/llvm/llvm.mli": Permission denied.
     63832    Call Stack (most recent call first):
     63833      bindings/ocaml/cmake_install.cmake:42 (include)
     63834      cmake_install.cmake:71 (include)
     63835    
     63836    
     63837    make: *** [Makefile:143: install] Error 1

See build log for details:
  /tmp/mrez/spack-stage/spack-stage-llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/spack-build-out.txt

==> Error: Failed to install llvm due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j8' 'install'
2 errors found in build log:
     63822    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMTextAPI.a
     63823    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMDlltoolDriver.a
     63824    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMLibDriver.a
     63825    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMXRay.a
     63826    -- Installing: /home/mrez/.local/src/spack/opt/spack/linux-ubuntu19.10-haswell/gcc-9.2.1/llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/lib/libLLVMWindowsManifest.a
     63827    -- Installing: /usr/lib/ocaml/llvm/llvm.mli
  >> 63828    CMake Error at bindings/ocaml/llvm/cmake_install.cmake:49 (file):
     63829      file INSTALL cannot copy file
     63830      "/tmp/mrez/spack-stage/spack-stage-llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/spack-build/bindings/ocaml/llvm/llvm.mli"
  >> 63831      to "/usr/lib/ocaml/llvm/llvm.mli": Permission denied.
     63832    Call Stack (most recent call first):
     63833      bindings/ocaml/cmake_install.cmake:42 (include)
     63834      cmake_install.cmake:71 (include)
     63835    
     63836    
     63837    make: *** [Makefile:143: install] Error 1

See build log for details:
  /tmp/mrez/spack-stage/spack-stage-llvm-master-3fkwhjsr4xfqqpv73rl7evztzvtk2rqr/spack-build-out.txt
Traceback (most recent call last):
  File "/home/mrez/.local/src/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/home/mrez/.local/src/spack/lib/spack/spack/installer.py", line 1114, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/home/mrez/.local/src/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/home/mrez/.local/src/spack/lib/spack/spack/build_systems/cmake.py", line 353, in install
    inspect.getmodule(self).make(*self.install_targets)
  File "/home/mrez/.local/src/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/home/mrez/.local/src/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j8' 'install'

**Comment by mmrezaie** [comment]
Just in case:

Why this build is trying to write to this location: /usr/lib/ocaml/llvm/llvm.mli. Obiousely it should not have the permission. Maybe I can help but I do not understand why that file?

**Comment by jamesETsmith** [comment]
I'm seeing this error also, were you ever able to fix it? For reference, I'm trying to build `llvm@14.0.5` with `gcc@12.1.0` and spack 1bc3b0a.

**Comment by mmrezaie** [comment]
I gave up and installed it by my own and manually created the module. I have not checked it since then.

**Comment by kindjie** [comment]
This still happens on the latest version of Spack.
