### ISSUE TITLE
spack buildcache check fails when hash is used as argument

### ISSUE THREAD

**Issue by mc-allen** [spack/spack#15662]
I was trying to add a check to avoid pushing to the buildcache unnecessarily, and used a hash to unambiguously refer to a package. This resulted in an exception. This reproduced for me in develop and releases/v0.14.

### Spack version

```console
$ spack --version
0.14.1-344-1a5e4232e
```

### Steps to reproduce the issue

```console
$ spack buildcache check --mirror-url=s3://build-cache -s /any-valid-hash
==> Error: local variable 'spack' referenced before assignment
```

### Error Message

```console
$ spack -d buildcache check --mirror-url=s3://build-cache -s /zexzppv37zdl2pgi7jt5hlrlxfqbripw
==> [2020-03-24-15:44:50.831822, 25104] Imported buildcache from built-in commands
==> [2020-03-24-15:44:50.837586, 25104] Imported buildcache from built-in commands
==> [2020-03-24-15:44:50.838766, 25104] Reading config file src/spack/etc/spack/defaults/config.yaml
==> [2020-03-24-15:44:50.850790, 25104] DATABASE LOCK TIMEOUT: 3s
==> [2020-03-24-15:44:50.850835, 25104] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-03-24-15:44:50.851022, 25104] READ LOCK (database): src/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2020-03-24-15:44:50.851127, 25104] read locking [0:0]: timeout 3 sec
==> [2020-03-24-15:44:50.851179, 25104] READ LOCK (database): src/spack/opt/spack/.spack-db/lock[0:0] [Acquired at 15:44:50.851166]
==> [2020-03-24-15:44:50.869195, 25104] READ LOCK (database): src/spack/opt/spack/.spack-db/lock[0:0] [Releasing]
==> [2020-03-24-15:44:50.869277, 25104] READ LOCK (database): src/spack/opt/spack/.spack-db/lock[0:0] [Released at 15:44:50.869263]
Traceback (most recent call last):
  File "src/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "src/spack/lib/spack/spack/main.py", line 763, in main
    return _invoke_command(command, parser, args, unknown)
  File "src/spack/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "src/spack/lib/spack/spack/cmd/buildcache.py", line 755, in buildcache
    args.func(args)
  File "src/spack/lib/spack/spack/cmd/buildcache.py", line 526, in check_binaries
    specs = [get_concrete_spec(args)]
  File "src/spack/lib/spack/spack/cmd/buildcache.py", line 613, in get_concrete_spec
    spec.concretize()
  File "src/spack/lib/spack/spack/spec.py", line 2138, in concretize
    raise spack.error.SpecError(
UnboundLocalError: local variable 'spack' referenced before assignment
```

### Information on your system

Ubuntu 18.04, no special configuration.

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by mc-allen** [comment]
I believe that this can be closed now with the merge of #15663
