### ISSUE TITLE
Installation issue: charmpp

### ISSUE THREAD

**Issue by yellowhat** [spack/spack#15803]
Hi,
I am trying to build charmpp.

### Spack version

```console
$ spack --version
0.14.1-365-7b4354b
```

### Steps to reproduce the issue

```console
$ spack install charmpp backend=mpi +cuda arch=linux-centos7-x86_64 %intel ^openmpi
[+] /apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.5.281/libiconv-1.16-aqfhawrnp7nvv6gyr47sc56yofvpxrj6
[+] /apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.5.281/pkgconf-1.6.3-joa5olkzyjwezwcmr7lzpmno5xvmvkrr
[+] /apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.5.281/xz-5.2.5-n2twqlgbv6ojdkarrcri52r44czcyhfe
[+] /apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.5.281/zlib-1.2.11-kdh3v4z6c36m67oovrg55ba53abj3wev
==> openmpi@4.0.3 : has external module in mpi/openmpi-4.0.3
==> openmpi@4.0.3 : is actually installed in /opt/openmpi-4.0.3
==> openmpi@4.0.3 : already registered in DB
[+] /opt/openmpi-4.0.3
[+] /apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.5.281/libxml2-2.9.9-ttbguawfhdnehyowlggfumed4iln4ex3
[+] /apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.5.281/cuda-10.2.89-nfguegtn4hshimv4qrssjco3tidzmmgu
==> 29085: Installing charmpp
==> Using cached archive: /apps/spack/var/spack/cache/_source-cache/archive/ab/ab96198105daabbb8c8bdf370f87b0523521ce502c656cb6cd5b89f69a2c70a8.tar.gz
==> Staging archive: /mnt/resource/root/spack-stage/spack-stage-charmpp-6.10.1-km6ksrbj2gox5cmsykroqtkb2drx6ro5/charm-6.10.1.tar.gz
==> Created stage in /mnt/resource/root/spack-stage/spack-stage-charmpp-6.10.1-km6ksrbj2gox5cmsykroqtkb2drx6ro5
==> No patches needed for charmpp
==> 29085: charmpp: Building charmpp [Package]
==> 29085: charmpp: Executing phase: 'install'
==> Error: OSError: [Errno 2] No such file or directory: '/apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.5.281/charmpp-6.10.1-km6ksrbj2gox5cmsykroqtkb2drx6ro5/doc'

/apps/spack/var/spack/repos/builtin/packages/charmpp/package.py:249, in install:
        246        try:
        247            os.stat(prefix.doc)
        248        except OSError:
  >>    249            os.remove(prefix.doc)
        250            mkdirp(prefix.doc)

See build log for details:
  /mnt/resource/root/spack-stage/spack-stage-charmpp-6.10.1-km6ksrbj2gox5cmsykroqtkb2drx6ro5/spack-build-out.txt

==> Error: Failed to install charmpp due to ChildError: OSError: [Errno 2] No such file or directory: '/apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.5.281/charmpp-6.10.1-km6ksrbj2gox5cmsykroqtkb2drx6ro5/doc'
/apps/spack/var/spack/repos/builtin/packages/charmpp/package.py:249, in install:
        246        try:
        247            os.stat(prefix.doc)
        248        except OSError:
  >>    249            os.remove(prefix.doc)
        250            mkdirp(prefix.doc)

See build log for details:
  /mnt/resource/root/spack-stage/spack-stage-charmpp-6.10.1-km6ksrbj2gox5cmsykroqtkb2drx6ro5/spack-build-out.txt
Traceback (most recent call last):
  File "/apps/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/apps/spack/lib/spack/spack/installer.py", line 1113, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/apps/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/apps/spack/var/spack/repos/builtin/packages/charmpp/package.py", line 250, in install
    mkdirp(prefix.doc)
OSError: [Errno 2] No such file or directory: '/apps/spack/opt/spack/linux-centos7-x86_64/intel-19.0.5.281/charmpp-6.10.1-km6ksrbj2gox5cmsykroqtkb2drx6ro5/doc'
```

### Platform and user environment
```commandline
$ uname -a 
Linux ip-AC127404 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
CentOS Linux release 7.7.1908 (Core)
``` 

### Additional information

```console
$ spack spec --install-status charmpp backend=mpi +cuda arch=linux-centos7-x86_64 %intel ^openmpi
Input spec
--------------------------------
 -   charmpp%intel backend=mpi +cuda arch=linux-centos7-x86_64
 -       ^openmpi

Concretized
--------------------------------
 -   charmpp@6.10.1%intel@19.0.5.281 backend=mpi build-target=LIBS +cuda~omp~papi+production~pthreads+shared+smp~syncft~tcp~tracing arch=linux-centos7-x86_64
[+]      ^cuda@10.2.89%intel@19.0.5.281 arch=linux-centos7-x86_64
[+]          ^libxml2@2.9.9%intel@19.0.5.281~python arch=linux-centos7-x86_64
[+]              ^libiconv@1.16%intel@19.0.5.281 arch=linux-centos7-x86_64
[+]              ^pkgconf@1.6.3%intel@19.0.5.281 arch=linux-centos7-x86_64
[+]              ^xz@5.2.5%intel@19.0.5.281 arch=linux-centos7-x86_64
[+]              ^zlib@1.2.11%intel@19.0.5.281+optimize+pic+shared arch=linux-centos7-x86_64
[+]      ^openmpi@4.0.3%gcc@9.2.0~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=linux-centos7-x86_64
```

Thanks

**Comment by yellowhat** [comment]
Commenting the line:
```
            os.remove(prefix.doc)
```
make it complete successfully.

**Comment by s-sajid-ali** [comment]
This should be fixed by https://github.com/spack/spack/pull/15666.

**Comment by alalazo** [comment]
@s-sajid-ali Added a line to the description in #15666 so that this issue will be closed automatically when the PR is merged
