### ISSUE TITLE
Environment Install: Failure Corrupts Python

### ISSUE THREAD

**Issue by ax3l** [spack/spack#15934]
Spack Environment: if one adds a couple of packages, one of them `python`, and the `spack install` fails then the environment will be corrupted because spack tries to take the new (not yet installed) python

### Steps to reproduce the issue

```console
spack env create test
spack env activate test
spack add py-h5py
spack add hdf5
spack add mpi
spack add python

spack install # fails on h5py no being HDF5 1.12.0 compatible

spack add hdf5@1.10.6
# uauaauauuaa nothing works anymore
spack --help
# aua aua
```

### Error Message

```console
spack --help
Traceback (most recent call last):
  File "/home/axel/src/spack/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/home/axel/src/spack/lib/spack/spack/main.py", line 704, in main
    ev.activate(env, args.use_env_repo)
  File "/home/axel/src/spack/lib/spack/spack/environment.py", line 163, in activate
    cmds += env.add_default_view_to_shell(shell)
  File "/home/axel/src/spack/lib/spack/spack/environment.py", line 1107, in add_default_view_to_shell
    spec, self.default_view))
  File "/home/axel/src/spack/lib/spack/spack/user_environment.py", line 89, in environment_modifications_for_spec
    spec.package.setup_run_environment(env)
  File "/home/axel/src/spack/var/spack/repos/builtin/packages/python/package.py", line 742, in setup_run_environment
  File "/home/axel/src/spack/var/spack/repos/builtin/packages/python/package.py", line 709, in headers
  File "/home/axel/src/spack/var/spack/repos/builtin/packages/python/package.py", line 599, in get_config_h_filename
  File "/home/axel/src/spack/var/spack/repos/builtin/packages/python/package.py", line 556, in command
RuntimeError: Unable to locate python command in /home/axel/src/spack/var/spack/environments/test/.spack-env/view/bin
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
```
usage: spack debug [-h] SUBCOMMAND ...
spack debug: error: argument SUBCOMMAND: invalid choice: 'report' choose from:
    create-db-tarball
```
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Duplicate of #15884

**Comment by ax3l** [comment]
Thx, did not catch that one!
