### ISSUE TITLE
Python packages installed in a chain reference upstream and cannot be removed

### ISSUE THREAD

**Issue by ilbiondo** [spack/spack#15966]
I installed a python package in my local Spack installation which is chained to our central Spack.

I cannot uninstall it as it needs to access the upstream extension configuration despite having never been activated. 

This looks similar but not identical to https://github.com/spack/spack/issues/13268

### Steps to reproduce the issue

Install a python package in a chain then try and uninstall it 

```
$ spack install scons
==> 131661: Installing scons
..
==> 131661: scons: Successfully installed scons
  Fetch: 0.62s.  Build: 9.47s.  Total: 10.09s.
[+] /dcsrsoft/sandbox/eroche/meleze/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/scons-3.1.2-iqc25yqsqoecf3w2pvvrg752u5zshimv
```

### Error Message

Then

```
$ spack uninstall scons
==> The following packages will be uninstalled:

    -- linux-centos7-skylake_avx512 / gcc@8.3.0 ---------------------
    iqc25yq scons@3.1.2

==> Do you want to proceed? [y/N] y
==> Error: [Errno 13] Permission denied: '/dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/python-3.7.6-3qfa6rjryjmwkj7zdc26ntxkqxq6mkdi/.spack/extensions.yaml'
```

The file in the error message is in the upstream Spack and hasn't been changed recently:

```
$ ll /dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/python-3.7.6-3qfa6rjryjmwkj7zdc26ntxkqxq6mkdi/.spack/extensions.yaml
-rw------- 1 dcsrsoft dcsr-soft-u-g 1550 Mar 31 20:42 /dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/python-3.7.6-3qfa6rjryjmwkj7zdc26ntxkqxq6mkdi/.spack/extensions.yaml
```

With -d the latter part is

```
==> [2020-04-09-10:26:40.615561, 133285] WRITE LOCK (scons): /dcsrsoft/sandbox/eroche/meleze/opt/spack/.spack-db/prefix_lock[2450758027729552401:1] [Releasing] 
==> [2020-04-09-10:26:40.615767, 133285] WRITE LOCK (scons): /dcsrsoft/sandbox/eroche/meleze/opt/spack/.spack-db/prefix_lock[2450758027729552401:1] [Released at 10:26:40.615744] 
Traceback (most recent call last):
  File "/dcsrsoft/sandbox/eroche/meleze/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/main.py", line 763, in main
    return _invoke_command(command, parser, args, unknown)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/main.py", line 488, in _invoke_command
    return_val = command(parser, args)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/cmd/uninstall.py", line 348, in uninstall
    uninstall_specs(args, specs)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/cmd/uninstall.py", line 323, in uninstall_specs
    do_uninstall(env, uninstall_list, args.force)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/cmd/uninstall.py", line 225, in do_uninstall
    item.do_uninstall(force=force)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/package.py", line 1739, in do_uninstall
    Package.uninstall_by_spec(self.spec, force)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/package.py", line 1711, in uninstall_by_spec
    spack.hooks.pre_uninstall(spec)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/hooks/__init__.py", line 59, in __call__
    hook(*args, **kwargs)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/hooks/extensions.py", line 18, in pre_uninstall
    if pkg.is_activated(view):
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/package.py", line 1008, in is_activated
    exts = extensions_layout.extension_map(self.extendee_spec)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/directory_layout.py", line 430, in extension_map
    return self._extension_map(spec).copy()
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/directory_layout.py", line 457, in _extension_map
    with open(path) as ext_file:
PermissionError: [Errno 13] Permission denied: '/dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/python-3.7.6-3qfa6rjryjmwkj7zdc26ntxkqxq6mkdi/.spack/extensions.yaml'
```

### Information on your system

```
$ spack -V
0.13.3-1359-09dfbf9
```

upstreams.yaml

```
upstreams:
  spack-dcsr-meleze:
    install_tree: /dcsrsoft/spack/meleze/v2/opt/spack
    modules:
      lmod: /dcsrsoft/spack/meleze/v2/share/spack/lmod/S6g1-IB
```

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
There's an additional step to reproduce this. The file:
```
/dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/python-3.7.6-3qfa6rjryjmwkj7zdc26ntxkqxq6mkdi/.spack/extensions.yaml
```
must exist already (i.e. a `python` with nothing activated upstream doesn't seem to trigger this)

**Comment by scheibelp** [comment]
Apologies for taking so long to get to this, what are the permissions on 

```
/dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/python-3.7.6-3qfa6rjryjmwkj7zdc26ntxkqxq6mkdi/.spack/extensions.yaml
```

?

I would only expect to see the error where it occurred if this file was not readable by the downstream Spack instance. I assume that if this is the case there would be other problems though (if extensions.yaml is not readable, I assume the downstream instance cannot read other files in the prefix).

**Comment by ilbiondo** [comment]
Hi,
the permissions are:

```
$ ll /dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/python-3.7.6-3qfa6rjryjmwkj7zdc26ntxkqxq6mkdi/.spack/
total 6656
-rw------- 1 dcsrsoft dcsr-soft-u-g    2128 Apr 22 10:49 extensions.yaml
-rw-r--r-- 1 dcsrsoft dcsr-soft-u-g 2558818 Mar 31 14:48 install_manifest.json
drwxr-sr-x 3 dcsrsoft dcsr-soft-u-g    4096 Mar 31 14:47 repos
-rw-r--r-- 1 dcsrsoft dcsr-soft-u-g   18938 Mar 31 14:47 spack-build-env.txt
-rw-r--r-- 1 dcsrsoft dcsr-soft-u-g 2358718 Mar 31 14:47 spack-build-out.txt
-rw-r--r-- 1 dcsrsoft dcsr-soft-u-g   18618 Mar 31 14:43 spec.yaml
-rw-r--r-- 1 dcsrsoft dcsr-soft-u-g    1350 Mar 31 14:47 sysconfig.json
```

So extensions.yaml is `600` unlike the other files 

@alalazo - do you see the same permissions when you reproduce the problem?

**Comment by ilbiondo** [comment]
I think this is more than permissions related - if I set the permissions to `644` then things get even more fun.

```
$ chmod 644 extensions.yaml 
[dcsrsoft@wally-head .spack]$ ll
total 6656
-rw-r--r-- 1 dcsrsoft dcsr-soft-u-g    2128 Apr 22 10:49 extensions.yaml
```

Then try and uninstall something:

```
[eroche@login1 meleze]$ spack uninstall scons
==> The following packages will be uninstalled:

    -- linux-centos7-skylake_avx512 / gcc@8.3.0 ---------------------
    iqc25yq scons@3.1.2

==> Do you want to proceed? [y/N] y
==> Error: Spec 4il43c3uaudxv5msg7g7serjnhvrxgq7 not found in /dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/py-bottleneck-1.2.1-4il43c3uaudxv5msg7g7serjnhvrxgq7
```

With -d we see:

```
==> [2020-06-24-08:56:54.935450, 208479] InvalidExtensionSpecError: Spec 4il43c3uaudxv5msg7g7serjnhvrxgq7 not found in /dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/py-bottleneck-1.2.1-4il43c3uaudxv5msg7g7serjnhvrxgq7
==> [2020-06-24-08:56:54.935508, 208479] Error: Spec 4il43c3uaudxv5msg7g7serjnhvrxgq7 not found in /dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/py-bottleneck-1.2.1-4il43c3uaudxv5msg7g7serjnhvrxgq7
Traceback (most recent call last):
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/main.py", line 761, in main
    return _invoke_command(command, parser, args, unknown)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/main.py", line 489, in _invoke_command
    return_val = command(parser, args)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/cmd/uninstall.py", line 349, in uninstall
    uninstall_specs(args, specs)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/cmd/uninstall.py", line 324, in uninstall_specs
    do_uninstall(env, uninstall_list, args.force)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/cmd/uninstall.py", line 226, in do_uninstall
    item.do_uninstall(force=force)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/package.py", line 1769, in do_uninstall
    Package.uninstall_by_spec(self.spec, force)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/package.py", line 1741, in uninstall_by_spec
    spack.hooks.pre_uninstall(spec)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/hooks/__init__.py", line 59, in __call__
    hook(*args, **kwargs)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/hooks/extensions.py", line 18, in pre_uninstall
    if pkg.is_activated(view):
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/package.py", line 1030, in is_activated
    exts = extensions_layout.extension_map(self.extendee_spec)
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/directory_layout.py", line 431, in extension_map
    return self._extension_map(spec).copy()
  File "/dcsrsoft/sandbox/eroche/meleze/lib/spack/spack/directory_layout.py", line 467, in _extension_map
    "Spec %s not found in %s" % (dag_hash, prefix))
spack.directory_layout.InvalidExtensionSpecError: Spec 4il43c3uaudxv5msg7g7serjnhvrxgq7 not found in /dcsrsoft/spack/meleze/v2/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/py-bottleneck-1.2.1-4il43c3uaudxv5msg7g7serjnhvrxgq7
```

**Comment by scheibelp** [comment]
Thanks for the update! I see where Spack is going wrong. I think https://github.com/spack/spack/pull/17231 will resolve this for you (both the original error, and the one you reported at https://github.com/spack/spack/issues/15966#issuecomment-648632110)

Lower-level details: When validating the extension_map, Spack is using the directory layout rather than the DB (which I think makes sense in avoiding circular dependencies between those modules); if an extension is installed upstream, it won't be found in the downstream directory layout and the validation will fail (i.e. the error message in https://github.com/spack/spack/issues/15966#issuecomment-648632110).
