### ISSUE TITLE
Installation issue: openblas

### ISSUE THREAD

**Issue by LDAmorim** [spack/spack#16028]
Hi,

Sorry to bother you all, in an updated macOS machine (Catalina 10.15.4) and spack installation, I am finding this issue when trying to instal openBLAS.

I am not sure if I am doing something wrong in my installation.
And I think a similar one is described here https://github.com/rust-lang/rust/issues/59674, but I don't understand how to proceed for doing an identical workaround for installing openBLAS.

Do you have any suggestion?
I will open an issue in openBLAS referring to this one, in case the solution can come from their side.

Thank you again for all your help,
Diana

```console
$ spack install openblas
==> Warning: clang@11.0.3-apple cannot build optimized binaries for "skylake". Using best target possible: "x86_64"
==> 60422: Installing openblas
==> Warning: microarchitecture specific optimizations are not supported yet on mixed compiler toolchains [check clang@11.0.3-apple for further details]
==> Fetching https://github.com/xianyi/OpenBLAS/archive/v0.3.9.tar.gz
#################################################################################################################################################################################################################### 100.0%                                                                                                                                -=O=-                               #            #            #         #                 
==> Staging archive: /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-openblas-0.3.9-yp4utei5m5k6bd7e7s327ptob6lv5vdf/v0.3.9.tar.gz
==> Created stage in /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-openblas-0.3.9-yp4utei5m5k6bd7e7s327ptob6lv5vdf
==> No patches needed for openblas
==> 60422: openblas: Building openblas [MakefilePackage]
==> 60422: openblas: Executing phase: 'edit'
==> 60422: openblas: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'CC=/Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang' 'FC=/Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/gfortran' 'MAKE_NB_JOBS=0' 'ARCH=x86_64' 'DYNAMIC_ARCH=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'libs' 'netlib' 'shared'

4 errors found in build log:
     10585    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dgemm_beta_SKYLAKEX -DASMFNAME=_dgemm_beta_SKYLAKEX_ -DNAME=dgemm_beta_SKYLAKEX_ -DCNAME=dgemm_beta_SKYLAKEX -DCHAR_NAME=\"dgemm_beta_SKYLAKEX_\" -DCHAR_CNAME=\"dg
              emm_beta_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DDOUBLE -UCOMPLEX ../kernel/x86_64/dgemm_beta_skylakex.c -
              o dgemm_beta_SKYLAKEX.o
     10586    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrmm_kernel_LN_SKYLAKEX -DASMFNAME=_dtrmm_kernel_LN_SKYLAKEX_ -DNAME=dtrmm_kernel_LN_SKYLAKEX_ -DCNAME=dtrmm_kernel_LN_SKYLAKEX -DCHAR_NAME=\"dtrmm_kernel_LN_SKYL
              AKEX_\" -DCHAR_CNAME=\"dtrmm_kernel_LN_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPL
              EX -DLEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_16x2_skylakex.c -o dtrmm_kernel_LN_SKYLAKEX.o
     10587    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrmm_kernel_LT_SKYLAKEX -DASMFNAME=_dtrmm_kernel_LT_SKYLAKEX_ -DNAME=dtrmm_kernel_LT_SKYLAKEX_ -DCNAME=dtrmm_kernel_LT_SKYLAKEX -DCHAR_NAME=\"dtrmm_kernel_LT_SKYL
              AKEX_\" -DCHAR_CNAME=\"dtrmm_kernel_LT_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPL
              EX -DLEFT -DTRANSA ../kernel/x86_64/dgemm_kernel_16x2_skylakex.c -o dtrmm_kernel_LT_SKYLAKEX.o
     10588    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrmm_kernel_RN_SKYLAKEX -DASMFNAME=_dtrmm_kernel_RN_SKYLAKEX_ -DNAME=dtrmm_kernel_RN_SKYLAKEX_ -DCNAME=dtrmm_kernel_RN_SKYLAKEX -DCHAR_NAME=\"dtrmm_kernel_RN_SKYL
              AKEX_\" -DCHAR_CNAME=\"dtrmm_kernel_RN_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPL
              EX -ULEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_16x2_skylakex.c -o dtrmm_kernel_RN_SKYLAKEX.o
     10589    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrmm_kernel_RT_SKYLAKEX -DASMFNAME=_dtrmm_kernel_RT_SKYLAKEX_ -DNAME=dtrmm_kernel_RT_SKYLAKEX_ -DCNAME=dtrmm_kernel_RT_SKYLAKEX -DCHAR_NAME=\"dtrmm_kernel_RT_SKYL
              AKEX_\" -DCHAR_CNAME=\"dtrmm_kernel_RT_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPL
              EX -ULEFT -DTRANSA ../kernel/x86_64/dgemm_kernel_16x2_skylakex.c -o dtrmm_kernel_RT_SKYLAKEX.o
     10590    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -c -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARAL
              LEL_NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrsm_kernel_LN_SKYLAKEX -DASMFNAME=_dtrsm_kernel_LN_SKYLAKEX_ -DNAME=dtrsm_kernel_LN_SKYLAKEX_ -DCNAME=dtrsm_kernel_LN_SKYLAKEX -DCHAR_NAME=\"dtrsm_kernel_LN_S
              KYLAKEX_\" -DCHAR_CNAME=\"dtrsm_kernel_LN_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -DTRSMKERNEL -UCOMPLEX -DDOUB
              LE -DUPPER -DLN -UCONJ ../kernel/x86_64/../generic/trsm_kernel_LN.c -o dtrsm_kernel_LN_SKYLAKEX.o
  >> 10591    fatal error: error in backend: Cannot emit physreg copy instruction
  >> 10592    clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
     10593    Apple clang version 11.0.3 (clang-1103.0.32.29)
     10594    Target: x86_64-apple-darwin19.4.0
     10595    Thread model: posix
     10596    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
     10597    clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
     10598    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -c -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARAL
              LEL_NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrsm_kernel_LT_SKYLAKEX -DASMFNAME=_dtrsm_kernel_LT_SKYLAKEX_ -DNAME=dtrsm_kernel_LT_SKYLAKEX_ -DCNAME=dtrsm_kernel_LT_SKYLAKEX -DCHAR_NAME=\"dtrsm_kernel_LT_S
              KYLAKEX_\" -DCHAR_CNAME=\"dtrsm_kernel_LT_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -DTRSMKERNEL -UCOMPLEX -DDOUB
              LE -UUPPER -DLT -UCONJ ../kernel/x86_64/../generic/trsm_kernel_LT.c -o dtrsm_kernel_LT_SKYLAKEX.o

     ...

     10607    clang: note: diagnostic msg: Crash backtrace is located in
     10608    clang: note: diagnostic msg: /Users/LDianaAmorim/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
     10609    clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
     10610    clang: note: diagnostic msg:
     10611    
     10612    ********************
  >> 10613    make[1]: *** [dsymv_L_SKYLAKEX.o] Error 70
     10614    make[1]: *** Waiting for unfinished jobs....
  >> 10615    make: *** [libs] Error 1

See build log for details:
  /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-openblas-0.3.9-yp4utei5m5k6bd7e7s327ptob6lv5vdf/spack-build-out.txt

==> Error: Failed to install openblas due to ChildError: ProcessError: Command exited with status 2:
    'make' '-j8' 'CC=/Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang' 'FC=/Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/gfortran' 'MAKE_NB_JOBS=0' 'ARCH=x86_64' 'DYNAMIC_ARCH=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'libs' 'netlib' 'shared'
4 errors found in build log:
     10585    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dgemm_beta_SKYLAKEX -DASMFNAME=_dgemm_beta_SKYLAKEX_ -DNAME=dgemm_beta_SKYLAKEX_ -DCNAME=dgemm_beta_SKYLAKEX -DCHAR_NAME=\"dgemm_beta_SKYLAKEX_\" -DCHAR_CNAME=\"dg
              emm_beta_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DDOUBLE -UCOMPLEX ../kernel/x86_64/dgemm_beta_skylakex.c -
              o dgemm_beta_SKYLAKEX.o
     10586    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrmm_kernel_LN_SKYLAKEX -DASMFNAME=_dtrmm_kernel_LN_SKYLAKEX_ -DNAME=dtrmm_kernel_LN_SKYLAKEX_ -DCNAME=dtrmm_kernel_LN_SKYLAKEX -DCHAR_NAME=\"dtrmm_kernel_LN_SKYL
              AKEX_\" -DCHAR_CNAME=\"dtrmm_kernel_LN_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPL
              EX -DLEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_16x2_skylakex.c -o dtrmm_kernel_LN_SKYLAKEX.o
     10587    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrmm_kernel_LT_SKYLAKEX -DASMFNAME=_dtrmm_kernel_LT_SKYLAKEX_ -DNAME=dtrmm_kernel_LT_SKYLAKEX_ -DCNAME=dtrmm_kernel_LT_SKYLAKEX -DCHAR_NAME=\"dtrmm_kernel_LT_SKYL
              AKEX_\" -DCHAR_CNAME=\"dtrmm_kernel_LT_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPL
              EX -DLEFT -DTRANSA ../kernel/x86_64/dgemm_kernel_16x2_skylakex.c -o dtrmm_kernel_LT_SKYLAKEX.o
     10588    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrmm_kernel_RN_SKYLAKEX -DASMFNAME=_dtrmm_kernel_RN_SKYLAKEX_ -DNAME=dtrmm_kernel_RN_SKYLAKEX_ -DCNAME=dtrmm_kernel_RN_SKYLAKEX -DCHAR_NAME=\"dtrmm_kernel_RN_SKYL
              AKEX_\" -DCHAR_CNAME=\"dtrmm_kernel_RN_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPL
              EX -ULEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_16x2_skylakex.c -o dtrmm_kernel_RN_SKYLAKEX.o
     10589    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL
              _NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrmm_kernel_RT_SKYLAKEX -DASMFNAME=_dtrmm_kernel_RT_SKYLAKEX_ -DNAME=dtrmm_kernel_RT_SKYLAKEX_ -DCNAME=dtrmm_kernel_RT_SKYLAKEX -DCHAR_NAME=\"dtrmm_kernel_RT_SKYL
              AKEX_\" -DCHAR_CNAME=\"dtrmm_kernel_RT_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPL
              EX -ULEFT -DTRANSA ../kernel/x86_64/dgemm_kernel_16x2_skylakex.c -o dtrmm_kernel_RT_SKYLAKEX.o
     10590    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -c -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARAL
              LEL_NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrsm_kernel_LN_SKYLAKEX -DASMFNAME=_dtrsm_kernel_LN_SKYLAKEX_ -DNAME=dtrsm_kernel_LN_SKYLAKEX_ -DCNAME=dtrsm_kernel_LN_SKYLAKEX -DCHAR_NAME=\"dtrsm_kernel_LN_S
              KYLAKEX_\" -DCHAR_CNAME=\"dtrsm_kernel_LN_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -DTRSMKERNEL -UCOMPLEX -DDOUB
              LE -DUPPER -DLN -UCONJ ../kernel/x86_64/../generic/trsm_kernel_LN.c -o dtrsm_kernel_LN_SKYLAKEX.o
  >> 10591    fatal error: error in backend: Cannot emit physreg copy instruction
  >> 10592    clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
     10593    Apple clang version 11.0.3 (clang-1103.0.32.29)
     10594    Target: x86_64-apple-darwin19.4.0
     10595    Thread model: posix
     10596    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
     10597    clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
     10598    /Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang -c -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARAL
              LEL_NUMBER=1 -DVERSION=\"0.3.9\" -DASMNAME=_dtrsm_kernel_LT_SKYLAKEX -DASMFNAME=_dtrsm_kernel_LT_SKYLAKEX_ -DNAME=dtrsm_kernel_LT_SKYLAKEX_ -DCNAME=dtrsm_kernel_LT_SKYLAKEX -DCHAR_NAME=\"dtrsm_kernel_LT_S
              KYLAKEX_\" -DCHAR_CNAME=\"dtrsm_kernel_LT_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -DDOUBLE  -UCOMPLEX -DTRSMKERNEL -UCOMPLEX -DDOUB
              LE -UUPPER -DLT -UCONJ ../kernel/x86_64/../generic/trsm_kernel_LT.c -o dtrsm_kernel_LT_SKYLAKEX.o

     ...

     10607    clang: note: diagnostic msg: Crash backtrace is located in
     10608    clang: note: diagnostic msg: /Users/LDianaAmorim/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
     10609    clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
     10610    clang: note: diagnostic msg:
     10611    
     10612    ********************
  >> 10613    make[1]: *** [dsymv_L_SKYLAKEX.o] Error 70
     10614    make[1]: *** Waiting for unfinished jobs....
  >> 10615    make: *** [libs] Error 1

See build log for details:
  /var/folders/5p/x7ftfty12yndrs3p6ntlk1jc0000gp/T/LDianaAmorim/spack-stage/spack-stage-openblas-0.3.9-yp4utei5m5k6bd7e7s327ptob6lv5vdf/spack-build-out.txt
Traceback (most recent call last):
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/build_environment.py", line 801, in child_process
    return_value = function()
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/installer.py", line 1113, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/package.py", line 108, in phase_wrapper
    phase(spec, prefix)
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/build_systems/makefile.py", line 81, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/build_environment.py", line 131, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/Users/LDianaAmorim/Documents/opt/spack/lib/spack/spack/util/executable.py", line 189, in __call__
    proc.returncode, long_msg)
spack.util.executable.ProcessError: Command exited with status 2:
    'make' '-j8' 'CC=/Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/clang' 'FC=/Users/LDianaAmorim/Documents/opt/spack/lib/spack/env/clang/gfortran' 'MAKE_NB_JOBS=0' 'ARCH=x86_64' 'DYNAMIC_ARCH=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'libs' 'netlib' 'shared'
```

The two build files are:
[spack-build-env.txt](https://github.com/spack/spack/files/4471865/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4471868/spack-build-out.txt)

### Information on your system
```bash
$ spack debug report
* **Spack:** 0.14.1-603-91e22b8ae
* **Python:** 3.7.6
* **Platform:** darwin-catalina-skylake
```

Changed file `~/.spack/darwin/packages.yaml`:
```
packages:
  all:
    providers:
      mpi: [mpich, openmpi]
```
Changed file `~/.spack/darwin/compilers.yaml`:
```
compilers:
- compiler:
    spec: clang@11.0.3-apple
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-xmd4ztofmwdhv56ho452xzv6uz7nbwyn/bin/gfortran
      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-xmd4ztofmwdhv56ho452xzv6uz7nbwyn/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {unset: []}
    extra_rpaths: []
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-xmd4ztofmwdhv56ho452xzv6uz7nbwyn/bin/gcc
      cxx: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-xmd4ztofmwdhv56ho452xzv6uz7nbwyn/bin/g++
      f77: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-xmd4ztofmwdhv56ho452xzv6uz7nbwyn/bin/gfortran
      fc: /Users/LDianaAmorim/Documents/opt/spack/opt/spack/darwin-catalina-x86_64/clang-11.0.3-apple/gcc-9.3.0-xmd4ztofmwdhv56ho452xzv6uz7nbwyn/bin/gfortran
    flags: {}
    operating_system: catalina
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
```
### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x ] I have uploaded the build log and environment files
- [x ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I've also been having a lot of problems with Clang 11.0.3, https://github.com/pytorch/pytorch/issues/35478 seems similar. I reported that bug to Apple but never got a response.

**Comment by LDAmorim** [comment]
Thanks @adamjstewart !
That's unfortunate. But then I'll try to use gcc compiler instead of clang.

**Comment by adamjstewart** [comment]
Just a heads up, the GCC compiler on macOS doesn't work very well...

**Comment by LDAmorim** [comment]
Thanks, I will still try it. Just in case we can make it work well ... enough.
If not then do you suggest that I install a clang compiler with spack?

**Comment by adamjstewart** [comment]
In the PyTorch issue I linked you to, their "solution" is to install a Clang compiler and use that. It's more of a workaround until Apple fixes this, but yeah, that's probably more likely to succeed than using GCC. Personally I'm holding out for the next version of XCode and hoping it will be fixed, as PyTorch is the only package I've encountered so far that breaks. I'm using Intel MKL instead of OpenBLAS, so you can also try that if OpenBLAS is the only issue you've encountered.

**Comment by LDAmorim** [comment]
Thank you!! Your suggestion of using intel-MKL instead was the best solution for me (I just wanted to install openPMD-api), but I needed to follow the instructions in https://github.com/spack/spack/issues/7396.
Now I can use the in-built clang-1103.0.32.29 with intel MKL-2020.1.216 successfully.
