### ISSUE TITLE
 "buildable: False" not always working?

### ISSUE THREAD

**Issue by pramodk** [spack/spack#2150]
`packages.yaml` has following:

``` bash
  cmake:
       modules:
           cmake@2.8.12: cmake/2.8.12
       version: [2.8.12]
       buildable: False
```

And `spack install` for some package gives:

``` bash
==> Installing cmake
==> Warning: There is no checksum on file to fetch cmake@2.8.12 safely.
 Fetch anyway? [y/N] Traceback (most recent call last):
 File "/somepath/spack/bin/spack", line 192, in <module>
   main()
 File "/somepath/spack/bin/spack", line 169, in main
   return_val = command(parser, args)
 File "/somepath/spack/lib/spack/spack/cmd/install.py", line 117, in install
   package.do_install(**kwargs)
 File "/somepath/spack/lib/spack/spack/package.py", line 1183, in do_install
   dirty=dirty)
 File "/somepath/spack/lib/spack/spack/package.py", line 1268, in do_install
   spack.build_environment.fork(self, build_process, dirty=dirty)
 File "/somepath/spack/lib/spack/spack/build_environment.py", line 550, in fork
   raise exception
EOFError: EOF when reading a line
```

I change that `modules` to `paths` as:

``` bash
   cmake:
       paths:
           cmake@2.8.12:/somepathotherpath/cmake/cmake-2.8.12/install
       version: [2.8.12]
       buildable: False
```

And then it was fine. Anything that I am obviously missing?
I am using spack more for development workflow i.e. on multiple systems I am setting spack and only using `external` packages. During last two days I have seen similar issue multiple times (like #2130).

**Comment by citibeth** [comment]
When I saw the following line:

> cmake@2.8.12: cmake/2.8.12

I thought it looked wrong, because the path to cmake is not absolute.  Not sure what that is supposed to mean.  Your problem was fixed by putting in an absolute path there.  Is there any issue beyond that?

**Comment by pramodk** [comment]
> I thought it looked wrong, because the path to cmake is not absolute. Not sure what that is supposed to mean.

@citibeth : thats the name of module (hence I have put that under `modules`).
In the second case I put absolute path under `paths`. So its switching from `modules` to `paths`.

**Comment by citibeth** [comment]
Oh I see... Not sure this is the best design for how that file should work.  But anyway... I agree, looks like a bug to me when specifying packages as existing in external modules.

**Comment by BarrySmith** [comment]
I am seeing a similar problem, when I define 

```
    netlib-lapack:
        paths:
            netlib-lapack@system: /usr
        version: [system]
        buildable: False        
```

for some packages, for example mumps it works fine:

```
$ spack install mumps
==> Installing mumps
==> netlib-lapack is externally installed in /usr
```

but for PETSc 

```
$ spack install petsc@develop
==> Installing petsc
==> hypre is already installed in /Users/barrysmith/Src/spack/opt/spack/darwin-sierra-x86_64/gcc-6.2.0/hypre-2.11.1-lwyprzrygz7lk3svfaj4ghapsh33iwms
==> superlu-dist is already installed in /Users/barrysmith/Src/spack/opt/spack/darwin-sierra-x86_64/gcc-6.2.0/superlu-dist-5.1.1-kkotlwkgzwdivvu5hh46qfef5632s4ih
==> hdf5 is already installed in /Users/barrysmith/Src/spack/opt/spack/darwin-sierra-x86_64/gcc-6.2.0/hdf5-1.10.0-patch1-wrytririodtxehi5tzdshwrhhdw7yqzu
==> python is externally installed in /usr/local/bin
==> metis is already installed in /Users/barrysmith/Src/spack/opt/spack/darwin-sierra-x86_64/gcc-6.2.0/metis-5.1.0-vormfy2xg4yyhg5goi2ksek5f6czlcb7
==> netlib-scalapack is already installed in /Users/barrysmith/Src/spack/opt/spack/darwin-sierra-x86_64/gcc-6.2.0/netlib-scalapack-2.0.2-jkomz3mtpkoqslcw3tnv4hbbq7dgifqq
==> Installing netlib-lapack
==> Warning: There is no checksum on file to fetch netlib-lapack@system safely.
  Fetch anyway? [y/N] Traceback (most recent call last):
  File "./spack", line 202, in <module>
    main()
  File "./spack", line 179, in main
    return_val = command(parser, args)
  File "/Users/barrysmith/Src/spack/lib/spack/spack/cmd/install.py", line 340, in install
    package.do_install(**kwargs)
  File "/Users/barrysmith/Src/spack/lib/spack/spack/package.py", line 1184, in do_install
    **kwargs
  File "/Users/barrysmith/Src/spack/lib/spack/spack/package.py", line 1270, in do_install
    spack.build_environment.fork(self, build_process, dirty=dirty)
  File "/Users/barrysmith/Src/spack/lib/spack/spack/build_environment.py", line 547, in fork
    raise exception
EOFError: EOF when reading a line
```

It thinks it needs to install netlib-lapack. For hypre it works, for trilinos it tries to install netlib-lapack. All of the packages have 

```
    depends_on("blas")
    depends_on("lapack")
```

In the index.yaml database it lists

```
idx5umkuq46ksoqdh2vnkbwffbstgyzk:
      explicit: false
      installed: false
      path: None
      ref_count: 7
      spec:
        netlib-lapack:
          version: system
          compiler:
            name: gcc
            version: 6.2.0
          namespace: builtin
          parameters:
            debug: false
            external-blas: false
            lapacke: true
            shared: true
            cflags: []
            cppflags: []
            cxxflags: []
            fflags: []
            ldflags: []
            ldlibs: []
          arch:
            platform: darwin
            platform_os: sierra
            target: x86_64
```

Thoughts on how to debug this? Is it possible sometimes it doesn't check the database but looks for the installed directory in opt/spack?

**Comment by pramodk** [comment]
I am also seeing this behaviour quite often with many `external` packages : `works -> doesn't work -> works -> works -> doesn't work....`. If someone could provide some hints to debug, would be happy to do!

**Comment by TomasPuverle** [comment]
Pretty much the same as my issue: #2473

**Comment by alalazo** [comment]
There are unit tests now to verify this is working with the new concretizer.
