### ISSUE TITLE
`spack setup` fails to finish installation or generate module

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2319]
See below...

```
$ spack -d setup pism@dev
...
==> Generating spconfig.py [pism@dev%gcc@4.9.3+cxx11~docs~extra+icebin~parallel-hdf5~parallel-netcdf3~parallel-netcdf4+proj~python+shared arch=linux-centos7-x86_64-74lsgxk]
==> '/home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/python-3.5.2-fsiwqdnbv37srf4h67uuhxrffixlkwbn/bin/python3' '-c' 'import sys; print(sys.prefix)'
==> READ LOCK: /home2/rpfische/spack4/opt/spack/.spack-db/prefix_lock[9190599643867472633:1] [Acquiring]
==> READ LOCK: /home2/rpfische/spack4/opt/spack/.spack-db/prefix_lock[9190599643867472633:1] [Released]
==> WRITE LOCK: /home2/rpfische/spack4/opt/spack/.spack-db/lock[0:0] [Released]
==> Error: Install prefix exists but contains no spec.yaml:
  /home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/pism-dev-74lsgxkldlc7fqpg4slrhiawnh2tca24
Traceback (most recent call last):
  File "/home2/rpfische/spack4/bin/spack", line 180, in main
    return_val = command(parser, args)
  File "/home2/rpfische/spack4/lib/spack/spack/cmd/setup.py", line 191, in setup
    install.install(parser, inst_args)
  File "/home2/rpfische/spack4/lib/spack/spack/cmd/install.py", line 342, in install
    package.do_install(**kwargs)
  File "/home2/rpfische/spack4/lib/spack/spack/package.py", line 1158, in do_install
    if layout.check_installed(self.spec):
  File "/home2/rpfische/spack4/lib/spack/spack/directory_layout.py", line 265, in check_installed
    "  " + path)
spack.directory_layout.InconsistentInstallDirectoryError: Install prefix exists but contains no spec.yaml:
      /home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/pism-dev-74lsgxkldlc7fqpg4slrhiawnh2tca24
```

**Comment by citibeth** [comment]
OK I've tracked this down a bit.  It looks like `build_environment.setup_package()` writes into the prefix:
```
def write_spconfig(package):
    # Set-up the environment
    spack.build_environment.setup_package(package)
```
Somewhere in there, it is generating empty Python install directories.
```
$ ls -ld `find /home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/pism-dev-74lsgxkldlc7fqpg4slrhiawnh2tca24 -name '*'`
drwxr-xr-x. 3 rpfische rpfische 4096 Nov 12 12:35 /home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/pism-dev-74lsgxkldlc7fqpg4slrhiawnh2tca24
drwxr-xr-x. 3 rpfische rpfische 4096 Nov 12 12:35 /home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/pism-dev-74lsgxkldlc7fqpg4slrhiawnh2tca24/lib
drwxr-xr-x. 3 rpfische rpfische 4096 Nov 12 12:35 /home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/pism-dev-74lsgxkldlc7fqpg4slrhiawnh2tca24/lib/python3.5
drwxr-xr-x. 2 rpfische rpfische 4096 Nov 12 12:35 /home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/pism-dev-74lsgxkldlc7fqpg4slrhiawnh2tca24/lib/python3.5/site-packages
```
It seems this is somewhat wrong.  I don't think that setting up the build environment should entail creating empty directories in the install location.  I also don't have a good idea where this might be happening.

For now, I'll see if I can fix `directory_layout.check_installed()`.

**Comment by citibeth** [comment]
@adamjstewart 

This continues to be a problem, even after #2317.  It is not a problem on ALL packages, just some.  For example, on Python extensions.  The problem is that a skeleton Python tree gets generated, and then that is confusing `directory_layout`.

Any ideas on how to  fix this?  See below...

```
spack setup ibmisc@develop+everytrace+proj+blitz+netcdf+boost+udunits2+python
...
==> Error: Install prefix exists but contains no spec.yaml:
  /home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/ibmisc-develop-lp74neu2nzptnicozbzfamikzmewn5rm

$ls -lR /home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/ibmisc-develop-lp74neu2nzptnicozbzfamikzmewn5rm
/home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/ibmisc-develop-lp74neu2nzptnicozbzfamikzmewn5rm:
total 4
drwxr-xr-x. 3 rpfische rpfische 4096 Dec 21 15:21 lib

/home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/ibmisc-develop-lp74neu2nzptnicozbzfamikzmewn5rm/lib:
total 4
drwxr-xr-x. 3 rpfische rpfische 4096 Dec 21 15:21 python3.5

/home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/ibmisc-develop-lp74neu2nzptnicozbzfamikzmewn5rm/lib/python3.5:
total 4
drwxr-xr-x. 2 rpfische rpfische 4096 Dec 21 15:21 site-packages

/home2/rpfische/spack4/opt/spack/linux-centos7-x86_64/gcc-4.9.3/ibmisc-develop-lp74neu2nzptnicozbzfamikzmewn5rm/lib/python3.5/site-packages:
```

**Comment by adamjstewart** [comment]
Hmm, sorry, I've never used `spack setup` before, so I'm not sure how it even works. @alalazo?

**Comment by citibeth** [comment]
The general gist of the problem is as follows... `spack setup` goes through an entire install process, except it does not actually build or install.  But it still generates the module file.  It is presumed that the user will later do the installation for real by running `mkdir build; cd build; ../spconfig.py ..; make install`
