### ISSUE TITLE
Spack Crashes with Mystery Error

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2354]
The following was caused by a bad/garbage `package.py` file.  This should really have a better error message.

Anyone know what is going wrong?  `spack reindex` did not fix.

```
$ spack install modele-control
Traceback (most recent call last):
  File "/home2/rpfische/spack4/bin/spack", line 203, in <module>
    main()
  File "/home2/rpfische/spack4/bin/spack", line 180, in main
    return_val = command(parser, args)
  File "/home2/rpfische/spack4/lib/spack/spack/cmd/install.py", line 313, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/home2/rpfische/spack4/lib/spack/spack/cmd/__init__.py", line 108, in parse_specs
    spec.concretize()  # implies normalize
  File "/home2/rpfische/spack4/lib/spack/spack/spec.py", line 1330, in concretize
    self._expand_virtual_packages(),
  File "/home2/rpfische/spack4/lib/spack/spack/spec.py", line 1247, in _expand_virtual_packages
    spec)
  File "/home2/rpfische/spack4/lib/spack/spack/concretize.py", line 122, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/home2/rpfische/spack4/lib/spack/spack/concretize.py", line 62, in _valid_virtuals_and_externals
    providers = spack.repo.providers_for(spec)
  File "/home2/rpfische/spack4/lib/spack/spack/repository.py", line 75, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home2/rpfische/spack4/lib/spack/spack/repository.py", line 240, in providers_for
    providers = self.provider_index.providers_for(vpkg_spec)
  File "/home2/rpfische/spack4/lib/spack/spack/repository.py", line 234, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/home2/rpfische/spack4/lib/spack/spack/repository.py", line 645, in provider_index
    self._update_provider_index()
  File "/home2/rpfische/spack4/lib/spack/spack/repository.py", line 639, in _update_provider_index
    self._provider_index.to_yaml(new)
  File "/home2/rpfische/spack4/lib/spack/llnl/util/lock.py", line 312, in __exit__
    if self._as.__exit__(type, value, traceback):
  File "/home2/rpfische/spack4/lib/spack/spack/file_cache.py", line 152, in __exit__
    raise value
AttributeError
```

**Comment by alalazo** [comment]
```console
$ spack list modele-control
==> 0 packages.
```
