### ISSUE TITLE
Spack Crashes during Concretization

### ISSUE THREAD

**Issue by citibeth** [spack/spack#2355]
```
Concretized
--------------------------------
Traceback (most recent call last):
  File "/home2/rpfische/spack4/bin/spack", line 203, in <module>
    main()
  File "/home2/rpfische/spack4/bin/spack", line 180, in main
    return_val = command(parser, args)
  File "/home2/rpfische/spack4/lib/spack/spack/cmd/spec.py", line 79, in spec
    print spec.tree(**kwargs)
  File "/home2/rpfische/spack4/lib/spack/spack/spec.py", line 2433, in tree
    status = node._install_status()
  File "/home2/rpfische/spack4/lib/spack/spack/spec.py", line 2404, in _install_status
    record = spack.store.db.get_record(self)
  File "/home2/rpfische/spack4/lib/spack/spack/database.py", line 80, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/home2/rpfische/spack4/lib/spack/spack/database.py", line 530, in get_record
    key = self._get_matching_spec_key(spec, **kwargs)
  File "/home2/rpfische/spack4/lib/spack/spack/database.py", line 521, in _get_matching_spec_key
    match = self.query_one(spec, **kwargs)
  File "/home2/rpfische/spack4/lib/spack/spack/database.py", line 656, in query_one
    assert len(concrete_specs) <= 1
AssertionError
```

**Comment by citibeth** [comment]
@tgamblin 
It crashed on the command `spack spec -lI env-icebin-scripts`.  The file `env-icebin-scripts/package.py` is below.  Could putting version numbers and variants in the `depends_on()` have anything to do with it?

```
from spack import *


class EnvIcebinScripts(Package):

    """Environment used to run IceBin from Python scripts, to prepare
    ModelE input files."""

    homepage = ""

    version('1.0')

    # Regridding...
    depends_on('icebin@0.1.7~everytrace+gridgen+python')
    # Force icebin dependencies to particular versions
    depends_on('ibmisc@0.1.3')
    depends_on('py-giss@0.1.3')

    # Needed for ModelE input file generation
    depends_on('modele-control@0.1.1')

    # Utilities
    depends_on('emacs')
    depends_on('git')

    def url_for_version(self, version):
        return 'https://github.com/citibeth/dummy/tarball/v1.0'

    def install(self, spec, prefix):
        with open(os.path.join(spec.prefix, 'dummy.txt'), 'w') as out:
            out.write('This is a bundle\n')
```

**Comment by pramodk** [comment]
I think this is related/similar to #2123.

**Comment by alalazo** [comment]
Closing, as the issue involves packages that are not in the built-in repo.
