### ISSUE TITLE
spack lock problem

### ISSUE THREAD

**Issue by ashkan2200** [spack/spack#2383]
Hi guys,

I use spack on a cluster and everytime there is a network drop the file locks become corrupted and I can't install anything. Is there a way to reset all the locks on files? How does one get rid of this issue.

Here is the newest exception I get in spack

    p4est is already installed in /pica/h1/alid/spack/opt/spack/linux-scientific6-x86_64/gcc-6.2.0/p4est-1.1-suhfwcxtftbbi74aji3wnugtkiia2b7o
    Traceback (most recent call last):
      File "/home/alid/spack/bin/spack", line 203, in <module>
        main()
      File "/home/alid/spack/bin/spack", line 180, in main
        return_val = command(parser, args)
      File "/pica/h1/alid/spack/lib/spack/spack/cmd/install.py", line 342, in install
        package.do_install(**kwargs)
      File "/pica/h1/alid/spack/lib/spack/spack/package.py", line 1190, in do_install
        **kwargs
      File "/pica/h1/alid/spack/lib/spack/spack/package.py", line 1158, in do_install
        with self._prefix_read_lock():
      File "/usr/lib64/python2.6/contextlib.py", line 16, in __enter__
        return self.gen.next()
      File "/pica/h1/alid/spack/lib/spack/spack/package.py", line 1102, in _prefix_read_lock
        self.prefix_lock.release_read()
      File "/pica/h1/alid/spack/lib/spack/llnl/util/lock.py", line 238, in release_read
        assert self._reads > 0
    AssertionError

Best,
Ashkan

**Comment by XL64** [comment]
I have similar issue but on the WRITE_LOCK part during install...

**Comment by tgamblin** [comment]
Does this still happen for you?

**Comment by tgamblin** [comment]
Closing -- please reopen if this is still an issue.

**Comment by citibeth** [comment]
I had a similar issue today.  I was debugging the setup code, which involved trying different things in the install process.  That code development / testing must have gotten things in a bad state, and I couldn't get out of it.   I finally solved the problem with:
```
rm `find . -name '*lock'`
```

**Comment by alalazo** [comment]
Closing again since we had no other report (as far as I know) in more than a year.
