### ISSUE TITLE
Concretization broken for version ranges

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#2793]
```
$ spack spec py-configparser
...
py-configparser@3.5.0%gcc@6.1.0 arch=linux-centos6-x86_64
    ^py-ordereddict@1.1%gcc@6.1.0 arch=linux-centos6-x86_64
        ^python@2.6.999%gcc@6.1.0+tk~ucs4 arch=linux-centos6-x86_64
            ^bzip2@1.0.6%gcc@6.1.0 arch=linux-centos6-x86_64
            ^ncurses@6.0%gcc@6.1.0 arch=linux-centos6-x86_64
            ^openssl@1.0.2j%gcc@6.1.0 arch=linux-centos6-x86_64
                ^zlib@1.2.10%gcc@6.1.0+pic arch=linux-centos6-x86_64
            ^readline@6.3%gcc@6.1.0 arch=linux-centos6-x86_64
            ^sqlite@3.8.5%gcc@6.1.0 arch=linux-centos6-x86_64
            ^tcl@8.6.5%gcc@6.1.0 arch=linux-centos6-x86_64
            ^tk@8.6.5%gcc@6.1.0~X arch=linux-centos6-x86_64
    ^py-setuptools@25.2.0%gcc@6.1.0 arch=linux-centos6-x86_64
```
Why is it choosing `python@2.6.999` here? I see two places where we went wrong.

First of all, `py-configparser` doesn't depend on `py-ordereddict` _unless_ we are building with Python 2.6. Spack should still default to the latest version of Python 2.7.

Second, the following doesn't fare any better:
```
$ spack spec py-ordereddict
...
py-ordereddict@1.1%gcc@6.1.0 arch=linux-centos6-x86_64
    ^python@2.6.999%gcc@6.1.0+tk~ucs4 arch=linux-centos6-x86_64
        ^bzip2@1.0.6%gcc@6.1.0 arch=linux-centos6-x86_64
        ^ncurses@6.0%gcc@6.1.0 arch=linux-centos6-x86_64
        ^openssl@1.0.2j%gcc@6.1.0 arch=linux-centos6-x86_64
            ^zlib@1.2.10%gcc@6.1.0+pic arch=linux-centos6-x86_64
        ^readline@6.3%gcc@6.1.0 arch=linux-centos6-x86_64
        ^sqlite@3.8.5%gcc@6.1.0 arch=linux-centos6-x86_64
        ^tcl@8.6.5%gcc@6.1.0 arch=linux-centos6-x86_64
        ^tk@8.6.5%gcc@6.1.0~X arch=linux-centos6-x86_64
```
This is also choosing `python@2.6.999` even though it should be choosing the latest version of Python 2.6 in Spack.

**Comment by adamjstewart** [comment]
@tgamblin These packages have changed a bit, but the original problem is that something like:
```python
depends_on('py-ordereddict', when='^python@2.6:2.6.999', type=('build', 'run'))
```
doesn't work. Now that I think about it, didn't we recently discover that:
```python
if '^python@2.6:2.6.999' in spec:
```
and
```python
if spec.satisfies('^python@2.6:2.6.999'):
```
don't work either? It's probably the same problem.

**Comment by alalazo** [comment]
There's an high chance that this issue stems from #4135

**Comment by healther** [comment]
FYI: I uncommented most of these lines while trying to build our dependency stack with python 3 on an older `spack`. It does seem that explicitly setting the python version prevents this bug from being triggered.

On the current HEAD:
```
$ git diff
diff --git a/var/spack/repos/builtin/packages/py-configparser/package.py b/var/spack/repos/builtin/packages/py-configparser/package.py
index 2d463b3..37706ab 100644
--- a/var/spack/repos/builtin/packages/py-configparser/package.py
+++ b/var/spack/repos/builtin/packages/py-configparser/package.py
@@ -38,4 +38,4 @@ class PyConfigparser(PythonPackage):
 
     # This dependency breaks concretization
     # See https://github.com/spack/spack/issues/2793
-    # depends_on('py-ordereddict', when='^python@:2.6', type=('build', 'run'))
+    depends_on('py-ordereddict', when='^python@:2.6', type=('build', 'run'))
```

```
$ spack spec py-configparser
Input spec
--------------------------------
py-configparser

Concretized
--------------------------------
==> Error: py-configparser does not depend on py-ordereddict
```

But it works for
```
wv385@hel:~/spack_failure/spack4$ spack spec py-configparser ^python@2.7.14
Input spec
--------------------------------
py-configparser
    ^python@2.7.14

Concretized
--------------------------------
py-configparser@3.5.0%gcc@4.9.2 arch=linux-debian8-x86_64 
    ^py-setuptools@35.0.2%gcc@4.9.2 arch=linux-debian8-x86_64 
        ^py-appdirs@1.4.3%gcc@4.9.2 arch=linux-debian8-x86_64 
            ^python@2.7.14%gcc@4.9.2 patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+shared~tk~ucs4 arch=linux-debian8-x86_64 
                ^bzip2@1.0.6%gcc@4.9.2+shared arch=linux-debian8-x86_64 
                ^ncurses@6.0%gcc@4.9.2 patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=linux-debian8-x86_64 
                    ^pkgconf@1.3.10%gcc@4.9.2 arch=linux-debian8-x86_64 
                ^openssl@1.0.2n%gcc@4.9.2 arch=linux-debian8-x86_64 
                    ^zlib@1.2.11%gcc@4.9.2+optimize+pic+shared arch=linux-debian8-x86_64 
                ^readline@7.0%gcc@4.9.2 arch=linux-debian8-x86_64 
                ^sqlite@3.21.0%gcc@4.9.2 patches=5bbcba091045e547eb550e6e9b9372009c41be0a9de8a5c030d03361c11ff939 arch=linux-debian8-x86_64 
        ^py-packaging@16.8%gcc@4.9.2 arch=linux-debian8-x86_64 
            ^py-pyparsing@2.2.0%gcc@4.9.2 arch=linux-debian8-x86_64 
            ^py-six@1.10.0%gcc@4.9.2 arch=linux-debian8-x86_64 
```

It also works with `^python@3.6.3`

**Comment by healther** [comment]
Running this in debug mode yields the following:
```
$ spack -d spec py-configparser
Input spec
--------------------------------
py-configparser

Concretized
--------------------------------
==> Reading config file /wang/users/wv385/cluster_home/spack_failure/spack4/etc/spack/defaults/packages.yaml
==> READ LOCK: /wang/users/wv385/cluster_home/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /wang/users/wv385/cluster_home/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /wang/users/wv385/cluster_home/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> Reading config file /wang/users/wv385/cluster_home/.spack/linux/compilers.yaml
==> Error: py-configparser does not depend on py-ordereddict
Traceback (most recent call last):
  File "/wang/users/wv385/cluster_home/spack_failure/spack4/lib/spack/spack/main.py", line 439, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/wang/users/wv385/cluster_home/spack_failure/spack4/lib/spack/spack/main.py", line 355, in _invoke_spack_command
    return_val = command(parser, args)
  File "/wang/users/wv385/cluster_home/spack_failure/spack4/lib/spack/spack/cmd/spec.py", line 85, in spec
    spec.concretize()
  File "/wang/users/wv385/cluster_home/spack_failure/spack4/lib/spack/spack/spec.py", line 1794, in concretize
    changes = (self.normalize(force),
  File "/wang/users/wv385/cluster_home/spack_failure/spack4/lib/spack/spack/spec.py", line 2198, in normalize
    self.name + " does not depend on " + comma_or(extra))
spack.spec.InvalidDependencyError: py-configparser does not depend on py-ordereddict
```

It seems to me that 
`spec_deps = self.flat_dependencies(copy=False)` in https://github.com/spack/spack/blob/develop/lib/spack/spack/spec.py#L2180 returns all possible dependencies. Maybe I'll find some time later today to look at it, but I'm not sure if I understand enough of what is happening there

**Comment by jkelling** [comment]
This bug is referenced in py-ipython/package.py:24 . Yesterday, I could not compile py-ipython with python 3.5.2 because of a hard dependency on backports packages. I tried uncommenting the workaround for this bug and the current develp HEAD was able to concretize and install it.

Maybe this is no longer an issue and can be closed.

```diff
--- a/var/spack/repos/builtin/packages/py-ipython/package.py
+++ b/var/spack/repos/builtin/packages/py-ipython/package.py
@@ -22,10 +22,10 @@ class PyIpython(PythonPackage):
 
     # These dependencies breaks concretization
     # See https://github.com/spack/spack/issues/2793
-    # depends_on('py-backports-shutil-get-terminal-size', type=('build', 'run'), when="^python@:3.2")  # noqa
-    # depends_on('py-pathlib2', type=('build', 'run'), when="^python@:3.3")
-    depends_on('py-backports-shutil-get-terminal-size', type=('build', 'run'))
-    depends_on('py-pathlib2',                   type=('build', 'run'))
+    depends_on('py-backports-shutil-get-terminal-size', type=('build', 'run'), when="^python@:3.2")  # noqa
+    depends_on('py-pathlib2', type=('build', 'run'), when="^python@:3.3")
+    # depends_on('py-backports-shutil-get-terminal-size', type=('build', 'run'))
+    # depends_on('py-pathlib2',                   type=('build', 'run'))
 
     depends_on('py-pygments',                   type=('build', 'run'))
     depends_on('py-pickleshare',                type=('build', 'run'))

```

**Comment by adamjstewart** [comment]
You're right, this seems to be working now. I'll submit a PR to uncomment all the dependencies.
