### ISSUE TITLE
paraview: openmpi spec not constructed properly during install?

### ISSUE THREAD

**Issue by alalazo** [spack/spack#3581]
This problem has been reported first in #3537 by @olesenm . The following command:
```console
$ spack install --only=dependencies paraview
```
results in the error:
```console
...
==> jpeg is already installed in /home/mculpo/PycharmProjects/spack/opt/spack/linux-ubuntu14-x86_64/gcc-4.8/jpeg-9b-ltd7bgtodplrr66etkl2eqa7434ppip5
==> Installing openmpi
==> Using cached archive: /home/mculpo/PycharmProjects/spack/var/spack/cache/openmpi/openmpi-2.1.0.tar.bz2
==> Staging archive: /home/mculpo/PycharmProjects/spack/var/spack/stage/openmpi-2.1.0-6i2dsekkgbsvfdx24vtgwcsflhi725px/openmpi-2.1.0.tar.bz2
==> Created stage in /home/mculpo/PycharmProjects/spack/var/spack/stage/openmpi-2.1.0-6i2dsekkgbsvfdx24vtgwcsflhi725px
==> Ran patch() for openmpi
==> Building openmpi [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Error: KeyError: 'No spec with name hwloc in openmpi@2.1.0%gcc@4.8~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=linux-ubuntu14-x86_64'
/home/mculpo/PycharmProjects/spack/var/spack/repos/builtin/packages/openmpi/package.py:223, in configure_args:
     176      def configure_args(self):
     177          spec = self.spec
     178  
     179          config_args = [
     180              '--enable-shared',
     181              '--enable-static',
     182              '--enable-mpi-cxx',
     183              # Schedulers
     184              '--with-tm' if '+tm' in spec else '--without-tm',
     185              '--with-slurm' if '+slurm' in spec else '--without-slurm',
     186              # Fabrics
     187              '--with-psm' if '+psm' in spec else '--without-psm',
     188          ]
     189  
     190          # Intel PSM2 support
     191          if spec.satisfies('@1.10:'):
     192              if '+psm2' in spec:
     193                  config_args.append('--with-psm2')
     194              else:
     195                  config_args.append('--without-psm2')
     196  
     197          # PMI support
     198          if spec.satisfies('@1.5.5:'):
     199              if '+pmi' in spec:
     200                  config_args.append('--with-pmi')
     201              else:
     202                  config_args.append('--without-pmi')
     203  
     204          # Mellanox Messaging support
     205          if spec.satisfies('@1.5.4:'):
     206              if '+mxm' in spec:
     207                  config_args.append('--with-mxm')
     208              else:
     209                  config_args.append('--without-mxm')
     210  
     211          # OpenFabrics verbs support
     212          if '+verbs' in spec:
     213              path = _verbs_dir()
     214              if path is not None and path not in ('/usr', '/usr/local'):
     215                  config_args.append('--with-{0}={1}'.format(self.verbs, path))
     216              else:
     217                  config_args.append('--with-{0}'.format(self.verbs))
     218          else:
     219              config_args.append('--without-{0}'.format(self.verbs))
     220  
     221          # Hwloc support
     222          if spec.satisfies('@1.5.2:'):
  >> 223              config_args.append('--with-hwloc={0}'.format(spec['hwloc'].prefix))
     224  
     225          # Java support
     226          if spec.satisfies('@1.7.4:'):
     227              if '+java' in spec:
     228                  config_args.extend([
     229                      '--enable-java',
     230                      '--enable-mpi-java',
     231                      '--with-jdk-dir={0}'.format(spec['jdk'].prefix)
     232                  ])
     233              else:
     234                  config_args.extend([
     235                      '--disable-java',
     236                      '--disable-mpi-java'
     237                  ])
     238  
     239          # SQLite3 support
     240          if spec.satisfies('@1.7.3:1.999'):
     241              if '+sqlite3' in spec:
     242                  config_args.append('--with-sqlite3')
     243              else:
     244                  config_args.append('--without-sqlite3')
     245  
     246          # VampirTrace support
     247          if spec.satisfies('@1.3:1.999'):
     248              if '+vt' not in spec:
     249                  config_args.append('--enable-contrib-no-build=vt')
     250  
     251          # Multithreading support
     252          if spec.satisfies('@1.5.4:'):
     253              if '+thread_multiple' in spec:
     254                  config_args.append('--enable-mpi-thread-multiple')
     255              else:
     256                  config_args.append('--disable-mpi-thread-multiple')
     257  
     258          return config_args

See build log for details:
  /tmp/pytest-of-mculpo/pytest-0/test_keep_exceptions1/tmp/spack-stage/spack-stage-G8U6yt/openmpi-2.1.0/spack-build.out
```

**Comment by pramodskumbhar** [comment]
@alalazo : Having the same problem with latest develop.  I was looking at deps and tried to print some info:

```
304         print spec.to_yaml()
305         print spec
306         if spec.satisfies('@1.5.2:'):
307             config_args.append('--with-hwloc={0}'.format(spec['hwloc'].prefix))
```

And this gives:

```
$ spack -d install -v openmpi
==> '/usr/bin/ibv_devices'
==> Reading config file /gpfs/homeb/pcp0/pcp0043/soft/spack/etc/spack/defaults/packages.yaml
==> Reading config file /gpfs/homeb/pcp0/pcp0043/.spack/packages.yaml
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Released]
==> Reading config file /gpfs/homeb/pcp0/pcp0043/.spack/linux/compilers.yaml
==> '/gpfs/software/opt/lmod/lmod/libexec/lmod' 'python' 'list'
==> '/gpfs/software/opt/lmod/lmod/libexec/lmod' 'python' 'show' 'openmpi/2.0.2-xl'
==> openmpi@2.0.2 : has external module in openmpi/2.0.2-xl
==> openmpi@2.0.2 : is actually installed in /gpfs/software/opt/openmpi-2.0.2-xl
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> openmpi@2.0.2 : generating module file
==> SKIP: shebang filtering [external package]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> 	WRITE: openmpi@2.0.2%gcc@4.8.5~cuda fabrics=verbs ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-ppc64le /3kaee72 [/gpfs/homeb/pcp0/pcp0043/soft/spack/share/spack/modules/linux-centos7-ppc64le/openmpi-2.0.2-gcc-4.8.5-3kaee72]
==> '/usr/bin/ibv_devices'
spec:
- openmpi:
    version: 2.0.2
    arch:
      platform: linux
      platform_os: centos7
      target: ppc64le
    compiler:
      name: gcc
      version: 4.8.5
    namespace: builtin
    parameters:
      cuda: false
      fabrics:
      - verbs
      java: false
      schedulers:
      - ''
      sqlite3: false
      thread_multiple: false
      vt: true
      cflags: []
      cppflags: []
      cxxflags: []
      fflags: []
      ldflags: []
      ldlibs: []
    external:
      module: true
      path: /gpfs/software/opt/openmpi-2.0.2-xl
    hash: 3kaee72w5i2n7vufoj5qkk4lywwxzjfs

openmpi@2.0.2%gcc@4.8.5~cuda fabrics=verbs ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-ppc64le
Traceback (most recent call last):
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/main.py", line 548, in main
    return _main(command, parser, args, unknown)
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/main.py", line 440, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/main.py", line 356, in _invoke_spack_command
    return_val = command(parser, args)
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/cmd/install.py", line 379, in install
    package.do_install(**kwargs)
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/package.py", line 1252, in do_install
    return self._process_external_package(explicit)
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/package.py", line 1191, in _process_external_package
    spack.hooks.post_install(self.spec)
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/hooks/__init__.py", line 73, in __call__
    hook(*args, **kwargs)
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/hooks/module_file_generation.py", line 43, in <lambda>
    post_install = lambda spec: _for_each_enabled(spec, 'write')
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/hooks/module_file_generation.py", line 40, in _for_each_enabled
    getattr(generator, method_name)()
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/modules/common.py", line 640, in write
    context = self.context.to_dict()
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/tengine.py", line 85, in to_dict
    d = [(name, getattr(self, name)) for name in self.context_properties]
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/modules/common.py", line 464, in configure_options
    configure_args = getattr(pkg, attr)()
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/var/spack/repos/builtin/packages/openmpi/package.py", line 307, in configure_args
    config_args.append('--with-hwloc={0}'.format(spec['hwloc'].prefix))
  File "/gpfs/homeb/pcp0/pcp0043/soft/spack/lib/spack/spack/spec.py", line 2647, in __getitem__
    raise KeyError("No spec with name %s in %s" % (name, self))
KeyError: 'No spec with name hwloc in openmpi@2.0.2%gcc@4.8.5~cuda fabrics=verbs ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-ppc64le'
```

Let me know if more info is needed.

**Comment by pramodskumbhar** [comment]
If I go to commit  `081403f2805f77ba6a1e555cf99b2034062428e2` which is before #3183 then I don't see issue now:

```
$ spack -d install -v openmpi
==> '/usr/bin/ibv_devices'
==> Reading config file /gpfs/homeb/pcp0/pcp0043/soft/spack/etc/spack/defaults/packages.yaml
==> Reading config file /gpfs/homeb/pcp0/pcp0043/.spack/packages.yaml
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/.spack/cache/providers/.bbp-index.yaml.lock[0:0] [Released]
==> Reading config file /gpfs/homeb/pcp0/pcp0043/.spack/linux/compilers.yaml
==> '/gpfs/software/opt/lmod/lmod/libexec/lmod' 'python' 'list'
==> '/gpfs/software/opt/lmod/lmod/libexec/lmod' 'python' 'show' 'openmpi/2.0.2-xl'
==> openmpi@2.0.2 : has external module in openmpi/2.0.2-xl
==> openmpi@2.0.2 : is actually installed in /gpfs/software/opt/openmpi-2.0.2-xl
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> openmpi@2.0.2 : generating module file
==> SKIP: shebang filtering [external package]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> 	WRITE : openmpi@2.0.2%gcc@4.8.5~cuda fabrics=verbs ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-ppc64le /3kaee72 [/gpfs/homeb/pcp0/pcp0043/soft/spack/share/spack/modules/linux-centos7-ppc64le/openmpi-2.0.2-gcc-4.8.5-3kaee72]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> 	WRITE : openmpi@2.0.2%gcc@4.8.5~cuda fabrics=verbs ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-ppc64le /3kaee72 [/gpfs/homeb/pcp0/pcp0043/soft/spack/share/spack/dotkit/linux-centos7-ppc64le/openmpi-2.0.2-gcc-4.8.5-3kaee72.dk]
==> openmpi@2.0.2 : registering into DB
==> WRITE LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> WRITE LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> WRITE LOCK: /gpfs/homeb/pcp0/pcp0043/soft/spack/opt/spack/.spack-db/lock[0:0] [Released]
```

**Comment by alalazo** [comment]
Just tried this on our clusters:
```console
$ uname -a
Linux fidis 3.10.0-514.26.2.el7.x86_64 #1 SMP Fri Jun 30 05:26:04 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
and it works as of 951679376e1ffbfaf626625158ea9fafecec36d8
