### ISSUE TITLE
Unable to add external packages built with Spack to packages.yaml

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#3787]
Never seen this one before. I'm trying to build something with `intel-parallel-studio` and I don't want to reinstall `intel-parallel-studio` for every compiler, so I added it to my `packages.yaml` like so:
```yaml
packages:
  all:
    # Set Intel as default compiler
    compiler: [intel, gcc, pgi, nag]
    providers:
      # Set Intel MKL as default BLAS/LAPACK
      blas:   [intel-parallel-studio]
      lapack: [intel-parallel-studio]
      # Set MVAPICH2 as default MPI
      mpi: [mvapich2, mpich, openmpi]
    variants: ~mpi+openmp
  intel-parallel-studio:
    paths:
      intel-parallel-studio@professional.2017.2+all+daal~ilp64+ipp+mkl+mpi~newdtags~openmp+rpath+shared+tools arch=linux-rhel7-x86_64: /data/software/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/intel-parallel-studio-professional.2017.2-2btuqpiiqgrqbmnmxxe7jletuqppyktc
    buildable: False
```
But when I try to build `hpl`, I see:
```
$ spack install hpl
==> Installing hpl
==> mvapich2 is already installed in /data/software/spack/opt/spack/linux-rhel7-x86_64/intel-17.0.2/mvapich2-2.2-bn3h2ts3ncoizpmyebhq6ofdvrobq57i
==> intel-parallel-studio is externally installed in /data/software/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/intel-parallel-studio-professional.2017.2-2btuqpiiqgrqbmnmxxe7jletuqppyktc
==> Error: AssertionError: 
/data/software/spack/lib/spack/spack/build_environment.py:569, in child_execution:
     549      def child_execution(child_connection, input_stream):
     550          try:
     551              setup_package(pkg, dirty=dirty)
     552              function(input_stream)
     553              child_connection.send(None)
     554          except StopIteration as e:
     555              # StopIteration is used to stop installations
     556              # before the final stage, mainly for debug purposes
     557              tty.msg(e.message)
     558              child_connection.send(None)
     559          except:
     560              # catch ANYTHING that goes wrong in the child process
     561              exc_type, exc, tb = sys.exc_info()
     562  
     563              # Need to unwind the traceback in the child because traceback
     564              # objects can't be sent to the parent.
     565              tb_string = traceback.format_exc()
     566  
     567              # build up some context from the offending package so we can
     568              # show that, too.
  >> 569              package_context = get_package_context(tb)
     570  
     571              build_log = None
     572              if hasattr(pkg, 'log_path'):
     573                  build_log = pkg.log_path
     574  
     575              # make a pickleable exception to send to parent.
     576              msg = "%s: %s" % (str(exc_type.__name__), str(exc))
     577  
     578              ce = ChildError(msg, tb_string, build_log, package_context)
     579              child_connection.send(ce)
     580  
     581          finally:
     582              child_connection.close()
```
I have no idea what this means. Anyone else? The `intel-parallel-studio` installation went by fine and I'm using it to install the dependencies, so there's nothing wrong with that.

**Comment by svenevs** [comment]
Yes. I'm getting this too, mine might be more helpful since more things are happening?

```console
$ spack spec -I qt
Input spec
--------------------------------
     qt

Normalized
--------------------------------
     qt
         ^icu4c
         ^jpeg
         ^libmng
             ^lcms
                 ^libtiff
                     ^xz
                     ^zlib
         ^libxcb
             ^libpthread-stubs
             ^libxau@0.99.2:
                 ^pkg-config@0.9.0:
                 ^util-macros
                 ^xproto
             ^libxdmcp
             ^xcb-proto
         ^libxml2
         ^openssl

Concretized
--------------------------------
     qt@5.7.1%gcc@5.3.1~dbus~examples~gtk~krellpatch~mesa~phonon~webkit arch=linux-fedora23-x86_64 
[+]      ^glib@2.49.7%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^autoconf@2.69%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]              ^m4@1.4.18%gcc@5.3.1+sigsegv arch=linux-fedora23-x86_64 
[+]                  ^libsigsegv@2.11%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^automake@1.15%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^gettext@0.19.8.1%gcc@5.3.1+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-fedora23-x86_64 
[+]              ^bzip2@1.0.6%gcc@5.3.1+shared arch=linux-fedora23-x86_64 
[+]              ^libxml2@2.9.4%gcc@5.3.1~python arch=linux-fedora23-x86_64 
[+]                  ^pkg-config@0.29.2%gcc@5.3.1+internal_glib arch=linux-fedora23-x86_64 
[+]                  ^xz@5.2.3%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]                  ^zlib@1.2.11%gcc@5.3.1+pic+shared arch=linux-fedora23-x86_64 
[+]              ^ncurses@6.0%gcc@5.3.1~symlinks arch=linux-fedora23-x86_64 
[+]                  ^mawk@1.3.4%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]              ^tar@1.29%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^libffi@3.2.1%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^libtool@2.4.6%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^pcre@8.40%gcc@5.3.1+utf arch=linux-fedora23-x86_64 
[+]      ^icu4c@58.2%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]      ^jpeg@9b%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]      ^libmng@2.0.2%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^lcms@2.6%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]              ^libtiff@4.0.6%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]      ^libpng@1.6.27%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]      ^libxcb@1.12%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^libpthread-stubs@0.3%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^libxau@1.0.8%gcc@5.3.1 arch=linux-fedora23-x86_64 
                 ^util-macros@1.19.1%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]              ^xproto@7.0.29%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]          ^libxdmcp@1.1.2%gcc@5.3.1 arch=linux-fedora23-x86_64 
             ^xcb-proto@1.12%gcc@5.3.1 arch=linux-fedora23-x86_64 
[+]      ^openssl@1.0.2k%gcc@5.3.1 arch=linux-fedora23-x86_64 
         ^python@2.7.13%gcc@5.3.1~tk~ucs4 arch=linux-fedora23-x86_64 
```

On install:

```console
$ spack install qt
==> Installing qt
==> glib is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/glib-2.49.7-dvq2yp6bufsi77nr663g6egcaum257wm
==> zlib is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/zlib-1.2.11-br6mxvnmdow252hgfxl74lmrfx4yxsm7
==> python is externally installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/python-2.7.13-or3c6jjndwcaste6cblsy2npmfaabx6b
==> libxml2 is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/libxml2-2.9.4-exxfg3qib4gw7kkpjqwusixffs3tqzig
==> libtiff is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/libtiff-4.0.6-mdzax3yzvewviecol7ri765tfpdobbio
==> openssl is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/openssl-1.0.2k-lyj3aryw6e5bwzknpraebzwpv2tigvpj
==> jpeg is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/jpeg-9b-izuys7ewu6khsyc4vueqt77evihphjjo
==> icu4c is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/icu4c-58.2-xwursrzpd3icnoe3fyh6r3nxuczeyaa7
==> libxcb is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/libxcb-1.12-e2skinccuduixjz7tg3anwebdde6du35
==> libpng is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/libpng-1.6.27-lv547knfzyg7u2dfb6cttlrh7sjxawc4
==> libmng is already installed in /home/sven/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/libmng-2.0.2-rmswdn2ek6t75fr7kli2ihesn4eq5wzj
==> Error: AssertionError: 
/home/sven/spack/lib/spack/spack/build_environment.py:569, in child_execution:
     549      def child_execution(child_connection, input_stream):
     550          try:
     551              setup_package(pkg, dirty=dirty)
     552              function(input_stream)
     553              child_connection.send(None)
     554          except StopIteration as e:
     555              # StopIteration is used to stop installations
     556              # before the final stage, mainly for debug purposes
     557              tty.msg(e.message)
     558              child_connection.send(None)
     559          except:
     560              # catch ANYTHING that goes wrong in the child process
     561              exc_type, exc, tb = sys.exc_info()
     562  
     563              # Need to unwind the traceback in the child because traceback
     564              # objects can't be sent to the parent.
     565              tb_string = traceback.format_exc()
     566  
     567              # build up some context from the offending package so we can
     568              # show that, too.
  >> 569              package_context = get_package_context(tb)
     570  
     571              build_log = None
     572              if hasattr(pkg, 'log_path'):
     573                  build_log = pkg.log_path
     574  
     575              # make a pickleable exception to send to parent.
     576              msg = "%s: %s" % (str(exc_type.__name__), str(exc))
     577  
     578              ce = ChildError(msg, tb_string, build_log, package_context)
     579              child_connection.send(ce)
     580  
     581          finally:
     582              child_connection.close()
```

So it seems like it's freaking out because even though I have the package installed, it's dependencies are not?

**Comment by svenevs** [comment]
Yeah definitely smells like a concretizer bug.  I hacked `libxcb` and `xcbproto` to rid the `python` dependencies.  Just _reset_ those to back to what they are supposed to be and now it gets past that in the sense that it did something different.  But something different is it now is using `clang@3.9.0`.  Relevant section of `packages.yaml`:

```yaml
packages:
  all:
    compiler: [gcc@5.3.1, clang@3.9.0]
```

Isn't that supposed to use `gcc@5.3.1` over `clang@3.9.0`?

**Comment by adamjstewart** [comment]
Hmm, but `intel-parallel-studio` doesn't have any dependencies. I might just uninstall everything and start over.

**Comment by svenevs** [comment]
I don't think the above analysis was very clear on my part.  It appears to me that **anything** marked as `buildable: False` is _unable to be used_ in compiling any package.  I tried doing `libxcb` with just `xcp-proto` in my `packages.yaml`, for example, and it failed as well.

I think the best / most important test case would be `mpi` related packages, if those are marked as `buildable: False` and you cannot use them to build something that uses MPI, then it seems likely that this is indeed the problem.

**Comment by adamjstewart** [comment]
>  It appears to me that **anything** marked as `buildable: False` is _unable to be used_ in compiling any package.

Wow, this is bad. Your statement is almost right. I just tried a simple:
```
$ spack install libsigsegv
```
added it to my `packages.yaml`:
```yaml
packages:
  libsigsegv:
    paths:
      libsigsegv@1.11: /data/software/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/libsigsegv-1.11-3byxblkv2nvzumj3wk5cbzyud5hpjdlv
    buildable: False
```
and now `spack install m4` produces the aforementioned error message. Even if I remove `buildable: False`, the error message still persists. `spack reindex` doesn't help.

However, if I use an external package that wasn't installed with Spack:
```yaml
packages:
  openssl:
    paths:
      openssl@1.0.1e: /usr
    buildable: False
```
it works just fine. So I would refine your comment and say that _you cannot add external packages built with Spack to `packages.yaml`_. This is definitely a bug.

**Comment by adamjstewart** [comment]
Ooh, and if I run `spack find` I'm seeing it in the database:
```
$ spack find -p openssl
==> 1 installed packages.
-- linux-rhel7-x86_64 / gcc@4.8.5 -------------------------------
    openssl@1.0.1e  /data/software/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/openssl-1.0.1e-qnrgzbso4mykho5wl27dw5hiisyq7wu7
```
Of course, that's not the right path:
```
$ ls /data/software/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/openssl-1.0.1e-qnrgzbso4mykho5wl27dw5hiisyq7wu7
ls: cannot access /data/software/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/openssl-1.0.1e-qnrgzbso4mykho5wl27dw5hiisyq7wu7: No such file or directory
```

**Comment by adamjstewart** [comment]
@alalazo Any change these bugs will be fixed by #1167?

**Comment by alalazo** [comment]
@adamjstewart I'll have time to have a look at this starting next week.

> Ooh, and if I run spack find I'm seeing it in the database:

Are you sure it's **in** the database? Can you check the `json` file?

**Comment by adamjstewart** [comment]
In `opt/spack/.spack-db/index.json` I see:
```json
{
 "database": {
  "installs": {
   "qnrgzbso4mykho5wl27dw5hiisyq7wu7": {
    "path": "None",
    "explicit": false,
    "spec": {
     "openssl": {
      "version": "1.0.1e",
      "arch": {
       "platform": "linux",
       "platform_os": "rhel7",
       "target": "x86_64"
      },
      "compiler": {
       "name": "gcc",
       "version": "4.8.5"
      },
      "namespace": "builtin",
      "parameters": {
       "cflags": [],
       "cppflags": [],
       "cxxflags": [],
       "fflags": [],
       "ldflags": [],
       "ldlibs": []
      }
     }
    },
    "ref_count": 1,
    "installed": false
   },
  "version": "0.9.2"
 }
}
```
Btw, that `0.9.2`, is that the Spack version? `spack --version` returns `0.10.0`. Is there somewhere we forgot to update the database version?

**Comment by adamjstewart** [comment]
The previous comment shows the package immediately after installation of `curl`. If I run `spack reindex`, it changes to:
```json
{
 "database": {
  "installs": {
   "qnrgzbso4mykho5wl27dw5hiisyq7wu7": {
    "path": "/data/software/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/openssl-1.0.1e-qnrgzbso4mykho5wl27dw5hiisyq7wu7",
    "explicit": false,
    "spec": {
     "openssl": {
      "version": "1.0.1e",
      "arch": {
       "platform": "linux",
       "platform_os": "rhel7",
       "target": "x86_64"
      },
      "compiler": {
       "name": "gcc",
       "version": "4.8.5"
      },
      "namespace": "builtin",
      "parameters": {
       "cflags": [],
       "cppflags": [],
       "cxxflags": [],
       "fflags": [],
       "ldflags": [],
       "ldlibs": []
      }
     }
    },
    "ref_count": 1,
    "installed": true
   },
  "version": "0.9.2"
 }
}
```
Notice that `path` is updated to the wrong path and `installed` is now `true`.

**Comment by adamjstewart** [comment]
@alalazo Has this gotten worse? Now I'm seeing:
```
$ spack install cbench
==> mvapich2 is already installed in /nfs/software/spack/opt/spack/linux-centos7-x86_64/intel-17.0.2/mvapich2-2.2-67wgghlkechibsuudo7xron7m7cuty75
==> intel-parallel-studio@professional.2017.2 : externally installed in /nfs/software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/intel-parallel-studio-professional.2017.2-2y4rd25t5awbm6sdp6dx4kdi3rsyxade
==> intel-parallel-studio@professional.2017.2 : generating module file
Traceback (most recent call last):
  File "/nfs/software/spack/bin/spack", line 220, in <module>
    main(sys.argv)
  File "/nfs/software/spack/bin/spack", line 216, in main
    _main(args, unknown)
  File "/nfs/software/spack/bin/spack", line 183, in _main
    return_val = command(parser, args)
  File "/nfs/software/spack/lib/spack/spack/cmd/install.py", line 346, in install
    package.do_install(**kwargs)
  File "/nfs/software/spack/lib/spack/spack/package.py", line 1213, in do_install
    **kwargs
  File "/nfs/software/spack/lib/spack/spack/package.py", line 1178, in do_install
    return self._process_external_package(explicit)
  File "/nfs/software/spack/lib/spack/spack/package.py", line 1120, in _process_external_package
    spack.hooks.post_install(self.spec)
  File "/nfs/software/spack/lib/spack/spack/hooks/__init__.py", line 73, in __call__
    hook(*args, **kwargs)
  File "/nfs/software/spack/lib/spack/spack/hooks/module_file_generation.py", line 32, in post_install
    generator.write()
  File "/nfs/software/spack/lib/spack/spack/modules.py", line 380, in write
    env = inspect_path(self.spec.prefix)
  File "/nfs/software/spack/lib/spack/spack/spec.py", line 1316, in prefix
    return Prefix(spack.store.layout.path_for_spec(self))
  File "/nfs/software/spack/lib/spack/spack/directory_layout.py", line 127, in path_for_spec
    assert(not path.startswith(self.root))
AssertionError
```
Is it mad because external packages aren't allowed to have the same root as Spack?

**Comment by wscullin** [comment]
Hi, I ran into this too with the Intel 2018 beta.

**Comment by scheibelp** [comment]
> Will a bad thing happen if I remove that assertion statement?

From glancing at it - probably not. I'll be able to look into this more in-depth tomorrow.

**Comment by scheibelp** [comment]
I'm currently working on this at https://github.com/spack/spack/pull/7759. I anticipate it getting merged next week

**Comment by adamjstewart** [comment]
@scheibelp this bug was reproduced in #12830, any progress on #7759?

**Comment by adamjstewart** [comment]
Is this still an issue? I haven't needed to do this in a long time, so I'm fine with closing this issue unless someone else can reproduce it.
