### ISSUE TITLE
Error in spack spec : not all arguments converted during string formatting

### ISSUE THREAD

**Issue by pramodk** [spack/spack#3818]
I am not sure if I have specified incompatible options : 

```
$ spack spec coreneuron %cce@8.5.5 ^mod2c target=x86_64
Input spec
--------------------------------
coreneuron%cce@8.5.5
    ^mod2c arch=cray-None-x86_64

Normalized
--------------------------------
coreneuron%cce@8.5.5
    ^cmake@2.8.12:
    ^mod2c arch=cray-None-x86_64

Concretized
--------------------------------
coreneuron@develop%cce@8.5.5~gpu+mpi+neurodamusmod+openmp~profile+report~tests arch=cray-CNL-haswell
    ^cmake@3.0.2%cce@8.5.5~doc+ncurses+openssl+ownlibs~qt arch=cray-CNL-haswell
    ^mod2c@develop%cce@8.5.5 arch=cray-CNL-x86_64
    ^mpich@7.5.0%cce@8.5.5+hydra+pmi+romio~verbs arch=cray-CNL-haswell
    ^neurodamus@develop%cce@8.5.5~compile~profile arch=cray-CNL-haswell
    ^reportinglib@develop%cce@8.5.5~profile+static arch=cray-CNL-haswell

[kumbhar@daint103 ~]$ spack spec coreneuron %cce@8.5.5 ^mod2c target=x86_64 os=sles12
Input spec
--------------------------------
coreneuron%cce@8.5.5
    ^mod2c arch=cray-sles12-x86_64

Normalized
--------------------------------
coreneuron%cce@8.5.5
    ^cmake@2.8.12:
    ^mod2c arch=cray-sles12-x86_64

Concretized
--------------------------------
Traceback (most recent call last):
  File "/home/sources/spack/bin/spack", line 220, in <module>
    main(sys.argv)
  File "/home/sources/spack/bin/spack", line 216, in main
    _main(args, unknown)
  File "/home/sources/spack/bin/spack", line 183, in _main
    return_val = command(parser, args)
  File "/home/sources/spack/lib/spack/spack/cmd/spec.py", line 88, in spec
    spec.concretize()
  File "/home/sources/spack/lib/spack/spack/spec.py", line 1678, in concretize
    self._concretize_helper())
  File "/home/sources/spack/lib/spack/spack/spec.py", line 1519, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/home/sources/spack/lib/spack/spack/spec.py", line 1530, in _concretize_helper
    spack.concretizer.concretize_compiler(self),
  File "/home/sources/spack/lib/spack/spack/concretize.py", line 308, in concretize_compiler
    spec.compiler, spec.architecture)
  File "/home/sources/spack/lib/spack/spack/concretize.py", line 425, in _compiler_concretization_failure
    raise UnavailableCompilerVersionError(compiler_spec, arch)
  File "/home/sources/spack/lib/spack/spack/concretize.py", line 457, in __init__
    (compiler_spec, arch.platform_os, arch.target))
TypeError: not all arguments converted during string formatting
```

**Comment by adamjstewart** [comment]
Is this due to:
```
- !!python/unicode 'intel/15.0.3.187'
```
In your `compilers.yaml`?

**Comment by pramodk** [comment]
I tried removing `!!python/unicode` but same issue. I looked into details and I now understood whats going on.

The default concretisation is : 
```
spack spec coreneuron %cce@8.5.5 ^mod2c
Input spec
--------------------------------
coreneuron%cce@8.5.5
    ^mod2c

Normalized
--------------------------------
coreneuron%cce@8.5.5
    ^cmake@2.8.12:
    ^mod2c

Concretized
--------------------------------
coreneuron@develop%cce@8.5.5~gpu+mpi+neurodamusmod+openmp~profile+report~tests arch=cray-CNL-haswell
    ^cmake@3.0.2%cce@8.5.5~doc+ncurses+openssl+ownlibs~qt arch=cray-CNL-haswell
    ^mod2c@develop%cce@8.5.5 arch=cray-CNL-haswell
    ^mpich@7.5.0%cce@8.5.5+hydra+pmi+romio~verbs arch=cray-CNL-haswell
    ^neurodamus@develop%cce@8.5.5~compile~profile arch=cray-CNL-haswell
    ^reportinglib@develop%cce@8.5.5~profile+static arch=cray-CNL-haswell
```

In `compilers.yaml` I have compiler : 
```
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sles12
    paths:
      cc: /usr/bin/gcc-4.8
      cxx: /usr/bin/g++-4.8
      f77: /usr/bin/gfortran-4.8
      fc: /usr/bin/gfortran-4.8
    spec: gcc@4.8
    target: x86_64
```
So I want to build one dependency with above gcc. If I use one of the below, I get reported error : 
```
spack spec coreneuron %cce@8.5.5 target=haswell ^mod2c % gcc@4.8 target=x86_64
spack spec coreneuron %cce@8.5.5 os=CNL ^mod2c % gcc@4.8 target=x86_64
```

If I say : 
```
spack spec coreneuron %cce@8.5.5 os=CNL ^mod2c % gcc@4.8 os=sles12
Input spec
--------------------------------
coreneuron%cce@8.5.5 arch=cray-CNL-None
    ^mod2c%gcc@4.8 arch=cray-sles12-None

Normalized
--------------------------------
coreneuron%cce@8.5.5 arch=cray-CNL-None
    ^cmake@2.8.12:
    ^mod2c%gcc@4.8 arch=cray-sles12-None

Concretized
--------------------------------
==> Error: No compilers found for operating system sles12 and target haswell.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	CNL-any
	sles12-x86_64
Run 'spack compiler find' to add compilers.
```

Ok, now if I try to be more specific : 
```
$ spack spec coreneuron %cce@8.5.5 os=CNL ^mod2c % gcc@4.8 os=sles12 target=x86_64
Input spec
--------------------------------
coreneuron%cce@8.5.5 arch=cray-CNL-None
    ^mod2c%gcc@4.8 arch=cray-sles12-x86_64

Normalized
--------------------------------
coreneuron%cce@8.5.5 arch=cray-CNL-None
    ^cmake@2.8.12:
    ^mod2c%gcc@4.8 arch=cray-sles12-x86_64

Concretized
--------------------------------
coreneuron@develop%cce@8.5.5~gpu+mpi+neurodamusmod+openmp~profile+report~tests arch=cray-CNL-haswell
    ^cmake@3.0.2%cce@8.5.5~doc+ncurses+openssl+ownlibs~qt arch=cray-CNL-haswell
    ^mod2c@develop%gcc@4.8 arch=cray-sles12-x86_64
    ^mpich@7.5.0%cce@8.5.5+hydra+pmi+romio~verbs arch=cray-CNL-haswell
    ^neurodamus@develop%cce@8.5.5~compile~profile arch=cray-CNL-haswell
    ^reportinglib@develop%cce@8.5.5~profile+static arch=cray-CNL-haswell
```

In the past I remember only specifying `os` was sufficient for cross-compiling build. But all looks fine now as I understood whats going on.

**Comment by pramodk** [comment]
As mentioned above, spack has added `gcc` compiler for `x86_64` which I assume for front-end. But `install` fails with `spec architecture is too different`: 
```
spack install -v mod2c %gcc os=sles12 target=x86_64
==> Installing mod2c
==> cmake is externally installed in /apps/santis/cmake/3.0.2
==> Error: ValueError: Can't recreate arch for spec cray-sles12-x86_64 on current arch cray-CNL-haswell; spec architecture is too different
/users/kumbhar/workarena/systems/daint/softwares/sources/spack/lib/spack/spack/package.py:895, in architecture:
     889      @property
     890      def architecture(self):
     891          """Get the spack.architecture.Arch object that represents the
     892          environment in which this package will be built."""
     893          if not self.spec.concrete:
     894              raise ValueError("Can only get the arch for concrete package.")
  >> 895          return spack.architecture.arch_for_spec(self.spec.architecture)
```

If I specify `os=sles12` then it also fails. How am I supposed to build for front-end only?

**Comment by becker33** [comment]
This issue was specific to the `platform=cray` support, which has been removed. Cray systems now detect as `platform=linux`. Closing this issue as resolved on that basis.
