### ISSUE TITLE
ValueError: Specs passed to a DirectoryLayout must be concrete

### ISSUE THREAD

**Issue by eschnett** [spack/spack#4040]
I received this error while trying to view a package:

```
$ spack view -d true hardlink "../cosmomc" cosmomc
Traceback (most recent call last):
  File "/xfs1/applications/spack/spack/bin/spack", line 220, in <module>
    main(sys.argv)
  File "/xfs1/applications/spack/spack/bin/spack", line 216, in main
    _main(args, unknown)
  File "/xfs1/applications/spack/spack/bin/spack", line 183, in _main
    return_val = command(parser, args)
  File "/xfs1/applications/spack/spack/lib/spack/spack/cmd/view.py", line 303, in view
    visitor(specs, args)
  File "/xfs1/applications/spack/spack/lib/spack/spack/cmd/view.py", line 262, in visitor_hardlink
    link_one(spec, path, os.link, verbose=args.verbose)
  File "/xfs1/applications/spack/spack/lib/spack/spack/cmd/view.py", line 227, in link_one
    for dirpath, dirnames, filenames in os.walk(spec.prefix):
  File "/xfs1/applications/spack/spack/lib/spack/spack/spec.py", line 1308, in prefix
    return Prefix(spack.store.layout.path_for_spec(self))
  File "/xfs1/applications/spack/spack/lib/spack/spack/directory_layout.py", line 124, in path_for_spec
    _check_concrete(spec)
  File "/xfs1/applications/spack/spack/lib/spack/spack/directory_layout.py", line 42, in _check_concrete
    raise ValueError('Specs passed to a DirectoryLayout must be concrete!')
ValueError: Specs passed to a DirectoryLayout must be concrete!
```

There is only a single package matching this spec:
```
$ spack find -l cosmomc
==> 1 installed packages.
-- linux-ubuntu14-x86_64 / gcc@6.2.0 ----------------------------
k56w7ep cosmomc@2016.11
```

Is there a work-around?

**Comment by adamjstewart** [comment]
Similar error message as #2911 and a few other PRs linked to in the first post. @alalazo @scheibelp

**Comment by becker33** [comment]
I believe this issue was resolved years ago when we ensured that old hashes are consistently read as concrete regardless of whether they are valid concretizations under the current constraints. Please reopen if you're able to reproduce this in a more recent version of Spack.
