### ISSUE TITLE
Spack install of py-flake8, shows backports.configparser error

### ISSUE THREAD

**Issue by luigi-calori** [spack/spack#4154]
On my linux Mint, I have installed with spack environment modules, configured with autoloading and use them to load python extensions.
It happens that 
spack install py-flake8
module load py-flake8
flake8

result in error:
------
------
  File "/kubuntu/home/lcalori/spack/RCM_test/deploy/rcm08/install/linux-linuxmint18-x86_64/gcc-5.4.0/py-configparser-3.5.0-gyfsxqxnkenrlpaam7zqlk4zox7uq4yi/lib/python2.7/site-packages/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: No module named backports.configparser

Googling around, I found:
https://pypi.python.org/pypi/backports/

It seems that, the proper__init__.py file is lacking from

lib/python2.7/site-packages/backports

It probably relates to setuptools deciding to not install as it is a namespace package,
as shown by the line in spack-build.out:

Skipping installation of /kubuntu/home/lcalori/spack/RCM_test/deploy/rcm08/install/linux-linuxmint18-x86_64/gcc-5.4.0/py-configparser-3.5.0-gyfsxqxnkenrlpaam7zqlk4zox7uq4yi/lib/python2.7/site-packages/backports/__init__.py (namespace package)

it seems a simple patch to setup.py can fix

**Comment by healther** [comment]
I just ran into this problem, when I tried to get a lokal flake8 version to run. Is there an open PR that should solve this?

**Comment by JusticeForMikeBrown** [comment]
I am having this issue now as well

**Comment by JusticeForMikeBrown** [comment]
Using custom repo:

```

[root@harris spack]# spack load -r py-flake8
[root@harris spack]# spack flake8
=======================================================
flake8: running flake8 code checks on spack.

Modified files:
  var/spack/repos/tensorflow/packages/tensorflow/package.py
=======================================================
Traceback (most recent call last):
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-flake8-3.0.4-unb6pq3hw2summ55ictea3whas7satby/bin/flake8", line 12, in <module>
    load_entry_point('flake8==3.0.4', 'console_scripts', 'flake8')()
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-setuptools-35.0.2-22v5lkfhueuv2xfc536tkkcmfr4uviz2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-setuptools-35.0.2-22v5lkfhueuv2xfc536tkkcmfr4uviz2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-setuptools-35.0.2-22v5lkfhueuv2xfc536tkkcmfr4uviz2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-setuptools-35.0.2-22v5lkfhueuv2xfc536tkkcmfr4uviz2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-flake8-3.0.4-unb6pq3hw2summ55ictea3whas7satby/lib/python2.7/site-packages/flake8/main/cli.py", line 2, in <module>
    from flake8.main import application
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-flake8-3.0.4-unb6pq3hw2summ55ictea3whas7satby/lib/python2.7/site-packages/flake8/main/application.py", line 14, in <module>
    from flake8.main import options
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-flake8-3.0.4-unb6pq3hw2summ55ictea3whas7satby/lib/python2.7/site-packages/flake8/main/options.py", line 3, in <module>
    from flake8.main import vcs
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-flake8-3.0.4-unb6pq3hw2summ55ictea3whas7satby/lib/python2.7/site-packages/flake8/main/vcs.py", line 4, in <module>
    from flake8.main import mercurial
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-flake8-3.0.4-unb6pq3hw2summ55ictea3whas7satby/lib/python2.7/site-packages/flake8/main/mercurial.py", line 7, in <module>
    import configparser
  File "/pbtech_mounts/softlib001/apps/EL7/spack/opt/spack/linux-centos7-x86_64/gcc-6.3.0/py-configparser-3.5.0-ummckpw3oyvl2cm6ywkeeqxgyyxy3uba/lib/python2.7/site-packages/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: No module named backports.configparser

Flake8 found errors.

```

**Comment by luigi-calori** [comment]
@healther  @JusticeForMikeBrown  #4155 should fix

**Comment by JusticeForMikeBrown** [comment]
Thanks @luigi-calori!

**Comment by scheibelp** [comment]
This was fixed by https://github.com/spack/spack/pull/10433
