### ISSUE TITLE
File lock issue on ORNL Titan (cray xk7)

### ISSUE THREAD

**Issue by keitat** [spack/spack#4512]
I have been in trouble to acquire lock when installing on ORNL Titan.
```shell
titan-ext1 teranish/spack> ./bin/spack -vd install xsdk@xsdk-0.2.0 
==> Reading config file /autofs/nccs-svm1_home1/teranish/spack/etc/spack/defaults/packages.yaml
==> Reading config file /ccs/home/teranish/.spack/cray/packages.yaml
==> READ LOCK: /ccs/home/teranish/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /ccs/home/teranish/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
Traceback (most recent call last):
  File "./bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/main.py", line 465, in main
    return _main(command, parser, args, unknown)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/main.py", line 353, in _main
    return_val = command(parser, args)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/cmd/install.py", line 323, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/cmd/__init__.py", line 116, in parse_specs
    spec.concretize()  # implies normalize
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 1708, in concretize
    self._expand_virtual_packages(),
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 1624, in _expand_virtual_packages
    spec)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/concretize.py", line 113, in choose_virtual_or_external
    candidates = self._valid_virtuals_and_externals(spec)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/concretize.py", line 90, in _valid_virtuals_and_externals
    externals = spec_externals(cspec)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/package_prefs.py", line 220, in spec_externals
    external_path=canonicalize_path(path))
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/util/path.py", line 69, in canonicalize_path
    path = substitute_config_variables(path)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/util/path.py", line 64, in substitute_config_variables
    return re.sub(r'(\$\w+\b|\$\{\w+\})', repl, path)
  File "/usr/lib64/python2.6/re.py", line 151, in sub
    return _compile(pattern, 0).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by JusticeForMikeBrown** [comment]
Did you try deleting the lock file?
