### ISSUE TITLE
Failing to configure compilers on ORNL Titan

### ISSUE THREAD

**Issue by keitat** [spack/spack#4513]
I am having a trouble to set up compilers on ORNL Titan.

Here is my module environment.
```shell
titan-ext1 teranish/spack> module list
Currently Loaded Modulefiles:
  1) eswrap/1.3.3-1.020200.1278.0          11) hsi/5.0.2.p1                          21) alps/5.2.4-2.0502.9774.31.12.gem
  2) craype-network-gemini                 12) DefApps                               22) rca/1.0.0-2.0502.60530.1.63.gem
  3) gcc/5.3.0                             13) cray-libsci/16.11.1                   23) atp/2.0.5
  4) craype/2.5.9                          14) udreg/2.3.2-1.0502.10518.2.17.gem     24) PrgEnv-gnu/5.2.82
  5) cray-mpich/7.5.2                      15) ugni/6.0-1.0502.10863.8.28.gem        25) modules/3.2.10.5
  6) craype-interlagos                     16) pmi/5.0.11                            26) cmake3/3.6.1
  7) lustredu/1.4                          17) dmapp/7.0.1-1.0502.11080.8.74.gem     27) cray-hdf5-parallel/1.8.14
  8) xalt/0.7.5                            18) gni-headers/4.0-1.0502.10859.7.8.gem  28) mercurial/2.6.3
  9) module_msg/0.1                        19) xpmem/0.1-2.0502.64982.5.3.gem
 10) modulator/1.2.0                       20) dvs/2.5_0.9.0-1.0502.2188.1.113.gem
```
Then, 
```shell
titan-ext1 teranish/spack> ./bin/spack -vd install libelf%gcc@5.3.0
==> Reading config file /autofs/nccs-svm1_home1/teranish/spack/etc/spack/defaults/packages.yaml
==> Reading config file /ccs/home/teranish/.spack/cray/packages.yaml
==> READ LOCK: /ccs/home/teranish/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /ccs/home/teranish/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> '/opt/cray/craype/2.5.9/bin/cc' '-V'
==> '/usr/bin/cc' '-V'
==> '/usr/bin/cc' '-V'
==> '/opt/cray/craype/2.5.9/bin/ftn' '-V'
==> Couldn't get version for compiler /usr/bin/cc
  Command exited with status 1:
    '/usr/bin/cc' '-V'
==> '/opt/cray/craype/2.5.9/bin/CC' '-V'
==> Couldn't get version for compiler /usr/bin/cc
  Command exited with status 1:
    '/usr/bin/cc' '-V'
==> '/opt/cray/craype/2.5.9/bin/ftn' '-V'
==> '/opt/gcc/5.3.0/bin/gcc' '--version'
==> '/usr/bin/gcc-4.3' '--version'
==> '/usr/bin/gcc-4.7' '--version'
==> '/usr/bin/gcc' '--version'
==> '/usr/bin/gcc-4.3' '--version'
==> '/usr/bin/gcc-4.7' '--version'
==> '/usr/bin/gcc' '--version'
==> '/usr/bin/gcc-4.3' '-dumpversion'
==> '/usr/bin/gcc-4.7' '-dumpversion'
==> '/usr/bin/gcc-4.3' '-dumpversion'
==> '/usr/bin/gcc' '-dumpversion'
==> '/usr/bin/gcc-4.7' '-dumpversion'
==> '/opt/gcc/5.3.0/bin/g++' '--version'
==> '/usr/bin/gcc' '-dumpversion'
==> '/usr/bin/g++' '--version'
==> '/opt/gcc/5.3.0/bin/gcc' '-dumpversion'
==> '/usr/bin/g++-4.3' '--version'
==> Couldn't get version for compiler /opt/cray/craype/2.5.9/bin/cc
  Command exited with status 1:
    '/opt/cray/craype/2.5.9/bin/cc' '-V'
==> '/usr/bin/g++-4.7' '--version'
==> '/usr/bin/g++' '--version'
==> '/usr/bin/g++-4.3' '--version'
==> '/usr/bin/g++-4.7' '--version'
==> '/usr/bin/g++' '-dumpversion'
==> '/usr/bin/g++-4.3' '-dumpversion'
==> Couldn't get version for compiler /opt/cray/craype/2.5.9/bin/ftn
  Command exited with status 1:
    '/opt/cray/craype/2.5.9/bin/ftn' '-V'
==> '/usr/bin/g++-4.7' '-dumpversion'
==> '/usr/bin/g++' '-dumpversion'
==> '/opt/gcc/5.3.0/bin/g++' '-dumpversion'
==> '/usr/bin/g++-4.3' '-dumpversion'
==> '/opt/gcc/5.3.0/bin/gfortran' '-dumpversion'
==> '/usr/bin/g++-4.7' '-dumpversion'
==> Couldn't get version for compiler /opt/cray/craype/2.5.9/bin/CC
  Command exited with status 1:
    '/opt/cray/craype/2.5.9/bin/CC' '-V'
==> '/usr/bin/gfortran-4.3' '-dumpversion'
==> '/usr/bin/gfortran' '-dumpversion'
==> '/usr/bin/gfortran-4.3' '-dumpversion'
==> '/usr/bin/gfortran' '-dumpversion'
==> Couldn't get version for compiler /opt/cray/craype/2.5.9/bin/ftn
  Command exited with status 1:
    '/opt/cray/craype/2.5.9/bin/ftn' '-V'
==> '/opt/gcc/5.3.0/bin/gfortran' '-dumpversion'
==> '/usr/bin/gfortran-4.3' '-dumpversion'
==> '/usr/bin/gfortran' '-dumpversion'
==> '/usr/bin/gfortran-4.3' '-dumpversion'
==> '/usr/bin/gfortran' '-dumpversion'
==> '/opt/modules/3.2.10.5/bin/modulecmd' 'python' 'avail' 'cce'
==> '/opt/modules/3.2.10.5/bin/modulecmd' 'python' 'avail' 'gcc'
==> '/opt/modules/3.2.10.5/bin/modulecmd' 'python' 'avail' 'intel'
==> '/opt/modules/3.2.10.5/bin/modulecmd' 'python' 'avail' 'pgi'
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/util/multiproc.py", line 37, in fun
    pipe.send(f(x))
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/operating_systems/cnl.py", line 53, in <lambda>
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/util/multiproc.py", line 37, in fun
    lambda cmp_cls: self.find_compiler(cmp_cls, *paths), types)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/operating_systems/cnl.py", line 76, in find_compiler
    spack.spec.CompilerSpec(name + '@' + v),
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 475, in __init__
    pipe.send(f(x))
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/operating_systems/cnl.py", line 53, in <lambda>
    lambda cmp_cls: self.find_compiler(cmp_cls, *paths), types)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/operating_systems/cnl.py", line 76, in find_compiler
    spack.spec.CompilerSpec(name + '@' + v),
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 475, in __init__
    c = SpecParser().parse_compiler(arg)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 3039, in parse_compiler
    self.setup(text)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 166, in setup
    self.push_tokens(self.lexer.lex(text))
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 104, in lex
    tokens = self.lex_word(word)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 97, in lex_word
    raise LexError("Invalid character", word, word.index(remainder))
LexError: Invalid character
    c = SpecParser().parse_compiler(arg)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 3039, in parse_compiler
    self.setup(text)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 166, in setup
    self.push_tokens(self.lexer.lex(text))
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 104, in lex
    tokens = self.lex_word(word)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 97, in lex_word
    raise LexError("Invalid character", word, word.index(remainder))
LexError: Invalid character
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/util/multiproc.py", line 37, in fun
    pipe.send(f(x))
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/operating_systems/cnl.py", line 53, in <lambda>
    lambda cmp_cls: self.find_compiler(cmp_cls, *paths), types)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/operating_systems/cnl.py", line 76, in find_compiler
    spack.spec.CompilerSpec(name + '@' + v),
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 475, in __init__
    c = SpecParser().parse_compiler(arg)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 3039, in parse_compiler
    self.setup(text)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 166, in setup
    self.push_tokens(self.lexer.lex(text))
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 104, in lex
    tokens = self.lex_word(word)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 97, in lex_word
    raise LexError("Invalid character", word, word.index(remainder))
LexError: Invalid character
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/util/multiproc.py", line 37, in fun
    pipe.send(f(x))
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/operating_systems/cnl.py", line 53, in <lambda>
    lambda cmp_cls: self.find_compiler(cmp_cls, *paths), types)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/operating_systems/cnl.py", line 76, in find_compiler
    spack.spec.CompilerSpec(name + '@' + v),
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 475, in __init__
    c = SpecParser().parse_compiler(arg)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/spec.py", line 3039, in parse_compiler
    self.setup(text)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 166, in setup
    self.push_tokens(self.lexer.lex(text))
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 104, in lex
    tokens = self.lex_word(word)
  File "/autofs/nccs-svm1_home1/teranish/spack/lib/spack/spack/parse.py", line 97, in lex_word
    raise LexError("Invalid character", word, word.index(remainder))
LexError: Invalid character
```

**Comment by mamelara** [comment]
This looks similar to what I was experience on Edison. I have a fix for it submitted but waiting for it to be reviewed #4355.

**Comment by jgalarowicz** [comment]
@keitat @mamelara @adamjstewart I'm seeing a similar issue on a DOD Cray platform (shepard).   I see there are other PRs and Issues that are also in progress.

**Comment by mamelara** [comment]
@jgalarowicz #5033 should also address this error.

**Comment by jgalarowicz** [comment]
@mamelara Great!  Thanks for your work on these issues.

**Comment by adamjstewart** [comment]
Is this still an issue? Spack's Cray support has been completely overhauled in the last few years.
