### ISSUE TITLE
spack config edit fails when there are syntax errors in modules.yaml

### ISSUE THREAD

**Issue by tgamblin** [spack/spack#6296]
Discovered by @rmetzler

### Expected Result

If there's a syntax error in a config file like `modules.yaml`, it should be possible to run `spack config edit <config>`.

### Actual Result

YAML configs are parsed at the beginning of a Spack run, and Spack complains when there is even a small error in the configuration file.

### Steps to reproduce the issue

```console
$ spack config edit --scope=site modules
... edit the file so that it has invalid YAML syntax
$ spack config --scope=site edit modules 
Traceback (most recent call last):
  File "/Users/gamblin2/src/spack/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "/Users/gamblin2/src/spack/lib/spack/spack/main.py", line 547, in main
    return _main(command, parser, args, unknown)
  File "/Users/gamblin2/src/spack/lib/spack/spack/main.py", line 435, in _main
    spack.hooks.pre_run()
  File "/Users/gamblin2/src/spack/lib/spack/spack/hooks/__init__.py", line 69, in __call__
    for module in all_hook_modules():
  File "/Users/gamblin2/src/spack/lib/spack/llnl/util/lang.py", line 182, in __call__
    self.cache[args] = self.func(*args)
  File "/Users/gamblin2/src/spack/lib/spack/spack/hooks/__init__.py", line 57, in all_hook_modules
    mod = imp.load_source(mod_name, path)
  File "/Users/gamblin2/src/spack/lib/spack/spack/hooks/module_file_generation.py", line 25, in <module>
    import spack.modules
  File "/Users/gamblin2/src/spack/lib/spack/spack/modules/__init__.py", line 32, in <module>
    from .dotkit import DotkitModulefileWriter
  File "/Users/gamblin2/src/spack/lib/spack/spack/modules/dotkit.py", line 28, in <module>
    from .common import BaseConfiguration, BaseFileLayout
  File "/Users/gamblin2/src/spack/lib/spack/spack/modules/common.py", line 71, in <module>
    configuration = spack.config.get_config('modules')
  File "/Users/gamblin2/src/spack/lib/spack/spack/config.py", line 409, in get_config
    data = scope.get_section(section)
  File "/Users/gamblin2/src/spack/lib/spack/spack/config.py", line 180, in get_section
    data   = _read_config_file(path, schema)
  File "/Users/gamblin2/src/spack/lib/spack/spack/config.py", line 287, in _read_config_file
    "Error parsing yaml%s: %s" % (str(e.context_mark), e.problem))
spack.config.ConfigFileError: Error parsing yaml  in "/Users/gamblin2/src/spack/etc/spack/modules.yaml", line 1, column 1: expected <block end>, but found ':'
...
```

### Information on your system

macOS, no custom configuration

**Comment by alalazo** [comment]
Already fixed.
