### ISSUE TITLE
install --use-cache does not print error message

### ISSUE THREAD

**Issue by sknigh** [spack/spack#6404]
Summary

```spack install --use-cache <SPEC>``` cryptically fails when installing an unsigned package

### Expected Result

A readable error at minimum, and possibly a flag to ignore it like ``` spack buildcache install``` or a ```[y/N]``` similar to the behaviour when installing an untrusted spec version with ```spack install```

### Actual Result

``` bash
spack buildcache list pkg-config
==> Finding buildcaches in /<PATH>/build_cache
==> buildcache spec(s) matching set(['pkg-config']) and commands to install them
==> Enter
spack buildcache install /rhaia4m
 to install "pkg-config@0.29.1%gcc@4.8.5+internal_glib patches=49ffcd644e190dc5efcb2fab491177811ea746c1a526f75d77118c2706574358 arch=linux-centos7-x86_64 "
[sknigh@klogin1 spack]$ spack install --use-cache pkg-config@0.29.1%gcc@4.8.5
==> Installing pkg-config
==> Searching for binary cache of pkg-config
==> Finding buildcaches in <PATH>/build_cache
==> Installing pkg-config from binary cache
==> Fetching file://<PATH>/build_cache/linux-centos7-x86_64/gcc-4.8.5/pkg-config-0.29.1/linux-centos7-x86_64-gcc-4.8.5-pkg-config-0.29.1-rhaia4mg3zxhtrwkm6qluc7aef2eozu3.spack
######################################################################## 100.0%
==> Error:
```

When run with debugging:

``` bash
...
==> Installing pkg-config from binary cache
==> Already downloaded <SPACK_ROOT>/var/spack/stage/build_cache/linux-centos7-x86_64-gcc-4.8.5-pkg-config-0.29.1-rhaia4mg3zxhtrwkm6qluc7aef2eozu3.spack
Traceback (most recent call last):
  File "<SPACK_ROOT>/bin/spack", line 81, in <module>
    sys.exit(spack.main.main())
  File "<SPACK_ROOT>/lib/spack/spack/main.py", line 547, in main
    return _main(command, parser, args, unknown)
  File "<SPACK_ROOT>/lib/spack/spack/main.py", line 439, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "<SPACK_ROOT>/lib/spack/spack/main.py", line 355, in _invoke_spack_command
    return_val = command(parser, args)
  File "<SPACK_ROOT>/lib/spack/spack/cmd/install.py", line 461, in install
    install_spec(args, kwargs, spec)
  File "<SPACK_ROOT>/lib/spack/spack/cmd/install.py", line 358, in install_spec
    package.do_install(**kwargs)
  File "<SPACK_ROOT>/lib/spack/spack/package.py", line 1370, in do_install
    if self.try_install_from_binary_cache(explicit):
  File "<SPACK_ROOT>/lib/spack/spack/package.py", line 1282, in try_install_from_binary_cache
    binary_spec, tarball, yes_to_all=False, force=False)
  File "<SPACK_ROOT>/lib/spack/spack/binary_distribution.py", line 400, in extract_tarball
    raise NoVerifyException()
spack.binary_distribution.NoVerifyException
```

### Information on your system

Centos 7.4

**Comment by gartung** [comment]
https://github.com/spack/spack/pull/6344 addresses this.
