### ISSUE TITLE
Fenics fails to run after installation with spack

### ISSUE THREAD

**Issue by patrickb314** [spack/spack#6419]
Fenics fails to run after installation with spack

### Expected Result

To be able to execute simple fenics scripts using the spack-built fenics.

### Actual Result

Simply importing the fenics module into the spack-provided python fails with:
```console
ImportError: No module named _common
```

### Steps to reproduce the issue

```
bridges@wheeler-sn[500]> module load fenics-2017.1.0-intel-17.0.4-impi-mkl-python2-zre3f5b
Autoloading eigen-3.3.3-intel-17.0.4-impi-mkl-lnbosvu
Autoloading metis-5.1.0-intel-17.0.4-xyonw4o
Autoloading fftw-3.3.6-pl2-intel-17.0.4-impi-bwlmvhs
Autoloading intel-mpi-2017.4-intel-17.0.4-ataurnp
Autoloading suite-sparse-4.5.5-intel-17.0.4-mkl-v6mhhmc
Autoloading intel-mkl-17.0.4-intel-17.0.4-z2nms2r
Autoloading gmp-6.1.2-intel-17.0.4-asgihpm
Autoloading scotch-6.0.4-intel-17.0.4-impi-dxrzrfk
Autoloading mpfr-3.1.5-intel-17.0.4-e2wn26r
Autoloading py-mpmath-0.19-intel-17.0.4-python2-bub4nhr
Autoloading python-2.7.13-intel-17.0.4-ufhcwdr
Autoloading bzip2-1.0.6-intel-17.0.4-zjtu25w
Autoloading ncurses-6.0-intel-17.0.4-j3ftwhg
Autoloading openssl-1.0.2k-intel-17.0.4-6n2jfwi
Autoloading sqlite-3.18.0-intel-17.0.4-cyhl22m
Autoloading readline-7.0-intel-17.0.4-psasazv
Autoloading readline-7.0-intel-17.0.4-psasazv
Autoloading py-ply-3.8-intel-17.0.4-python2-ntmnh7h
Autoloading py-instant-2017.1.0-intel-17.0.4-mkl-python2-ebd5pyo
Autoloading swig-3.0.12-intel-17.0.4-bbmqam2
Autoloading pcre-8.40-intel-17.0.4-72ed5lu
Autoloading py-setuptools-35.0.2-intel-17.0.4-python2-jg3axmx
Autoloading py-six-1.10.0-intel-17.0.4-python2-mj2hiwx
Autoloading py-appdirs-1.4.3-intel-17.0.4-python2-mupwe3g
Autoloading py-packaging-16.8-intel-17.0.4-python2-js2s5wi
Autoloading py-pyparsing-2.2.0-intel-17.0.4-python2-vh7hq5e
Autoloading py-numpy-1.13.0-intel-17.0.4-mkl-python2-bby27xc
Autoloading py-subprocess32-3.2.7-intel-17.0.4-python2-5aviwgl
Autoloading py-subprocess32-3.2.7-intel-17.0.4-python2-5aviwgl
Autoloading py-slepc4py-3.7.0-intel-17.0.4-impi-mkl-python2-iahwthv
Autoloading py-petsc4py-3.7.0-intel-17.0.4-impi-mkl-python2-y6jgyt6
Autoloading petsc-3.7.6-intel-17.0.4-impi-mkl-3x6zx5l
Autoloading hypre-2.11.2-intel-17.0.4-impi-mkl-g5srp2y
Autoloading superlu-dist-5.1.3-intel-17.0.4-impi-mkl-ymsttjs
Autoloading parmetis-4.0.3-intel-17.0.4-impi-3bbdt5v
Autoloading hdf5-1.10.1-intel-17.0.4-impi-63jbam2
Autoloading parmetis-4.0.3-intel-17.0.4-impi-3bbdt5v
Autoloading py-mpi4py-2.0.0-intel-17.0.4-impi-python2-ozw6g4g
Autoloading slepc-3.7.4-intel-17.0.4-impi-mkl-fy5wf4h
Autoloading arpack-ng-3.5.0-intel-17.0.4-impi-mkl-l7ewls2
Autoloading py-ufl-2017.1.0-intel-17.0.4-mkl-python2-2xalq65
Autoloading cmake-3.8.1-intel-17.0.4-m63t5kd
Autoloading py-sympy-1.0-intel-17.0.4-python2-tap7mf2
Autoloading py-dijitso-2017.1.0-intel-17.0.4-mkl-python2-ljegoot
Autoloading boost-1.63.0-intel-17.0.4-bjbzbtc
Autoloading trilinos-12.10.1-intel-17.0.4-impi-mkl-l67gizf
Autoloading glm-0.9.7.1-intel-17.0.4-wmre6yo
Autoloading netcdf-4.4.1.1-intel-17.0.4-impi-bdktit6
Autoloading mumps-5.1.1-intel-17.0.4-impi-mkl-6enszkq
Autoloading matio-1.5.9-intel-17.0.4-impi-sjmlxnf
Autoloading python-2.7.13-intel-17.0.4-ufhcwdr
Autoloading swig-3.0.12-intel-17.0.4-bbmqam2
Autoloading py-six-1.10.0-intel-17.0.4-python2-mj2hiwx
Autoloading suite-sparse-4.5.5-intel-17.0.4-mkl-v6mhhmc
Autoloading py-setuptools-35.0.2-intel-17.0.4-python2-jg3axmx
Autoloading parmetis-4.0.3-intel-17.0.4-impi-3bbdt5v
Autoloading hdf5-1.10.1-intel-17.0.4-impi-63jbam2
Autoloading slepc-3.7.4-intel-17.0.4-impi-mkl-python2-fy5wf4h
Autoloading py-numpy-1.13.0-intel-17.0.4-mkl-python2-bby27xc
Autoloading petsc-3.7.6-intel-17.0.4-impi-mkl-python2-3x6zx5l
Autoloading py-petsc4py-3.7.0-intel-17.0.4-impi-mkl-python2-y6jgyt6
Autoloading py-fiat-2017.1.0-intel-17.0.4-mkl-python2-6krzj5q
Autoloading py-ffc-2017.1.0-intel-17.0.4-mkl-python2-mleunix
Autoloading scotch-6.0.4-intel-17.0.4-impi-dxrzrfk
Autoloading intel-mpi-2017.4-intel-17.0.4-ataurnp
bridges@wheeler-sn[501]> which python
python is /opt/spack/opt/spack/linux-centos7-x86_64/intel-17.0.4/python-2.7.13-ufhcwdrlqo7lt2i2otrgvmgh5f4jrzyt/bin/python
bridges@wheeler-sn[502]> python -c 'import fenics'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/spack/opt/spack/linux-centos7-x86_64/intel-17.0.4/fenics-2017.1.0-zre3f5b4xo4u2z45jjnoeqvzzfv4l35m/lib/python2.7/site-packages/fenics/__init__.py", line 7, in <module>
    from dolfin import *
  File "/opt/spack/opt/spack/linux-centos7-x86_64/intel-17.0.4/fenics-2017.1.0-zre3f5b4xo4u2z45jjnoeqvzzfv4l35m/lib/python2.7/site-packages/dolfin/__init__.py", line 17, in <module>
    from . import cpp
  File "/opt/spack/opt/spack/linux-centos7-x86_64/intel-17.0.4/fenics-2017.1.0-zre3f5b4xo4u2z45jjnoeqvzzfv4l35m/lib/python2.7/site-packages/dolfin/cpp/__init__.py", line 43, in <module>
    exec("from . import %s" % module_name)
  File "<string>", line 1, in <module>
  File "/opt/spack/opt/spack/linux-centos7-x86_64/intel-17.0.4/fenics-2017.1.0-zre3f5b4xo4u2z45jjnoeqvzzfv4l35m/lib/python2.7/site-packages/dolfin/cpp/common.py", line 21, in <module>
    _common = swig_import_helper()
  File "/opt/spack/opt/spack/linux-centos7-x86_64/intel-17.0.4/fenics-2017.1.0-zre3f5b4xo4u2z45jjnoeqvzzfv4l35m/lib/python2.7/site-packages/dolfin/cpp/common.py", line 20, in swig_import_helper
    return importlib.import_module('_common')
  File "/opt/spack/opt/spack/linux-centos7-x86_64/intel-17.0.4/python-2.7.13-ufhcwdrlqo7lt2i2otrgvmgh5f4jrzyt/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _common
bridges@wheeler-sn[503]>
```

### Information on your system

This includes:

 1. OpenHPC Running on CentOS 7.3

**Comment by alalazo** [comment]
For future reference.  A simple Google search points to similar problems in conda:

- https://github.com/conda-forge/fenics-feedstock/issues/15
- https://github.com/conda-forge/fenics-feedstock/issues/46

**Comment by patrickb314** [comment]
Yep, I've seen those as well. Using the lastest version of fenics in conda-forge with python=3 works, but it's easy to get conda builds that give the same error due to varying version mismatches. Importantly, the conda versions don't use MPI so there's a limit to the size of the models it can run, which is one of the reasons I was hoping the spack-directed version would work. I'm currently working on trying it from a pre-built singularity container, but a spack version would be good, too...

**Comment by alalazo** [comment]
@nrichart FYI

**Comment by patrickb314** [comment]
We, did, FWIW, resort to running it out of a singularity container. I expect there are some combination of build options that would make this work, but it's not clear what they are.

**Comment by patrickb314** [comment]
Haven't re-tested and problem addressed through other means.
