### ISSUE TITLE
Installing vanilla mesa fails on OSX

### ISSUE THREAD

**Issue by scottwittenburg** [spack/spack#6697]
On OSX High Sierra, simply installing mesa is failing for me.  I actually saw this before the spack mesa package was recently updated as well, so I don't think it was introduced with the addition mesa `17.2.3`.

### Build failure details

To reproduce this on OSX, just try to install mesa:

```console
$ spack -d install mesa
...
==> py-mako is already installed in /Users/scott/projects/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/py-mako-1.0.4-zmmyrrvplczvewgmjjhqpnzqi3eu2rwa
==> READ LOCK: /Users/scott/projects/spack/opt/spack/.spack-db/prefix_lock[7317439425521932713:1] [Released]
==> Installing mesa
==> '/Users/scott/projects/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/python-2.7.14-faeyyeltritkxvwaxv2hhlfy7n72scqa/bin/python2.7' '-c' 'from distutils.sysconfig import get_config_var; print get_config_var('"'"'prefix'"'"')'
==> '/Users/scott/projects/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/python-2.7.14-faeyyeltritkxvwaxv2hhlfy7n72scqa/bin/python2.7' '-c' 'from distutils.sysconfig import get_config_var; print get_config_var('"'"'prefix'"'"')'
==> link /Users/scott/projects/spack/var/spack/stage/mesa-17.2.3-7qg6kz7rtkbygadlxatj7qjoseuw2dv7 -> /tmp/scott/spack-stage/spack-stage-4ExYnw
==> Using cached archive: /Users/scott/projects/spack/var/spack/cache/mesa/mesa-17.2.3.tar.xz
==> Staging archive: /Users/scott/projects/spack/var/spack/stage/mesa-17.2.3-7qg6kz7rtkbygadlxatj7qjoseuw2dv7/mesa-17.2.3.tar.xz
==> '/usr/bin/tar' '-xf' '/Users/scott/projects/spack/var/spack/stage/mesa-17.2.3-7qg6kz7rtkbygadlxatj7qjoseuw2dv7/mesa-17.2.3.tar.xz'
==> Created stage in /Users/scott/projects/spack/var/spack/stage/mesa-17.2.3-7qg6kz7rtkbygadlxatj7qjoseuw2dv7
==> No patches needed for mesa
==> Building mesa [AutotoolsPackage]
==> WRITE LOCK: /Users/scott/projects/spack/var/spack/stage/.lock[7687979487936018491:1] [Acquiring]
==> WRITE LOCK: /Users/scott/projects/spack/var/spack/stage/.lock[7687979487936018491:1] [Acquired]
==> WRITE LOCK: /Users/scott/projects/spack/opt/spack/.spack-db/prefix_lock[9081212553426452929:1] [Acquiring]
==> WRITE LOCK: /Users/scott/projects/spack/opt/spack/.spack-db/prefix_lock[9081212553426452929:1] [Acquired]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> WRITE LOCK: /Users/scott/projects/spack/opt/spack/.spack-db/prefix_lock[9081212553426452929:1] [Released]
==> WRITE LOCK: /Users/scott/projects/spack/var/spack/stage/.lock[7687979487936018491:1] [Released]
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

7 errors found in build log:
     [ ... ]
     5275    CCLD     nir/libnir.la
     5276    CCLD     glsl/libglcpp.la
     5277    CXXLD    glsl/libglsl.la
     5278    CXXLD    spirv2nir
     5279  ld: warning: ignoring file ../../src/util/.libs/libmesautil.a, file was built for archive which is not the architecture being linked (x86_64): ../../src/util/.libs/libmesautil.a
     5280  ld: warning: ignoring file nir/.libs/libnir.a, file was built for archive which is not the architecture being linked (x86_64): nir/.libs/libnir.a
  >> 5281  Undefined symbols for architecture x86_64:
     5282    "_nir_print_shader", referenced from:
     5283        _main in spirv2nir-spirv2nir.o
     5284    "_spirv_to_nir", referenced from:
     5285        _main in spirv2nir-spirv2nir.o
     5286  ld: symbol(s) not found for architecture x86_64
  >> 5287  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 5288  make[4]: *** [spirv2nir] Error 1
     5289  make[4]: *** Waiting for unfinished jobs....
  >> 5290  make[3]: *** [all] Error 2
  >> 5291  make[2]: *** [all-recursive] Error 1
  >> 5292  make[1]: *** [all] Error 2
  >> 5293  make: *** [all-recursive] Error 1

See build log for details:
  /Users/scott/projects/spack/var/spack/stage/mesa-17.2.3-7qg6kz7rtkbygadlxatj7qjoseuw2dv7/mesa-17.2.3/spack-build.out
Traceback (most recent call last):
  File "/Users/scott/projects/spack/lib/spack/spack/build_environment.py", line 662, in child_process
    return_value = function()
  File "/Users/scott/projects/spack/lib/spack/spack/package.py", line 1444, in build_process
    phase(self.spec, self.prefix)
  File "/Users/scott/projects/spack/lib/spack/spack/package.py", line 114, in phase_wrapper
    phase(spec, prefix)
  File "/Users/scott/projects/spack/lib/spack/spack/build_systems/autotools.py", line 274, in build
    inspect.getmodule(self).make(*self.build_targets)
  File "/Users/scott/projects/spack/lib/spack/spack/build_environment.py", line 125, in __call__
    return super(MakeExecutable, self).__call__(*args, **kwargs)
  File "/Users/scott/projects/spack/lib/spack/spack/util/executable.py", line 183, in __call__
    proc.returncode, cmd_line)
ProcessError: Command exited with status 2:
    'make' '-j8'
```

Here is the build output log referenced above:

[spack-build.out.txt](https://github.com/spack/spack/files/1563611/spack-build.out.txt)

### System Information

I guess this is obvious from the pasted build results, but I encountered this error on:

* darwin-highsierra-x86_64
* clang-9.0.0-apple

I do not believe I have any relevant, machine-specific configuration like `packages.yaml` etc...

**Comment by erimar77** [comment]
Can you try commenting out the binutils dependency at line 60?  This resulted in a successful build for me.

**Comment by scottwittenburg** [comment]
Indeed, commenting out the `binutils` dependency resulted in a successful build for me as well.

**Comment by kwierman** [comment]
@erminar77 This has worked for me on this product plus a few others where I'm building on OSX and the product depends on `binutils`. Much thanks. Would it help to wrap this in an if statement along the lines of `if darwin in 'arch'`?

**Comment by erimar77** [comment]
@kwierman something like this would work, but I'm unfamiliar with the prerequisites of this software. 
```
depends_on('binutils', type='build', when=sys.platform != 'darwin')
```
