### ISSUE TITLE
linux-debianstable-updates-x86_64 is an invalid arch spec

### ISSUE THREAD

**Issue by healther** [spack/spack#7356]
Summary

Tried to use `spack` locally on one of our office PCs

### Expected Result

A working spack installation

### Steps to reproduce the issue

```console
$ git clone https://github.com/spack/spack.git
$ cd spack 
$ . share/spack/setup-env.sh 
$ spack install zlib
==> Error: linux-debianstable-updates-x86_64 is an invalid arch spec
```

### Information on your system

I'm not too sure what exactly this system is but 
```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
seems to indicate an unstable release and it seems that spack doesn't want to play with it. I'm completely out of my depth here...

edit: Fixed the `os-release` output, I first took it from my local machine (which works)

**Comment by scheibelp** [comment]
I'm curious if #7381 helps

**Comment by scheibelp** [comment]
Could you rerun with `-d`: `spack -d install...`

**Comment by healther** [comment]
```
$ spack -d install zlib
==> Reading config file /afs/kip.uni-heidelberg.de/user/wv385/spack/spack/etc/spack/defaults/packages.yaml
==> READ LOCK: /afsuser/wv385/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /afsuser/wv385/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /afsuser/wv385/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
Traceback (most recent call last):
  File "/afsuser/wv385/spack/spack/bin/spack", line 85, in <module>
    sys.exit(spack.main.main())
  File "/afs/kip.uni-heidelberg.de/user/wv385/spack/spack/lib/spack/spack/main.py", line 577, in main
    return _main(command, parser, args, unknown)
  File "/afs/kip.uni-heidelberg.de/user/wv385/spack/spack/lib/spack/spack/main.py", line 469, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/afs/kip.uni-heidelberg.de/user/wv385/spack/spack/lib/spack/spack/main.py", line 381, in _invoke_spack_command
    return_val = command(parser, args)
  File "/afs/kip.uni-heidelberg.de/user/wv385/spack/spack/lib/spack/spack/cmd/install.py", line 203, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/afs/kip.uni-heidelberg.de/user/wv385/spack/spack/lib/spack/spack/cmd/__init__.py", line 138, in parse_specs
    spec.concretize()  # implies normalize
  File "/afs/kip.uni-heidelberg.de/user/wv385/spack/spack/lib/spack/spack/spec.py", line 1811, in concretize
    self._concretize_helper())
  File "/afs/kip.uni-heidelberg.de/user/wv385/spack/spack/lib/spack/spack/spec.py", line 1658, in _concretize_helper
    (spack.concretizer.concretize_architecture(self),
  File "/afs/kip.uni-heidelberg.de/user/wv385/spack/spack/lib/spack/spack/concretize.py", line 218, in concretize_architecture
    sys_arch = spack.spec.ArchSpec(spack.architecture.sys_type())
  File "/afs/kip.uni-heidelberg.de/user/wv385/spack/spack/lib/spack/spack/spec.py", line 254, in __init__
    raise ValueError("%s is an invalid arch spec" % spec_like)
ValueError: linux-debianstable-updates-x86_64 is an invalid arch spec
```
