### ISSUE TITLE
anyone seeing problems with libpciaccess when building on Cray XC systems?

### ISSUE THREAD

**Issue by hppritcha** [spack/spack#7397]
-----

### Summary

I'm trying to install various packages on a Cray XC running CLE 6.0UP05, including HDF5, PMIx, OpenMPI, etc.  What I'm seeing is that installs fail if there is a dependency on the libpciaccess package. One cannot see this at NERSC - at least not on edison and cori since these systems are still running CLE 6UP04.  

### Actual Results

I've noticed dependencies on which SHA I'm on in develop, but at 35115127 I get this error
when trying to do a spack install libpciaccess
```
/scratch1/users/hpp/spack@ga-fe1:/scratch1/users/hpp/spack> (develop)spack install libpciaccess
==> libsigsegv is already installed in /scratch1/users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libsigsegv-2.11-tatqezxww74hs74fsldkwvpy6kf5isjp
==> m4 is already installed in /scratch1/users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/m4-1.4.18-uuicyh5c6ms2gfbfklywbkrqujjvepbe
==> libtool is already installed in /scratch1/users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libtool-2.4.6-sy3pq3d4f466lgiggepp3meln2tsomrx
==> pkgconf is already installed in /scratch1/users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/pkgconf-1.4.0-ph4es5l4lx5zv367oxkd6jm7dndysuzs
==> util-macros is already installed in /scratch1/users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/util-macros-1.19.1-exb3t3uusocfq3ou63vbscihaf2sq5i5
==> Installing libpciaccess
==> Error: SyntaxError: invalid syntax (<string>, line 494)
SyntaxError: SyntaxError: invalid syntax (<string>, line 494)

/scratch1/users/hpp/spack/lib/spack/spack/build_environment.py:684, in child_process:
     27    
     28                # build up some context from the offending package so we can
     29                # show that, too.
  >> 30                package_context = get_package_context(tb)
     31    
     32                build_log = None
     33                if hasattr(pkg, 'log_path'):

```
If I do a bit of patching on build_envrionment.py to bypass what appears to be a bug in spack itself when handling an exception 
```
==> Installing libpciaccess
Unloading module PrgEnv
Unloaded module PrgEnv
Unloading module PrgEnv-x1
Unloaded module PrgEnv-x1
Unloading module PrgEnv-x2
Unloaded module PrgEnv-x2
Unloading module PrgEnv-cray
Unloaded module PrgEnv-cray
Unloading module PrgEnv-intel
Unloaded module PrgEnv-intel
Unloading module PrgEnv-pgi
Unloaded module PrgEnv-pgi
Unloading module PrgEnv-pathscale
Unloaded module PrgEnv-pathscale
Unloading module PrgEnv-gnu
tb_string = Traceback (most recent call last):
  File "/scratch1/users/hpp/spack/lib/spack/spack/build_environment.py", line 665, in child_process
    setup_package(pkg, dirty=dirty)
  File "/scratch1/users/hpp/spack/lib/spack/spack/build_environment.py", line 617, in setup_package
    load_module(mod)
  File "/scratch1/users/hpp/spack/lib/spack/spack/util/module_cmd.py", line 135, in load_module
    error=str), '<string>', 'exec'))
  File "<string>", line 494
    rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari(21):ERROR:102: Tcl command execution failed: if { [ file exists /opt/cray/rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari/lib64/pkgconfig/cray-rca.pc ] } {
```
### Steps to reproduce the issue

First find a Cray XC or similar variant (not XE since I'm pretty sure CLE 6 isn't supported on these near end-of-life systems).  Make sure its running CLE 6.0UP05 by 

```
cat /etc/opt/cray/release/cle-release
```
and verifying that it reports CLE 6.0UP05.  Then,

```console
$ git clone git@github.com:spack/spack.git
$ cd spack
$ export PATH=$PWD/bin:$PATH
$ spack install libpciaccess
...
```

### Information on your system

 1.  Cray XC running CLE 6.0UP05
 2. Here's my module list before I do spack install
```
Currently Loaded Modulefiles:
  1) modules/3.2.10.6                               13) pmi/5.0.13
  2) eproxy/2.0.22-6.0.5.0_2.1__g1ebe45c.ari        14) dmapp/7.1.1-6.0.5.0_49.8__g1125556.ari
  3) gcc/7.2.0                                      15) gni-headers/5.0.12-6.0.5.0_2.15__g2ef1ebc.ari
  4) craype-haswell                                 16) xpmem/2.2.4-6.0.5.1_8.6__g35d5e73.ari
  5) craype-hugepages2M                             17) job/2.2.2-6.0.5.0_8.47__g3c644b5.ari
  6) craype-network-aries                           18) dvs/2.7_2.2.52-6.0.5.2_17.6__g5170dea
  7) craype/2.5.13                                  19) alps/6.5.28-6.0.5.0_18.6__g13a91b6.ari
  8) cray-mpich/7.7.0                               20) rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari
  9) slurm/17.02.9-SSE.6                            21) atp/2.1.1
 10) cray-libsci/17.12.1                            22) perftools-base/7.0.0
 11) udreg/2.3.2-6.0.5.0_13.12__ga14955a.ari        23) PrgEnv-gnu/6.0.4
 12) ugni/6.0.14-6.0.5.0_16.9__g19583bb.ari
```

-----

**Comment by mamelara** [comment]
that looks like the PKG_CONFIG_PATH error that my PR was suppose to resolve 😞 . What did Cray do in their new update??

**Comment by scheibelp** [comment]
Perhaps the location for `.pc` files moved? https://github.com/spack/spack/pull/7171 added `/usr/lib64/pkgconfig` and `/usr/local/lib64/pkgconfig` to `PKG_CONFIG_PATH` to resolve an error like this - do you see `.pc` files elsewhere (maybe `/usr/lib/pkgconfig`)?

**Comment by hppritcha** [comment]
the location of the problematic ```.pc``` files haven't moved from CLE 6 UP04 -> CLE 6 UP05.  They are in ```/usr/lib64/pkgconfig.```

**Comment by hppritcha** [comment]
@flouquet could you try this out on trinitite when its returned to users?

Just try steps above with a fresh spack clone -

```console
$ git clone git@github.com:spack/spack.git
$ cd spack
$ export PATH=$PWD/bin:$PATH
$ spack install libpciaccess
...
```

Other packages (but not all) fail with a similar signature, so its not something special about libpciaccess.

**Comment by hppritcha** [comment]
With @flouquet help I narrowed this problem down to this being present in my .bashrc (or .profile, doesn't matter) -
```
if $( echo ${LOADEDMODULES} | grep --quiet 'PrgEnv-intel' ); then
    module unload mpt
    module swap PrgEnv-intel PrgEnv-gnu
    module swap gcc gcc/7.1.0
fi
```
If I have the above in my .bashrc, here's what happens to spack as it tries to build libpciaccess
```
==> Installing libpciaccess
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'avail' '-t' 'craype-'
==> '/usr/bin/env' '-' 'USER=hpp' 'HOME=/users/hpp' '/bin/bash' '--noprofile' '--norc' '-c' '. /etc/profile; module list -lt'
==> Found default modules:
       modules/3.2.10.6
       eproxy/2.0.22-6.0.5.0_2.1__g1ebe45c.ari
       intel/17.0.4
       craype-network-aries
       craype/2.5.13
       cray-libsci/17.12.1
       udreg/2.3.2-6.0.5.0_13.12__ga14955a.ari
       ugni/6.0.14-6.0.5.0_16.9__g19583bb.ari
       pmi/5.0.13
       dmapp/7.1.1-6.0.5.0_49.8__g1125556.ari
       gni-headers/5.0.12-6.0.5.0_2.15__g2ef1ebc.ari
       xpmem/2.2.4-6.0.5.1_8.17__g35d5e73.ari
       job/2.2.2-6.0.5.0_8.47__g3c644b5.ari
       dvs/2.7_2.2.53-6.0.5.2_8.11__ge13250e
       alps/6.5.28-6.0.5.0_18.6__g13a91b6.ari
       rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari
       atp/2.1.1
       perftools-base/7.0.0
       PrgEnv-intel/6.0.4
       cray-mpich/7.7.0
       craype-haswell
       slurm/17.02.10-SSE.0
       craype-hugepages2M
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'PrgEnv-gnu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-x1'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-x2'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-cray'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-intel'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-pgi'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-pathscale'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-gnu'
==> Error: SyntaxError: invalid syntax (<string>, line 494)
SyntaxError: SyntaxError: invalid syntax (<string>, line 494)

/users/hpp/spack/lib/spack/spack/build_environment.py:684, in child_process:
     27
     28                # build up some context from the offending package so we can
     29                # show that, too.
  >> 30                package_context = get_package_context(tb)
     31
     32                build_log = None
     33                if hasattr(pkg, 'log_path'):


Traceback (most recent call last):
  File "/users/hpp/spack/lib/spack/spack/build_environment.py", line 665, in child_process
    setup_package(pkg, dirty=dirty)
  File "/users/hpp/spack/lib/spack/spack/build_environment.py", line 617, in setup_package
    load_module(mod)
  File "/users/hpp/spack/lib/spack/spack/util/module_cmd.py", line 134, in load_module
    error=str), '<string>', 'exec'))
  File "<string>", line 494
    rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari(21):ERROR:102: Tcl command execution failed: if { [ file exists /opt/cray/rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari/lib64/pkgconfig/cray-rca.pc ] } {
```
but if I don't have these lines the debug output from spack shows this
```
==> Installing libpciaccess
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'avail' '-t' 'craype-'
==> '/usr/bin/env' '-' 'USER=hpp' 'HOME=/users/hpp' '/bin/bash' '--noprofile' '--norc' '-c' '. /etc/profile; module list -lt'
==> Found default modules:
       modules/3.2.10.6
       eproxy/2.0.22-6.0.5.0_2.1__g1ebe45c.ari
       intel/17.0.4
       craype-network-aries
       craype/2.5.13
       cray-libsci/17.12.1
       udreg/2.3.2-6.0.5.0_13.12__ga14955a.ari
       ugni/6.0.14-6.0.5.0_16.9__g19583bb.ari
       pmi/5.0.13
       dmapp/7.1.1-6.0.5.0_49.8__g1125556.ari
       gni-headers/5.0.12-6.0.5.0_2.15__g2ef1ebc.ari
       xpmem/2.2.4-6.0.5.1_8.17__g35d5e73.ari
       job/2.2.2-6.0.5.0_8.47__g3c644b5.ari
       dvs/2.7_2.2.53-6.0.5.2_8.11__ge13250e
       alps/6.5.28-6.0.5.0_18.6__g13a91b6.ari
       rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari
       atp/2.1.1
       perftools-base/7.0.0
       PrgEnv-intel/6.0.4
       cray-mpich/7.7.0
       craype-haswell
       slurm/17.02.10-SSE.0
       craype-hugepages2M
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'PrgEnv-gnu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-x1'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-x2'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-cray'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-intel'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-pgi'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-pathscale'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'PrgEnv-gnu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'load' 'PrgEnv-gnu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'gcc'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'gcc-cross-aarch64'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'load' 'gcc/7.1.0'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'avail' '-t' 'craype-'
==> '/usr/bin/env' '-' 'USER=hpp' 'HOME=/users/hpp' '/bin/bash' '--noprofile' '--norc' '-c' '. /etc/profile; module list -lt'
==> Found default modules:
       modules/3.2.10.6
       eproxy/2.0.22-6.0.5.0_2.1__g1ebe45c.ari
       intel/17.0.4
       craype-network-aries
       craype/2.5.13
       cray-libsci/17.12.1
       udreg/2.3.2-6.0.5.0_13.12__ga14955a.ari
       ugni/6.0.14-6.0.5.0_16.9__g19583bb.ari
       pmi/5.0.13
       dmapp/7.1.1-6.0.5.0_49.8__g1125556.ari
       gni-headers/5.0.12-6.0.5.0_2.15__g2ef1ebc.ari
       xpmem/2.2.4-6.0.5.1_8.17__g35d5e73.ari
       job/2.2.2-6.0.5.0_8.47__g3c644b5.ari
       dvs/2.7_2.2.53-6.0.5.2_8.11__ge13250e
       alps/6.5.28-6.0.5.0_18.6__g13a91b6.ari
       rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari
       atp/2.1.1
       perftools-base/7.0.0
       PrgEnv-intel/6.0.4
       cray-mpich/7.7.0
       craype-haswell
       slurm/17.02.10-SSE.0
       craype-hugepages2M
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'avail' '-t' 'craype-'
==> '/usr/bin/env' '-' 'USER=hpp' 'HOME=/users/hpp' '/bin/bash' '--noprofile' '--norc' '-c' '. /etc/profile; module list -lt'
==> Found default modules:
       modules/3.2.10.6
       eproxy/2.0.22-6.0.5.0_2.1__g1ebe45c.ari
       intel/17.0.4
       craype-network-aries
       craype/2.5.13
       cray-libsci/17.12.1
       udreg/2.3.2-6.0.5.0_13.12__ga14955a.ari
       ugni/6.0.14-6.0.5.0_16.9__g19583bb.ari
       pmi/5.0.13
       dmapp/7.1.1-6.0.5.0_49.8__g1125556.ari
       gni-headers/5.0.12-6.0.5.0_2.15__g2ef1ebc.ari
       xpmem/2.2.4-6.0.5.1_8.17__g35d5e73.ari
       job/2.2.2-6.0.5.0_8.47__g3c644b5.ari
       dvs/2.7_2.2.53-6.0.5.2_8.11__ge13250e
       alps/6.5.28-6.0.5.0_18.6__g13a91b6.ari
       rca/2.2.16-6.0.5.0_15.34__g5e09e6d.ari
       atp/2.1.1
       perftools-base/7.0.0
       PrgEnv-intel/6.0.4
       cray-mpich/7.7.0
       craype-haswell
       slurm/17.02.10-SSE.0
       craype-hugepages2M
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'craype-haswell'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-abudhabi'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-abudhabi-cu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-barcelona'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtep-haswell'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-intel-knc'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-interlagos'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-interlagos-cu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-istanbul'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-ivybridge'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-mc8'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-mc12'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-mic-knl'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-sandybridge'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-shanghai'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'xtpe-xeon'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-abudhabi'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-abudhabi-cu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-barcelona'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-broadwell'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-haswell'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-intel-knc'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-interlagos'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-interlagos-cu'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-istanbul'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-ivybridge'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-mc8'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-mc12'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-mic-knl'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-sandybridge'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-shanghai'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-x86-skylake'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-xeon'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-aarch64'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'unload' 'craype-arm-thunderx'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'load' 'craype-haswell'
==> Fetching http://xorg.freedesktop.org/archive/individual/lib/libpciaccess-0.13.5.tar.gz
==> '/usr/bin/curl' '-C' '-' '-o' '/users/hpp/spack/var/spack/stage/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/libpciaccess-0.13.5.tar.gz.part' '-f' '-D' '-' '-L' 'http://xorg.freedesktop.org/archive/individual/lib/libpciaccess-0.13.5.tar.gz' '-#'
######################################################################## 100.0%
==> Staging archive: /users/hpp/spack/var/spack/stage/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/libpciaccess-0.13.5.tar.gz
==> '/bin/tar' '-xf' '/users/hpp/spack/var/spack/stage/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/libpciaccess-0.13.5.tar.gz'
==> Created stage in /users/hpp/spack/var/spack/stage/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76
==> No patches needed for libpciaccess
==> Building libpciaccess [AutotoolsPackage]
==> WRITE LOCK: /users/hpp/spack/var/spack/stage/.lock[7393830076270277311:1] [Acquiring]
==> WRITE LOCK: /users/hpp/spack/var/spack/stage/.lock[7393830076270277311:1] [Acquired]
==> WRITE LOCK: /users/hpp/spack/opt/spack/.spack-db/prefix_lock[7235523982311068755:1] [Acquiring]
==> WRITE LOCK: /users/hpp/spack/opt/spack/.spack-db/prefix_lock[7235523982311068755:1] [Acquired]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Installing /users/hpp/spack/var/spack/stage/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/libpciaccess-0.13.5/spack-build.out to /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/.spack/build.out
==> Installing /users/hpp/spack/var/spack/stage/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/libpciaccess-0.13.5/spack-build.env to /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/.spack/build.env
==> Installing /users/hpp/spack/var/spack/repos/builtin/packages/libpciaccess/package.py to /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/.spack/repos/builtin/packages/libpciaccess
==> Installing /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libtool-2.4.6-sy3pq3d4f466lgiggepp3meln2tsomrx/.spack/repos/builtin/packages/libtool to /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/.spack/repos/builtin/packages/libtool
==> Installing /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/m4-1.4.18-uuicyh5c6ms2gfbfklywbkrqujjvepbe/.spack/repos/builtin/packages/m4 to /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/.spack/repos/builtin/packages/m4
==> Installing /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libsigsegv-2.11-tatqezxww74hs74fsldkwvpy6kf5isjp/.spack/repos/builtin/packages/libsigsegv to /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/.spack/repos/builtin/packages/libsigsegv
==> Installing /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/pkgconf-1.4.0-ph4es5l4lx5zv367oxkd6jm7dndysuzs/.spack/repos/builtin/packages/pkgconf to /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/.spack/repos/builtin/packages/pkgconf
==> Installing /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/util-macros-1.19.1-exb3t3uusocfq3ou63vbscihaf2sq5i5/.spack/repos/builtin/packages/util-macros to /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76/.spack/repos/builtin/packages/util-macros
==> READ LOCK: /users/hpp/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /users/hpp/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /users/hpp/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> 	WRITE: libpciaccess@0.13.5%gcc@7.1.0 arch=cray-CNL-haswell /zdjx247 [/users/hpp/spack/share/spack/modules/cray-CNL-haswell/libpciaccess-0.13.5-gcc-7.1.0-zdjx247]
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> READ LOCK: /users/hpp/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /users/hpp/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /users/hpp/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> 	WRITE: libpciaccess@0.13.5%gcc@7.1.0 arch=cray-CNL-haswell /zdjx247 [/users/hpp/spack/share/spack/dotkit/cray-CNL-haswell/libpciaccess-0.13.5-gcc-7.1.0-zdjx247.dk]
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'list'
==> '/opt/cray/pe/modules/3.2.10.6/bin/modulecmd' 'python' 'show' 'gcc/7.1.0'
==> WRITE LOCK: /users/hpp/spack/opt/spack/.spack-db/prefix_lock[7235523982311068755:1] [Released]
==> WRITE LOCK: /users/hpp/spack/var/spack/stage/.lock[7393830076270277311:1] [Released]
==> Successfully installed libpciaccess
  Fetch: 0.60s.  Build: 6.36s.  Total: 6.96s.
[+] /users/hpp/spack/opt/spack/cray-CNL-haswell/gcc-7.1.0/libpciaccess-0.13.5-zdjx247s6eukpmaeykejc3uyx7botc76
==> WRITE LOCK: /users/hpp/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> WRITE LOCK: /users/hpp/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> WRITE LOCK: /users/hpp/spack/opt/spack/.spack-db/lock[0:0] [Released]
```

**Comment by hppritcha** [comment]
I also noticed a different way to get libpciaccess to install is to edit out this dependency in the libpciaccess package.py:

```
--- a/var/spack/repos/builtin/packages/libpciaccess/package.py
+++ b/var/spack/repos/builtin/packages/libpciaccess/package.py
@@ -35,5 +35,5 @@ class Libpciaccess(AutotoolsPackage):
     version('0.13.4', 'cc1fad87da60682af1d5fa43a5da45a4')
 
     depends_on('libtool', type='build')
-    depends_on('pkgconfig', type='build')
+#    depends_on('pkgconfig', type='build')
     depends_on('util-macros', type='build')
```

**Comment by hppritcha** [comment]
i decided to close this since I've figured out workarounds for my spack setup that I can tell others to use if they hit this problem
