### ISSUE TITLE
modulecmd fails to load already loaded modules

### ISSUE THREAD

**Issue by f-sim** [spack/spack#7420]
I have the following situation:

On the HPC cluster I use the intel compiler is provided by a module (intel/16.0). So I have the following in my compilers.yaml:
```
modules:
- intel/16.0
```

If I run some spec (e.g., ```spack -d spec openfoam-com```) I get the following output
```
==> Reading config file /root/cluster/home/user/Software/spack/etc/spack/defaults/packages.yaml
==> Reading config file /home/user/.spack/packages.yaml
==> READ LOCK: /home/user/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /home/user/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /home/user/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> '/usr/bin/ibv_devices'
==> Reading config file /home/user/.spack/linux/compilers.yaml
==> '/usr/bin/tclsh' '/usr/local_rwth/modules/src/' 'python' 'list'
==> Warning: Could not detect module function from bash. Trying to detect modulecmd from `which`
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'list'
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'show' 'intel/16.0'
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'list'
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'load' 'intel/16.0'
==> '/usr/bin/tclsh' '/usr/local_rwth/modules/src/' 'python' 'list'
==> Warning: Could not detect module function from bash. Trying to detect modulecmd from `which`
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'list'
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'show' 'cmake/3.10.1'
==> '/usr/bin/tclsh' '/usr/local_rwth/modules/src/' 'python' 'list'
==> Warning: Could not detect module function from bash. Trying to detect modulecmd from `which`
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'list'
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'show' 'intel/16.0'
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'list'
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'load' 'intel/16.0'
==> '/root/cluster/home/user/Software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/environment-modules-3.2.10-umhcypeub6lma7y6wv2tvwcvr75mh4ag/Modules/bin/modulecmd' 'python' 'load' 'intel/16.0'
Input spec
--------------------------------
openfoam-com

Concretized
--------------------------------
Traceback (most recent call last):
  File "/root/cluster/home/user/Software/spack/bin/spack", line 85, in <module>
    sys.exit(spack.main.main())
  File "/root/cluster/home/user/Software/spack/lib/spack/spack/main.py", line 577, in main
    return _main(command, parser, args, unknown)
  File "/root/cluster/home/user/Software/spack/lib/spack/spack/main.py", line 469, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/root/cluster/home/user/Software/spack/lib/spack/spack/main.py", line 381, in _invoke_spack_command
    return_val = command(parser, args)
  File "/root/cluster/home/user/Software/spack/lib/spack/spack/cmd/spec.py", line 85, in spec
    spec.concretize()
  File "/root/cluster/home/user/Software/spack/lib/spack/spack/spec.py", line 1875, in concretize
    load_module(mod)
  File "/root/cluster/home/user/Software/spack/lib/spack/spack/util/module_cmd.py", line 144, in load_module
    exec(compile(load, '<string>', 'exec'))
  File "<string>", line 1
    intel/16.0 already loaded, doing nothing                                                                                                                                                                                      [ WARNING ]
                     ^
SyntaxError: invalid syntax
```

Obviously, the the intel/16.0 module is loaded several times but never unloaded. Further, I saw that the issue arises in https://github.com/spack/spack/blob/develop/lib/spack/spack/util/module_cmd.py#137. In case, the module is already loaded, it writes a message to stderr and nothing to stdout. Therefore, in line 138 the if is true.

I wonder what the best solution is. I added the following:
```
loaded = modulecmd('list', output=str, error=str)
if mod in loaded:
  return
```

By this, I check if the module is already loaded. However, I do not know if this is a good solution. Would it be better to unload the module at some position? I do not know where the origin is. The issue does not appear for every package. E.g., ```spack spec boost``` works without any issues.

**Comment by becker33** [comment]
The module_cmd implementation was refactored in ways that make this issue irrelevant.
