### ISSUE TITLE
Question about module generation involving the openspeedshop and python packages 

### ISSUE THREAD

**Issue by jgalarowicz** [spack/spack#7678]
Summary

After a spack build of openspeedshop, I load the openspeedshop module file.   When I execute openspeedshop's "openss -cli" command.   I get python errors.   If I load the python module, then when I execute the "openss -cli" command, all is well.

I had thought that just loading the openspeedshop module would be enough for it to function properly.
Maybe that is not the expected result, so I'm posting the issue to see what is expected.

Maybe the openspeedshop spec file is supposed to add something to the module file to fix the python dependency.  I'm not sure what that would be.  It looks like spack python it accessing the system python.

Here is the scenario:

```
modules/linux-sles12-x86_64> module load openspeedshop-2.3.1-gcc-4.8-t34et3a
modules/linux-sles12-x86_64> openss -cli
Traceback (most recent call last):
  File "init.py", line 27, in <module>
  File "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/python-2.7.14-buxkxinpr2nlrvl5us2zmds54zbpwpx3/lib/python2.7/shutil.py", line 12, in <module>
    import collections
  File "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/python-2.7.14-buxkxinpr2nlrvl5us2zmds54zbpwpx3/lib/python2.7/collections.py", line 20, in <module>
    from _collections import deque, defaultdict
ImportError: /usr/lib/python2.7/lib-dynload/_collections.so: wrong ELF class: ELFCLASS32
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Welcome to OpenSpeedShop 2.3.1
openss>>NameError: name 'myparse' is not defined
```

If I load the python module, then openspeedshop functions as expected.

modules/linux-sles12-x86_64> module load python-2.7.14-gcc-4.8-buxkxin
modules/linux-sles12-x86_64> openss -cli
openss>>Welcome to OpenSpeedShop 2.3.1
openss>>help

Open|SpeedShop is a performance tool brought
to you by The Krell Institute and sponsors.
 

### Expected Result

What you expected

I had thought that just loading the openspeedshop module would be enough for it to function properly.
Maybe that is not the expected result, that is why I'm asking.
Maybe the openspeedshop spec file is supposed to add something to the module file to fix the python dependency.  I'm not sure what that would be.  It looks like spack python it accessing the system python.

### Actual Result

What happened instead

I had to load the python module that was used as part of the openspeedshop build.

### Steps to reproduce the issue

```
I used this command to build:

$ spack install openspeedshop +cbtf+mpich %gcc@4.8

```

### Information on your system
```
This includes: 
1. which platform you are using

linux-sles12-x86_64/gcc-4.8> uname -a
Linux tt-fey1 4.4.114-94.11-default #1 SMP Thu Feb 1 19:28:26 UTC 2018 (4309ff9) x86_64 x86_64 x86_64 GNU/Linux

 2. any relevant configuration detail (custom `packages.yaml` or `modules.yaml`, etc.)
linux-sles12-x86_64/gcc-4.8> cat ~/.spack/linux/packages.yaml 
packages:
   all:
      providers:
         pkgconfig: [pkg-config]
   mpich:
      buildable: False
      paths:
         mpich@7.6.2%gcc@4.8 arch=cray-CNL-haswell: /opt/cray/pe/mpt/7.7.0/gni/mpich-gnu/5.1

```

**Comment by adamjstewart** [comment]
There are a couple of problems here. First of all, `openspeedshop` doesn't mention that Python is needed at runtime:
```python
depends_on("python")
```
The default dependency type is `('build', 'link')`, meaning that Python should be in the `PATH` at build time, should be linked to when compiling, but you can uninstall it for all Spack cares because it isn't needed at runtime. You'll need to specify the dependency type if you want it available at runtime.

The second problem (which may or may not be a problem) is that as far as I know Spack doesn't add runtime dependencies when you load a module for a package? You can explicitly tell Spack to do this. See http://spack.readthedocs.io/en/latest/module_file_support.html#autoload-dependencies

@alalazo Is there any reason that Spack doesn't automatically add `type='run'` PATHS to a module file? If it's needed at runtime, the module file should autoload that dependency. (Correct me if I'm wrong and it already does this).

**Comment by jgalarowicz** [comment]
@adamjstewart @alalazo Thanks for the information!    I thought the depends_on without link or build defaulted to run.   I will try adding type=run to the python depends_on and will report the result back to this issue.   Thanks again!

**Comment by jgalarowicz** [comment]
@adamjstewart @alalazo I changed the openspeedshop package.py file in this way:
```
     depends_on("dyninst@9.3.2")
-    depends_on("python")
+    depends_on("python", type='run')
     depends_on("libxml2+python")
```
The problem still persists with python as shown above.   The module file generated doesn't appear to have changed.   python only shows up in the configure options.

```
modules/linux-sles12-x86_64> cat openspeedshop-2.3.1-gcc-4.8-fpunsyf
#%Module1.0
## Module file created by spack (https://github.com/spack/spack) on 2018-04-05 18:32:09.890602
##
## openspeedshop@2.3.1%gcc@4.8 build_type=None +cbtf~crayfe~cti~cuda gui=qt3 +mpich~mpich2~mpt~mvapich~mvapich2~offline~openmpi~runtime arch=linux-sles12-x86_64 /fpunsyf
##
## Configure options: -DBINUTILS_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/binutils-2.29.1-5ooh3gkvwt6i37gp3b6fdccogl7hdgty -DLIBELF_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/elfutils-0.170-zgcr3f7n3zl7m3hqm2jtsxp34bqhwzzi -DLIBDWARF_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/libdwarf-20160507-imcv52lmydp35h3seikq3yehm3tzjav5 -DPYTHON_EXECUTABLE=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/python-2.7.14-buxkxinpr2nlrvl5us2zmds54zbpwpx3/bin/python2.7 -DPYTHON_INCLUDE_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/python-2.7.14-buxkxinpr2nlrvl5us2zmds54zbpwpx3/include/python2.7 -DPYTHON_LIBRARY=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/python-2.7.14-buxkxinpr2nlrvl5us2zmds54zbpwpx3/lib/libpython2.7.so -DBoost_NO_SYSTEM_PATHS=TRUE -DBoost_NO_BOOST_CMAKE=TRUE -DBOOST_ROOT=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/boost-1.59.0-lf2kg4ihbgv3toaxoi6jsr4txc4cinyy -DBoost_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/boost-1.59.0-lf2kg4ihbgv3toaxoi6jsr4txc4cinyy -DBOOST_LIBRARYDIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/boost-1.59.0-lf2kg4ihbgv3toaxoi6jsr4txc4cinyy/lib -DDYNINST_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/dyninst-9.3.2-rsg6cipjpesgqbgtvewj5bc7egohw5uu -DCMAKE_CXX_FLAGS=-O2 -g -DCMAKE_C_FLAGS=-O2 -g -DINSTRUMENTOR=cbtf -DSQLITE3_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/sqlite-3.21.0-ml4bmaamsq2qfvud4a5ixuhrqs6bxo7q -DCBTF_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/cbtf-1.9.1-4ghvtbdpcgrzfswwsjr5ehgrujwubnez -DCBTF_KRELL_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/cbtf-krell-1.9.1-i43l2as7pav3nbkwkfpnvdni4ypraehr -DMRNET_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/mrnet-5.0.1-3-qy3o3gdd7uvnme2gej52riorsmbvqhh3 -DQTLIB_DIR=/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/qt-3.3.8b-ubfq3rrv27a3talssx3snaddhef6miho
##


module-whatis "OpenSpeedShop is a community effort by The Krell Institute with current direct funding from DOEs NNSA. It builds on top of a broad list of community infrastructures, most notably Dyninst and MRNet from UW, libmonitor from Rice, and PAPI from UTK. OpenSpeedShop is an open source multi platform Linux performance tool which is targeted to support performance analysis of applications running on both single node and large scale IA64, IA32, EM64T, AMD64, PPC, ARM, Power8, Intel Phi, Blue Gene and Cray platforms. OpenSpeedShop development is hosted by the Krell Institute. The infrastructure and base components of OpenSpeedShop are released as open source code primarily under LGPL. "

proc ModulesHelp { } {
puts stderr "OpenSpeedShop is a community effort by The Krell Institute with current"
puts stderr "direct funding from DOEs NNSA. It builds on top of a broad list of"
puts stderr "community infrastructures, most notably Dyninst and MRNet from UW,"
puts stderr "libmonitor from Rice, and PAPI from UTK. OpenSpeedShop is an open source"
puts stderr "multi platform Linux performance tool which is targeted to support"
puts stderr "performance analysis of applications running on both single node and"
puts stderr "large scale IA64, IA32, EM64T, AMD64, PPC, ARM, Power8, Intel Phi, Blue"
puts stderr "Gene and Cray platforms. OpenSpeedShop development is hosted by the"
puts stderr "Krell Institute. The infrastructure and base components of OpenSpeedShop"
puts stderr "are released as open source code primarily under LGPL."
}


prepend-path PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/openspeedshop-2.3.1-fpunsyf3ocxeewyu33ruwq4fqvlgftib/bin"
prepend-path MANPATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/openspeedshop-2.3.1-fpunsyf3ocxeewyu33ruwq4fqvlgftib/share/man"
prepend-path LIBRARY_PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/openspeedshop-2.3.1-fpunsyf3ocxeewyu33ruwq4fqvlgftib/lib64"
prepend-path LD_LIBRARY_PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/openspeedshop-2.3.1-fpunsyf3ocxeewyu33ruwq4fqvlgftib/lib64"
prepend-path CPATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/openspeedshop-2.3.1-fpunsyf3ocxeewyu33ruwq4fqvlgftib/include"
prepend-path CMAKE_PREFIX_PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/openspeedshop-2.3.1-fpunsyf3ocxeewyu33ruwq4fqvlgftib/"
prepend-path PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/openspeedshop-2.3.1-fpunsyf3ocxeewyu33ruwq4fqvlgftib/bin"
setenv DYNINSTAPI_RT_LIB "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/dyninst-9.3.2-rsg6cipjpesgqbgtvewj5bc7egohw5uu/lib/libdyninstAPI_RT.so"
prepend-path LD_LIBRARY_PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/openspeedshop-2.3.1-fpunsyf3ocxeewyu33ruwq4fqvlgftib/lib64"
setenv OPENSS_RAWDATA_DIR "."
setenv XPLAT_RSH "ssh"
setenv MRNET_COMM_PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/cbtf-krell-1.9.1-i43l2as7pav3nbkwkfpnvdni4ypraehr/sbin/cbtf_mrnet_commnode"
setenv CBTF_MRNET_BACKEND_PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/cbtf-krell-1.9.1-i43l2as7pav3nbkwkfpnvdni4ypraehr/sbin/cbtf_libcbtf_mrnet_backend"
prepend-path PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/mrnet-5.0.1-3-qy3o3gdd7uvnme2gej52riorsmbvqhh3/bin"
prepend-path PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/cbtf-krell-1.9.1-i43l2as7pav3nbkwkfpnvdni4ypraehr/bin"
prepend-path PATH "/usr/projects/packages/openspeedshop/jegsgi/generic_spack/spack/opt/spack/linux-sles12-x86_64/gcc-4.8/cbtf-krell-1.9.1-i43l2as7pav3nbkwkfpnvdni4ypraehr/sbin"

```

**Comment by alalazo** [comment]
Apologies for the very late reply. Autoloading dependencies on module files must be enabled explicitly, [see here](https://spack-tutorial.readthedocs.io/en/latest/tutorial_modules.html#autoload-dependencies). I'll be closing the issue as I think this answer the question, but feel free to reopen or file a new one if problems persist.
