### ISSUE TITLE
py-py2cairo with python3 build error

### ISSUE THREAD

**Issue by gozwei** [spack/spack#7700]
I'm trying to install `pygtk` for `python3`

`spack install --use-cache py-pygtk%gcc@7.3.0 ^python@3.6.5 ^glib@2.55.1`

I need to specify `^glib@2.55.1` because newer glib fails to compile on our HPC (https://github.com/spack/spack/issues/7607)

Multiple dependencies are installed successfully, until: 

```==> Installing py-py2cairo
==> Searching for binary cache of py-py2cairo
==> Warning: No Spack mirrors are currently configured
==> No binary for py-py2cairo found: installing from source
==> Using cached archive: /cfs/fs2/home/users/mpolkowski/spack/var/spack/cache/py-py2cairo/py-py2cairo-1.10.0.tar.bz2
==> Staging archive: /cfs/fs2/home/users/mpolkowski/spack/var/spack/stage/py-py2cairo-1.10.0-orta3kep6zvdrj6kf3emg27wnyoxsmlp/py2cairo-1.10.0.tar.bz2
==> Created stage in /cfs/fs2/home/users/mpolkowski/spack/var/spack/stage/py-py2cairo-1.10.0-orta3kep6zvdrj6kf3emg27wnyoxsmlp
==> No patches needed for py-py2cairo
==> Building py-py2cairo [WafPackage]
==> Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 2:
    '/cfs/fs2/home/users/mpolkowski/spack/opt/spack/linux-scientific6-x86_64/gcc-7.3.0/python-3.6.5-an4tzucegt4pvrhczfszojh7xp2u3bt2/bin/python3.6' 'waf' '-j20' 'configure' '--prefix=/cfs/fs2/home/users/mpolkowski/spack/opt/spack/linux-scientific6-x86_64/gcc-7.3.0/py-py2cairo-1.10.0-orta3kep6zvdrj6kf3emg27wnyoxsmlp'
See build log for details:
  /cfs/fs2/home/users/mpolkowski/spack/var/spack/stage/py-py2cairo-1.10.0-orta3kep6zvdrj6kf3emg27wnyoxsmlp/py2cairo-1.10.0/spack-build.out
```
`spack-build.out` contents: 

```==> Executing phase: 'configure'
==> '/cfs/fs2/home/users/mpolkowski/spack/opt/spack/linux-scientific6-x86_64/gcc-7.3.0/python-3.6.5-an4tzucegt4pvrhczfszojh7xp2u3bt2/bin/python3.6' 'waf' '-j20' 'configure' '--prefix=/cfs/fs2/home/users/mpolkowski/spack/opt/spack/linux-scientific6-x86_64/gcc-7.3.0/py-py2cairo-1.10.0-orta3kep6zvdrj6kf3emg27wnyoxsmlp'
Setting top to                           : /ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0 
Setting out to                           : /ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/build_directory 
Checking for 'gcc' (c compiler)          : ok 
Checking for program python              : /cfs/fs2/home/users/mpolkowski/spack/opt/spack/linux-scientific6-x86_64/gcc-7.3.0/python-3.6.5-an4tzucegt4pvrhczfszojh7xp2u3bt2/bin/python 
python executable '/cfs/fs2/home/users/mpolkowski/spack/opt/spack/linux-scientific6-x86_64/gcc-7.3.0/python-3.6.5-an4tzucegt4pvrhczfszojh7xp2u3bt2/bin/python' different from sys.executable '/cfs/fs2/home/users/mpolkowski/spack/opt/spack/linux-scientific6-x86_64/gcc-7.3.0/python-3.6.5-an4tzucegt4pvrhczfszojh7xp2u3bt2/bin/python3.6'
Checking for python version              : (3, 6, 5, 'final', 0) 
Checking for library python3.6           :   ./options()
  ./configure()
Traceback (most recent call last):
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Scripting.py", line 93, in waf_entry_point
    run_commands()
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Scripting.py", line 145, in run_commands
    run_command(cmd_name)
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Scripting.py", line 138, in run_command
    ctx.execute()
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Configure.py", line 124, in execute
    super(ConfigurationContext,self).execute()
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Context.py", line 127, in recurse
    user_function(self)
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/wscript", line 29, in configure
    ctx.check_python_headers()
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Configure.py", line 214, in fun
    return f(*k,**kw)
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Tools/python.py", line 133, in check_python_headers
    result=conf.check(lib=name,uselib='PYEMBED',libpath=path,mandatory=False)
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Configure.py", line 214, in fun
    return f(*k,**kw)
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Tools/c_config.py", line 357, in check
    ret=self.run_c_code(*k,**kw)
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Configure.py", line 214, in fun
    return f(*k,**kw)
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Tools/c_config.py", line 435, in run_c_code
    bld.compile()
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Build.py", line 191, in compile
    self.store()
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Utils.py", line 300, in f
    ret=fun(*k,**kw)
  File "/ram/tmp/mpolkowski/spack-stage/spack-stage-Gau3VJ/py2cairo-1.10.0/.waf3-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Build.py", line 164, in store
    cPickle.dump(data,f)
AttributeError: Can't pickle local object 'Context.__init__.<locals>.node_class'
```

If I do `spack install --use-cache py-pygtk%gcc@7.3.0 ^python@2.7.14 ^glib@2.55.1` it installs with no error.

**Comment by healther** [comment]
If I read https://cairographics.org/pycairo/ correctly then `py2cairo` is the python2 version of the cairo python bindings. Can you try to change the dependency in `pypygtk` to `pycairo`

**Comment by adamjstewart** [comment]
> Since version 1.11.0 pycairo has moved to GitHub and pycairo and py2cairo have been merged back into one project.

I think @healther is right, can you try replacing the `py-py2cairo` dependency with `py-pycairo` and see if that works? We may also want to drop the `py-py2cairo` dependency in `py-pygobject`. The default version of Python in Spack will be Python 3 soon, so it's important to clean up these lingering Python 3 issues.

**Comment by alalazo** [comment]
Default Python version is already Python 3 and Python 2 has been deprecated. Closing.
