### ISSUE TITLE
spack versions/checksum crashes for packages without URL

### ISSUE THREAD

**Issue by adamjstewart** [spack/spack#7798]
Many packages download via git, not via a URL. For these packages, running `spack versions` or `spack checksum` produces a useless error message.

### Expected Result

I would like to see something like this:
```console
$ spack versions stream
==> Safe versions (already checksummed):
  5.10
==> Remote versions (not yet checksummed):
  Found no versions for stream
```

### Actual Result

```console
$ spack versions stream
==> Error: <class 'spack.pkg.builtin.stream.Stream'>
```

**Comment by adamjstewart** [comment]
A slightly more useful error message:
```console
$ spack -d versions stream
==> Reading config file /Users/Adam/spack/etc/spack/defaults/modules.yaml
==> Error: <class 'spack.pkg.builtin.stream.Stream'>
Traceback (most recent call last):
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 469, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 381, in _invoke_spack_command
    return_val = command(parser, args)
  File "/Users/Adam/spack/lib/spack/spack/cmd/versions.py", line 45, in versions
    fetched_versions = pkg.fetch_remote_versions()
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 2094, in fetch_remote_versions
    raise spack.util.web.VersionFetchError(self.__class__)
spack.util.web.VersionFetchError: <exception str() failed>
```

**Comment by healther** [comment]
This probably ties into the whole "prefetch a repository-based package"-problem. I don't find the issue/PR right now but I know that at some point we discussed that it would be necessary to be able to do `spack fetch <git-based-package>` in order to build git-based packages on air gapped machines. But I don't think this went anywhere did it?
