### ISSUE TITLE
Bug Running from Non-Existant Directory

### ISSUE THREAD

**Issue by citibeth** [spack/spack#7872]
If you run from a non-existant directory, you get this wonderful error message upon Spack startup:

```
$ spack --debug env twoway-dev concretize
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Traceback (most recent call last):
  File "/home2/rpfische/spack6/bin/spack", line 85, in <module>
    sys.exit(spack.main.main())
  File "/home2/rpfische/spack6/lib/spack/spack/main.py", line 577, in main
    return _main(command, parser, args, unknown)
  File "/home2/rpfische/spack6/lib/spack/spack/main.py", line 460, in _main
    set_working_dir()
  File "/home2/rpfische/spack6/lib/spack/spack/main.py", line 97, in set_working_dir
    os.chdir(spack.spack_prefix)
AttributeError: 'module' object has no attribute 'spack_prefix'
```

Running from a non-existant directory is easy to do if you are using Spack environments.  Every time you run `spack env` from within the environment directory, Spack overwrites your CWD and leaves you dangling.  To fix it, you have to run:
```
cd `pwd`
```

**Comment by alalazo** [comment]
I think this was fixed, but feel free to reopen if I'm wrong.
