### ISSUE TITLE
Compilers Requiring Modules Broken

### ISSUE THREAD

**Issue by citibeth** [spack/spack#8131]
@mamelara  I'm getting the following error on `spack install`:

```
('rrrrrrrpaths', ['/gpfsm/dnb53/rpfische/spack6/opt/spack/linux-suse_linux11-x86_64/gcc-5.3.0/zlib-1.2.11-hi5w6recfqqqffad6vsnidjx3zy2js6k/lib', '/gpfsm/dnb53/rpfische/spack6/opt/spack/linux-suse_linux11-x86_64/gcc-5.3.0/zlib-1.2.11-hi5w6recfqqqffad6vsnidjx3zy2js6k/lib64', None])
==> Error: TypeError: sequence item 2: expected string, NoneType found
TypeError: TypeError: sequence item 2: expected string, NoneType found

/gpfsm/dnb53/rpfische/spack6/lib/spack/spack/build_environment.py:689, in child_process:
     27    
     28                # build up some context from the offending package so we can
     29                # show that, too.
  >> 30                package_context = get_package_context(tb)
     31    
     32                build_log = None
     33                if hasattr(pkg, 'log_path'):


Traceback (most recent call last):
  File "/gpfsm/dnb53/rpfische/spack6/lib/spack/spack/build_environment.py", line 670, in child_process
    setup_package(pkg, dirty=dirty)
  File "/gpfsm/dnb53/rpfische/spack6/lib/spack/spack/build_environment.py", line 607, in setup_package
    set_module_variables_for_package(pkg, pkg.module)
  File "/gpfsm/dnb53/rpfische/spack6/lib/spack/spack/build_environment.py", line 374, in set_module_variables_for_package
    m.std_cmake_args = spack.CMakePackage._std_args(pkg)
  File "/gpfsm/dnb53/rpfische/spack6/lib/spack/spack/build_systems/cmake.py", line 168, in _std_args
    rpaths = ';'.join(spack.build_environment.get_rpaths(pkg))
TypeError: sequence item 2: expected string, NoneType found
```

This is code from 175a042fd332c13200fb30f7f834541c3bbaa6c4:
```
Author: Mario Melara <maamelara@gmail.com>
Date:   Thu May 19 16:42:13 2016 -0700

    Changed rpaths method so that it only grabs rpaths using the compiler module
 name instead of PrgEnv-x module name
```
Questions:

1. Do you know why the `rpaths` varaible ends up with a `None` in it?
2. Why is the second module our compiler name?  That doesn't make sense to me.  I have in `compilers.yaml`:
```
compilers:
- compiler:
    modules: [other/comp/gcc-5.3-sp3,linux-suse_linux11-x86_64/binutils-2.27-gcc-5.3.0-p7ewifc]
```
3. What is wrong and how should it best be fixed?  (I'm NOT running on a Cray).

**Comment by mamelara** [comment]
Perhaps I should improve the wording in that section...

So when we get the rpaths from modules we have a list of [PrgEnv-*, compiler/version]. 

To avoid having magic numbers, the comment was there to show that we want the second entry of the list because of the ordering in the list.

I believe that the modules entry should be the module for the compiler, not modules that are loaded with the compiler.

**Comment by alalazo** [comment]
Closing as very likely outdated (Cray implementation changed a lot since this bug report). Feel free to reopen if I am wrong about that.
