### ISSUE TITLE
spack test fails with pytest version error

### ISSUE THREAD

**Issue by twang15** [spack/spack#8507]
Summary

Following spack contribution guide (http://spack.readthedocs.io/en/latest/contribution_guide.html) to run "spack test" for unit test on develop branch, "spack test"  fails with the following error message:

### Expected Result

Unit test is running...

### Actual Result
```
==> Reading config file /usr/workspace/wsa/wang102/temp/spack/etc/spack/defaults/modules.yaml
==> Reading config file /usr/workspace/wsa/wang102/temp/spack/etc/spack/defaults/config.yaml
Traceback (most recent call last):
  File "/usr/workspace/wsa/wang102/temp/spack/bin/spack", line 85, in <module>
    sys.exit(spack.main.main())
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/spack/main.py", line 608, in main
    return _main(command, parser, args, unknown)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/spack/main.py", line 500, in _main
    return _invoke_spack_command(command, parser, args, unknown_args)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/spack/main.py", line 408, in _invoke_spack_command
    return_val = command(parser, args, unknown_args)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/spack/cmd/test.py", line 112, in test
    return pytest.main(unknown_args + args.tests)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py", line 168, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py", line 957, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py", line 1121, in parse
    self._preparse(args, addopts=addopts)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/config.py", line 1084, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/tce/packages/python/python-2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/tce/packages/python/python-2.7.14/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/workspace/wsa/wang102/temp/spack/lib/spack/external/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/usr/tce/packages/python/python-2.7.14/lib/python2.7/site-packages/hypothesis/extra/pytestplugin.py", line 32, in <module>
    re.sub('-.+', '', pytest.__version__).split('.')[:3]
ValueError: invalid literal for int() with base 10: 'unknown'
```
### Steps to reproduce the issue
1. git clone https://github.com/spack/spack.git
2. export $SPACK_ROOT=/path/to/spack/
3. export PATH=$SPACK_ROOT/bin:$PATH
4. source $SPACK_ROOT/share/spack/setup-env.sh
5. follow contribution guide to install dependencies
6. spack test

### Information on your system
spack: 0.11.2, development branch
machine architecture: Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz
OS: (Red Hat Enterprise Linux Server release 7.4 (Maipo)
compiler: Intel 18.0.2

**Comment by adamjstewart** [comment]
Hmm, the version of `pytest` in Spack is indeed `'unknown'`:
```
$ spack python
Spack version 0.11.2
Python 3.6.4, Darwin x86_64
>>> import pytest
>>> pytest.__version__
'unknown'
```
https://github.com/spack/spack/blob/develop/lib/spack/external/_pytest/__init__.py

I'm not sure why that would be a problem though, and I can't reproduce the problem locally. @alalazo might know more.

**Comment by twang15** [comment]
Here is mine:

[wang102@quartz188:control]$ spack python
Spack version 0.11.2
Python 2.7.14, Linux x86_64

**Comment by twang15** [comment]
import pytest succeeds without any messages.

**Comment by chissg** [comment]
Concur: on Scientific Linux 7.4:
```
[greenc@woof] ~/work/cet-is/sources/spack (fnal-develop) $ . share/spack/setup-env.sh 
[greenc@woof] ~/work/cet-is/sources/spack (fnal-develop) $ . $(spack location -i lmod)/lmod/lmod/init/bash
[greenc@woof] ~/work/cet-is/sources/spack (fnal-develop) $ . share/spack/setup-env.sh 
Spack version 0.11.2
Python 2.7.5, Linux x86_64
>>> import pytest
>>> pytest.__version__¨
'unknown'
>>> pytest.__file__
'/home/greenc/work/cet-is/sources/spack/lib/spack/external/pytest.pyc'
```

**Comment by adamjstewart** [comment]
@chissg Do you also have problems running `spack test`?

**Comment by adamjstewart** [comment]
> test_all_virtual_packages_have_default_providers

This one should definitely pass, regardless of your environment. This suggests that you either added your own virtual package or updated Spack but didn't update `etc/spack/defaults/packages.yaml`.

The other 2, you may be right. But it sounds like you don't have the same problem as @twang15 at least.

**Comment by chissg** [comment]
@adamjstewart I think that must be a leftover cache entry from a different branch. Regardless, you're right: it looks like the unknown version for `pytest` is a red herring.

**Comment by tgamblin** [comment]
If you look at the test output, it's pulling in test cases from other places for some reason.  This:

```
/usr/tce/packages/python/python-2.7.14/lib/python2.7/site-packages/hypothesis/extra/pytestplugin.py
```

Is part of LLNL's Spack installation and it's the thing that tries to make an `int` out of the `pytest` version.  So this is a bug in however we're collecting test cases in `spack test`.  We need to restrict them to what is in the Spack tree, and not be overly aggressive digging around in system packages.

**Comment by tgamblin** [comment]
It turns out there is not a great way to make `pytest` ignore system packages when inspecting tests (maybe @lee218llnl knows how or at least would be interested in this issue).

Regardless, upgrading to the latest version of `pytest` that still has Python 2.6 support fixes this.  I'll make a PR.

**Comment by scheibelp** [comment]
I ran into this problem and had success creating a view with python:

```
$ spack install py-flake8                                          (this includes python)
$ spack view soft --ignore-conflicts view-directory py-flake8
$ export PATH=...
$ spack test ...
```

I think this should avoid issues with more-traditional site-packages locations but in this case it will definitely avoid `/usr/tce/packages/...`

**Comment by adamjstewart** [comment]
> upgrading to the latest version of pytest that still has Python 2.6 support fixes this.

I thought 3.2.5 was the last version that supported Python 2.6? That's what we currently have.

**Comment by lee218llnl** [comment]
I don't know how to get pytest to ignore system packages.

**Comment by tgamblin** [comment]
>> upgrading to the latest version of pytest that still has Python 2.6 support fixes this.
>>
> I thought 3.2.5 was the last version that supported Python 2.6? That's what we currently have.

@adamjstewart: I guess I should say I took the 3.2.5 release tarball and put that in, instead of whatever we had.  Maybe the version in the repo was from a git checkout of the 3.2.5 tag, but not a release?  Either way, the version I put in is 3.2.5, but reports a proper version.
