### ISSUE TITLE
Is spack usage without lsb_release?

### ISSUE THREAD

**Issue by JohnWGrove** [spack/spack#8568]
I am trying to use space on a Linux system where the command lsb_release returns nothing. This breaks spack.

-----

On the Los Alamos system the trinitite HPC system (a cray linux system) has a version of `lsb_release` in `/usr/bin` that returns
```
LSB Version:	n/a
```
when I use spack this causes a cascade of error, even during sourcing `$SPACK_ROOT/share/spack/setup-env.csh`

The result of the sourcing this file is
```
nid00012> source $SPACK_ROOT/share/spack/setup-env.csh
Traceback (most recent call last):
  File "/usr/projects/eap//spack/spack/bin/spack", line 80, in <module>
    import spack.main  # noqa
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/__init__.py", line 84, in <module>
    import spack.repository
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/repository.py", line 52, in <module>
    import spack.spec
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/spec.py", line 119, in <module>
    import spack.compilers as compilers
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/compilers/__init__.py", line 36, in <module>
    import spack.config
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/config.py", line 212, in <module>
    _platform = spack.architecture.platform().name
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/llnl/util/lang.py", line 182, in __call__
    self.cache[args] = self.func(*args)
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/architecture.py", line 499, in platform
    return platform_cls()
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/platforms/cray.py", line 91, in __init__
    front_distro = CrayFrontend()
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/operating_systems/linux_distro.py", line 40, in __init__
    from external.distro import linux_distribution
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/external/distro.py", line 1057, in <module>
    _distro = LinuxDistribution()
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/external/distro.py", line 596, in __init__
    if include_lsb else {}
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/external/distro.py", line 935, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 2
Traceback (most recent call last):
  File "/usr/projects/eap//spack/spack/bin/spack", line 80, in <module>
    import spack.main  # noqa
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/__init__.py", line 84, in <module>
    import spack.repository
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/repository.py", line 52, in <module>
    import spack.spec
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/spec.py", line 119, in <module>
    import spack.compilers as compilers
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/compilers/__init__.py", line 36, in <module>
    import spack.config
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/config.py", line 212, in <module>
    _platform = spack.architecture.platform().name
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/llnl/util/lang.py", line 182, in __call__
    self.cache[args] = self.func(*args)
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/architecture.py", line 499, in platform
    return platform_cls()
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/platforms/cray.py", line 91, in __init__
    front_distro = CrayFrontend()
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/operating_systems/linux_distro.py", line 40, in __init__
    from external.distro import linux_distribution
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/external/distro.py", line 1057, in <module>
    _distro = LinuxDistribution()
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/external/distro.py", line 596, in __init__
    if include_lsb else {}
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/external/distro.py", line 935, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 2
Traceback (most recent call last):
  File "/usr/projects/eap//spack/spack/bin/spack", line 80, in <module>
    import spack.main  # noqa
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/__init__.py", line 84, in <module>
    import spack.repository
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/repository.py", line 52, in <module>
    import spack.spec
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/spec.py", line 119, in <module>
    import spack.compilers as compilers
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/compilers/__init__.py", line 36, in <module>
    import spack.config
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/config.py", line 212, in <module>
    _platform = spack.architecture.platform().name
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/llnl/util/lang.py", line 182, in __call__
    self.cache[args] = self.func(*args)
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/architecture.py", line 499, in platform
    return platform_cls()
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/platforms/cray.py", line 91, in __init__
    front_distro = CrayFrontend()
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/spack/operating_systems/linux_distro.py", line 40, in __init__
    from external.distro import linux_distribution
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/external/distro.py", line 1057, in <module>
    _distro = LinuxDistribution()
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/external/distro.py", line 596, in __init__
    if include_lsb else {}
  File "/usr/projects/eap/spack/spack-0.11.2/lib/spack/external/distro.py", line 935, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 2
```

### Steps to reproduce the issue

Find a system where `lsb_release` doesn't return any information. This will break spack.

### Information on your system

This includes:
Trinitite is a an unclassified computing cluster for ASC code developers who target the Trinity platform. Cray CLE, based on SLES. The compute nodes run a Lightweight Operating System (LWOS), while both the (external) front-end nodes and (internal) login nodes run the fully featured OS. The Cray User Guide is a useful document for users and developers. See the Cray Documentation for complete information.     2 front-end nodes, external to the interconnect

    100 compute nodes with Intel Haswell processor, and
    100 compute nodes with an Intel Knights Landing (KNL) processor

    32 CPU cores per Haswell compute node (2x hyperthreads each), and
    68 CPU cores per KNL (4x hyperthreads each)

    Haswell, per node: 128 GB Memory,
    KNL, per node: 16 GB Multi-Channel Dynamic Random Access Memory (MCDRAM), aka. High-bandwidth memory (HBM)
    96 GB Double Data Rate Random Acess Memory (DDRAM)

    Peak speed = 100 HSW nodes * 32 cores * 2.3 GHz * 8 Flops/clock = 59 TFlops
    + 100 KNL nodes * 68 cores * 1.4 GHz * 2 FMAs/core * 16 ops/clock/FMA = 305 Tflops
    for a grand total of 364 TFlops*. 

I searched your documentation, but didn't find anything about this routine (lsb_release). Is there a workaround for this issue?

**Comment by adamjstewart** [comment]
Spack uses the [`distro`](https://github.com/nir0s/distro) library to detect your Linux distribution. It looks like `distro` calls `lsb_release -a` to help determine this. You might want to open up a bug report with the `distro` developers. This problem could very well have been fixed in a later release. Spack is stuck on `distro` 1.0.4, as this is the last version to officially support Python 2.6, but if they point you to a commit that solves the problem we can easily backport it.

Pinging @nir0s.

**Comment by JohnWGrove** [comment]
Thanks, I figured out that distro was the routine calling lsb_release. I will see what I can do and let you know.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov

**Comment by JohnWGrove** [comment]
HI Adam: I check the current release for distro and it has the same problem. If the routine lsb_release is broken, so is distro, and hence spack. I don’t see any workaround in the distro package.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov

**Comment by JohnWGrove** [comment]
Hi Adam. I constructed a partial workaround for distro being broken due to lsb_release not being compliant. I simply copied the shell script lsb_release into a local copy and replaced all of the exit statements with exit 0, so it always returns status 0. When I insert my hacked copy into my path before the system version, spack works perfectly. Would it perhaps be something as simple as having spack ignore the return status from distro, or would this be something to change in the distro package itself. Even with lsb_release disabled (it never did anything on this system anyway except return an error status) the machine characteristics seem to be found by someone. Also, you suggested I try a newer version of distro. Is this as simple as copying the py file for distro into the external directory, or is there more to be done than this? I found the installation instructions for distro to be confusing at best and seem to be directed at a system installation.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov

**Comment by adamjstewart** [comment]
> Would it perhaps be something as simple as having spack ignore the return status from distro, or would this be something to change in the distro package itself. 

I'm not sure. Maybe @nir0s can comment on that one? I'm not sure what the scope of `distro` is, but I don't think it should crash just because `lsb_release` isn't available. At the very least, it should return "unknown".

> Is this as simple as copying the py file for distro into the external directory

Yes, that should be the only thing you need to do. Although we can't merge this change, it might help @nir0s narrow down what needs to be fixed.

**Comment by tgamblin** [comment]
@JohnWGrove: we should really be detecting Trinitite as a cray machine -- Spack has extra support for Crays.  I'm curious why that is not happening.  We use `distro` for regular Linux systems, and I agree it should work, but Cray is always "special".

@becker33: this might be relevant for you -- can you take a look?

**Comment by JohnWGrove** [comment]
I believe spack does detect Trinitite as Cray although I am not sure if this is before or after distro is used. This problem is very odd since it occurs for me but not others in my group. I tried running with a completely vanilla environment and still got the failure due to lsb_release returning status 2 which got passed up from distro into spack and caused the python script to abort. As I mentioned previously, hacking lsb_release to always return status 0 got things working for me. With this hack spack was able to correctly find the machine characteristics and work (as far as I know). Why this fails for me and not others is a mystery. If I find out more I will let you know. Trinitite is on dedicated system time right now until Friday.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov

**Comment by JohnWGrove** [comment]
I succeeded in tracking down my issue. I had a version of getopt that was incorrect for the cray. I removed this version and now spack works as advertised.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov

**Comment by tgamblin** [comment]
@JownWGrove: Great!  Is there something we could do to avoid picking that up?  Was it in your home directory or someplace we should avoid looking?

**Comment by JohnWGrove** [comment]
Hi Todd: The getopt routine was in my bin. Apparently the way trinitite is set up this directory was added to the users path independently of whatever was done by the user and put before /usr/bin, so that routines there override system commandshas nodetype. Generally for things I set up I would put $HOME/bin at the end of my path so it doesn’t override anything. As far as spack is concerned I think you could consider not aborting if distro returns a non-zero status. When I was testing this, it appeared that spack worked correctly even when distro did not. This may be a platform dependent situation.

John W. Grove
CCS-2 MS D413, PO Box 1663
Los Alamos National Laboratory
Los Alamos, NM 87545
(505) 667-0723
jgrove@lanl.gov
