### ISSUE TITLE
scipy build fails for python 3.5 and 3.6

### ISSUE THREAD

**Issue by s-sajid-ali** [spack/spack#8616]
### Expected Result

py-scipy is installed correctly

### Actual Result

```
[sajid@xrmlite ~]$ spack find -ldf /ldoodkc
==> 1 installed packages.
-- linux-centos7-x86_64 / intel@18.0.3 --------------------------
ldoodkc    py-scipy@1.1.0%intel
igylo3k        ^intel-mkl@2018.2.199%intel
zgjk6yk        ^py-numpy@1.14.5%intel
qwym4uc            ^python@3.5.5%intel
akk4pld                ^bzip2@1.0.6%intel
4krmbbu                ^gdbm@1.14.1%intel
c7bu4ts                    ^readline@7.0%intel
rpcqo55                        ^ncurses@6.1%intel
frn5dwp                ^openssl@1.0.2o%intel
vonxam4                    ^zlib@1.2.11%intel
uhrj5qt                ^sqlite@3.23.1%intel

[sajid@xrmlite ~]$ spack load python@3.5.5
[sajid@xrmlite ~]$ python
Python 3.5.5 (default, Jun 29 2018, 11:28:26)
[GCC Intel(R) C++ gcc 7.3 mode] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.integrate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/integrate/__init__.py", line 89, in <module>
    from .quadrature import *
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/integrate/quadrature.py", line 10, in <module>
    from scipy.special import roots_legendre
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/special/__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: /home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-x86_64-linux-gnu.so: undefined symbol: d_int_val
>>>
```

This includes:

 1. CentOS7, linux-x86_64
 2. fails for both python 3.5 and 3.6
 3. I have ```ulimit -s unlimited``` in my ```.bashrc```
 4. This works find with gcc@7.3.0 so it's an issue with the intel compilers.

**Comment by scheibelp** [comment]
> undefined symbol: d_int_val

According to https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/274133 this symbol is provided by intel's `libifcore` library. Does this error go away if you add the intel compiler libraries directory to your `LD_LIBRARY_PATH`?

I'm assuming those libraries don't show up in your RPATHs if you run `readelf -d /home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/special/_ufuncs.cpython-35m-x86_64-linux-gnu.so`. Do they show up in `icc -v`? There is an effort to automatically RPATH compiler libs at https://github.com/spack/spack/pull/7153.

**Comment by s-sajid-ali** [comment]
My ```LD_LIBRARY_PATH``` has 
```
[sajid@xrmlite ~]$ echo $LD_LIBRARY_PATH
/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.6.5-wx6bzjnnsw2qtl5hglr4sgt2x7twlzu4/lib:/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2018.3.222/linux/mpi/mic/lib:/opt/intel/compilers_and_libraries_2018.3.222/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.3.222/linux/tbb/lib/intel64/gcc4.7:/opt/intel/debugger_2018/iga/lib:/opt/intel/debugger_2018/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2018.3.222/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.3.222/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-xyzezhjmbiebkjfoakso464rhfshlkyq/lib64:/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-xyzezhjmbiebkjfoakso464rhfshlkyq/lib:/usr/local/lib
```

Note that the path ```/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin:``` is present.

The ```libifcore``` libraries are at : 
```
[sajid@xrmlite ~]$ find /opt/intel/ -name '*libifcore*'
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/ia32_lin/libifcore.a
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/ia32_lin/libifcore.so
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/ia32_lin/libifcore.so.5
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/ia32_lin/libifcore_pic.a
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/ia32_lin/libifcoremt.a
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/ia32_lin/libifcoremt.so
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/ia32_lin/libifcoremt.so.5
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/ia32_lin/libifcoremt_pic.a
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libifcore.so.5
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libifcore_pic.a
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libifcoremt.a
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libifcoremt.so
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libifcore.a
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libifcore.so
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libifcoremt.so.5
/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libifcoremt_pic.a
```

So it should get picked up from the ```intel64_lin``` folder but it doesn't.

Check if readelf shows the libifcore : 
```
[sajid@xrmlite ~]$ readelf -d /home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.6.5-wx6bzjnnsw2qtl5hglr4sgt2x7twlzu4/lib/python3.6/site-packages/scipy/special/_ufuncs.cpython-36m-x86_64-linux-gnu.so > temp
[sajid@xrmlite ~]$ grep libifcore temp
[sajid@xrmlite ~]$
```

My ```compilers.yaml ``` for the relevant compiler is  : 
```
- compiler:
    environment: {}
    extra_rpaths: ['/opt/intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin']
    flags: {}
    modules: [intel18]
    operating_system: centos7
    paths:
      cc: /opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icc
      cxx: /opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc
      f77: /opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/ifort
      fc: /opt/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/ifort
    spec: intel@18.0.3
    target: x86_64
```

(I re-installed the library just to make sure everything was correct so the DAG might have changed)

**Comment by s-sajid-ali** [comment]
I think this is related to the fortran libraries since even ```scipy.optimize``` doesn't work : 
```
[sajid@xrmlite ~]$ python
Python 3.5.5 (default, Jul  6 2018, 15:37:34)
[GCC Intel(R) C++ gcc 7.3 mode] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.optimize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/optimize/__init__.py", line 270, in <module>
    from .optimize import *
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "/home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/optimize/linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: /home/sajid/packages/spack/opt/spack/linux-centos7-x86_64/intel-18.0.3/python-3.5.5-qwym4ucsaweonootprbowof6e54s3a76/lib/python3.5/site-packages/scipy/optimize/minpack2.cpython-35m-x86_64-linux-gnu.so: undefined symbol: for_cpystr
>>>
```

**Comment by adamjstewart** [comment]
I don't think that will help, `numpy` and `scipy` are notoriously painful to build with Intel. See #3204 and https://github.com/numpy/numpy/issues/8653 for my own personal struggles. It links to a lot of good issues. 

The problem is that `numpy` and `scipy` allow you to pass in RPATHs during installation, and then completely ignore them and pick up whatever libraries they feel like. I've had good success with OpenBLAS, but never with Intel+MKL.

**Comment by s-sajid-ali** [comment]
I'll report back when I test with ```^openblas %intel``` because I think the problem is with intel fortran libraries and not mkl since numpy build succeeds.

**Comment by s-sajid-ali** [comment]
I tried doing that and realized that for some reason numpy picks up ```mkl_rt``` instead of openblas. This happens even tough openblas being listed in the site.cfg. Very confusing.

**Comment by adamjstewart** [comment]
Yes, I encountered this problem as well. Numpy detects that you are using Intel and assumes it should be using MKL even if you tell it otherwise. I tried reporting an issue but they closed it on me. Good luck!

**Comment by s-sajid-ali** [comment]
Ugh. I just realized that the issue was never solved. I asked LCRC staff for help but they said they've stopped doing that and have switched over to conda as well. I'll try opening a new issue at numpy and see what happens :(

**Comment by s-sajid-ali** [comment]
The files that come as part of the intel-conda channel are [available here](https://anaconda.org/intel/numpy/files). Though I don't see a ```setup.cfg``` file there is a ```__config__.py``` that's generated as part of the build process. 

Here's the relevant bit : 
```
mkl_info={'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/opt/anaconda1anaconda2anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/opt/anaconda1anaconda2anaconda3/include']}
blas_mkl_info={'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/opt/anaconda1anaconda2anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/opt/anaconda1anaconda2anaconda3/include']}
blas_opt_info={'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/opt/anaconda1anaconda2anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/opt/anaconda1anaconda2anaconda3/include']}
lapack_mkl_info={'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/opt/anaconda1anaconda2anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/opt/anaconda1anaconda2anaconda3/include']}
lapack_opt_info={'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/opt/anaconda1anaconda2anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/opt/anaconda1anaconda2anaconda3/include']}
```

I'll have a look at the spack built numpy and see if I can glean something.

**Comment by s-sajid-ali** [comment]
Real issue is : https://github.com/xianyi/OpenBLAS/issues/1956#issuecomment-452730500

**Comment by samcom12** [comment]
May I know how you guys succeed in using **_py-scipy_** with Intel compilers?

I'm getting the below error at runtime.

```

from scipy.optimize import minpack2
ImportError: /home/apps/spack/opt/spack/linux-centos7-skylake_avx512/intel-2020.2.254/py-scipy-1.6.2-e46dp6s42ng4i5up3nlivam667tqll7x/lib/python3.9/site-packages/scipy/optimize/minpack2.cpython-39-x86_64-linux-gnu.so: undefined symbol: for_cpystr
```

I have followed all the above-discussed links but couldn't get it working.
@adamjstewart @s-sajid-ali
