### ISSUE TITLE
basic Spack commands fail in container if host is Cray and container is not

### ISSUE THREAD

**Issue by reidpr** [spack/spack#8618]
Simple commands such as `spack compilers` and `spack spec` fail when Spack is installed within a non-Cray container and the container is run on a Cray host. I demonstrate this with Charliecloud below, but I suspect it applies to other container runtimes as well. Thank you!

### Expected Result

With Debian Stretch host:

```
$ ch-run $CH_TEST_IMGDIR/spack -- /spack/bin/spack compilers
==> Available compilers
-- gcc debian9-x86_64 -------------------------------------------
gcc@6.3.0
```

### Actual Result

With Cray CLE 6.0.UP05, same container image:

```
$ ch-run /var/tmp/ch-images/spack -- /spack/bin/spack compilers
==> Warning: Could not detect module function from bash. Trying to detect modulecmd from `which`
Traceback (most recent call last):
  File "/spack/bin/spack", line 85, in <module>
    sys.exit(spack.main.main())
  File "/spack/lib/spack/spack/main.py", line 580, in main
    parser.add_command(cmd_name)
  File "/spack/lib/spack/spack/main.py", line 291, in add_command
    module.setup_parser(subparser)
  File "/spack/lib/spack/spack/cmd/compilers.py", line 34, in setup_parser
    scopes = spack.config.scopes()
  File "/spack/lib/spack/spack/config.py", line 528, in scopes
    return config.scopes
  File "/spack/lib/spack/llnl/util/lang.py", line 556, in __getattr__
    return getattr(self.instance, name)
  File "/spack/lib/spack/llnl/util/lang.py", line 552, in instance
    self._instance = self.factory()
  File "/spack/lib/spack/spack/config.py", line 492, in _config
    platform = spack.architecture.platform().name
  File "/spack/lib/spack/llnl/util/lang.py", line 182, in __call__
    self.cache[args] = self.func(*args)
  File "/spack/lib/spack/spack/architecture.py", line 498, in platform
    return platform_cls()
  File "/spack/lib/spack/spack/platforms/cray.py", line 68, in __init__
    for target in self._avail_targets():
  File "/spack/lib/spack/spack/platforms/cray.py", line 156, in _avail_targets
    module = get_module_cmd()
  File "/spack/lib/spack/spack/util/module_cmd.py", line 46, in get_module_cmd
    raise ModuleError('Spack requires modulecmd or a defined module'
spack.util.module_cmd.ModuleError: Spack requires modulecmd or a defined module fucntion. Make sure modulecmd is in your path or the function "module" is defined in your bash environment.
```

### Steps to reproduce the issue

On a Linux workstation with Docker installed and Charliecloud source code in `/usr/local/src/charliecloud`, something along the lines of the following. This may work on a Cray as well.

```
$ cd /usr/local/src/charliecloud
$ make
$ export PATH=/usr/local/src/charliecloud/bin:$PATH
$ ch-build -t spack -f examples/other/spack/Dockerfile
$ ch-docker2tar spack /tmp
162M /tmp/spack.tar.gz
```

I can provide `spack.tar.gz` out of band if needed.

Copy `spack.tar.gz` to your local Cray, say to `/scratch`.

Build Charliecloud on the Cray as well and add its `bin` directory to your `$PATH`.

On the Cray:

```
$ ch-tar2dir /scratch/spack/tar.gz /var/tmp
$ ch-run /var/tmp/spack -- /spack/bin/spack compilers
```

### Information on your system

* Image build host is Debian Stretch.
* Image is Debian Stretch too.
* Cray version:
```
$ cat /etc/opt/cray/release/cle-release
RELEASE=6.0.UP05
BUILD=6.0.5116
DATE=201709151057
ARCH=x86_64
NETWORK=ari
``` 
* Charliecloud version 0.9.0~pre+69f99a1, but this probably does not matter.
* [Dockerfile and test script](https://github.com/hpc/charliecloud/tree/69f99a144b6960fc6d54f8e7e90b182e89847c5b/examples/other/spack)

**Comment by reidpr** [comment]
This container has no `module` command or function at all. If the referenced PR can deal with that situation gracefully, sure, we can try it.

**Comment by adamjstewart** [comment]
@becker33

**Comment by mamelara** [comment]
Hello,

Does Charliecloud bring in variables from the Cray environment when you try to run the container? We recently experienced this with `shifter` and found that Spack was picking up the CRAYOS_VERSION variable that was in the container and then proceeded to do all the cray things. If you are able to enter into a clean environment then it might be able to run properly.

**Comment by reidpr** [comment]
We normally leave the environment untouched, so yes, we'd get all the Cray variables. Thank you for the suggestion! We will investigate.

**Comment by becker33** [comment]
This should be fixed by the effort that changed Cray systems to be treated as normal linux with additional externals.
