### ISSUE TITLE
py-basemap broken again

### ISSUE THREAD

**Issue by citibeth** [spack/spack#8716]
@lee218llnl @adamjstewart 

## Back Story

py-basemap (at least with Python3) is problematic because it uses namespace packages.  This problem was solved in #1964 with a post-install patch.  Since then, #3835 came up with a different solution that did not need the post-install patch.  And we all seemed to agree at the time it was a good and elegant solution.

## The Problem

Unfortunately... the original problem from #1964 has reared its ugly head again:

```
[rpfische@gs611-gibbs stieglitz]$ python3 -c 'from mpl_toolkits.axes_grid1 import make_axes_locatable'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'mpl_toolkits.axes_grid1'
[rpfische@gs611-gibbs stieglitz]$ python3 -c 'import mpl_toolkits.basemap'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home2/rpfische/spack6/opt/spack/linux-centos7-x86_64/gcc-4.9.3/py-basemap-1.0.7-fpu2nxnadqokntqdzweoinytf6wuu5bx/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 31, in <module>
    from mpl_toolkits.axes_grid1 import make_axes_locatable
ImportError: No module named 'mpl_toolkits.axes_grid1'
[rpfische@gs611-gibbs stieglitz]$ python3 --version
Python 3.5.2
```

Note that I'm running Python by `module loading` a bunch of Spack-generated modules, rather than using `spack activate`.

## What To Do?

Any ideas on a way forward?  From my local point of view, it looks like the patch from #1964 actually is required, at least in some cases.

**Comment by citibeth** [comment]
This Issue has received no comment so far.  In that case, I will soon submit a PR to re-apply the patch from #1964

**Comment by scheibelp** [comment]
A couple questions:

* Did #3835 ever work for you?
* What versions of `py-setuptools`, `py-matplotlib`, and `py-basemap` are you using (`spack find -d -L py-basemap` may help)?

**Comment by citibeth** [comment]
> Did #3835 ever work for you?

I doubt it.  I probably had my stuff working and just mumbled "OK" when I saw #3835, without testing it.  This works MOST of the time :-)

> What versions of py-setuptools, py-matplotlib, and py-basemap are you using (spack find -d -L py-basemap may help)?


See versions below.

```
     ryqdc6u  py-giss@0.1.2%gcc@4.9.3 copy=standard arch=linux-centos7-x86_64 
[+]  fpu2nxn      ^py-basemap@1.0.7%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  qtdofvk          ^geos@3.6.2%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  x76p3ft          ^py-matplotlib@2.2.2%gcc@4.9.3~animation+image+ipython~latex+python3~qt+tk arch=linux-centos7-x86_64 
[+]  ns2vqgk              ^freetype@2.7.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  4mrpd3t                  ^bzip2@1.0.6%gcc@4.9.3+shared arch=linux-centos7-x86_64 
[+]  iucl3ey                  ^libpng@1.6.34%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  qln4wqd                      ^zlib@1.2.11%gcc@4.9.3+optimize+pic+shared arch=linux-centos7-x86_64 
[+]  oxurpfy                  ^pkgconf@1.4.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  oguuz24              ^py-cycler@0.10.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  laptdfd                  ^py-setuptools@39.0.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  o4sbclg                      ^python@3.5.2%gcc@4.9.3+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic~pythoncmd+shared~tk~ucs4 arch=linux-centos7-x86_64 
[+]  vozam77                          ^gdbm@1.14.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  knmmfzk                              ^readline@7.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  vwjzpwq                                  ^ncurses@6.0%gcc@4.9.3 patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks~termlib arch=linux-centos7-x86_64 
[+]  vfw2pyj                          ^openssl@1.0.1e%gcc@4.9.3+systemcerts arch=linux-centos7-x86_64 
[+]  avl4mcz                          ^sqlite@3.22.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  o5c6mr5                  ^py-six@1.11.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  ua34eq4              ^py-dateutil@2.5.2%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  pqpnguw              ^py-ipython@5.1.0%gcc@4.9.3+python3 arch=linux-centos7-x86_64 
[+]  k4iz5aj                  ^py-decorator@4.0.9%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  v77moiz                  ^py-pexpect@4.2.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  xgxg7bo                      ^py-ptyprocess@0.5.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  dvlrk3g                  ^py-pickleshare@0.7.4%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  ibjscko                  ^py-prompt-toolkit@1.0.9%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  slbld7z                      ^py-wcwidth@0.1.7%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  dn52dpg                  ^py-pygments@2.2.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  hrkm62o                  ^py-simplegeneric@0.8.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  ebzc7zx                  ^py-traitlets@4.3.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  v46x5zj                      ^py-enum34@1.1.6%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  jaseyms                      ^py-ipython-genutils@0.1.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  f72s6t3              ^py-kiwisolver@1.0.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  kptblrt              ^py-numpy@1.14.2%gcc@4.9.3+blas+lapack arch=linux-centos7-x86_64 
[+]  amd6l6z                  ^openblas@0.2.20%gcc@4.9.3 cpu_target= ~ilp64 patches=47cfa7a952ac7b2e4632c73ae199d69fb54490627b66a62c681e21019c4ddc9d +pic+shared threads=none ~virtual_machine arch=linux-centos7-x86_64 
[+]  sew4eve              ^py-pillow@3.2.0%gcc@4.9.3~freetype+jpeg~jpeg2000~lcms~tiff+zlib arch=linux-centos7-x86_64 
[+]  ueojvzh                  ^binutils@2.29.1%gcc@4.9.3+gold~libiberty patches=0a0ca84889b6727dc0cc88650f55fd79452dddba762674a83a153374792fdaac ~plugins arch=linux-centos7-x86_64 
[+]  4w542bs                      ^bison@3.0.4%gcc@4.9.3 patches=b72914fe38e54a6fc25f29019e0a0786705c4f61ce20d414cc2010c8d62448c7 arch=linux-centos7-x86_64 
[+]  q3lv6ly                          ^m4@1.4.18%gcc@4.9.3 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00 +sigsegv arch=linux-centos7-x86_64 
[+]  ortj3lz                              ^libsigsegv@2.11%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  xgkjjtv                      ^flex@2.6.1%gcc@4.9.3+lex arch=linux-centos7-x86_64 
[+]  pp2glkb                          ^gettext@0.19.8.1%gcc@4.9.3+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=linux-centos7-x86_64 
[+]  ae3f5oz                              ^libxml2@2.9.4%gcc@4.9.3~python arch=linux-centos7-x86_64 
[+]  qyqnepu                                  ^xz@5.2.3%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  onlquan                              ^tar@1.30%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  ufhgqec                          ^help2man@1.47.4%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  wgmawag                  ^libjpeg-turbo@1.5.3%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  d4nel32                      ^nasm@2.13.03%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  ihl3oti              ^py-pyparsing@2.2.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  epa5vc2              ^py-pytz@2017.2%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  mpctzi4              ^qhull@2015.2%gcc@4.9.3 build_type=RelWithDebInfo patches=10ddc62a1600b0ede23fb0502e29dca389d18689fd8dfe7a849e3a989c0e607e arch=linux-centos7-x86_64 
[+]  joeqauy                  ^cmake@3.11.1%gcc@4.9.3~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-x86_64 
[+]  qqufl3d              ^tk@8.6.8%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  an33imh                  ^libx11@1.6.5%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  gab54ej                      ^inputproto@2.3.2%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  mnhrb6u                          ^util-macros@1.19.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  2xuesfy                      ^kbproto@1.0.7%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  7yyach6                      ^libxcb@1.13%gcc@4.9.3+python3 arch=linux-centos7-x86_64 
[+]  4tbao2p                          ^libpthread-stubs@0.4%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  vtny3tk                          ^libxau@1.0.8%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  dt7us6e                              ^xproto@7.0.31%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  wb3uus2                          ^libxdmcp@1.1.2%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  trxdury                          ^xcb-proto@1.13%gcc@4.9.3+python3 arch=linux-centos7-x86_64 
[+]  3plvgdb                      ^perl@5.26.2%gcc@4.9.3+cpanm+shared arch=linux-centos7-x86_64 
[+]  lqns2h6                      ^xextproto@7.3.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  yddafcu                      ^xtrans@1.3.5%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  4pe26wm                  ^tcl@8.6.8%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  f5nnpkz      ^py-netcdf4@1.2.7%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  lu4lnaj          ^hdf5@1.8.18%gcc@4.9.3~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-centos7-x86_64 
[+]  eiylqoa              ^openmpi@3.1.0%gcc@4.9.3~cuda fabrics= ~java~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-x86_64 
[+]  o2rqowx                  ^hwloc@1.11.9%gcc@4.9.3~cairo~cuda+libxml2+pci+shared arch=linux-centos7-x86_64 
[+]  rlsuvhs                      ^libpciaccess@0.13.5%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  j3ybwof                          ^libtool@2.4.6%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  dvnqg3u                      ^numactl@2.0.11%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  lktpm7j                          ^autoconf@2.69%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  zttqzxi                          ^automake@1.16.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  7hecfhz          ^netcdf@4.4.0%gcc@4.9.3~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+shared arch=linux-centos7-x86_64 
[+]  zw3dpum          ^py-cython@0.23.5%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  aot767e      ^py-proj@1.9.5.1.1%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  wy7uols      ^py-scipy@1.0.0%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  j6nr5wb      ^py-udunits@1.1.3%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  mvm56v7          ^udunits2@2.2.24%gcc@4.9.3 arch=linux-centos7-x86_64 
[+]  l4gvzwa              ^expat@2.2.5%gcc@4.9.3+libbsd arch=linux-centos7-x86_64 
[+]  wdcni4t                  ^libbsd@0.8.6%gcc@4.9.3 patches=aaae81b3edc29362a94770cc235f1eb
```

**Comment by adamjstewart** [comment]
For what it's worth, it looks like basemap is now deprecated in favor of cartopy: https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement

**Comment by adamjstewart** [comment]
Is this still an issue?

**Comment by adamjstewart** [comment]
I think this can be closed. basemap is deprecated, all users should use cartopy instead.
