### ISSUE TITLE
py-vmd-python "No module named pkg_resources"

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [spack/spack#8841]
Per [Usage](https://github.com/Eigenstate/vmd-python) this should work.

**Comment by JusticeForMikeBrown** [comment]
**me@node103[~]$ spack load -r py-vmd-python**

> dod2014@node103[~]$ module list
> Currently Loaded Modulefiles:
>   1) libbsd-0.8.6-gcc-6.3.0-ivk7mlv           6) libxml2-2.9.8-gcc-6.3.0-zrdgx44         11) netcdf-4.6.1-gcc-6.3.0-3z5cefi          16) gdbm-1.14.1-gcc-6.3.0-ye56lvz           21) tcl-8.6.8-gcc-6.3.0-igznzsa
>   2) expat-2.2.5-gcc-6.3.0-cxe665y            7) numactl-2.0.11-gcc-6.3.0-dqrr7l5        12) openblas-0.2.20-gcc-6.3.0-oq3x5fo       17) openssl-1-gcc-6.3.0-jfeudwn             22) py-vmd-python-2.0.10-gcc-6.3.0-pz2cxy4
>   3) libpciaccess-0.13.5-gcc-6.3.0-bkmqzbd    8) hwloc-1.11.9-gcc-6.3.0-mq5dzo4          13) bzip2-1.0.6-gcc-6.3.0-x5hwxgo           18) sqlite-3.23.1-gcc-6.3.0-impps3n
>   4) xz-5.2.4-gcc-6.3.0-o2xme3g               9) openmpi-3.1.0-gcc-6.3.0-m2rov3w         14) ncurses-6.1-gcc-6.3.0-rqwrhpn           19) python-2.7.15-gcc-6.3.0-fvf4vy3
>   5) zlib-1.2.11-gcc-6.3.0-rjqs3cq           10) hdf5-1.10.2-gcc-6.3.0-42y7cl5           15) readline-7.0-gcc-6.3.0-gt74ike          20) py-numpy-1.14.2-gcc-6.3.0-a3f3vuz



```
> me@node103[~]$ python
> Python 2.7.15 (default, May 30 2018, 16:45:15) 
> [GCC 6.3.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from vmd import molecule, vmdnumpy
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/pbtech_mounts/softlib001/apps/EL6/spack/opt/spack/linux-rhel6-x86_64/gcc-6.3.0/py-vmd-python-2.0.10-pz2cxy4j5frxqydqzxsuh5di2qf3z5vc/lib/python2.7/site-packages/vmd/__init__.py", line 17, in <module>
>     from pkg_resources import resource_filename
> ImportError: No module named pkg_resources
> 
```

**Comment by JusticeForMikeBrown** [comment]
Looks like we need `setuptools`

**spack load -r py-setuptools ^/fvf4vy3**

me@node103[~]$ python
Python 2.7.15 (default, May 30 2018, 16:45:15) 
[GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from vmd import molecule, vmdnumpy
>>>
