### ISSUE TITLE
spack install results always in ==>Error:

### ISSUE THREAD

**Issue by tomtok9** [spack/spack#8915]
Summary
new spack installation on Ubtunu 18.04. Commands like spack list, spack arch does work without problems. 
As soon as I install any package it troughs just "==> Error:" without more information. I have no idea whats wrong or where I can look for the detailed error. I didn't find any log files or build directories.  Where can I find a more detailed failure description? 
 
### Expected Result

install some package

### Actual Result

==> Error:

### Steps to reproduce the issue

spack install <anything>

### Information on your system

Cluster with some Centos 7 nodes and some new nodes (with GPUs) with ubuntu 18.04 installed. they work with slurm for scheduling. I have an installation of spack for CentOS this one works very well and another installation for our new  Ubuntu-based nodes.

**Comment by adamjstewart** [comment]
Can you run `spack --debug install ...`? That should give you the information you need. I'm really curious about the non-existant error message though. I recently played around with Spack's error messages so I hope I didn't break something...

**Comment by tomtok9** [comment]
Thanks for you reply.

I done spack clean and then tried to install different packages, always with the same result. I am not quite sure about the problem. looks like it can not acquire a lock. Permission looks ok should be ok.  
All files have 
-rw-r--r-- 1 root root 
(I run spack as root) 

spack --debug install unzip
==> Reading config file /opt/cluster/spool/wsl/ubuntuspack/spack/etc/spack/defaults/modules.yaml
==> Reading config file /opt/cluster/spool/wsl/ubuntuspack/spack/etc/spack/defaults/config.yaml
==> Reading config file /opt/cluster/spool/wsl/ubuntuspack/spack/etc/spack/defaults/repos.yaml
==> Reading config file /opt/cluster/spool/wsl/ubuntuspack/spack/etc/spack/defaults/packages.yaml
==> READ LOCK: /root/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /root/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquired]
==> READ LOCK: /root/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> Reading config file /root/.spack/linux/compilers.yaml
==> WRITE LOCK: /opt/cluster/spool/wsl/ubuntuspack/spack/opt/spack/.spack-db/prefix_lock[2502880559062125543:1] [Acquiring]
Traceback (most recent call last):
  File "/opt/cluster/spool/wsl/ubuntuspack/spack/bin/spack", line 61, in <module>
    sys.exit(spack.main.main())
  File "/opt/cluster/spool/wsl/ubuntuspack/spack/lib/spack/spack/main.py", line 653, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/cluster/spool/wsl/ubuntuspack/spack/lib/spack/spack/main.py", line 432, in _invoke_command
    return_val = command(parser, args)
  File "/opt/cluster/spool/wsl/ubuntuspack/spack/lib/spack/spack/cmd/install.py", line 273, in install
    install_spec(args, kwargs, spec)
  File "/opt/cluster/spool/wsl/ubuntuspack/spack/lib/spack/spack/cmd/install.py", line 154, in install_spec
    spec.package.do_install(**kwargs)
  File "/opt/cluster/spool/wsl/ubuntuspack/spack/lib/spack/spack/package.py", line 1344, in do_install
    partial = self.check_for_unfinished_installation(keep_prefix, restage)
  File "/opt/cluster/spool/wsl/ubuntuspack/spack/lib/spack/spack/package.py", line 1563, in check_for_unfinished_installation
    with spack.store.db.prefix_write_lock(self.spec):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/cluster/spool/wsl/ubuntuspack/spack/lib/spack/spack/database.py", line 259, in prefix_write_lock
    prefix_lock.release_write()
  File "/opt/cluster/spool/wsl/ubuntuspack/spack/lib/spack/llnl/util/lock.py", line 289, in release_write
    assert self._writes > 0
AssertionError

**Comment by tgamblin** [comment]
@tomtok9: what filesystem are you using for spack?

Try running with `spack -L` to disable locks as a workaround.

**Comment by adamjstewart** [comment]
If we can manage to reproduce this it would be great to fix the error message to let people know there is a locking problem and what options they have as a workaround.

**Comment by tgamblin** [comment]
Yes if really like a reproducer for this. If we know what filesystem we could try to reproduce it in AWS.

**Comment by tomtok9** [comment]
We use XFS on this ubuntu nodes. `spack -L` does work we could install several packages. 
But they do not list in `module available` it does not list any modulefiles for spack only the default ones but this probably another issue we have.

**Comment by adamjstewart** [comment]
`echo $MODULEPATH`?

**Comment by adamjstewart** [comment]
@tgamblin I just managed to reproduce this, though for an unrelated reason. I was building on Blue Waters when my connection dropped. Spack claims that it successfully installed the package it was working on (it shows up in the db), but it sounds like it didn't get a chance to cleanup the locks before crashing. So you might be able to reproduce this by running remotely and turning your WiFi off mid-build.

**Comment by adamjstewart** [comment]
P.S. Can we get a `spack clean --locks` flag?

**Comment by healther** [comment]
I'm seeing similar effects on our system, but I hesitate to open an issue as we have a fairly old version of `spack` and currently a rather unstable filesystem. I _think_ this may also be triggered by having an unresponsive file system

**Comment by tgamblin** [comment]
@adamjstewart: what would `spack clean --locks` do?  The locks are files but they're empty, and locks are dropped when processes die. It's actually better to not remove the lock files.

**Comment by healther** [comment]
Actually @tgamblin that isn't true, removing the `.prefix-lock` file does sometimes help (granted I have no idea why, but I can attest to that it does). Can you take a look at #9166 and tell me if our conjectures are reasonable?

**Comment by adamjstewart** [comment]
@tgamblin When my connection dropped, the only way I could get Spack to work again was to delete the `.prefix-lock` file. So `spack clean --locks` would delete that file and any other temporary lock files.

**Comment by tgamblin** [comment]
@adamjstewart: If that is the case then a spack process must've still been running somewhere... `fcntl` locks are dropped automatically when processes die.

**Comment by tgamblin** [comment]
Unless NFS botched it, I suppose.  The issue with this is that blowing away the lock files means that if someone doesn't have write access to the Spack directory, they can't use Spack, because they need to create the lock file.

**Comment by healther** [comment]
@tgamblin could you elaborate on how "NFS botched it" could have happened or how one could diagnose this?

> The issue with this is that blowing away the lock files means that if someone doesn't have write access to the Spack directory, they can't use Spack, because they need to create the lock file.

In practice I don't think this will matter, because either a) you have write access, in which case you will immediately afterwards perform another operation (i.e. the one which failed and triggered you to clean) or b) the clean will fail, because you are not allowed to delete the file in the first place.

**Comment by scheibelp** [comment]
#9219 addresses https://github.com/spack/spack/issues/8915#issuecomment-411687585

https://github.com/spack/spack/pull/9347 (which is a work in progress) should address https://github.com/spack/spack/issues/8915#issuecomment-417728840 and https://github.com/spack/spack/issues/8915#issuecomment-418166162

**Comment by alalazo** [comment]
Closing, since there has been no activity in a while. Feel free to reopen if you think this is still an issue.
