### ISSUE TITLE
failing to use already existing module hdf5

### ISSUE THREAD

**Issue by srinathv** [spack/spack#9126]
Can't give all details because of environment of operaiton.

==> hdf5@1.8.16 : has external module in cray-hdf5-parallel/1.8.16
==> hdf5@1.8.16 : is actually installed in None
==> hdf5@1.8.16 : generating module file
Traceback (most recent call last):
  File "/home/svadlam/spack-sv/bin/spack", line 54, in <module>
    sys.exit(spack.main.main())
  File "/home/svadlam/spack-sv/lib/spack/spack/main.py", line 653, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/svadlam/spack-sv/lib/spack/spack/main.py", line 432, in _invoke_command
    return_val = command(parser, args)
  File "/home/svadlam/spack-sv/lib/spack/spack/cmd/install.py", line 273, in install
    install_spec(args, kwargs, spec)
  File "/home/svadlam/spack-sv/lib/spack/spack/cmd/install.py", line 154, in install_spec
    spec.package.do_install(**kwargs)
  File "/home/svadlam/spack-sv/lib/spack/spack/package.py", line 1420, in do_install
    **kwargs)
  File "/home/svadlam/spack-sv/lib/spack/spack/package.py", line 1380, in do_install
    return self._process_external_package(explicit)
  File "/home/svadlam/spack-sv/lib/spack/spack/package.py", line 1302, in _process_external_package
    spack.hooks.post_install(self.spec)
  File "/home/svadlam/spack-sv/lib/spack/spack/hooks/__init__.py", line 73, in __call__
    hook(*args, **kwargs)
  File "/home/svadlam/spack-sv/lib/spack/spack/hooks/module_file_generation.py", line 48, in <lambda>
    post_install = lambda spec: _for_each_enabled(spec, 'write')
  File "/home/svadlam/spack-sv/lib/spack/spack/hooks/module_file_generation.py", line 41, in _for_each_enabled
    getattr(generator, method_name)()
  File "/home/svadlam/spack-sv/lib/spack/spack/modules/common.py", line 698, in write
    context = self.context.to_dict()
  File "/home/svadlam/spack-sv/lib/spack/spack/tengine.py", line 86, in to_dict
    d = [(name, getattr(self, name)) for name in self.context_properties]
  File "/home/svadlam/spack-sv/lib/spack/spack/modules/common.py", line 523, in environment_modifications
    self.spec.prefix,
  File "/home/svadlam/spack-sv/lib/spack/spack/spec.py", line 1406, in prefix
    self.prefix = spack.store.layout.path_for_spec(self)
  File "/home/svadlam/spack-sv/lib/spack/spack/directory_layout.py", line 97, in path_for_spec
    assert(not path.startswith(self.root))
AttributeError: 'NoneType' object has no attribute 'startswith'

---

### Steps to reproduce the issue

```console
$  spack --debug -k install --log-file log.txt --dirty -j 4 -v nalu-wind %gcc@7.2.0 '^trilinos~alloptpkgs~xsdkflags~metis~mumps~superlu-dist+superlu~hypre+hdf5~suite-sparse~python~shared+boost+tpetra~epetra~epetraext+exodus+pnetcdf+zlib+stk+teuchos+belos+zoltan+zoltan2~amesos+amesos2~anasazi~ifpack+ifpack2+muelu~fortran~ml+gtest~aztec~sacado~x11+instantiate~instantiate_cmplx~dtk~fortrilinos+openmp~rol~nox+shards~intrepid~intrepid2~cgns@develop'
... # and the relevant part of the error message
```

### Platform and user environment

Please report your OS here:
```commandline
$ uname -a 
Linux mutrino 4.4.114-94.11-default #1 SMP Thu Feb 1 19:28:26 UTC 2018 (4309ff9) x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	SUSE Linux Enterprise Server 12 SP3
``` 

I've seen another issue 
https://github.com/spack/spack/issues/5273#issuecomment-328363658
but no resolution in that question helped with this issue.

**Comment by becker33** [comment]
@srinathv is this resolved by #12693?
