### ISSUE TITLE
Installation issue: cuda@9.2.88 %gcc@4.8.5 

### ISSUE THREAD

**Issue by samfux84** [spack/spack#9576]
### Steps to reproduce the issue

```
[spackapps@lo-login-01 scripts]$ spack install cuda@9.2.88 %gcc@4.8.5 arch=linux-centos7-x86-64
==> Installing cuda
==> Fetching https://developer.nvidia.com/compute/cuda/9.2/Prod/local_installers/cuda_9.2.88_396.26_linux
######################################################################## 100.0%
==> Already staged cuda-9.2.88-pquxqrclfyimmjuz5l6jxntzrnao3d2y in /cluster/apps/spack/var/spack/stage/cuda-9.2.88-pquxqrclfyimmjuz5l6jxntzrnao3d2y
==> Ran patch() for cuda
==> Building cuda [Package]
==> Executing phase : 'install'
==> Error: IndexError: list index out of range
/cluster/apps/spack/var/spack/repos/builtin/packages/cuda/package.py:59, in install:
     58       def install(self, spec, prefix):
  >> 59           runfile = glob(join_path(self.stage.path, 'cuda*run'))[0]
     60           chmod = which('chmod')
     61           chmod('+x', runfile)
     62           runfile = which(runfile)
     63   
     64           # Note: NVIDIA does not officially support many newer versions of
     65           # compilers.  For example, on CentOS 6, you must use GCC 4.4.7 or
     66           # older. See:
     67           # http://docs.nvidia.com/cuda/cuda-installation-guide-linux/#system-requirements
     68           # for details.
     69   
     70           runfile(
     71               '--silent',         # disable interactive prompts
     72               '--verbose',        # create verbose log file
     73               '--override',       # override compiler version checks
     74               '--toolkit',        # install CUDA Toolkit
     75               '--toolkitpath=%s' % prefix
     76           )

See build log for details:
  /dev/shm/spackapps/spack-stage/spack-stage-2mMUcE/spack-build.out
[spackapps@lo-login-01 scripts]$ vi /dev/shm/spackapps/spack-stage/spack-stage-2mMUcE/spack-build.out
[spackapps@lo-login-01 scripts]$
```

The spack-build.out file is empty.

### Platform and user environment

```
[spackapps@lo-login-01 scripts]$ uname -a
Linux lo-login-01 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 GNU/Linux
[spackapps@lo-login-01 scripts]$ lsb_release -d
Description:    CentOS Linux release 7.5.1804 (Core)
``` 

### Additional information

```
[spackapps@lo-login-01 scripts]$ spack spec --install-status cuda@9.2.88 %gcc@4.8.5 arch=linxu-centos7-x86_64
Input spec
--------------------------------
     cuda@9.2.88%gcc@4.8.5 arch=linux-centos7-x86_64 

Normalized
--------------------------------
     cuda@9.2.88%gcc@4.8.5 arch=linux-centos7-x86_64 

Concretized
--------------------------------
     cuda@9.2.88%gcc@4.8.5 cflags="-ftree-vectorize -O2 -march=core-avx2 -fPIC -mavx2" cppflags="-ftree-vectorize -O2 -march=core-avx2 -fPIC -mavx2" cxxflags="-ftree-vectorize -O2 -march=core-avx2 -fPIC -mavx2"  arch=linux-centos7-x86_64 

[spackapps@lo-login-01 scripts]$ 

```

```
[spackapps@lo-login-01 scripts]$ spack -d install -j 1 cuda@9.2.88 %gcc@4.8.5 arch=linux-centos7-x86_64
==> Reading config file /cluster/apps/spack/etc/spack/defaults/packages.yaml
==> Reading config file /cluster/home/spackapps/.spack/linux/packages.yaml
==> READ LOCK: /cluster/home/spackapps/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /cluster/home/spackapps/.spack/cache/providers/.builtin-index.yaml.lock[0:0] [Released]
==> READ LOCK: /cluster/home/spackapps/.spack/cache/providers/.hpc-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /cluster/home/spackapps/.spack/cache/providers/.hpc-index.yaml.lock[0:0] [Released]
==> Reading config file /cluster/home/spackapps/.spack/linux/compilers.yaml
==> READ LOCK: /cluster/spack/apps/.spack-db/prefix_lock[4473407184731310179:1] [Acquiring]
==> READ LOCK: /cluster/spack/apps/.spack-db/prefix_lock[4473407184731310179:1] [Released]
==> Installing cuda dependencies
==> Installing cuda
==> Using cached archive: /cluster/apps/spack/var/spack/cache/cuda/cuda-9.2.88.None
==> Already staged cuda-9.2.88-pquxqrclfyimmjuz5l6jxntzrnao3d2y in /cluster/apps/spack/var/spack/stage/cuda-9.2.88-pquxqrclfyimmjuz5l6jxntzrnao3d2y
==> Already patched cuda
==> Building cuda [Package]
==> WRITE LOCK: /cluster/apps/spack/var/spack/stage/.lock[3072098670558868349:1] [Acquiring]
==> WRITE LOCK: /cluster/spack/apps/.spack-db/prefix_lock[4473407184731310179:1] [Acquiring]
==> Executing phase : 'install'
==> WRITE LOCK: /cluster/spack/apps/.spack-db/prefix_lock[4473407184731310179:1] [Released]
==> WRITE LOCK: /cluster/apps/spack/var/spack/stage/.lock[3072098670558868349:1] [Released]
==> Error: IndexError: list index out of range
/cluster/apps/spack/var/spack/repos/builtin/packages/cuda/package.py:59, in install:
     58       def install(self, spec, prefix):
  >> 59           runfile = glob(join_path(self.stage.path, 'cuda*run'))[0]
     60           chmod = which('chmod')
     61           chmod('+x', runfile)
     62           runfile = which(runfile)
     63   
     64           # Note: NVIDIA does not officially support many newer versions of
     65           # compilers.  For example, on CentOS 6, you must use GCC 4.4.7 or
     66           # older. See:
     67           # http://docs.nvidia.com/cuda/cuda-installation-guide-linux/#system-requirements
     68           # for details.
     69   
     70           runfile(
     71               '--silent',         # disable interactive prompts
     72               '--verbose',        # create verbose log file
     73               '--override',       # override compiler version checks
     74               '--toolkit',        # install CUDA Toolkit
     75               '--toolkitpath=%s' % prefix
     76           )

See build log for details:
  /dev/shm/spackapps/spack-stage/spack-stage-2mMUcE/spack-build.out
Traceback (most recent call last):
  File "/cluster/apps/spack/lib/spack/spack/build_environment.py", line 593, in child_execution
    function(input_stream)
  File "/cluster/apps/spack/lib/spack/spack/package.py", line 1305, in build_process
    self.spec, self.prefix)
  File "/cluster/apps/spack/lib/spack/spack/package.py", line 109, in phase_wrapper
    phase(spec, prefix)
  File "/cluster/apps/spack/var/spack/repos/builtin/packages/cuda/package.py", line 59, in install
    runfile = glob(join_path(self.stage.path, 'cuda*run'))[0]
IndexError: list index out of range

```

I am using a maybe outdated version of spack, therefore I am not sure if the problem is related to the package itself or to my old spack installation. So far installing the cuda package worked fine. I only see the problem with version 9.2.88:

```
[spackapps@lo-login-01 scripts]$ spack find cuda
==> 10 installed packages.
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
cuda@8.0.61  cuda@9.0.176

-- linux-centos7-x86_64 / gcc@5.4.0 -----------------------------
cuda@8.0.61  cuda@9.0.176

-- linux-centos7-x86_64 / gcc@6.3.0 -----------------------------
cuda@8.0.61  cuda@9.0.176

-- linux-centos7-x86_64 / gcc@7.1.0 -----------------------------
cuda@8.0.61  cuda@9.0.176

-- linux-centos7-x86_64 / intel@18.0.1 --------------------------
cuda@8.0.61  cuda@9.0.176
[spackapps@lo-login-01 scripts]$
```

**Comment by samfux84** [comment]
Problem solved by replacing

runfile = glob(join_path(self.stage.path, 'cuda*run'))[0]

with

runfile = glob(join_path(self.stage.path, 'cuda*_linux*'))[0]
