### ISSUE TITLE
py-cython: ProcessError

### ISSUE THREAD

**Issue by Sinan81** [spack/spack#9844]
### Steps to reproduce the issue

```console
$ spack install py-cython
```

### Error Message

```console
==> Installing py-cython
==> Searching for binary cache of py-cython
==> Warning: No Spack mirrors are currently configured
==> No binary for py-cython found: installing from source
==> '/var/spackdev/opt/spack/linux-linuxmint19-x86_64/gcc-8.2.0/python-2.7.15-zwgof6gt6zkz2q7iolrsns23srs7x4c7/bin/python' '-c' 'from distutils.sysconfig import get_config_var; print get_config_var('"'"'prefix'"'"')'
==> Error: ProcessError: /var/spackdev/opt/spack/linux-linuxmint19-x86_64/gcc-8.2.0/python-2.7.15-zwgof6gt6zkz2q7iolrsns23srs7x4c7/bin/python: Exec format error
    Command: '/var/spackdev/opt/spack/linux-linuxmint19-x86_64/gcc-8.2.0/python-2.7.15-zwgof6gt6zkz2q7iolrsns23srs7x4c7/bin/python' '-c' 'from distutils.sysconfig import get_config_var; print get_config_var('"'"'prefix'"'"')'
Traceback (most recent call last):
  File "/var/spackdev/lib/spack/spack/build_environment.py", line 724, in child_process
    setup_package(pkg, dirty=dirty)
  File "/var/spackdev/lib/spack/spack/build_environment.py", line 650, in setup_package
    dpkg.setup_dependent_package(pkg.module, spec)
  File "/var/spackdev/var/spack/repos/builtin/packages/python/package.py", line 607, in setup_dependent_package
  File "/var/spackdev/var/spack/repos/builtin/packages/python/package.py", line 489, in home
    return Prefix(prefix)
  File "/var/spackdev/var/spack/repos/builtin/packages/python/package.py", line 467, in get_config_var
  File "/var/spackdev/lib/spack/spack/util/executable.py", line 195, in __call__
    '%s: %s' % (self.exe[0], e.strerror), 'Command: ' + cmd_line)
ProcessError: /var/spackdev/opt/spack/linux-linuxmint19-x86_64/gcc-8.2.0/python-2.7.15-zwgof6gt6zkz2q7iolrsns23srs7x4c7/bin/python: Exec format error
    Command: '/var/spackdev/opt/spack/linux-linuxmint19-x86_64/gcc-8.2.0/python-2.7.15-zwgof6gt6zkz2q7iolrsns23srs7x4c7/bin/python' '-c' 'from distutils.sysconfig import get_config_var; print get_config_var('"'"'prefix'"'"')'
```

### Information on your system

1- platform: linux-linuxmint19-x86_64
2- Linux somehost 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Sinan81** [comment]
Just pulled the latest develop branch, and it seems this error is no longer an issue.

**Comment by scheibelp** [comment]
I'm going to close this for now but feel free to reopen if it comes up again
