### ISSUE TITLE
Package: igv  every version installs, but fails to run: 'Exception in thread "main" java.lang.NoClassDefFoundError: htsjdk/samtools/seekablestream/ISeekableStreamFactory'

### ISSUE THREAD

**Issue by 23skdu** [spack/spack#9873]
Linux XXXXXXXXX 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Description:    CentOS Linux release 7.2.1511 (Core)

$  spack spec --install-status igv
Input spec
--------------------------------
     igv

Concretized
--------------------------------
[+]  igv@2.4.5%gcc@5.4.0 arch=linux-centos7-x86_64
[+]      ^ant@1.9.9%gcc@5.4.0 arch=linux-centos7-x86_64
[+]          ^jdk@8u141-b15%gcc@5.4.0 arch=linux-centos7-x86_64

Every version it successfully installs, but throws the following error:

$ igv.sh
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: htsjdk/samtools/seekablestream/ISeekableStreamFactory
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: htsjdk.samtools.seekablestream.ISeekableStreamFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by 23skdu** [comment]
Versions previous to 2.4 use JDK7, and throw a different error:

$ module load igv/2.3.16

The following have been reloaded with a version change:
  1) igv/2.4.10 => igv/2.3.16     2) jdk/8u141-b15 => jdk/7u80-b0

$ igv.sh
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at org.broad.igv.ui.Main.<clinit>(Main.java:49)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 1 more
