### ISSUE TITLE
spack find -L in non-empty environment fails

### ISSUE THREAD

**Issue by nazavode** [spack/spack#9875]
Trying to run `spack find -L` inside a non-empty environment (e.g.: with at least one root spec) triggers an error.

### Steps to reproduce the issue

```console
$ spack env create test
==> Created environment 'test' in /Users/fmontag/Documents/Hacking/spack/var/spack/environments/test
$ spack env activate test
$ spack find -L
==> In environment test
==> No root specs

==> 0 installed packages
$ spack add zlib
==> Adding zlib to environment test
$ spack find
==> In environment test
==> Root specs
zlib

==> 0 installed packages
$ spack find -L
==> In environment test
==> Root specs
==> Error: can't multiply sequence by non-int of type 'NoneType'
```

### Error Message

```console
$ spack --debug find -L
==> Reading config file /Users/fmontag/Documents/Hacking/spack/etc/spack/defaults/modules.yaml
==> Reading config file /Users/fmontag/Documents/Hacking/spack/etc/spack/defaults/darwin/modules.yaml
==> Reading config file /Users/fmontag/Documents/Hacking/spack/var/spack/environments/test/spack.yaml
==> Reading config file /Users/fmontag/Documents/Hacking/spack/etc/spack/defaults/config.yaml
==> Reading config file /Users/fmontag/.spack/config.yaml
==> DATABASE LOCK TIMEOUT: 120s
==> PACKAGE LOCK TIMEOUT: No timeout
==> READ LOCK: /Users/fmontag/Documents/Hacking/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> READ LOCK: /Users/fmontag/Documents/Hacking/spack/opt/spack/.spack-db/lock[0:0] [Acquired]
==> READ LOCK: /Users/fmontag/Documents/Hacking/spack/opt/spack/.spack-db/lock[0:0] [Released]
==> In environment test
==> Root specs
Traceback (most recent call last):
  File "/Users/fmontag/Documents/Hacking/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/Users/fmontag/Documents/Hacking/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/fmontag/Documents/Hacking/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/Users/fmontag/Documents/Hacking/spack/lib/spack/spack/cmd/find.py", line 180, in find
    decorator=lambda s, f: color.colorize('@*{%s}' % f))
  File "/Users/fmontag/Documents/Hacking/spack/lib/spack/spack/cmd/__init__.py", line 317, in display_specs
    colify((fmt(s) for s in specs), indent=indent)
  File "/Users/fmontag/Documents/Hacking/spack/lib/spack/llnl/util/tty/colify.py", line 140, in colify
    elts = [text_type(elt) for elt in elts]
  File "/Users/fmontag/Documents/Hacking/spack/lib/spack/spack/cmd/__init__.py", line 317, in <genexpr>
    colify((fmt(s) for s in specs), indent=indent)
  File "/Users/fmontag/Documents/Hacking/spack/lib/spack/spack/cmd/__init__.py", line 310, in fmt
    string += gray_hash(s, hlen) + ' '
  File "/Users/fmontag/Documents/Hacking/spack/lib/spack/spack/cmd/__init__.py", line 178, in gray_hash
    h = spec.dag_hash(length) if spec.concrete else '-' * length
TypeError: can't multiply sequence by non-int of type 'NoneType'
```

### Information on your system

 1. macOSX 10.13
 2. using a fresh clone of spack @ `26e51ff17`

**Comment by citibeth** [comment]
Do you know if it produces a different result if you find within an environment without activating?  I believe that would be something like `spack -e test find -L`
