### ISSUE TITLE
spack env list fails on mac due to .DS_Store

### ISSUE THREAD

**Issue by davydden** [spack/spack#9901]
spack env list does not `.DS_Store` somewhere on macOS.

### Steps to reproduce the issue

```console
$ spack env create programming
$ spack env list
```

### Error Message

```
$ spack -d env list
==> Reading config file /Users/davydden/spack/etc/spack/defaults/modules.yaml
==> Reading config file /Users/davydden/spack/etc/spack/defaults/darwin/modules.yaml
==> Reading config file /Users/davydden/spack/etc/spack/defaults/config.yaml
==> Reading config file /Users/davydden/.spack/config.yaml
Traceback (most recent call last):
  File "/Users/davydden/spack/bin/spack", line 48, in <module>
    sys.exit(spack.main.main())
  File "/Users/davydden/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/davydden/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/env.py", line 364, in env
    action(args)
  File "/Users/davydden/spack/lib/spack/spack/cmd/env.py", line 257, in env_list
    names = ev.all_environment_names()
  File "/Users/davydden/spack/lib/spack/spack/environment.py", line 291, in all_environment_names
    yaml_path = os.path.join(root(candidate), manifest_name)
  File "/Users/davydden/spack/lib/spack/spack/environment.py", line 237, in root
    validate_env_name(name)
  File "/Users/davydden/spack/lib/spack/spack/environment.py", line 82, in validate_env_name
    "letters, numbers, _, and -.") % name)
ValueError: '.DS_Store': names must start with a letter, and only contain letters, numbers, _, and -.
```

### Information on your system

This includes:

 1. macOS 10.14.1

related to https://github.com/spack/spack/issues/9659 but more severe

**Comment by davydden** [comment]
p.s. workaround for now is to recursively remove the file form `spack`, see https://jonbellah.com/articles/recursively-remove-ds-store/

**Comment by citibeth** [comment]
@davydden Do you have a hunch on whether this is Mac-specific?  @scheibelp ???>
