### ISSUE TITLE
slepc spec not satisfied when creating a mirror for dealii

### ISSUE THREAD

**Issue by luca-heltai** [spack/spack#9911]
fresh checkout of spack, slepc specs cannot be satisfied.

### Steps to reproduce the issue

```console
$ spack mirror create -D -d . dealii@develop
```

### Error Message

```console
==> Error: Conflicting conditional dependencies onpackage slepc for spec slepc@3.10.1+arpack~blopex ^blas ^bzip2 ^diffutils ^gdbm ^lapack ^ncurses ^openssl ^perl@5.14.0: ^petsc@3.10:3.10.99 ^pkgconfig ^python@2.6:2.8 ^readline ^sqlite ^zlib
...
```

I get the same error for many different version specification.

**Comment by davydden** [comment]
> Conflicting conditional dependencies

could you put the whole thing? it should show what's conflicting

**Comment by davydden** [comment]
are you sure you don't explicitly ask `trilinos` to use `superlu-dist`? That won't work until trilinos comes up with the next release, thus was this PR of mine https://github.com/spack/spack/pull/9492 which disables it by default...

**Comment by luca-heltai** [comment]
let me check...

**Comment by luca-heltai** [comment]
nope. This is what I get with 

```
spack -d mirror create -D -d . dealii@9.0.0
```


```
==> Error: Conflicting conditional dependencies onpackage slepc for spec slepc@3.10.1+arpack~blopex ^blas ^bzip2 ^diffutils ^gdbm ^lapack ^ncurses ^openssl ^perl@5.14.0: ^petsc@3.10:3.10.99 ^pkgconfig ^python@2.6:2.8 ^readline ^sqlite ^zlib
Traceback (most recent call last):
  File "/marconi_work/Sis18_heltai_1/spack/lib/spack/spack/main.py", line 669, in main
    return _invoke_command(command, parser, args, unknown)
  File "/marconi_work/Sis18_heltai_1/spack/lib/spack/spack/main.py", line 440, in _invoke_command
    return_val = command(parser, args)
  File "/marconi_work/Sis18_heltai_1/spack/lib/spack/spack/cmd/mirror.py", line 217, in mirror
    action[args.mirror_command](args)
  File "/marconi_work/Sis18_heltai_1/spack/lib/spack/spack/cmd/mirror.py", line 195, in mirror_create
    directory, specs, num_versions=args.one_version_per_spec)
  File "/marconi_work/Sis18_heltai_1/spack/lib/spack/spack/mirror.py", line 168, in create
    s.concretize()
  File "/marconi_work/Sis18_heltai_1/spack/lib/spack/spack/spec.py", line 1865, in concretize
    user_spec_deps=user_spec_deps),
  File "/marconi_work/Sis18_heltai_1/spack/lib/spack/spack/spec.py", line 2288, in normalize
    visited, all_spec_deps, provider_index, tests)
  File "/marconi_work/Sis18_heltai_1/spack/lib/spack/spack/spec.py", line 2215, in _normalize_helper
    dep = self._evaluate_dependency_conditions(dep_name)
  File "/marconi_work/Sis18_heltai_1/spack/lib/spack/spack/spec.py", line 2058, in _evaluate_dependency_conditions
    raise e
spack.variant.UnsatisfiableVariantSpecError: Conflicting conditional dependencies onpackage slepc for spec slepc@3.10.1+arpack~blopex ^blas ^bzip2 ^diffutils ^gdbm ^lapack ^ncurses ^openssl ^perl@5.14.0: ^petsc@3.10:3.10.99 ^pkgconfig ^python@2.6:2.8 ^readline ^sqlite ^zlib
```

**Comment by davydden** [comment]
Do you have any custom settings for packages?

**Comment by luca-heltai** [comment]
and my `packages.yaml` is:

```
 packages:
   openmpi:
     paths: 
       openmpi@1.10.7%gcc: /cineca/prod/opt/compilers/openmpi/1-10.7/gnu--6.1.0/
     version: [1.10.7]
     buildable: False
   cmake:
     paths: 
       cmake@3.5.2%gcc: /cineca/prod/opt/tools/cmake/3.5.2/none/
     version: [3.5.2]
     buildable: False
   suite-sparse:
     variants: ~tbb
   boost:
     variants: +thread+system+serialization+iostreams+mpi+python
   petsc:
     variants: +mumps
   dealii:
     version: [develop]
     variants: -doc+optflags-adol-c+nanoflann+sundials+assimp
   all:
     compiler: [gcc@6.1.0] 
     providers:
       mpi: [openmpi]

```

I get the same problems with `+mumps` and without. No constraints on Trilinos. I also tried specifying explicitly `^trilinos~superlu-dist`, no luck.

**Comment by jppelteret** [comment]
Out of interest, can you try with this configuration
```
$ spack spec dealii ^cmake@3.9.4 ^petsc@3.9.4 ^slepc@3.9.2
```
I, along with our computer admin, were installing `9.0.0` on a machine today, and it concretised.

**Comment by davydden** [comment]
@luca-heltai I will try to reproduce your issue today....

**Comment by davydden** [comment]
@luca-heltai what I can say for sure is that without any settings in `packages.yaml`, it works for me:

```
$ spack spec dealii@develop
Input spec
--------------------------------
dealii@develop

Concretized
--------------------------------
dealii@develop%gcc@7.3.0+adol-c+arpack+assimp build_type=DebugRelease ~cuda cuda_arch= ~doc+gmsh+gsl+hdf5~int64+metis+mpi+muparser+nanoflann+netcdf+oce~optflags+p4est+petsc~python+scalapack+slepc+sundials+trilinos arch=linux-ubuntu18.04-x86_64 
    ^adol-c@develop%gcc@7.3.0~advanced_branching+atrig_erf~boost+doc+examples~openmp~sparse arch=linux-ubuntu18.04-x86_64 
        ^autoconf@2.69%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
            ^m4@1.4.18%gcc@7.3.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-ubuntu18.04-x86_64 
                ^libsigsegv@2.11%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
            ^perl@5.26.2%gcc@7.3.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-ubuntu18.04-x86_64 
                ^gdbm@1.18.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
                    ^readline@7.0%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
                        ^ncurses@6.1%gcc@7.3.0~symlinks~termlib arch=linux-ubuntu18.04-x86_64 
                            ^pkgconf@1.5.4%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
        ^automake@1.16.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
        ^libtool@2.4.6%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
    ^arpack-ng@3.6.3%gcc@7.3.0+mpi+shared arch=linux-ubuntu18.04-x86_64 
        ^cmake@3.12.4%gcc@7.3.0~doc+ncurses+openssl+ownlibs patches=dd3a40d4d92f6b2158b87d6fb354c277947c776424aa03f6dc8096cf3135f5d0 ~qt arch=linux-ubuntu18.04-x86_64 
            ^openssl@1.1.1%gcc@7.3.0+systemcerts arch=linux-ubuntu18.04-x86_64 
                ^zlib@1.2.11%gcc@7.3.0+optimize+pic+shared arch=linux-ubuntu18.04-x86_64 
        ^openblas@0.3.3%gcc@7.3.0 cpu_target= ~ilp64 patches=714aea33692304a50bd0ccde42590c176c82ded4a8ac7f06e573dc8071929c33,f1b066a4481a50678caeb7656bf3e6764f45619686ac465f257c8017a2dc1ff0 +pic+shared threads=none ~virtual_machine arch=linux-ubuntu18.04-x86_64 
        ^openmpi@4.0.0%gcc@7.3.0~cuda+cxx_exceptions fabrics= ~java~legacylaunchers~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=linux-ubuntu18.04-x86_64 
            ^hwloc@1.11.9%gcc@7.3.0~cairo~cuda+libxml2+pci+shared arch=linux-ubuntu18.04-x86_64 
                ^libpciaccess@0.13.5%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
                    ^util-macros@1.19.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
                ^libxml2@2.9.8%gcc@7.3.0~python arch=linux-ubuntu18.04-x86_64 
                    ^xz@5.2.4%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
                ^numactl@2.0.11%gcc@7.3.0 patches=592f30f7f5f757dfc239ad0ffd39a9a048487ad803c26b419e0f96b8cda08c1a arch=linux-ubuntu18.04-x86_64 
    ^assimp@4.0.1%gcc@7.3.0 build_type=RelWithDebInfo +shared arch=linux-ubuntu18.04-x86_64 
        ^boost@1.68.0%gcc@7.3.0+atomic+chrono~clanglibcpp cxxstd=default +date_time~debug+exception+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199,b37164268f34f7133cbc9a4066ae98fda08adf51e1172223f6a969909216870f ~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave arch=linux-ubuntu18.04-x86_64 
            ^bzip2@1.0.6%gcc@7.3.0+shared arch=linux-ubuntu18.04-x86_64 
                ^diffutils@3.6%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
    ^gmsh@4.0.0%gcc@7.3.0 build_type=RelWithDebInfo +compression~fltk~hdf5+mpi+netgen+oce~petsc+shared~slepc+tetgen arch=linux-ubuntu18.04-x86_64 
        ^gmp@6.1.2%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
        ^netgen@5.3.1%gcc@7.3.0~gui~metis+mpi~oce arch=linux-ubuntu18.04-x86_64 
        ^oce@0.18.3%gcc@7.3.0~X11+tbb arch=linux-ubuntu18.04-x86_64 
            ^intel-tbb@2019.2%gcc@7.3.0 cxxstd=default patches=ca08c28bdb15582c30777f9303d1986e4c09b3d514776494f3fbf5f19381bfda +shared+tm arch=linux-ubuntu18.04-x86_64 
        ^tetgen@1.5.0%gcc@7.3.0~debug~except patches=250ee7a9c97fbef4ed8796c70233631559fd2f4663affe6c824896880a605a24 arch=linux-ubuntu18.04-x86_64 
    ^gsl@2.5%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
    ^hdf5@1.10.4%gcc@7.3.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-ubuntu18.04-x86_64 
    ^metis@5.1.0%gcc@7.3.0 build_type=Release ~gdb~int64 patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 +real64+shared arch=linux-ubuntu18.04-x86_64 
    ^muparser@2.2.6.1%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
    ^nanoflann@1.2.3%gcc@7.3.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 
    ^netcdf@4.6.1%gcc@7.3.0~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+pic+shared arch=linux-ubuntu18.04-x86_64 
    ^netcdf-cxx@4.2%gcc@7.3.0 arch=linux-ubuntu18.04-x86_64 
    ^netlib-scalapack@2.0.2%gcc@7.3.0 build_type=RelWithDebInfo ~pic+shared arch=linux-ubuntu18.04-x86_64 
    ^p4est@2.0%gcc@7.3.0~openmp patches=8fb829e34e3a1e28afdd6e56e0bdc1d377af569b7ccb9e9d8da0eeb5829ed27e,e9418b1a9347a409be241cd185519b31950e42a7f55b6fb80ce53097657098ee arch=linux-ubuntu18.04-x86_64 
    ^petsc@3.10.2%gcc@7.3.0~X clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi~mumps+shared~suite-sparse+superlu-dist~trilinos arch=linux-ubuntu18.04-x86_64 
        ^hypre@2.15.1%gcc@7.3.0~debug~int64~internal-superlu+mpi+shared arch=linux-ubuntu18.04-x86_64 
        ^parmetis@4.0.3%gcc@7.3.0 build_type=RelWithDebInfo ~gdb patches=4f892531eb0a807eb1b82e683a416d3e35154a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59cca6e1209df4ef3b033bc4ee3cf50f369bce972a9d +shared arch=linux-ubuntu18.04-x86_64 
        ^python@2.7.15%gcc@7.3.0+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+pythoncmd+shared~tk~ucs4 arch=linux-ubuntu18.04-x86_64 
            ^sqlite@3.25.3%gcc@7.3.0~functions arch=linux-ubuntu18.04-x86_64 
        ^superlu-dist@5.4.0%gcc@7.3.0 build_type=RelWithDebInfo ~int64+shared arch=linux-ubuntu18.04-x86_64 
    ^slepc@3.10.1%gcc@7.3.0+arpack~blopex arch=linux-ubuntu18.04-x86_64 
    ^suite-sparse@5.3.0%gcc@7.3.0~cuda~openmp+pic~tbb arch=linux-ubuntu18.04-x86_64 
    ^sundials@3.2.1%gcc@7.3.0+ARKODE+CVODE+CVODES+IDA+IDAS+KINSOL build_type=RelWithDebInfo ~cuda+examples-c~examples-cuda~examples-cxx+examples-f77~examples-f90+examples-install~examples-raja~fcmix+generic-math~hypre~int64~klu~lapack+mpi~openmp~petsc precision=double ~pthread~raja+shared+static~superlu-mt arch=linux-ubuntu18.04-x86_64 
    ^trilinos@12.12.1%gcc@7.3.0~alloptpkgs+amesos+amesos2+anasazi+aztec+belos+boost build_type=RelWithDebInfo ~cgns~complex~dtk+epetra+epetraext+exodus+explicit_template_instantiation~float+fortran~fortrilinos+gtest+hdf5+hypre+ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos+metis~minitensor+ml+muelu+mumps~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~shards+shared~stk+suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib+zoltan+zoltan2 arch=linux-ubuntu18.04-x86_64 
        ^glm@0.9.7.1%gcc@7.3.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 
        ^matio@1.5.9%gcc@7.3.0+hdf5+shared+zlib arch=linux-ubuntu18.04-x86_64 
        ^mumps@5.1.1%gcc@7.3.0+complex+double+float~int64~metis+mpi~parmetis~ptscotch~scotch+shared arch=linux-ubuntu18.04-x86_64
```

**Comment by davydden** [comment]
@luca-heltai can't reproduce it, also works with variation of your settings and older compiler
```
$ spack spec dealii@develop%gcc@5.5.0
Input spec
--------------------------------
dealii@develop%gcc@5.5.0

Concretized
--------------------------------
dealii@develop%gcc@5.5.0+adol-c+arpack+assimp build_type=DebugRelease ~cuda cuda_arch= ~doc+gmsh+gsl+hdf5~int64+metis+mpi+muparser+nanoflann+netcdf+oce~optflags+p4est+petsc~python+scalapack+slepc+sundials+trilinos arch=linux-ubuntu18.04-x86_64 
    ^adol-c@develop%gcc@5.5.0~advanced_branching+atrig_erf~boost+doc+examples~openmp~sparse arch=linux-ubuntu18.04-x86_64 
        ^autoconf@2.69%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
            ^m4@1.4.18%gcc@5.5.0 patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,c0a408fbffb7255fcc75e26bd8edab116fc81d216bfd18b473668b7739a4158e,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 +sigsegv arch=linux-ubuntu18.04-x86_64 
                ^libsigsegv@2.11%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
            ^perl@5.26.2%gcc@5.5.0+cpanm patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac +shared+threads arch=linux-ubuntu18.04-x86_64 
                ^gdbm@1.18.1%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
                    ^readline@7.0%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
                        ^ncurses@6.1%gcc@5.5.0~symlinks~termlib arch=linux-ubuntu18.04-x86_64 
                            ^pkgconf@1.5.4%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
        ^automake@1.16.1%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
        ^libtool@2.4.6%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
    ^arpack-ng@3.6.3%gcc@5.5.0+mpi+shared arch=linux-ubuntu18.04-x86_64 
        ^cmake@3.5.2%gcc@5.5.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-x86_64 
            ^openssl@1.0.2p%gcc@5.5.0+systemcerts arch=linux-ubuntu18.04-x86_64 
                ^zlib@1.2.11%gcc@5.5.0+optimize+pic+shared arch=linux-ubuntu18.04-x86_64 
        ^openblas@0.3.3%gcc@5.5.0 cpu_target= ~ilp64 patches=714aea33692304a50bd0ccde42590c176c82ded4a8ac7f06e573dc8071929c33,f1b066a4481a50678caeb7656bf3e6764f45619686ac465f257c8017a2dc1ff0 +pic+shared threads=none ~virtual_machine arch=linux-ubuntu18.04-x86_64 
        ^openmpi@4.0.0%gcc@5.5.0~cuda+cxx_exceptions fabrics= ~java~legacylaunchers~memchecker~pmi schedulers= ~sqlite3~thread_multiple+vt arch=linux-ubuntu18.04-x86_64 
            ^hwloc@1.11.9%gcc@5.5.0~cairo~cuda+libxml2+pci+shared arch=linux-ubuntu18.04-x86_64 
                ^libpciaccess@0.13.5%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
                    ^util-macros@1.19.1%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
                ^libxml2@2.9.8%gcc@5.5.0~python arch=linux-ubuntu18.04-x86_64 
                    ^xz@5.2.4%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
                ^numactl@2.0.11%gcc@5.5.0 patches=592f30f7f5f757dfc239ad0ffd39a9a048487ad803c26b419e0f96b8cda08c1a arch=linux-ubuntu18.04-x86_64 
    ^assimp@4.0.1%gcc@5.5.0 build_type=RelWithDebInfo +shared arch=linux-ubuntu18.04-x86_64 
        ^boost@1.68.0%gcc@5.5.0+atomic+chrono~clanglibcpp cxxstd=default +date_time~debug+exception+filesystem+graph~icu+iostreams+locale+log+math+mpi+multithreaded~numpy patches=b37164268f34f7133cbc9a4066ae98fda08adf51e1172223f6a969909216870f ~pic+program_options+python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave arch=linux-ubuntu18.04-x86_64 
            ^bzip2@1.0.6%gcc@5.5.0+shared arch=linux-ubuntu18.04-x86_64 
                ^diffutils@3.6%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
            ^python@2.7.15%gcc@5.5.0+dbm~optimizations patches=123082ab3483ded78e86d7c809e98a804b3465b4683c96bd79a2fd799f572244 +pic+pythoncmd+shared~tk~ucs4 arch=linux-ubuntu18.04-x86_64 
                ^sqlite@3.25.3%gcc@5.5.0~functions arch=linux-ubuntu18.04-x86_64 
    ^gmsh@4.0.0%gcc@5.5.0 build_type=RelWithDebInfo +compression~fltk~hdf5+mpi+netgen+oce~petsc+shared~slepc+tetgen arch=linux-ubuntu18.04-x86_64 
        ^gmp@6.1.2%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
        ^netgen@5.3.1%gcc@5.5.0~gui~metis+mpi~oce arch=linux-ubuntu18.04-x86_64 
        ^oce@0.18.3%gcc@5.5.0~X11+tbb arch=linux-ubuntu18.04-x86_64 
            ^intel-tbb@2019.2%gcc@5.5.0 cxxstd=default patches=ca08c28bdb15582c30777f9303d1986e4c09b3d514776494f3fbf5f19381bfda +shared+tm arch=linux-ubuntu18.04-x86_64 
        ^tetgen@1.5.0%gcc@5.5.0~debug~except patches=250ee7a9c97fbef4ed8796c70233631559fd2f4663affe6c824896880a605a24 arch=linux-ubuntu18.04-x86_64 
    ^gsl@2.5%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
    ^hdf5@1.10.4%gcc@5.5.0~cxx~debug~fortran+hl+mpi+pic+shared~szip~threadsafe arch=linux-ubuntu18.04-x86_64 
    ^metis@5.1.0%gcc@5.5.0 build_type=Release ~gdb~int64 patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 +real64+shared arch=linux-ubuntu18.04-x86_64 
    ^muparser@2.2.6.1%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
    ^nanoflann@1.2.3%gcc@5.5.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 
    ^netcdf@4.6.1%gcc@5.5.0~dap~hdf4 maxdims=1024 maxvars=8192 +mpi~parallel-netcdf+pic+shared arch=linux-ubuntu18.04-x86_64 
    ^netcdf-cxx@4.2%gcc@5.5.0 arch=linux-ubuntu18.04-x86_64 
    ^netlib-scalapack@2.0.2%gcc@5.5.0 build_type=RelWithDebInfo ~pic+shared arch=linux-ubuntu18.04-x86_64 
    ^p4est@2.0%gcc@5.5.0~openmp patches=8fb829e34e3a1e28afdd6e56e0bdc1d377af569b7ccb9e9d8da0eeb5829ed27e,e9418b1a9347a409be241cd185519b31950e42a7f55b6fb80ce53097657098ee arch=linux-ubuntu18.04-x86_64 
    ^petsc@3.10.2%gcc@5.5.0~X clanguage=C ~complex~debug+double+hdf5+hypre~int64+metis+mpi+mumps+shared~suite-sparse+superlu-dist~trilinos arch=linux-ubuntu18.04-x86_64 
        ^hypre@2.15.1%gcc@5.5.0~debug~int64~internal-superlu+mpi+shared arch=linux-ubuntu18.04-x86_64 
        ^mumps@5.1.1%gcc@5.5.0+complex+double+float~int64~metis+mpi~parmetis~ptscotch~scotch+shared arch=linux-ubuntu18.04-x86_64 
        ^parmetis@4.0.3%gcc@5.5.0 build_type=RelWithDebInfo ~gdb patches=4f892531eb0a807eb1b82e683a416d3e35154a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59cca6e1209df4ef3b033bc4ee3cf50f369bce972a9d +shared arch=linux-ubuntu18.04-x86_64 
        ^superlu-dist@5.4.0%gcc@5.5.0 build_type=RelWithDebInfo ~int64+shared arch=linux-ubuntu18.04-x86_64 
    ^slepc@3.10.1%gcc@5.5.0+arpack~blopex arch=linux-ubuntu18.04-x86_64 
    ^suite-sparse@5.3.0%gcc@5.5.0~cuda~openmp+pic~tbb arch=linux-ubuntu18.04-x86_64 
    ^sundials@3.2.1%gcc@5.5.0+ARKODE+CVODE+CVODES+IDA+IDAS+KINSOL build_type=RelWithDebInfo ~cuda+examples-c~examples-cuda~examples-cxx+examples-f77~examples-f90+examples-install~examples-raja~fcmix+generic-math~hypre~int64~klu~lapack+mpi~openmp~petsc precision=double ~pthread~raja+shared+static~superlu-mt arch=linux-ubuntu18.04-x86_64 
    ^trilinos@12.12.1%gcc@5.5.0~alloptpkgs+amesos+amesos2+anasazi+aztec+belos+boost build_type=RelWithDebInfo ~cgns~complex~dtk+epetra+epetraext+exodus+explicit_template_instantiation~float+fortran~fortrilinos+gtest+hdf5+hypre+ifpack+ifpack2~intrepid~intrepid2~isorropia+kokkos+metis~minitensor+ml+muelu+mumps~nox~openmp~phalanx~piro~pnetcdf~python~rol~rythmos+sacado~shards+shared~stk+suite-sparse~superlu~superlu-dist~teko~tempus+teuchos+tpetra~x11~xsdkflags~zlib+zoltan+zoltan2 arch=linux-ubuntu18.04-x86_64 
        ^glm@0.9.7.1%gcc@5.5.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-x86_64 
        ^matio@1.5.9%gcc@5.5.0+hdf5+shared+zlib arch=linux-ubuntu18.04-x86_64
```
and
```
packages:
  openmpi:
    version: [1.10.7]
  cmake:
    version: [3.5.2]
  suite-sparse:
    variants: ~tbb
  boost:
    variants: +thread+system+serialization+iostreams+mpi+python
  petsc:
    variants: +mumps
  dealii:
    version: [develop]
    variants: -doc+optflags-adol-c+nanoflann+sundials+assimp
#  dealii:
#    version: [develop]
#    variants: +scalapack
  arpack-ng:
#    version: [develop]
  flex:
#     version: [2.6.3]
```

**Comment by davydden** [comment]
@luca-heltai please try disabling dependencies in `deal.II` and/or simplifying your `packages.yaml` to try to figure out what triggers this behaviour.

**Comment by luca-heltai** [comment]
I think I have isolated the problem. It is not in the concretization step during install, but in the Mirroring step.
If I download by hand slepc and place it in the mirror directory, then `spack install dealii` succeeds.

The problem is when I try to add the package to a mirror (i'm on a cluster, and can only compile on the nodes, that have no internet access), or to download it as a dependency of deal.II, i.e., 

`spack install dealii@develop` 

concretizes without problems, 

`spack mirror create -D -d . dealii@develop`

fails with the error above. No matter what configuration I use for `packages.yaml`.

Can you try and see if 

`spack mirror create -D -d . dealii@develop`

works for you?

**Comment by davydden** [comment]
Now i can reproduce:

```
$ spack mirror create -D -d . dealii@develop
==> Error: Conflicting conditional dependencies onpackage slepc for spec slepc@3.10.1+arpack~blopex ^blas ^bzip2 ^diffutils ^gdbm ^lapack ^ncurses ^openssl ^perl@5.14.0: ^petsc@3.10:3.10.99 ^pkgconfig ^python@2.6:2.8 ^readline ^sqlite ^zlib
```

whereas concretization `spack spec -I dealii@develop` works perfectly fine.

This happens regardless of any settings in `packages.yaml`.  I don't know anything about mirrors, so pinging a few people who (might) know more @tgamblin @scheibelp @alalazo @becker33 @adamjstewart .

**Comment by scheibelp** [comment]
I can look at this on Wednesday 11/28

**Comment by scheibelp** [comment]
Unfortunately I cannot reproduce this (in an ubuntu 18.04 container or on Mac OS with python 2.7).

Would someone who can reproduce this error try the following:

* Try `spack spec dealii@develop`, note the compiler chosen for the spec, and then explicitly set that compiler when invoking `spack mirror create` (e.g. `spack mirror create -D -d test-mirror dealii@develop%X` if the compiler `X` appears in the successful concretization)
* Try `spack mirror create -D -d test-mirror dealii@develop ^slepc+arpack ^petsc+mpi~int64`
* The error reporting is lacking on Spack's end, so I've created a PR to print out more information at https://github.com/spack/spack/pull/9975. Would you be able to rerun the command using that PR?

Also, could you mention what python version you are using with Spack?

Thanks!

**Comment by davydden** [comment]
I will try next Monday (3 December) when I am back in the office, I can't reproduce it from my macbook...

**Comment by freifrauvonbleifrei** [comment]
I just had the same problem when trying to install slepc for other software. I could resolve it by specifying the current version for slepc and petsc: `./bin/spack install slepc@3.11.0^petsc@3.11.1`
hope this helps!
